"""EasyCrypt AST nodes and pretty-printer.

Scope limited to what's needed for the Phase 1 walking skeleton: abstract
types, distribution operators, axioms, module types, modules (with procs),
and equiv-lemmas with admit.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Union

# --- Type expressions ---------------------------------------------------


@dataclass(frozen=True)
class EcType:
    """A raw type expression, rendered verbatim (e.g. 'bs_lambda', 'int')."""

    text: str


# --- Top-level declarations ---------------------------------------------


@dataclass
class TypeDecl:
    """`type <name>.`"""

    name: str


@dataclass
class OpDecl:
    """`op <name> : <signature>.` where signature is a raw string."""

    name: str
    signature: str


@dataclass
class Axiom:
    """``axiom <name> [(<module_args>)] [<memory_args>] : <formula>.``"""

    name: str
    formula: str
    module_args: list[ModuleParam] = field(default_factory=list)
    memory_args: list[str] = field(default_factory=list)


# --- Module type members -------------------------------------------------


@dataclass
class ProcParam:
    """A parameter to a proc: `name : type`."""

    name: str
    type: EcType


@dataclass
class ProcSig:
    """A procedure signature (used inside module types)."""

    name: str
    params: list[ProcParam]
    return_type: EcType


# --- Procedure bodies ---------------------------------------------------


@dataclass
class VarDecl:
    """`var <name> : <type>;`"""

    name: str
    type: EcType


@dataclass
class Assign:
    """`<var> <- <rhs>;` where rhs is a raw string."""

    var: str
    rhs: str


@dataclass
class Sample:
    """`<var> <$ <distr>;` where distr is a raw string."""

    var: str
    distr: str


@dataclass
class Call:
    """`<var> <@ <callee>(<args>);` where args is already rendered."""

    var: str
    callee: str
    args: str


@dataclass
class Return:
    """`return <expr>;` where expr is a raw string."""

    expr: str


EcStmt = Union[VarDecl, Assign, Sample, Call, Return]


@dataclass
class Proc:
    """A procedure implementation."""

    name: str
    params: list[ProcParam]
    return_type: EcType
    body: list[EcStmt]


# --- Modules -------------------------------------------------------------


@dataclass
class ModuleType:
    """``module type <name> [(<params>)] = { <procs> }.``"""

    name: str
    procs: list[ProcSig]
    params: list[ModuleParam] = field(default_factory=list)


@dataclass
class ModuleParam:
    """A module parameter: `(E : SymEnc)`."""

    name: str
    module_type: str


@dataclass
class Module:
    """`module <name> [(<params>)] [: <iface>] = { <procs> }.`"""

    name: str
    procs: list[Proc]
    params: list[ModuleParam] = field(default_factory=list)
    implements: str | None = None


@dataclass
class ProbLemma:
    """A lemma with module / memory params and a free-form statement.

    Renders as::

        lemma <name> [<module_args>] [<memory_args>] :
          <statement>.
        proof.
          <body line 1>
          <body line 2>
          ...

    The body must end with ``"qed."``.
    """

    name: str
    module_args: list[ModuleParam]
    memory_args: list[str]
    statement: str
    body: list[str] = field(default_factory=list)


@dataclass
class Lemma:
    """An equiv lemma.

    Renders as::

        lemma <name> [<module_args>] :
          equiv [ <left> ~ <right> : <pre> ==> <post> ].
        proof.
          <body line 1>
          <body line 2>
          ...
        qed.

    The ``body`` list contains tactic lines without the surrounding
    ``proof.`` and ``qed.``; the pretty-printer adds those. If the body
    is empty, the lemma renders ``proof. admit. qed.`` as a fallback.
    """

    name: str
    module_args: list[ModuleParam]
    left: str
    right: str
    precondition: str
    postcondition: str
    body: list[str] = field(default_factory=list)


# --- The whole file ------------------------------------------------------


EcTopDecl = Union[TypeDecl, OpDecl, Axiom, ModuleType, Module, Lemma, ProbLemma, str]


@dataclass
class EcFile:
    """Top-level EasyCrypt file.

    `requires` is a list of import names for the initial `require import` line.
    `decls` is the ordered list of top-level declarations. A bare `str`
    element renders as a literal line (useful for comments / blank lines).
    """

    requires: list[str]
    decls: list[EcTopDecl]


# --- Pretty-printer ------------------------------------------------------


def pretty_print(ec_file: EcFile) -> str:
    """Render an EcFile as EasyCrypt source text."""
    lines: list[str] = []
    lines.append("(* Auto-generated by ProofFrog. Do not edit. *)")
    if ec_file.requires:
        lines.append(f"require import {' '.join(ec_file.requires)}.")
    lines.append("")
    for decl in ec_file.decls:
        lines.extend(_render_decl(decl))
        lines.append("")
    return "\n".join(lines)


def _render_decl(decl: EcTopDecl) -> list[str]:
    if isinstance(decl, str):
        return [decl]
    if isinstance(decl, TypeDecl):
        return [f"type {decl.name}."]
    if isinstance(decl, OpDecl):
        return [f"op {decl.name} : {decl.signature}."]
    if isinstance(decl, Axiom):
        header = f"axiom {decl.name}"
        if decl.module_args:
            args = ", ".join(f"({p.name} <: {p.module_type})" for p in decl.module_args)
            header += f" {args}"
        if decl.memory_args:
            header += " " + " ".join(decl.memory_args)
        if not decl.module_args and not decl.memory_args:
            return [f"{header} : {decl.formula}."]
        return [f"{header} :", f"  {decl.formula}."]
    if isinstance(decl, ModuleType):
        header = f"module type {decl.name}"
        if decl.params:
            param_str = ", ".join(f"{p.name} : {p.module_type}" for p in decl.params)
            header += f" ({param_str})"
        out = [f"{header} = {{"]
        for proc in decl.procs:
            out.append(f"  {_render_proc_sig(proc)}")
        out.append("}.")
        return out
    if isinstance(decl, Module):
        return _render_module(decl)
    if isinstance(decl, Lemma):
        return _render_lemma(decl)
    if isinstance(decl, ProbLemma):
        return _render_prob_lemma(decl)
    raise TypeError(f"Unknown top-level decl: {type(decl).__name__}")


def _render_prob_lemma(lemma: ProbLemma) -> list[str]:
    header = f"lemma {lemma.name}"
    if lemma.module_args:
        args = ", ".join(f"({p.name} <: {p.module_type})" for p in lemma.module_args)
        header += f" {args}"
    if lemma.memory_args:
        header += " " + " ".join(lemma.memory_args)
    out = [f"{header} :"]
    out.append(f"  {lemma.statement}.")
    if not lemma.body:
        out.append("proof. admit. qed.")
        return out
    out.append("proof.")
    for line in lemma.body:
        out.append(f"  {line}")
    return out


def _render_proc_sig(proc: ProcSig) -> str:
    param_str = ", ".join(f"{p.name} : {p.type.text}" for p in proc.params)
    return f"proc {proc.name}({param_str}) : {proc.return_type.text}"


def _render_module(module: Module) -> list[str]:
    header = f"module {module.name}"
    if module.params:
        param_str = ", ".join(f"{p.name} : {p.module_type}" for p in module.params)
        header += f" ({param_str})"
    if module.implements is not None:
        header += f" : {module.implements}"
    header += " = {"
    out = [header]
    for proc in module.procs:
        out.extend(_render_proc_impl(proc))
    out.append("}.")
    return out


def _render_proc_impl(proc: Proc) -> list[str]:
    param_str = ", ".join(f"{p.name} : {p.type.text}" for p in proc.params)
    out = [f"  proc {proc.name}({param_str}) : {proc.return_type.text} = {{"]
    for stmt in proc.body:
        out.append(f"    {_render_stmt(stmt)}")
    out.append("  }")
    return out


def _render_stmt(stmt: EcStmt) -> str:
    if isinstance(stmt, VarDecl):
        return f"var {stmt.name} : {stmt.type.text};"
    if isinstance(stmt, Assign):
        return f"{stmt.var} <- {stmt.rhs};"
    if isinstance(stmt, Sample):
        return f"{stmt.var} <$ {stmt.distr};"
    if isinstance(stmt, Call):
        return f"{stmt.var} <@ {stmt.callee}({stmt.args});"
    if isinstance(stmt, Return):
        return f"return {stmt.expr};"
    raise TypeError(f"Unknown statement: {type(stmt).__name__}")


def _render_lemma(lemma: Lemma) -> list[str]:
    header = f"lemma {lemma.name}"
    if lemma.module_args:
        arg_str = ", ".join(f"({p.name} <: {p.module_type})" for p in lemma.module_args)
        header += f" {arg_str}"
    out = [f"{header} :"]
    out.append(f"  equiv [ {lemma.left} ~ {lemma.right} :")
    out.append(f"          {lemma.precondition} ==> {lemma.postcondition} ].")
    if not lemma.body:
        out.append("proof. admit. qed.")
        return out
    out.append("proof.")
    for line in lemma.body:
        out.append(f"  {line}")
    return out
