(* Auto-generated by ProofFrog. Do not edit. *)
require import AllCore Distr DProd DMap.

(* ===== Abstract set declarations ===== *)

type D_K.

type E_K.

type M.

type C_1.

type C_2.

(* ===== Concrete primitive types ===== *)

op dC_2 : C_2 distr.

axiom dC_2_ll : is_lossless dC_2.

axiom dC_2_fu : is_funiform dC_2.

axiom dC_2_full : is_full dC_2.

op dC_1 : C_1 distr.

axiom dC_1_ll : is_lossless dC_1.

axiom dC_1_fu : is_funiform dC_1.

axiom dC_1_full : is_full dC_1.

(* ===== Abstract theory: primitive + security games + assumption ===== *)

abstract theory SymEnc_Theory.
  type key.

  type message.

  type ciphertext.

  op dciphertext : ciphertext distr.

  axiom dciphertext_ll : is_lossless dciphertext.

  axiom dciphertext_fu : is_funiform dciphertext.

  axiom dciphertext_full : is_full dciphertext.

  module type Scheme = {
    proc keygen() : key
    proc enc(k : key, m : message) : ciphertext
    proc dec(k : key, c : ciphertext) : message
  }.

  op ev_dec : key -> ciphertext -> message.

  module type INDCPA__MultiChal_Oracle = {
    proc initialize() : unit
    proc ctxt(m : message) : ciphertext
  }.

  module INDCPA__MultiChal_Real (E : Scheme) : INDCPA__MultiChal_Oracle = {
    var k : key
    proc initialize() : unit = {
      k <@ E.keygen();
    }
    proc ctxt(m : message) : ciphertext = {
      var _r0 : ciphertext;
      _r0 <@ E.enc(k, m);
      return _r0;
    }
  }.

  module INDCPA__MultiChal_Random (E : Scheme) : INDCPA__MultiChal_Oracle = {
    var k : key
    proc initialize() : unit = {
      k <@ E.keygen();
    }
    proc ctxt(m : message) : ciphertext = {
      var c : ciphertext;
      c <$ dciphertext;
      return c;
    }
  }.

  module type INDCPA__MultiChal_Adv (O : INDCPA__MultiChal_Oracle) = {
    proc distinguish() : bool {O.ctxt}
  }.

  module Game_INDCPA__MultiChal_Real (Em : Scheme, A : INDCPA__MultiChal_Adv) = {
    proc main() : bool = {
      var b : bool;
      INDCPA__MultiChal_Real(Em).initialize();
      b <@ A(INDCPA__MultiChal_Real(Em)).distinguish();
      return b;
    }
  }.

  module Game_INDCPA__MultiChal_Random (Em : Scheme, A : INDCPA__MultiChal_Adv) = {
    proc main() : bool = {
      var b : bool;
      INDCPA__MultiChal_Random(Em).initialize();
      b <@ A(INDCPA__MultiChal_Random(Em)).distinguish();
      return b;
    }
  }.

  op eps_INDCPA__MultiChal : real.

  axiom eps_INDCPA__MultiChal_pos : 0%r <= eps_INDCPA__MultiChal.

  axiom INDCPA__MultiChal_advantage (Em <: Scheme) (A <: INDCPA__MultiChal_Adv) &m :
    `| Pr[Game_INDCPA__MultiChal_Real(Em, A).main() @ &m : res] - Pr[Game_INDCPA__MultiChal_Random(Em, A).main() @ &m : res] | <= eps_INDCPA__MultiChal.
end SymEnc_Theory.

(* ===== Theory instantiation ===== *)

clone SymEnc_Theory as D_c with
  type message <- M,
  type ciphertext <- C_1,
  type key <- D_K,
  op dciphertext <- dC_1.

clone SymEnc_Theory as E_c with
  type message <- C_1,
  type ciphertext <- C_2,
  type key <- E_K,
  op dciphertext <- dC_2.

clone SymEnc_Theory as DSE_c with
  type message <- M,
  type ciphertext <- C_2,
  type key <- D_K * E_K,
  op dciphertext <- dC_2.

(* ===== Per-clone distribution axioms ===== *)

lemma D_dC_1_funi :
  is_funiform dC_1.
proof.
  exact dC_1_fu.
qed.

lemma D_dC_1_ll :
  is_lossless dC_1.
proof.
  exact dC_1_ll.
qed.

lemma E_dC_2_funi :
  is_funiform dC_2.
proof.
  exact dC_2_fu.
qed.

lemma E_dC_2_ll :
  is_lossless dC_2.
proof.
  exact dC_2_ll.
qed.

lemma DSE_dC_2_funi :
  is_funiform dC_2.
proof.
  exact dC_2_fu.
qed.

lemma DSE_dC_2_ll :
  is_lossless dC_2.
proof.
  exact dC_2_ll.
qed.

(* NOTE: the FrogLang scheme has `requires` clauses that are not enforced by the EC export. The scheme module below may fail EC type-checking because cross-clone type equalities implied by the `requires` are not expressed in the clones. Deferred to Phase 5D. *)

(* ===== Concrete scheme implementation ===== *)

module GeneralDoubleSymEnc (S : D_c.Scheme, T : E_c.Scheme) : DSE_c.Scheme = {
  proc keygen() : D_K * E_K = {
    var key1 : D_K;
    var key2 : E_K;
    key1 <@ S.keygen();
    key2 <@ T.keygen();
    return (key1, key2);
  }
  proc enc(k : D_K * E_K, m : M) : C_2 = {
    var c1 : C_1;
    var c2 : C_2;
    c1 <@ S.enc(k.`1, m);
    c2 <@ T.enc(k.`2, c1);
    return c2;
  }
  proc dec(k : D_K * E_K, c : C_2) : M = {
    var c2 : C_1;
    var m : M;
    c2 <@ T.dec(k.`2, c);
    m <@ S.dec(k.`1, c2);
    return m;
  }
}.

section Main.
  (* ===== Reductions ===== *)

  module R1 (D : D_c.Scheme, E : E_c.Scheme, DSE : DSE_c.Scheme, Challenger : E_c.INDCPA__MultiChal_Oracle) = {
    var dKey : D_K
    proc initialize() : unit = {
      dKey <@ D.keygen();
    }
    proc ctxt(m : M) : C_2 = {
      var c1 : C_1;
      var c2 : C_2;
      c1 <@ D.enc(dKey, m);
      c2 <@ Challenger.ctxt(c1);
      return c2;
    }
  }.

  (* ===== Reductions lifted to assumption-adversaries ===== *)

  module R1_Adv (D : D_c.Scheme, E : E_c.Scheme, A : DSE_c.INDCPA__MultiChal_Adv, C : E_c.INDCPA__MultiChal_Oracle) = {
    proc distinguish() : bool = {
      var b : bool;
      var pk0 : unit;
      pk0 <@ R1(D, E, GeneralDoubleSymEnc(D, E), C).initialize();
      b <@ A(R1(D, E, GeneralDoubleSymEnc(D, E), C)).distinguish(pk0);
      return b;
    }
  }.

  (* ===== Game-step wrappers ===== *)

  (* Game_step_0: INDCPA$_MultiChal.Real *)

  module Game_step_0 (D : D_c.Scheme, E : E_c.Scheme, A : DSE_c.INDCPA__MultiChal_Adv) = {
    proc main() : bool = {
      var b : bool;
      DSE_c.INDCPA__MultiChal_Real(GeneralDoubleSymEnc(D, E)).initialize();
      b <@ A(DSE_c.INDCPA__MultiChal_Real(GeneralDoubleSymEnc(D, E))).distinguish();
      return b;
    }
  }.

  (* Game_step_1: INDCPA$_MultiChal.Real composed with reduction R1 *)

  module Game_step_1 (D : D_c.Scheme, E : E_c.Scheme, A : DSE_c.INDCPA__MultiChal_Adv) = {
    proc main() : bool = {
      var b : bool;
      R1(D, E, GeneralDoubleSymEnc(D, E), E_c.INDCPA__MultiChal_Real(E)).initialize();
      b <@ A(R1(D, E, GeneralDoubleSymEnc(D, E), E_c.INDCPA__MultiChal_Real(E))).distinguish();
      return b;
    }
  }.

  (* Game_step_2: INDCPA$_MultiChal.Random composed with reduction R1 *)

  module Game_step_2 (D : D_c.Scheme, E : E_c.Scheme, A : DSE_c.INDCPA__MultiChal_Adv) = {
    proc main() : bool = {
      var b : bool;
      R1(D, E, GeneralDoubleSymEnc(D, E), E_c.INDCPA__MultiChal_Random(E)).initialize();
      b <@ A(R1(D, E, GeneralDoubleSymEnc(D, E), E_c.INDCPA__MultiChal_Random(E))).distinguish();
      return b;
    }
  }.

  (* Game_step_3: INDCPA$_MultiChal.Random *)

  module Game_step_3 (D : D_c.Scheme, E : E_c.Scheme, A : DSE_c.INDCPA__MultiChal_Adv) = {
    proc main() : bool = {
      var b : bool;
      DSE_c.INDCPA__MultiChal_Random(GeneralDoubleSymEnc(D, E)).initialize();
      b <@ A(DSE_c.INDCPA__MultiChal_Random(GeneralDoubleSymEnc(D, E))).distinguish();
      return b;
    }
  }.

  (* ===== Per-transform canonicalization chain ===== *)

  module Step_0L_state_0 (D : D_c.Scheme, E : E_c.Scheme) = {
    var k : D_K * E_K
    proc initialize() : unit = {
      var v_DSE_KeyGen_key10 : D_K;
      var v_DSE_KeyGen_key20 : E_K;
      v_DSE_KeyGen_key10 <@ D.keygen();
      v_DSE_KeyGen_key20 <@ E.keygen();
      k <- (v_DSE_KeyGen_key10, v_DSE_KeyGen_key20);
    }
    proc ctxt(m : M) : C_2 = {
      var v_DSE_Enc_c10 : C_1;
      var v_DSE_Enc_c20 : C_2;
      v_DSE_Enc_c10 <@ D.enc(k.`1, m);
      v_DSE_Enc_c20 <@ E.enc(k.`2, v_DSE_Enc_c10);
      return v_DSE_Enc_c20;
    }
  }.

  module Step_0L_state_1 (D : D_c.Scheme, E : E_c.Scheme) = {
    var k : D_K * E_K
    proc initialize() : unit = {
      var __a0__ : D_K;
      var __a1__ : E_K;
      __a0__ <@ D.keygen();
      __a1__ <@ E.keygen();
      k <- (__a0__, __a1__);
    }
    proc ctxt(m : M) : C_2 = {
      var __a2__ : C_1;
      var __a3__ : C_2;
      __a2__ <@ D.enc(k.`1, m);
      __a3__ <@ E.enc(k.`2, __a2__);
      return __a3__;
    }
  }.

  module Step_0L_state_2 (D : D_c.Scheme, E : E_c.Scheme) = {
    var k : D_K * E_K
    proc initialize() : unit = {
      var _r0 : D_K;
      var _r1 : E_K;
      _r0 <@ D.keygen();
      _r1 <@ E.keygen();
      k <- (_r0, _r1);
    }
    proc ctxt(m : M) : C_2 = {
      var _r0 : C_1;
      var _r1 : C_2;
      _r0 <@ D.enc(k.`1, m);
      _r1 <@ E.enc(k.`2, _r0);
      return _r1;
    }
  }.

  module Step_0L_state_3 (D : D_c.Scheme, E : E_c.Scheme) = {
    var k_0 : D_K
    var k_1 : E_K
    proc initialize() : unit = {
      k_0 <@ D.keygen();
      k_1 <@ E.keygen();
    }
    proc ctxt(m : M) : C_2 = {
      var _r0 : C_1;
      var _r1 : C_2;
      _r0 <@ D.enc(k_0, m);
      _r1 <@ E.enc(k_1, _r0);
      return _r1;
    }
  }.

  module Step_0L_state_4 (D : D_c.Scheme, E : E_c.Scheme) = {
    var field1 : D_K
    var field2 : E_K
    proc initialize() : unit = {
      field1 <@ D.keygen();
      field2 <@ E.keygen();
    }
    proc ctxt(m : M) : C_2 = {
      var _r0 : C_1;
      var _r1 : C_2;
      _r0 <@ D.enc(field1, m);
      _r1 <@ E.enc(field2, _r0);
      return _r1;
    }
  }.

  module Step_0R_state_0 (D : D_c.Scheme, E : E_c.Scheme) = {
    var challenger_k : E_K
    var dKey : D_K
    proc initialize() : unit = {
      challenger_k <@ E.keygen();
      dKey <@ D.keygen();
    }
    proc ctxt(m : M) : C_2 = {
      var c1 : C_1;
      var c2 : C_2;
      c1 <@ D.enc(dKey, m);
      c2 <@ E.enc(challenger_k, c1);
      return c2;
    }
  }.

  module Step_0R_state_1 (D : D_c.Scheme, E : E_c.Scheme) = {
    var challenger_k : E_K
    var dKey : D_K
    proc initialize() : unit = {
      challenger_k <@ E.keygen();
      dKey <@ D.keygen();
    }
    proc ctxt(m : M) : C_2 = {
      var __a0__ : C_1;
      var __a1__ : C_2;
      __a0__ <@ D.enc(dKey, m);
      __a1__ <@ E.enc(challenger_k, __a0__);
      return __a1__;
    }
  }.

  module Step_0R_state_2 (D : D_c.Scheme, E : E_c.Scheme) = {
    var challenger_k : E_K
    var dKey : D_K
    proc initialize() : unit = {
      challenger_k <@ E.keygen();
      dKey <@ D.keygen();
    }
    proc ctxt(m : M) : C_2 = {
      var _r0 : C_1;
      var _r1 : C_2;
      _r0 <@ D.enc(dKey, m);
      _r1 <@ E.enc(challenger_k, _r0);
      return _r1;
    }
  }.

  module Step_0R_state_3 (D : D_c.Scheme, E : E_c.Scheme) = {
    var field1 : D_K
    var field2 : E_K
    proc initialize() : unit = {
      field2 <@ E.keygen();
      field1 <@ D.keygen();
    }
    proc ctxt(m : M) : C_2 = {
      var _r0 : C_1;
      var _r1 : C_2;
      _r0 <@ D.enc(field1, m);
      _r1 <@ E.enc(field2, _r0);
      return _r1;
    }
  }.

  module Step_0R_state_4 (D : D_c.Scheme, E : E_c.Scheme) = {
    var field1 : D_K
    var field2 : E_K
    proc initialize() : unit = {
      field1 <@ D.keygen();
      field2 <@ E.keygen();
    }
    proc ctxt(m : M) : C_2 = {
      var _r0 : C_1;
      var _r1 : C_2;
      _r0 <@ D.enc(field1, m);
      _r1 <@ E.enc(field2, _r0);
      return _r1;
    }
  }.

  module Step_2L_state_0 (D : D_c.Scheme, E : E_c.Scheme) = {
    var challenger_k : E_K
    var dKey : D_K
    proc initialize() : unit = {
      challenger_k <@ E.keygen();
      dKey <@ D.keygen();
    }
    proc ctxt(m : M) : C_2 = {
      var c1 : C_1;
      var challenger_CTXT_c1 : C_2;
      var c2 : C_2;
      c1 <@ D.enc(dKey, m);
      challenger_CTXT_c1 <$ dC_2;
      c2 <- challenger_CTXT_c1;
      return c2;
    }
  }.

  module Step_2L_state_1 (D : D_c.Scheme, E : E_c.Scheme) = {
    var challenger_k : E_K
    var dKey : D_K
    proc initialize() : unit = {
      challenger_k <@ E.keygen();
      dKey <@ D.keygen();
    }
    proc ctxt(m : M) : C_2 = {
      var __a0__ : C_1;
      var __a1__ : C_2;
      var __a2__ : C_2;
      __a0__ <@ D.enc(dKey, m);
      __a1__ <$ dC_2;
      __a2__ <- __a1__;
      return __a2__;
    }
  }.

  module Step_2L_state_2 (D : D_c.Scheme, E : E_c.Scheme) = {
    var challenger_k : E_K
    var dKey : D_K
    proc initialize() : unit = {
      challenger_k <@ E.keygen();
      dKey <@ D.keygen();
    }
    proc ctxt(m : M) : C_2 = {
      var __a0__ : C_1;
      var __a1__ : C_2;
      __a0__ <@ D.enc(dKey, m);
      __a1__ <$ dC_2;
      return __a1__;
    }
  }.

  module Step_2L_state_3 (D : D_c.Scheme, E : E_c.Scheme) = {
    var challenger_k : E_K
    var dKey : D_K
    proc initialize() : unit = {
      challenger_k <@ E.keygen();
      dKey <@ D.keygen();
    }
    proc ctxt(m : M) : C_2 = {
      var __a1__ : C_2;
      var __a0__ : C_1;
      __a1__ <$ dC_2;
      __a0__ <@ D.enc(dKey, m);
      return __a1__;
    }
  }.

  module Step_2L_state_4 (D : D_c.Scheme, E : E_c.Scheme) = {
    proc ctxt(m : M) : C_2 = {
      var __a1__ : C_2;
      __a1__ <$ dC_2;
      return __a1__;
    }
  }.

  module Step_2L_state_5 (D : D_c.Scheme, E : E_c.Scheme) = {
    proc ctxt(m : M) : C_2 = {
      var v1 : C_2;
      v1 <$ dC_2;
      return v1;
    }
  }.

  module Step_2R_state_0 (D : D_c.Scheme, E : E_c.Scheme) = {
    var k : D_K * E_K
    proc initialize() : unit = {
      var v_DSE_KeyGen_key10 : D_K;
      var v_DSE_KeyGen_key20 : E_K;
      v_DSE_KeyGen_key10 <@ D.keygen();
      v_DSE_KeyGen_key20 <@ E.keygen();
      k <- (v_DSE_KeyGen_key10, v_DSE_KeyGen_key20);
    }
    proc ctxt(m : M) : C_2 = {
      var c : C_2;
      c <$ dC_2;
      return c;
    }
  }.

  module Step_2R_state_1 (D : D_c.Scheme, E : E_c.Scheme) = {
    var k : D_K * E_K
    proc initialize() : unit = {
      var __a0__ : D_K;
      var __a1__ : E_K;
      __a0__ <@ D.keygen();
      __a1__ <@ E.keygen();
      k <- (__a0__, __a1__);
    }
    proc ctxt(m : M) : C_2 = {
      var __a2__ : C_2;
      __a2__ <$ dC_2;
      return __a2__;
    }
  }.

  module Step_2R_state_2 (D : D_c.Scheme, E : E_c.Scheme) = {
    var k : D_K * E_K
    proc initialize() : unit = {
      var _r0 : D_K;
      var _r1 : E_K;
      _r0 <@ D.keygen();
      _r1 <@ E.keygen();
      k <- (_r0, _r1);
    }
    proc ctxt(m : M) : C_2 = {
      var __a2__ : C_2;
      __a2__ <$ dC_2;
      return __a2__;
    }
  }.

  module Step_2R_state_3 (D : D_c.Scheme, E : E_c.Scheme) = {
    proc ctxt(m : M) : C_2 = {
      var __a2__ : C_2;
      __a2__ <$ dC_2;
      return __a2__;
    }
  }.

  module Step_2R_state_4 (D : D_c.Scheme, E : E_c.Scheme) = {
    proc ctxt(m : M) : C_2 = {
      var v1 : C_2;
      v1 <$ dC_2;
      return v1;
    }
  }.

  declare module D <: D_c.Scheme {-DSE_c.INDCPA__MultiChal_Random, -DSE_c.INDCPA__MultiChal_Real, -E_c.INDCPA__MultiChal_Random, -E_c.INDCPA__MultiChal_Real, -R1}.

  declare module E <: E_c.Scheme {-D, -DSE_c.INDCPA__MultiChal_Random, -DSE_c.INDCPA__MultiChal_Real, -E_c.INDCPA__MultiChal_Random, -E_c.INDCPA__MultiChal_Real, -R1}.

  (* ===== Deterministic-method specs ===== *)

  declare axiom D_dec_det (g : (glob D)) (a0 : D_K) (a1 : C_1) : phoare[ D.dec : (glob D) = g /\ k = a0 /\ c = a1 ==> (glob D) = g /\ res = D_c.ev_dec a0 a1 ] = 1%r.

  declare axiom E_dec_det (g : (glob E)) (a0 : E_K) (a1 : C_2) : phoare[ E.dec : (glob E) = g /\ k = a0 /\ c = a1 ==> (glob E) = g /\ res = E_c.ev_dec a0 a1 ] = 1%r.

  (* ===== Per-hop equivalence lemmas ===== *)

  lemma hop_0_initialize :
    equiv [ DSE_c.INDCPA__MultiChal_Real(GeneralDoubleSymEnc(D, E)).initialize ~ R1(D, E, GeneralDoubleSymEnc(D, E), E_c.INDCPA__MultiChal_Real(E)).initialize :
            ={glob D} /\ ={glob E} ==> ={res} /\ ={glob D} /\ ={glob E} /\ DSE_c.INDCPA__MultiChal_Real.k{1} = E_c.INDCPA__MultiChal_Real.k{2} ].
  proof.
    (* resolution: synth-param *)
    proc.
    inline *.
    swap{2} [2..2] -1.
    wp.
    call (_: true).
    wp.
    call (_: true).
    skip => /#.
    qed.

  lemma hop_0_ctxt :
    equiv [ DSE_c.INDCPA__MultiChal_Real(GeneralDoubleSymEnc(D, E)).ctxt ~ R1(D, E, GeneralDoubleSymEnc(D, E), E_c.INDCPA__MultiChal_Real(E)).ctxt :
            ={m} /\ ={glob D} /\ ={glob E} /\ DSE_c.INDCPA__MultiChal_Real.k{1} = E_c.INDCPA__MultiChal_Real.k{2} ==> ={res} /\ ={glob D} /\ ={glob E} /\ DSE_c.INDCPA__MultiChal_Real.k{1} = E_c.INDCPA__MultiChal_Real.k{2} ].
  proof.
    (* resolution: admit-guided *)
    (* multi-oracle hop 0, oracle 'ctxt': post-init
       body transformed along the chain; not closed by proc; sim / reorder.
       VALIDATED fill template (det-axiom finisher; KEMPRF hop_0_challenge
       compiles EC EXIT 0). Fill <...> with this hop's EC inline names:
         proc. inline *. sp. wp.
         seq 1 1 : (={glob K, glob F} /\ <encapsResL>{1} = <encapsResR>{2}
                    /\ <live-state coupling>).
         + sim.                          (* relate the abstract encaps calls *)
         sp. wp.
         exists* (glob F){1}, <FseedL>{1}, <FinputL>{1}; elim* => gf1 a0 a1.
         call{1} (F_evaluate_det gf1 a0 a1).
         exists* (glob F){2}, <FseedR>{2}, <FinputR>{2}; elim* => gf2 b0 b1.
         call{2} (F_evaluate_det gf2 b0 b1).
         skip => /#.
       A reusable name-independent helper for the F.evaluate step (derive
       once per primitive from F_evaluate_det; lets 'wp. call F_evaluate_equiv'
       replace the two exists*/call blocks):
         lemma F_evaluate_equiv : equiv[ F.evaluate ~ F.evaluate :
           ={glob F, seed, input} ==> ={res, glob F} ].
         proof. proc*; exists* (glob F){1}, seed{1}, input{1}; elim* => g s i;
           call{1} (F_evaluate_det g s i); call{2} (F_evaluate_det g s i);
           skip => /#. qed.
       Per-shape variants (the body transform differs by hop):
       - distribution swap (e.g. dsharedsecret <-> dbs_lambda under the
         requires-equality alias): couple the two uniform samples with rnd,
         discharging the distribution equality from is_funiform + is_full;
       - sample/encaps order swap: swap{i} to align, then the det finisher;
       - dead F.evaluate: call{i} (F_evaluate_det ...) to drop it, then sim. *)
    admit.
    qed.

  lemma hop_2_initialize :
    equiv [ R1(D, E, GeneralDoubleSymEnc(D, E), E_c.INDCPA__MultiChal_Random(E)).initialize ~ DSE_c.INDCPA__MultiChal_Random(GeneralDoubleSymEnc(D, E)).initialize :
            ={glob D} /\ ={glob E} ==> ={res} /\ ={glob D} /\ ={glob E} /\ E_c.INDCPA__MultiChal_Random.k{1} = DSE_c.INDCPA__MultiChal_Random.k{2} ].
  proof.
    (* resolution: synth-param *)
    proc.
    inline *.
    swap{1} [2..2] -1.
    wp.
    call (_: true).
    wp.
    call (_: true).
    skip => /#.
    qed.

  lemma hop_2_ctxt :
    equiv [ R1(D, E, GeneralDoubleSymEnc(D, E), E_c.INDCPA__MultiChal_Random(E)).ctxt ~ DSE_c.INDCPA__MultiChal_Random(GeneralDoubleSymEnc(D, E)).ctxt :
            ={m} /\ ={glob D} /\ ={glob E} /\ E_c.INDCPA__MultiChal_Random.k{1} = DSE_c.INDCPA__MultiChal_Random.k{2} ==> ={res} /\ ={glob D} /\ ={glob E} /\ E_c.INDCPA__MultiChal_Random.k{1} = DSE_c.INDCPA__MultiChal_Random.k{2} ].
  proof.
    (* resolution: admit-guided *)
    (* multi-oracle hop 2, oracle 'ctxt': post-init
       body transformed along the chain; not closed by proc; sim / reorder.
       VALIDATED fill template (det-axiom finisher; KEMPRF hop_0_challenge
       compiles EC EXIT 0). Fill <...> with this hop's EC inline names:
         proc. inline *. sp. wp.
         seq 1 1 : (={glob K, glob F} /\ <encapsResL>{1} = <encapsResR>{2}
                    /\ <live-state coupling>).
         + sim.                          (* relate the abstract encaps calls *)
         sp. wp.
         exists* (glob F){1}, <FseedL>{1}, <FinputL>{1}; elim* => gf1 a0 a1.
         call{1} (F_evaluate_det gf1 a0 a1).
         exists* (glob F){2}, <FseedR>{2}, <FinputR>{2}; elim* => gf2 b0 b1.
         call{2} (F_evaluate_det gf2 b0 b1).
         skip => /#.
       A reusable name-independent helper for the F.evaluate step (derive
       once per primitive from F_evaluate_det; lets 'wp. call F_evaluate_equiv'
       replace the two exists*/call blocks):
         lemma F_evaluate_equiv : equiv[ F.evaluate ~ F.evaluate :
           ={glob F, seed, input} ==> ={res, glob F} ].
         proof. proc*; exists* (glob F){1}, seed{1}, input{1}; elim* => g s i;
           call{1} (F_evaluate_det g s i); call{2} (F_evaluate_det g s i);
           skip => /#. qed.
       Per-shape variants (the body transform differs by hop):
       - distribution swap (e.g. dsharedsecret <-> dbs_lambda under the
         requires-equality alias): couple the two uniform samples with rnd,
         discharging the distribution equality from is_funiform + is_full;
       - sample/encaps order swap: swap{i} to align, then the det finisher;
       - dead F.evaluate: call{i} (F_evaluate_det ...) to drop it, then sim. *)
    admit.
    qed.

  (* ===== Per-hop probability lemmas ===== *)

  (* Hop 0: interchangeability. The two adjacent games are equivalent (no advantage). *)

  lemma hop_0_pr (A <: DSE_c.INDCPA__MultiChal_Adv {-D, -E, -DSE_c.INDCPA__MultiChal_Random, -DSE_c.INDCPA__MultiChal_Real, -E_c.INDCPA__MultiChal_Random, -E_c.INDCPA__MultiChal_Real, -R1}) &m :
    Pr[Game_step_0(D, E, A).main() @ &m : res] = Pr[Game_step_1(D, E, A).main() @ &m : res].
  proof.
    byequiv (_: ={glob A, glob D, glob E} ==> ={res}) => //.
    proc.
    call (_: ={glob D} /\ ={glob E} /\ DSE_c.INDCPA__MultiChal_Real.k{1} = E_c.INDCPA__MultiChal_Real.k{2}).
    + conseq hop_0_ctxt.
    call hop_0_initialize.
    auto.
    qed.

  (* Hop 1: assumption hop. Bounded by the INDCPA$_MultiChal_advantage axiom applied to R1_Adv. *)

  lemma hop_1_pr (A <: DSE_c.INDCPA__MultiChal_Adv {-D, -E, -DSE_c.INDCPA__MultiChal_Random, -DSE_c.INDCPA__MultiChal_Real, -E_c.INDCPA__MultiChal_Random, -E_c.INDCPA__MultiChal_Real, -R1}) &m :
    `| Pr[Game_step_1(D, E, A).main() @ &m : res] - Pr[Game_step_2(D, E, A).main() @ &m : res] | <= E_c.eps_INDCPA__MultiChal.
  proof.
    have hL : Pr[Game_step_1(D, E, A).main() @ &m : res]
            = Pr[E_c.Game_INDCPA__MultiChal_Real(E, R1_Adv(D, E, A)).main() @ &m : res]
      by byequiv (_: ={glob A, glob D, glob E} ==> ={res}) => //; proc; inline *; sim.
    have hR : Pr[Game_step_2(D, E, A).main() @ &m : res]
            = Pr[E_c.Game_INDCPA__MultiChal_Random(E, R1_Adv(D, E, A)).main() @ &m : res]
      by byequiv (_: ={glob A, glob D, glob E} ==> ={res}) => //; proc; inline *; sim.
    rewrite hL hR.
    apply (E_c.INDCPA__MultiChal_advantage E (R1_Adv(D, E, A)) &m).
    qed.

  (* Hop 2: interchangeability. The two adjacent games are equivalent (no advantage). *)

  lemma hop_2_pr (A <: DSE_c.INDCPA__MultiChal_Adv {-D, -E, -DSE_c.INDCPA__MultiChal_Random, -DSE_c.INDCPA__MultiChal_Real, -E_c.INDCPA__MultiChal_Random, -E_c.INDCPA__MultiChal_Real, -R1}) &m :
    Pr[Game_step_2(D, E, A).main() @ &m : res] = Pr[Game_step_3(D, E, A).main() @ &m : res].
  proof.
    byequiv (_: ={glob A, glob D, glob E} ==> ={res}) => //.
    proc.
    call (_: ={glob D} /\ ={glob E} /\ E_c.INDCPA__MultiChal_Random.k{1} = DSE_c.INDCPA__MultiChal_Random.k{2}).
    + conseq hop_2_ctxt.
    call hop_2_initialize.
    auto.
    qed.

  (* ===== Main theorem ===== *)

  lemma main_theorem (A <: DSE_c.INDCPA__MultiChal_Adv {-D, -E, -DSE_c.INDCPA__MultiChal_Random, -DSE_c.INDCPA__MultiChal_Real, -E_c.INDCPA__MultiChal_Random, -E_c.INDCPA__MultiChal_Real, -R1}) &m :
    `| Pr[Game_step_0(D, E, A).main() @ &m : res] - Pr[Game_step_3(D, E, A).main() @ &m : res] | <= E_c.eps_INDCPA__MultiChal.
  proof.
    have h0 := hop_0_pr A &m.
    have h1 := hop_1_pr A &m.
    have h2 := hop_2_pr A &m.
    smt(E_c.eps_INDCPA__MultiChal_pos).
    qed.
end section Main.
