(* Auto-generated by ProofFrog. Do not edit. *)
require import AllCore Distr DProd DMap.

(* ===== Abstract set declarations ===== *)

type MessageSpace.

type CiphertextSpace.

type KeySpace.

(* ===== Concrete primitive types ===== *)

op dCiphertextSpace : CiphertextSpace distr.

axiom dCiphertextSpace_ll : is_lossless dCiphertextSpace.

axiom dCiphertextSpace_fu : is_funiform dCiphertextSpace.

axiom dCiphertextSpace_full : is_full dCiphertextSpace.

(* ===== Abstract theory: primitive + security games + assumption ===== *)

abstract theory SymEnc_Theory.
  type key.

  type message.

  type ciphertext.

  op dciphertext : ciphertext distr.

  axiom dciphertext_ll : is_lossless dciphertext.

  axiom dciphertext_fu : is_funiform dciphertext.

  axiom dciphertext_full : is_full dciphertext.

  module type Scheme = {
    proc keygen() : key
    proc enc(k : key, m : message) : ciphertext
    proc dec(k : key, c : ciphertext) : message option
  }.

  op ev_dec : key -> ciphertext -> message option.

  module type INDCPA_MultiChal_Oracle = {
    proc initialize() : unit
    proc eavesdrop(mL : message, mR : message) : ciphertext
  }.

  module INDCPA_MultiChal_Left (E : Scheme) : INDCPA_MultiChal_Oracle = {
    var k : key
    proc initialize() : unit = {
      k <@ E.keygen();
    }
    proc eavesdrop(mL : message, mR : message) : ciphertext = {
      var _r0 : ciphertext;
      _r0 <@ E.enc(k, mL);
      return _r0;
    }
  }.

  module INDCPA_MultiChal_Right (E : Scheme) : INDCPA_MultiChal_Oracle = {
    var k : key
    proc initialize() : unit = {
      k <@ E.keygen();
    }
    proc eavesdrop(mL : message, mR : message) : ciphertext = {
      var _r0 : ciphertext;
      _r0 <@ E.enc(k, mR);
      return _r0;
    }
  }.

  module type INDCPA_MultiChal_Adv (O : INDCPA_MultiChal_Oracle) = {
    proc distinguish() : bool {O.eavesdrop}
  }.

  module type INDCPA__MultiChal_Oracle = {
    proc initialize() : unit
    proc ctxt(m : message) : ciphertext
  }.

  module INDCPA__MultiChal_Real (E : Scheme) : INDCPA__MultiChal_Oracle = {
    var k : key
    proc initialize() : unit = {
      k <@ E.keygen();
    }
    proc ctxt(m : message) : ciphertext = {
      var _r0 : ciphertext;
      _r0 <@ E.enc(k, m);
      return _r0;
    }
  }.

  module INDCPA__MultiChal_Random (E : Scheme) : INDCPA__MultiChal_Oracle = {
    var k : key
    proc initialize() : unit = {
      k <@ E.keygen();
    }
    proc ctxt(m : message) : ciphertext = {
      var c : ciphertext;
      c <$ dciphertext;
      return c;
    }
  }.

  module type INDCPA__MultiChal_Adv (O : INDCPA__MultiChal_Oracle) = {
    proc distinguish() : bool {O.ctxt}
  }.

  module Game_INDCPA__MultiChal_Real (Em : Scheme, A : INDCPA__MultiChal_Adv) = {
    proc main() : bool = {
      var b : bool;
      INDCPA__MultiChal_Real(Em).initialize();
      b <@ A(INDCPA__MultiChal_Real(Em)).distinguish();
      return b;
    }
  }.

  module Game_INDCPA__MultiChal_Random (Em : Scheme, A : INDCPA__MultiChal_Adv) = {
    proc main() : bool = {
      var b : bool;
      INDCPA__MultiChal_Random(Em).initialize();
      b <@ A(INDCPA__MultiChal_Random(Em)).distinguish();
      return b;
    }
  }.

  op eps_INDCPA__MultiChal : real.

  axiom eps_INDCPA__MultiChal_pos : 0%r <= eps_INDCPA__MultiChal.

  axiom INDCPA__MultiChal_advantage (Em <: Scheme) (A <: INDCPA__MultiChal_Adv) &m :
    `| Pr[Game_INDCPA__MultiChal_Real(Em, A).main() @ &m : res] - Pr[Game_INDCPA__MultiChal_Random(Em, A).main() @ &m : res] | <= eps_INDCPA__MultiChal.
end SymEnc_Theory.

(* ===== Theory instantiation ===== *)

clone SymEnc_Theory as E_c with
  type message <- MessageSpace,
  type ciphertext <- CiphertextSpace,
  type key <- KeySpace,
  op dciphertext <- dCiphertextSpace.

(* ===== Per-clone distribution axioms ===== *)

lemma E_dCiphertextSpace_funi :
  is_funiform dCiphertextSpace.
proof.
  exact dCiphertextSpace_fu.
qed.

lemma E_dCiphertextSpace_ll :
  is_lossless dCiphertextSpace.
proof.
  exact dCiphertextSpace_ll.
qed.

section Main.
  (* ===== Reductions ===== *)

  module R1 (E : E_c.Scheme, Challenger : E_c.INDCPA__MultiChal_Oracle) = {
    proc eavesdrop(mL : MessageSpace, mR : MessageSpace) : CiphertextSpace = {
      var _r0 : CiphertextSpace;
      _r0 <@ Challenger.ctxt(mL);
      return _r0;
    }
  }.

  module R2 (E : E_c.Scheme, Challenger : E_c.INDCPA__MultiChal_Oracle) = {
    proc eavesdrop(mL : MessageSpace, mR : MessageSpace) : CiphertextSpace = {
      var _r0 : CiphertextSpace;
      _r0 <@ Challenger.ctxt(mR);
      return _r0;
    }
  }.

  (* ===== Reductions lifted to assumption-adversaries ===== *)

  module R1_Adv (E : E_c.Scheme, A : E_c.INDCPA_MultiChal_Adv, C : E_c.INDCPA__MultiChal_Oracle) = {
    proc distinguish() : bool = {
      var b : bool;
      var pk0 : unit;
      pk0 <@ R1(E, C).initialize();
      b <@ A(R1(E, C)).distinguish(pk0);
      return b;
    }
  }.

  module R2_Adv (E : E_c.Scheme, A : E_c.INDCPA_MultiChal_Adv, C : E_c.INDCPA__MultiChal_Oracle) = {
    proc distinguish() : bool = {
      var b : bool;
      var pk0 : unit;
      pk0 <@ R2(E, C).initialize();
      b <@ A(R2(E, C)).distinguish(pk0);
      return b;
    }
  }.

  (* ===== Game-step wrappers ===== *)

  (* Game_step_0: INDCPA_MultiChal.Left *)

  module Game_step_0 (E : E_c.Scheme, A : E_c.INDCPA_MultiChal_Adv) = {
    proc main() : bool = {
      var b : bool;
      E_c.INDCPA_MultiChal_Left(E).initialize();
      b <@ A(E_c.INDCPA_MultiChal_Left(E)).distinguish();
      return b;
    }
  }.

  (* Game_step_1: INDCPA$_MultiChal.Real composed with reduction R1 *)

  module Game_step_1 (E : E_c.Scheme, A : E_c.INDCPA_MultiChal_Adv) = {
    proc main() : bool = {
      var b : bool;
      R1(E, E_c.INDCPA__MultiChal_Real(E)).initialize();
      b <@ A(R1(E, E_c.INDCPA__MultiChal_Real(E))).distinguish();
      return b;
    }
  }.

  (* Game_step_2: INDCPA$_MultiChal.Random composed with reduction R1 *)

  module Game_step_2 (E : E_c.Scheme, A : E_c.INDCPA_MultiChal_Adv) = {
    proc main() : bool = {
      var b : bool;
      R1(E, E_c.INDCPA__MultiChal_Random(E)).initialize();
      b <@ A(R1(E, E_c.INDCPA__MultiChal_Random(E))).distinguish();
      return b;
    }
  }.

  (* Game_step_3: INDCPA$_MultiChal.Random composed with reduction R2 *)

  module Game_step_3 (E : E_c.Scheme, A : E_c.INDCPA_MultiChal_Adv) = {
    proc main() : bool = {
      var b : bool;
      R2(E, E_c.INDCPA__MultiChal_Random(E)).initialize();
      b <@ A(R2(E, E_c.INDCPA__MultiChal_Random(E))).distinguish();
      return b;
    }
  }.

  (* Game_step_4: INDCPA$_MultiChal.Real composed with reduction R2 *)

  module Game_step_4 (E : E_c.Scheme, A : E_c.INDCPA_MultiChal_Adv) = {
    proc main() : bool = {
      var b : bool;
      R2(E, E_c.INDCPA__MultiChal_Real(E)).initialize();
      b <@ A(R2(E, E_c.INDCPA__MultiChal_Real(E))).distinguish();
      return b;
    }
  }.

  (* Game_step_5: INDCPA_MultiChal.Right *)

  module Game_step_5 (E : E_c.Scheme, A : E_c.INDCPA_MultiChal_Adv) = {
    proc main() : bool = {
      var b : bool;
      E_c.INDCPA_MultiChal_Right(E).initialize();
      b <@ A(E_c.INDCPA_MultiChal_Right(E)).distinguish();
      return b;
    }
  }.

  (* ===== Per-transform canonicalization chain ===== *)

  module Step_0L_state_0 (E : E_c.Scheme) = {
    var k : KeySpace
    proc initialize() : unit = {
      k <@ E.keygen();
    }
    proc eavesdrop(mL : MessageSpace, mR : MessageSpace) : CiphertextSpace = {
      var _r0 : CiphertextSpace;
      _r0 <@ E.enc(k, mL);
      return _r0;
    }
  }.

  module Step_0L_state_1 (E : E_c.Scheme) = {
    var field1 : KeySpace
    proc initialize() : unit = {
      field1 <@ E.keygen();
    }
    proc eavesdrop(mL : MessageSpace, mR : MessageSpace) : CiphertextSpace = {
      var _r0 : CiphertextSpace;
      _r0 <@ E.enc(field1, mL);
      return _r0;
    }
  }.

  module Step_0R_state_0 (E : E_c.Scheme) = {
    var challenger_k : KeySpace
    proc initialize() : unit = {
      challenger_k <@ E.keygen();
    }
    proc eavesdrop(mL : MessageSpace, mR : MessageSpace) : CiphertextSpace = {
      var _r0 : CiphertextSpace;
      _r0 <@ E.enc(challenger_k, mL);
      return _r0;
    }
  }.

  module Step_0R_state_1 (E : E_c.Scheme) = {
    var field1 : KeySpace
    proc initialize() : unit = {
      field1 <@ E.keygen();
    }
    proc eavesdrop(mL : MessageSpace, mR : MessageSpace) : CiphertextSpace = {
      var _r0 : CiphertextSpace;
      _r0 <@ E.enc(field1, mL);
      return _r0;
    }
  }.

  module Step_2L_state_0 (E : E_c.Scheme) = {
    var challenger_k : KeySpace
    proc initialize() : unit = {
      challenger_k <@ E.keygen();
    }
    proc eavesdrop(mL : MessageSpace, mR : MessageSpace) : CiphertextSpace = {
      var challenger_CTXT_c0 : CiphertextSpace;
      challenger_CTXT_c0 <$ dCiphertextSpace;
      return challenger_CTXT_c0;
    }
  }.

  module Step_2L_state_1 (E : E_c.Scheme) = {
    var challenger_k : KeySpace
    proc initialize() : unit = {
      challenger_k <@ E.keygen();
    }
    proc eavesdrop(mL : MessageSpace, mR : MessageSpace) : CiphertextSpace = {
      var __a0__ : CiphertextSpace;
      __a0__ <$ dCiphertextSpace;
      return __a0__;
    }
  }.

  module Step_2L_state_2 (E : E_c.Scheme) = {
    proc eavesdrop(mL : MessageSpace, mR : MessageSpace) : CiphertextSpace = {
      var __a0__ : CiphertextSpace;
      __a0__ <$ dCiphertextSpace;
      return __a0__;
    }
  }.

  module Step_2L_state_3 (E : E_c.Scheme) = {
    proc eavesdrop(mL : MessageSpace, mR : MessageSpace) : CiphertextSpace = {
      var v1 : CiphertextSpace;
      v1 <$ dCiphertextSpace;
      return v1;
    }
  }.

  module Step_2R_state_0 (E : E_c.Scheme) = {
    var challenger_k : KeySpace
    proc initialize() : unit = {
      challenger_k <@ E.keygen();
    }
    proc eavesdrop(mL : MessageSpace, mR : MessageSpace) : CiphertextSpace = {
      var challenger_CTXT_c0 : CiphertextSpace;
      challenger_CTXT_c0 <$ dCiphertextSpace;
      return challenger_CTXT_c0;
    }
  }.

  module Step_2R_state_1 (E : E_c.Scheme) = {
    var challenger_k : KeySpace
    proc initialize() : unit = {
      challenger_k <@ E.keygen();
    }
    proc eavesdrop(mL : MessageSpace, mR : MessageSpace) : CiphertextSpace = {
      var __a0__ : CiphertextSpace;
      __a0__ <$ dCiphertextSpace;
      return __a0__;
    }
  }.

  module Step_2R_state_2 (E : E_c.Scheme) = {
    proc eavesdrop(mL : MessageSpace, mR : MessageSpace) : CiphertextSpace = {
      var __a0__ : CiphertextSpace;
      __a0__ <$ dCiphertextSpace;
      return __a0__;
    }
  }.

  module Step_2R_state_3 (E : E_c.Scheme) = {
    proc eavesdrop(mL : MessageSpace, mR : MessageSpace) : CiphertextSpace = {
      var v1 : CiphertextSpace;
      v1 <$ dCiphertextSpace;
      return v1;
    }
  }.

  module Step_4L_state_0 (E : E_c.Scheme) = {
    var challenger_k : KeySpace
    proc initialize() : unit = {
      challenger_k <@ E.keygen();
    }
    proc eavesdrop(mL : MessageSpace, mR : MessageSpace) : CiphertextSpace = {
      var _r0 : CiphertextSpace;
      _r0 <@ E.enc(challenger_k, mR);
      return _r0;
    }
  }.

  module Step_4L_state_1 (E : E_c.Scheme) = {
    var field1 : KeySpace
    proc initialize() : unit = {
      field1 <@ E.keygen();
    }
    proc eavesdrop(mL : MessageSpace, mR : MessageSpace) : CiphertextSpace = {
      var _r0 : CiphertextSpace;
      _r0 <@ E.enc(field1, mR);
      return _r0;
    }
  }.

  module Step_4R_state_0 (E : E_c.Scheme) = {
    var k : KeySpace
    proc initialize() : unit = {
      k <@ E.keygen();
    }
    proc eavesdrop(mL : MessageSpace, mR : MessageSpace) : CiphertextSpace = {
      var _r0 : CiphertextSpace;
      _r0 <@ E.enc(k, mR);
      return _r0;
    }
  }.

  module Step_4R_state_1 (E : E_c.Scheme) = {
    var field1 : KeySpace
    proc initialize() : unit = {
      field1 <@ E.keygen();
    }
    proc eavesdrop(mL : MessageSpace, mR : MessageSpace) : CiphertextSpace = {
      var _r0 : CiphertextSpace;
      _r0 <@ E.enc(field1, mR);
      return _r0;
    }
  }.

  declare module E <: E_c.Scheme {-E_c.INDCPA_MultiChal_Left, -E_c.INDCPA_MultiChal_Right, -E_c.INDCPA__MultiChal_Random, -E_c.INDCPA__MultiChal_Real, -Step_0L_state_0, -Step_0L_state_1, -Step_0R_state_0, -Step_0R_state_1, -Step_2L_state_0, -Step_2L_state_1, -Step_2L_state_2, -Step_2L_state_3, -Step_2R_state_0, -Step_2R_state_1, -Step_2R_state_2, -Step_2R_state_3, -Step_4L_state_0, -Step_4L_state_1, -Step_4R_state_0, -Step_4R_state_1}.

  (* ===== Deterministic-method specs ===== *)

  declare axiom E_dec_det (g : (glob E)) (a0 : KeySpace) (a1 : CiphertextSpace) : phoare[ E.dec : (glob E) = g /\ k = a0 /\ c = a1 ==> (glob E) = g /\ res = E_c.ev_dec a0 a1 ] = 1%r.

  lemma micro_0_eavesdrop_left_0 :
    equiv [ Step_0L_state_0(E).eavesdrop ~ Step_0L_state_1(E).eavesdrop :
            ={mL, mR} /\ (glob Step_0L_state_0(E)){1} = (glob Step_0L_state_1(E)){2} ==> ={res} /\ (glob Step_0L_state_0(E)){1} = (glob Step_0L_state_1(E)){2} ].
  proof.
    proc.
    sim.
  qed.

  lemma micro_0_eavesdrop_right_0_rev :
    equiv [ Step_0R_state_1(E).eavesdrop ~ Step_0R_state_0(E).eavesdrop :
            ={mL, mR} /\ (glob Step_0R_state_1(E)){1} = (glob Step_0R_state_0(E)){2} ==> ={res} /\ (glob Step_0R_state_1(E)){1} = (glob Step_0R_state_0(E)){2} ].
  proof.
    proc.
    sim.
  qed.

  lemma canon_bridge_0_eavesdrop :
    equiv [ Step_0L_state_1(E).eavesdrop ~ Step_0R_state_1(E).eavesdrop :
            ={mL, mR} /\ (glob Step_0L_state_1(E)){1} = (glob Step_0R_state_1(E)){2} ==> ={res} /\ (glob Step_0L_state_1(E)){1} = (glob Step_0R_state_1(E)){2} ].
  proof.
    proc; sim.
  qed.

  lemma hop_0_eavesdrop_chain :
    equiv [ Step_0L_state_0(E).eavesdrop ~ Step_0R_state_0(E).eavesdrop :
            ={mL, mR} /\ (glob Step_0L_state_0(E)){1} = (glob Step_0R_state_0(E)){2} ==> ={res} /\ (glob Step_0L_state_0(E)){1} = (glob Step_0R_state_0(E)){2} ].
  proof.
    (* Chain through per-transform micro-lemmas (coupling-preserving). *)
    transitivity Step_0L_state_1(E).eavesdrop (={mL, mR} /\ (glob Step_0L_state_0(E)){1} = (glob Step_0L_state_1(E)){2} ==> ={res} /\ (glob Step_0L_state_0(E)){1} = (glob Step_0L_state_1(E)){2}) (={mL, mR} /\ (glob Step_0L_state_1(E)){1} = (glob Step_0R_state_0(E)){2} ==> ={res} /\ (glob Step_0L_state_1(E)){1} = (glob Step_0R_state_0(E)){2}); [ smt() | smt() | apply micro_0_eavesdrop_left_0 |].
    transitivity Step_0R_state_1(E).eavesdrop (={mL, mR} /\ (glob Step_0L_state_1(E)){1} = (glob Step_0R_state_1(E)){2} ==> ={res} /\ (glob Step_0L_state_1(E)){1} = (glob Step_0R_state_1(E)){2}) (={mL, mR} /\ (glob Step_0R_state_1(E)){1} = (glob Step_0R_state_0(E)){2} ==> ={res} /\ (glob Step_0R_state_1(E)){1} = (glob Step_0R_state_0(E)){2}); [ smt() | smt() | apply canon_bridge_0_eavesdrop |].
    apply micro_0_eavesdrop_right_0_rev.
  qed.

  lemma micro_4_eavesdrop_left_0 :
    equiv [ Step_4L_state_0(E).eavesdrop ~ Step_4L_state_1(E).eavesdrop :
            ={mL, mR} /\ (glob Step_4L_state_0(E)){1} = (glob Step_4L_state_1(E)){2} ==> ={res} /\ (glob Step_4L_state_0(E)){1} = (glob Step_4L_state_1(E)){2} ].
  proof.
    proc.
    sim.
  qed.

  lemma micro_4_eavesdrop_right_0_rev :
    equiv [ Step_4R_state_1(E).eavesdrop ~ Step_4R_state_0(E).eavesdrop :
            ={mL, mR} /\ (glob Step_4R_state_1(E)){1} = (glob Step_4R_state_0(E)){2} ==> ={res} /\ (glob Step_4R_state_1(E)){1} = (glob Step_4R_state_0(E)){2} ].
  proof.
    proc.
    sim.
  qed.

  lemma canon_bridge_4_eavesdrop :
    equiv [ Step_4L_state_1(E).eavesdrop ~ Step_4R_state_1(E).eavesdrop :
            ={mL, mR} /\ (glob Step_4L_state_1(E)){1} = (glob Step_4R_state_1(E)){2} ==> ={res} /\ (glob Step_4L_state_1(E)){1} = (glob Step_4R_state_1(E)){2} ].
  proof.
    proc; sim.
  qed.

  lemma hop_4_eavesdrop_chain :
    equiv [ Step_4L_state_0(E).eavesdrop ~ Step_4R_state_0(E).eavesdrop :
            ={mL, mR} /\ (glob Step_4L_state_0(E)){1} = (glob Step_4R_state_0(E)){2} ==> ={res} /\ (glob Step_4L_state_0(E)){1} = (glob Step_4R_state_0(E)){2} ].
  proof.
    (* Chain through per-transform micro-lemmas (coupling-preserving). *)
    transitivity Step_4L_state_1(E).eavesdrop (={mL, mR} /\ (glob Step_4L_state_0(E)){1} = (glob Step_4L_state_1(E)){2} ==> ={res} /\ (glob Step_4L_state_0(E)){1} = (glob Step_4L_state_1(E)){2}) (={mL, mR} /\ (glob Step_4L_state_1(E)){1} = (glob Step_4R_state_0(E)){2} ==> ={res} /\ (glob Step_4L_state_1(E)){1} = (glob Step_4R_state_0(E)){2}); [ smt() | smt() | apply micro_4_eavesdrop_left_0 |].
    transitivity Step_4R_state_1(E).eavesdrop (={mL, mR} /\ (glob Step_4L_state_1(E)){1} = (glob Step_4R_state_1(E)){2} ==> ={res} /\ (glob Step_4L_state_1(E)){1} = (glob Step_4R_state_1(E)){2}) (={mL, mR} /\ (glob Step_4R_state_1(E)){1} = (glob Step_4R_state_0(E)){2} ==> ={res} /\ (glob Step_4R_state_1(E)){1} = (glob Step_4R_state_0(E)){2}); [ smt() | smt() | apply canon_bridge_4_eavesdrop |].
    apply micro_4_eavesdrop_right_0_rev.
  qed.

  (* ===== Per-hop equivalence lemmas ===== *)

  lemma hop_0_initialize :
    equiv [ E_c.INDCPA_MultiChal_Left(E).initialize ~ R1(E, E_c.INDCPA__MultiChal_Real(E)).initialize :
            ={glob E} ==> ={res} /\ ={glob E} /\ E_c.INDCPA_MultiChal_Left.k{1} = E_c.INDCPA__MultiChal_Real.k{2} ].
  proof.
    (* resolution: synth-static *)
    proc; inline *; sim.
    qed.

  lemma hop_0_eavesdrop :
    equiv [ E_c.INDCPA_MultiChal_Left(E).eavesdrop ~ R1(E, E_c.INDCPA__MultiChal_Real(E)).eavesdrop :
            ={mL, mR} /\ ={glob E} /\ E_c.INDCPA_MultiChal_Left.k{1} = E_c.INDCPA__MultiChal_Real.k{2} ==> ={res} /\ ={glob E} /\ E_c.INDCPA_MultiChal_Left.k{1} = E_c.INDCPA__MultiChal_Real.k{2} ].
  proof.
    (* Per-transform: bridge wrappers to flat states, chain through. *)
    transitivity Step_0L_state_0(E).eavesdrop (={mL, mR} /\ (glob E_c.INDCPA_MultiChal_Left(E)){1} = (glob Step_0L_state_0(E)){2} ==> ={res} /\ (glob E_c.INDCPA_MultiChal_Left(E)){1} = (glob Step_0L_state_0(E)){2}) (={mL, mR} /\ (glob Step_0L_state_0(E)){1} = (glob R1(E, E_c.INDCPA__MultiChal_Real(E))){2} ==> ={res} /\ (glob Step_0L_state_0(E)){1} = (glob R1(E, E_c.INDCPA__MultiChal_Real(E))){2}); [ smt() | smt() | proc; inline *; ((sp; wp; sim) || sim) |].
    transitivity Step_0R_state_0(E).eavesdrop (={mL, mR} /\ (glob Step_0L_state_0(E)){1} = (glob Step_0R_state_0(E)){2} ==> ={res} /\ (glob Step_0L_state_0(E)){1} = (glob Step_0R_state_0(E)){2}) (={mL, mR} /\ (glob Step_0R_state_0(E)){1} = (glob R1(E, E_c.INDCPA__MultiChal_Real(E))){2} ==> ={res} /\ (glob Step_0R_state_0(E)){1} = (glob R1(E, E_c.INDCPA__MultiChal_Real(E))){2}); [ smt() | smt() | apply hop_0_eavesdrop_chain | proc; inline *; ((sp; wp; sim) || sim) ].
    qed.

  lemma hop_2_initialize :
    equiv [ R1(E, E_c.INDCPA__MultiChal_Random(E)).initialize ~ R2(E, E_c.INDCPA__MultiChal_Random(E)).initialize :
            ={glob E} ==> ={res} /\ ={glob E} /\ E_c.INDCPA__MultiChal_Random.k{1} = E_c.INDCPA__MultiChal_Random.k{2} ].
  proof.
    (* resolution: synth-static *)
    proc; inline *; sim.
    qed.

  lemma hop_2_eavesdrop :
    equiv [ R1(E, E_c.INDCPA__MultiChal_Random(E)).eavesdrop ~ R2(E, E_c.INDCPA__MultiChal_Random(E)).eavesdrop :
            ={mL, mR} /\ ={glob E} /\ E_c.INDCPA__MultiChal_Random.k{1} = E_c.INDCPA__MultiChal_Random.k{2} ==> ={res} /\ ={glob E} /\ E_c.INDCPA__MultiChal_Random.k{1} = E_c.INDCPA__MultiChal_Random.k{2} ].
  proof.
    (* resolution: synth-param *)
    proc.
    inline *.
    do ! (wp; call (_: true)).
    wp.
    skip => /#.
    qed.

  lemma hop_4_initialize :
    equiv [ R2(E, E_c.INDCPA__MultiChal_Real(E)).initialize ~ E_c.INDCPA_MultiChal_Right(E).initialize :
            ={glob E} ==> ={res} /\ ={glob E} /\ E_c.INDCPA__MultiChal_Real.k{1} = E_c.INDCPA_MultiChal_Right.k{2} ].
  proof.
    (* resolution: synth-static *)
    proc; inline *; sim.
    qed.

  lemma hop_4_eavesdrop :
    equiv [ R2(E, E_c.INDCPA__MultiChal_Real(E)).eavesdrop ~ E_c.INDCPA_MultiChal_Right(E).eavesdrop :
            ={mL, mR} /\ ={glob E} /\ E_c.INDCPA__MultiChal_Real.k{1} = E_c.INDCPA_MultiChal_Right.k{2} ==> ={res} /\ ={glob E} /\ E_c.INDCPA__MultiChal_Real.k{1} = E_c.INDCPA_MultiChal_Right.k{2} ].
  proof.
    (* Per-transform: bridge wrappers to flat states, chain through. *)
    transitivity Step_4L_state_0(E).eavesdrop (={mL, mR} /\ (glob R2(E, E_c.INDCPA__MultiChal_Real(E))){1} = (glob Step_4L_state_0(E)){2} ==> ={res} /\ (glob R2(E, E_c.INDCPA__MultiChal_Real(E))){1} = (glob Step_4L_state_0(E)){2}) (={mL, mR} /\ (glob Step_4L_state_0(E)){1} = (glob E_c.INDCPA_MultiChal_Right(E)){2} ==> ={res} /\ (glob Step_4L_state_0(E)){1} = (glob E_c.INDCPA_MultiChal_Right(E)){2}); [ smt() | smt() | proc; inline *; ((sp; wp; sim) || sim) |].
    transitivity Step_4R_state_0(E).eavesdrop (={mL, mR} /\ (glob Step_4L_state_0(E)){1} = (glob Step_4R_state_0(E)){2} ==> ={res} /\ (glob Step_4L_state_0(E)){1} = (glob Step_4R_state_0(E)){2}) (={mL, mR} /\ (glob Step_4R_state_0(E)){1} = (glob E_c.INDCPA_MultiChal_Right(E)){2} ==> ={res} /\ (glob Step_4R_state_0(E)){1} = (glob E_c.INDCPA_MultiChal_Right(E)){2}); [ smt() | smt() | apply hop_4_eavesdrop_chain | proc; inline *; ((sp; wp; sim) || sim) ].
    qed.

  (* ===== Per-hop probability lemmas ===== *)

  (* Hop 0: interchangeability. The two adjacent games are equivalent (no advantage). *)

  lemma hop_0_pr (A <: E_c.INDCPA_MultiChal_Adv {-E, -E_c.INDCPA_MultiChal_Left, -E_c.INDCPA_MultiChal_Right, -E_c.INDCPA__MultiChal_Random, -E_c.INDCPA__MultiChal_Real}) &m :
    Pr[Game_step_0(E, A).main() @ &m : res] = Pr[Game_step_1(E, A).main() @ &m : res].
  proof.
    byequiv (_: ={glob A, glob E} ==> ={res}) => //.
    proc.
    call (_: ={glob E} /\ E_c.INDCPA_MultiChal_Left.k{1} = E_c.INDCPA__MultiChal_Real.k{2}).
    + conseq hop_0_eavesdrop.
    call hop_0_initialize.
    auto.
    qed.

  (* Hop 1: assumption hop. Bounded by the INDCPA$_MultiChal_advantage axiom applied to R1_Adv. *)

  lemma hop_1_pr (A <: E_c.INDCPA_MultiChal_Adv {-E, -E_c.INDCPA_MultiChal_Left, -E_c.INDCPA_MultiChal_Right, -E_c.INDCPA__MultiChal_Random, -E_c.INDCPA__MultiChal_Real}) &m :
    `| Pr[Game_step_1(E, A).main() @ &m : res] - Pr[Game_step_2(E, A).main() @ &m : res] | <= E_c.eps_INDCPA__MultiChal.
  proof.
    have hL : Pr[Game_step_1(E, A).main() @ &m : res]
            = Pr[E_c.Game_INDCPA__MultiChal_Real(E, R1_Adv(E, A)).main() @ &m : res]
      by byequiv (_: ={glob A, glob E} ==> ={res}) => //; proc; inline *; sim.
    have hR : Pr[Game_step_2(E, A).main() @ &m : res]
            = Pr[E_c.Game_INDCPA__MultiChal_Random(E, R1_Adv(E, A)).main() @ &m : res]
      by byequiv (_: ={glob A, glob E} ==> ={res}) => //; proc; inline *; sim.
    rewrite hL hR.
    apply (E_c.INDCPA__MultiChal_advantage E (R1_Adv(E, A)) &m).
    qed.

  (* Hop 2: interchangeability. The two adjacent games are equivalent (no advantage). *)

  lemma hop_2_pr (A <: E_c.INDCPA_MultiChal_Adv {-E, -E_c.INDCPA_MultiChal_Left, -E_c.INDCPA_MultiChal_Right, -E_c.INDCPA__MultiChal_Random, -E_c.INDCPA__MultiChal_Real}) &m :
    Pr[Game_step_2(E, A).main() @ &m : res] = Pr[Game_step_3(E, A).main() @ &m : res].
  proof.
    byequiv (_: ={glob A, glob E} ==> ={res}) => //.
    proc.
    call (_: ={glob E} /\ E_c.INDCPA__MultiChal_Random.k{1} = E_c.INDCPA__MultiChal_Random.k{2}).
    + conseq hop_2_eavesdrop.
    call hop_2_initialize.
    auto.
    qed.

  (* Hop 3: assumption hop. Bounded by the INDCPA$_MultiChal_advantage axiom applied to R2_Adv. *)

  lemma hop_3_pr (A <: E_c.INDCPA_MultiChal_Adv {-E, -E_c.INDCPA_MultiChal_Left, -E_c.INDCPA_MultiChal_Right, -E_c.INDCPA__MultiChal_Random, -E_c.INDCPA__MultiChal_Real}) &m :
    `| Pr[Game_step_3(E, A).main() @ &m : res] - Pr[Game_step_4(E, A).main() @ &m : res] | <= E_c.eps_INDCPA__MultiChal.
  proof.
    have hL : Pr[Game_step_3(E, A).main() @ &m : res]
            = Pr[E_c.Game_INDCPA__MultiChal_Random(E, R2_Adv(E, A)).main() @ &m : res]
      by byequiv (_: ={glob A, glob E} ==> ={res}) => //; proc; inline *; sim.
    have hR : Pr[Game_step_4(E, A).main() @ &m : res]
            = Pr[E_c.Game_INDCPA__MultiChal_Real(E, R2_Adv(E, A)).main() @ &m : res]
      by byequiv (_: ={glob A, glob E} ==> ={res}) => //; proc; inline *; sim.
    rewrite hL hR.
    have H := E_c.INDCPA__MultiChal_advantage E (R2_Adv(E, A)) &m.
    smt().
    qed.

  (* Hop 4: interchangeability. The two adjacent games are equivalent (no advantage). *)

  lemma hop_4_pr (A <: E_c.INDCPA_MultiChal_Adv {-E, -E_c.INDCPA_MultiChal_Left, -E_c.INDCPA_MultiChal_Right, -E_c.INDCPA__MultiChal_Random, -E_c.INDCPA__MultiChal_Real}) &m :
    Pr[Game_step_4(E, A).main() @ &m : res] = Pr[Game_step_5(E, A).main() @ &m : res].
  proof.
    byequiv (_: ={glob A, glob E} ==> ={res}) => //.
    proc.
    call (_: ={glob E} /\ E_c.INDCPA__MultiChal_Real.k{1} = E_c.INDCPA_MultiChal_Right.k{2}).
    + conseq hop_4_eavesdrop.
    call hop_4_initialize.
    auto.
    qed.

  (* ===== Main theorem ===== *)

  lemma main_theorem (A <: E_c.INDCPA_MultiChal_Adv {-E, -E_c.INDCPA_MultiChal_Left, -E_c.INDCPA_MultiChal_Right, -E_c.INDCPA__MultiChal_Random, -E_c.INDCPA__MultiChal_Real}) &m :
    `| Pr[Game_step_0(E, A).main() @ &m : res] - Pr[Game_step_5(E, A).main() @ &m : res] | <= E_c.eps_INDCPA__MultiChal + E_c.eps_INDCPA__MultiChal.
  proof.
    have h0 := hop_0_pr A &m.
    have h1 := hop_1_pr A &m.
    have h2 := hop_2_pr A &m.
    have h3 := hop_3_pr A &m.
    have h4 := hop_4_pr A &m.
    smt(E_c.eps_INDCPA__MultiChal_pos).
    qed.
end section Main.
