(* Auto-generated by ProofFrog. Do not edit. *)
require import AllCore Distr DProd DMap.

(* ===== Abstract set declarations ===== *)

type MessageSpace.

type KeySpace.

(* ===== Concrete primitive types ===== *)

op dMessageSpace : MessageSpace distr.

axiom dMessageSpace_ll : is_lossless dMessageSpace.

axiom dMessageSpace_fu : is_funiform dMessageSpace.

axiom dMessageSpace_full : is_full dMessageSpace.

(* ===== Abstract theory: primitive + security games + assumption ===== *)

abstract theory SymEnc_Theory.
  type key.

  type message.

  type ciphertext.

  op dciphertext : ciphertext distr.

  axiom dciphertext_ll : is_lossless dciphertext.

  axiom dciphertext_fu : is_funiform dciphertext.

  axiom dciphertext_full : is_full dciphertext.

  module type Scheme = {
    proc keygen() : key
    proc enc(k : key, m : message) : ciphertext
    proc dec(k : key, c : ciphertext) : message
  }.

  op ev_dec : key -> ciphertext -> message.

  (* Statelessness foundation *)

  op dkeygen : key distr.

  op denc : key -> message -> ciphertext distr.

  axiom dkeygen_ll : is_lossless dkeygen.

  axiom denc_ll : forall a0 a1, is_lossless (denc a0 a1).

  module Ideal : Scheme = {
  proc keygen() : key = { var r : key; r <$ dkeygen; return r; }
  proc enc(k : key, m : message) : ciphertext = { var r : ciphertext; r <$ denc k m; return r; }
  proc dec(k : key, c : ciphertext) : message = { return ev_dec k c; }
}.

  module type INDOT__Oracle = {
    proc ctxt(m : message) : ciphertext
  }.

  module INDOT__Real (E : Scheme) : INDOT__Oracle = {
    proc ctxt(m : message) : ciphertext = {
      var k : key;
      var c : ciphertext;
      k <@ E.keygen();
      c <@ E.enc(k, m);
      return c;
    }
  }.

  module INDOT__Random (E : Scheme) : INDOT__Oracle = {
    proc ctxt(m : message) : ciphertext = {
      var c : ciphertext;
      c <$ dciphertext;
      return c;
    }
  }.

  module type INDOT__Adv (O : INDOT__Oracle) = {
    proc distinguish() : bool
  }.

  module Game_INDOT__Real (Em : Scheme, A : INDOT__Adv) = {
    proc main() : bool = {
      var b : bool;
      b <@ A(INDOT__Real(Em)).distinguish();
      return b;
    }
  }.

  module Game_INDOT__Random (Em : Scheme, A : INDOT__Adv) = {
    proc main() : bool = {
      var b : bool;
      b <@ A(INDOT__Random(Em)).distinguish();
      return b;
    }
  }.

  op eps_INDOT_ : real.

  axiom eps_INDOT__pos : 0%r <= eps_INDOT_.

  axiom INDOT__advantage (Em <: Scheme) (A <: INDOT__Adv) &m :
    `| Pr[Game_INDOT__Real(Em, A).main() @ &m : res] - Pr[Game_INDOT__Random(Em, A).main() @ &m : res] | <= eps_INDOT_.
end SymEnc_Theory.

(* ===== Theory instantiation ===== *)

clone SymEnc_Theory as E_c with
  type message <- MessageSpace,
  type ciphertext <- MessageSpace,
  type key <- KeySpace,
  op dciphertext <- dMessageSpace.

clone SymEnc_Theory as D_c with
  type message <- MessageSpace,
  type ciphertext <- MessageSpace,
  type key <- KeySpace * KeySpace,
  op dciphertext <- dMessageSpace.

(* ===== Per-clone distribution axioms ===== *)

lemma E_dMessageSpace_funi :
  is_funiform dMessageSpace.
proof.
  exact dMessageSpace_fu.
qed.

lemma E_dMessageSpace_ll :
  is_lossless dMessageSpace.
proof.
  exact dMessageSpace_ll.
qed.

lemma D_dMessageSpace_funi :
  is_funiform dMessageSpace.
proof.
  exact dMessageSpace_fu.
qed.

lemma D_dMessageSpace_ll :
  is_lossless dMessageSpace.
proof.
  exact dMessageSpace_ll.
qed.

(* NOTE: the FrogLang scheme has `requires` clauses that are not enforced by the EC export. The scheme module below may fail EC type-checking because cross-clone type equalities implied by the `requires` are not expressed in the clones. Deferred to Phase 5D. *)

(* ===== Concrete scheme implementation ===== *)

module DoubleSymEnc (S : E_c.Scheme) : D_c.Scheme = {
  proc keygen() : KeySpace * KeySpace = {
    var key1 : KeySpace;
    var key2 : KeySpace;
    key1 <@ S.keygen();
    key2 <@ S.keygen();
    return (key1, key2);
  }
  proc enc(k : KeySpace * KeySpace, m : MessageSpace) : MessageSpace = {
    var c1 : MessageSpace;
    var c2 : MessageSpace;
    c1 <@ S.enc(k.`1, m);
    c2 <@ S.enc(k.`2, c1);
    return c2;
  }
  proc dec(k : KeySpace * KeySpace, c : MessageSpace) : MessageSpace = {
    var c2 : MessageSpace;
    var m : MessageSpace;
    c2 <@ S.dec(k.`2, c);
    m <@ S.dec(k.`1, c2);
    return m;
  }
}.

section Main.
  declare module E <: E_c.Scheme.

  (* ===== Deterministic-method specs ===== *)

  declare axiom E_dec_det (g : (glob E)) (a0 : KeySpace) (a1 : MessageSpace) : phoare[ E.dec : (glob E) = g /\ k = a0 /\ c = a1 ==> (glob E) = g /\ res = E_c.ev_dec a0 a1 ] = 1%r.

  (* ===== Statelessness specs ===== *)

  declare axiom E_keygen_sem : equiv[ E.keygen ~ E_c.Ideal.keygen : ={glob E} ==> ={res, glob E} ].

  declare axiom E_enc_sem : equiv[ E.enc ~ E_c.Ideal.enc : ={glob E, arg} ==> ={res, glob E} ].

  (* ===== Glob-preservation specs (dead-call drop) ===== *)

  declare axiom E_enc_pres (g : (glob E)) : phoare[ E.enc : (glob E) = g ==> (glob E) = g ] = 1%r.

  declare axiom E_keygen_pres (g : (glob E)) : phoare[ E.keygen : (glob E) = g ==> (glob E) = g ] = 1%r.

  (* ===== Reductions ===== *)

  module R1 (D : D_c.Scheme, E : E_c.Scheme, Challenger : E_c.INDOT__Oracle) = {
    proc ctxt(m : MessageSpace) : MessageSpace = {
      var k : KeySpace;
      var c : MessageSpace;
      var _r0 : MessageSpace;
      k <@ E.keygen();
      c <@ E.enc(k, m);
      _r0 <@ Challenger.ctxt(c);
      return _r0;
    }
  }.

  (* ===== Reductions lifted to assumption-adversaries ===== *)

  module R1_Adv (E : E_c.Scheme, A : D_c.INDOT__Adv, C : E_c.INDOT__Oracle) = {
    proc distinguish() : bool = {
      var b : bool;
      b <@ A(R1(DoubleSymEnc(E), E, C)).distinguish();
      return b;
    }
  }.

  (* ===== Game-step wrappers ===== *)

  (* Game_step_0: INDOT$.Real *)

  module Game_step_0 (E : E_c.Scheme, A : D_c.INDOT__Adv) = {
    proc main() : bool = {
      var b : bool;
      b <@ A(D_c.INDOT__Real(DoubleSymEnc(E))).distinguish();
      return b;
    }
  }.

  (* Game_step_1: INDOT$.Real composed with reduction R1 *)

  module Game_step_1 (E : E_c.Scheme, A : D_c.INDOT__Adv) = {
    proc main() : bool = {
      var b : bool;
      b <@ A(R1(DoubleSymEnc(E), E, E_c.INDOT__Real(E))).distinguish();
      return b;
    }
  }.

  (* Game_step_2: INDOT$.Random composed with reduction R1 *)

  module Game_step_2 (E : E_c.Scheme, A : D_c.INDOT__Adv) = {
    proc main() : bool = {
      var b : bool;
      b <@ A(R1(DoubleSymEnc(E), E, E_c.INDOT__Random(E))).distinguish();
      return b;
    }
  }.

  (* Game_step_3: INDOT$.Random *)

  module Game_step_3 (E : E_c.Scheme, A : D_c.INDOT__Adv) = {
    proc main() : bool = {
      var b : bool;
      b <@ A(D_c.INDOT__Random(DoubleSymEnc(E))).distinguish();
      return b;
    }
  }.

  (* ===== Per-transform canonicalization chain ===== *)

  module Step_0L_state_0 (E : E_c.Scheme) = {
    proc ctxt(m : MessageSpace) : MessageSpace = {
      var v_D_KeyGen_key10 : KeySpace;
      var v_D_KeyGen_key20 : KeySpace;
      var k : KeySpace * KeySpace;
      var v_D_Enc_c13 : MessageSpace;
      var v_D_Enc_c23 : MessageSpace;
      var c : MessageSpace;
      v_D_KeyGen_key10 <@ E.keygen();
      v_D_KeyGen_key20 <@ E.keygen();
      k <- (v_D_KeyGen_key10, v_D_KeyGen_key20);
      v_D_Enc_c13 <@ E.enc(k.`1, m);
      v_D_Enc_c23 <@ E.enc(k.`2, v_D_Enc_c13);
      c <- v_D_Enc_c23;
      return c;
    }
  }.

  module Step_0L_state_1 (E : E_c.Scheme) = {
    proc ctxt(m : MessageSpace) : MessageSpace = {
      var __a0__ : KeySpace;
      var __a1__ : KeySpace;
      var __a2__ : KeySpace * KeySpace;
      var __a3__ : MessageSpace;
      var __a4__ : MessageSpace;
      var __a5__ : MessageSpace;
      __a0__ <@ E.keygen();
      __a1__ <@ E.keygen();
      __a2__ <- (__a0__, __a1__);
      __a3__ <@ E.enc(__a2__.`1, m);
      __a4__ <@ E.enc(__a2__.`2, __a3__);
      __a5__ <- __a4__;
      return __a5__;
    }
  }.

  module Step_0L_state_2 (E : E_c.Scheme) = {
    proc ctxt(m : MessageSpace) : MessageSpace = {
      var __a0__ : KeySpace;
      var __a1__ : KeySpace;
      var __a2__ : KeySpace * KeySpace;
      var __a3__ : MessageSpace;
      var __a4__ : MessageSpace;
      __a0__ <@ E.keygen();
      __a1__ <@ E.keygen();
      __a2__ <- (__a0__, __a1__);
      __a3__ <@ E.enc(__a2__.`1, m);
      __a4__ <@ E.enc(__a2__.`2, __a3__);
      return __a4__;
    }
  }.

  module Step_0L_state_3 (E : E_c.Scheme) = {
    proc ctxt(m : MessageSpace) : MessageSpace = {
      var _r0 : KeySpace;
      var _r1 : KeySpace;
      var __a2__ : KeySpace * KeySpace;
      var _r2 : MessageSpace;
      var _r3 : MessageSpace;
      _r0 <@ E.keygen();
      _r1 <@ E.keygen();
      __a2__ <- (_r0, _r1);
      _r2 <@ E.enc(__a2__.`1, m);
      _r3 <@ E.enc(__a2__.`2, _r2);
      return _r3;
    }
  }.

  module Step_0L_state_4 (E : E_c.Scheme) = {
    proc ctxt(m : MessageSpace) : MessageSpace = {
      var _r0 : KeySpace;
      var _r1 : KeySpace;
      var _r2 : MessageSpace;
      var _r3 : MessageSpace;
      _r0 <@ E.keygen();
      _r1 <@ E.keygen();
      _r2 <@ E.enc(_r1, m);
      _r3 <@ E.enc(_r0, _r2);
      return _r3;
    }
  }.

  module Step_0R_state_0 (E : E_c.Scheme) = {
    proc ctxt(m : MessageSpace) : MessageSpace = {
      var k : KeySpace;
      var c : MessageSpace;
      var challenger_CTXT_k2 : KeySpace;
      var challenger_CTXT_c2 : MessageSpace;
      k <@ E.keygen();
      c <@ E.enc(k, m);
      challenger_CTXT_k2 <@ E.keygen();
      challenger_CTXT_c2 <@ E.enc(challenger_CTXT_k2, c);
      return challenger_CTXT_c2;
    }
  }.

  module Step_0R_state_1 (E : E_c.Scheme) = {
    proc ctxt(m : MessageSpace) : MessageSpace = {
      var __a0__ : KeySpace;
      var __a1__ : MessageSpace;
      var __a2__ : KeySpace;
      var __a3__ : MessageSpace;
      __a0__ <@ E.keygen();
      __a1__ <@ E.enc(__a0__, m);
      __a2__ <@ E.keygen();
      __a3__ <@ E.enc(__a2__, __a1__);
      return __a3__;
    }
  }.

  module Step_0R_state_2 (E : E_c.Scheme) = {
    proc ctxt(m : MessageSpace) : MessageSpace = {
      var _r0 : KeySpace;
      var _r1 : KeySpace;
      var _r2 : MessageSpace;
      var _r3 : MessageSpace;
      _r0 <@ E.keygen();
      _r1 <@ E.keygen();
      _r2 <@ E.enc(_r1, m);
      _r3 <@ E.enc(_r0, _r2);
      return _r3;
    }
  }.

  (* transform: Alpha Rename (bucket=canned) *)
  lemma micro_0_left_0 :
    equiv [ Step_0L_state_0(E).ctxt ~ Step_0L_state_1(E).ctxt :
            ={m, glob E} ==> ={res, glob E} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Remove Redundant Copies (bucket=canned) *)
  lemma micro_0_left_1 :
    equiv [ Step_0L_state_1(E).ctxt ~ Step_0L_state_2(E).ctxt :
            ={m, glob E} ==> ={res, glob E} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Inline Single-Use Variables (bucket=canned) *)
  lemma micro_0_left_2 :
    equiv [ Step_0L_state_2(E).ctxt ~ Step_0L_state_3(E).ctxt :
            ={m, glob E} ==> ={res, glob E} ].
  proof.
    (* resolution: synth-param *)
    proc.
    wp.
    call (_: true).
    wp.
    call (_: true).
    wp.
    call (_: true).
    wp.
    call (_: true).
    wp.
    skip => />.
  qed.

  module Step_0L_state_3b (E : E_c.Scheme) = {
    proc ctxt(m : MessageSpace) : MessageSpace = {
      var _r0 : KeySpace;
      var _r1 : KeySpace;
      var _r2 : MessageSpace;
      var _r3 : MessageSpace;
      _r0 <@ E.keygen();
      _r1 <@ E.keygen();
      _r2 <@ E.enc(_r0, m);
      _r3 <@ E.enc(_r1, _r2);
      return _r3;
    }
  }.

  (* transform: Inline Local Tuple Literal (bucket=open) *)
  lemma micro_0_left_3 :
    equiv [ Step_0L_state_3(E).ctxt ~ Step_0L_state_4(E).ctxt :
            ={m, glob E} ==> ={res, glob E} ].
  proof.
    (* resolution: synth-param *)
    transitivity Step_0L_state_3(E_c.Ideal).ctxt (={m, glob E} ==> ={res, glob E}) (={m, glob E} ==> ={res, glob E});
      [ smt() | smt() | proc; wp; call E_enc_sem; call E_enc_sem; wp; call E_keygen_sem; call E_keygen_sem; auto | ].
    transitivity Step_0L_state_3b(E_c.Ideal).ctxt (={m, glob E} ==> ={res, glob E}) (={m, glob E} ==> ={res, glob E});
      [ smt() | smt() | proc; inline*; auto | ].
    transitivity Step_0L_state_4(E_c.Ideal).ctxt (={m, glob E} ==> ={res, glob E}) (={m, glob E} ==> ={res, glob E});
      [ smt() | smt() | proc; swap{1} 2 -1; sim | symmetry; proc; wp; call E_enc_sem; call E_enc_sem; call E_keygen_sem; call E_keygen_sem; auto ].
  qed.

  (* transform: Alpha Rename (bucket=canned) *)
  lemma micro_0_right_0_fwd :
    equiv [ Step_0R_state_0(E).ctxt ~ Step_0R_state_1(E).ctxt :
            ={m, glob E} ==> ={res, glob E} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Alpha Rename (reversed) (bucket=canned) *)
  lemma micro_0_right_0_rev :
    equiv [ Step_0R_state_1(E).ctxt ~ Step_0R_state_0(E).ctxt :
            ={m, glob E} ==> ={res, glob E} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Inline Single-Use Variables (bucket=canned) *)
  lemma micro_0_right_1_fwd :
    equiv [ Step_0R_state_1(E).ctxt ~ Step_0R_state_2(E).ctxt :
            ={m, glob E} ==> ={res, glob E} ].
  proof.
    (* resolution: synth-param *)
    transitivity Step_0R_state_1(E_c.Ideal).ctxt (={m, glob E} ==> ={res, glob E}) (={m, glob E} ==> ={res, glob E});
      [ smt() | smt() | proc; wp; call E_enc_sem; call E_keygen_sem; call E_enc_sem; call E_keygen_sem; auto | ].
    transitivity Step_0R_state_2(E_c.Ideal).ctxt (={m, glob E} ==> ={res, glob E}) (={m, glob E} ==> ={res, glob E});
      [ smt() | smt() | proc; swap{1} 3 -2; sim | symmetry; proc; wp; call E_enc_sem; call E_enc_sem; call E_keygen_sem; call E_keygen_sem; auto ].
  qed.

  (* transform: Inline Single-Use Variables (reversed) (bucket=canned) *)
  lemma micro_0_right_1_rev :
    equiv [ Step_0R_state_2(E).ctxt ~ Step_0R_state_1(E).ctxt :
            ={m, glob E} ==> ={res, glob E} ].
  proof.
    (* resolution: synth-param *)
    symmetry.
    transitivity Step_0R_state_1(E_c.Ideal).ctxt (={m, glob E} ==> ={res, glob E}) (={m, glob E} ==> ={res, glob E});
      [ smt() | smt() | proc; wp; call E_enc_sem; call E_keygen_sem; call E_enc_sem; call E_keygen_sem; auto | ].
    transitivity Step_0R_state_2(E_c.Ideal).ctxt (={m, glob E} ==> ={res, glob E}) (={m, glob E} ==> ={res, glob E});
      [ smt() | smt() | proc; swap{1} 3 -2; sim | symmetry; proc; wp; call E_enc_sem; call E_enc_sem; call E_keygen_sem; call E_keygen_sem; auto ].
  qed.

  lemma canon_bridge_0 :
    equiv [ Step_0L_state_4(E).ctxt ~ Step_0R_state_2(E).ctxt :
            ={m, glob E} ==> ={res, glob E} ].
  proof.
    proc; sim.
  qed.

  lemma hop_0_chain :
    equiv [ Step_0L_state_0(E).ctxt ~ Step_0R_state_0(E).ctxt :
            ={m, glob E} ==> ={res, glob E} ].
  proof.
    (* Chain through per-transform micro-lemmas. *)
    transitivity Step_0L_state_1(E).ctxt (={m, glob E} ==> ={res, glob E}) (={m, glob E} ==> ={res, glob E}); [ smt() | smt() | apply micro_0_left_0 |].
    transitivity Step_0L_state_2(E).ctxt (={m, glob E} ==> ={res, glob E}) (={m, glob E} ==> ={res, glob E}); [ smt() | smt() | apply micro_0_left_1 |].
    transitivity Step_0L_state_3(E).ctxt (={m, glob E} ==> ={res, glob E}) (={m, glob E} ==> ={res, glob E}); [ smt() | smt() | apply micro_0_left_2 |].
    transitivity Step_0L_state_4(E).ctxt (={m, glob E} ==> ={res, glob E}) (={m, glob E} ==> ={res, glob E}); [ smt() | smt() | apply micro_0_left_3 |].
    transitivity Step_0R_state_2(E).ctxt (={m, glob E} ==> ={res, glob E}) (={m, glob E} ==> ={res, glob E}); [ smt() | smt() | apply canon_bridge_0 |].
    transitivity Step_0R_state_1(E).ctxt (={m, glob E} ==> ={res, glob E}) (={m, glob E} ==> ={res, glob E}); [ smt() | smt() | apply micro_0_right_1_rev |].
    apply micro_0_right_0_rev.
  qed.

  module Step_2L_state_0 (E : E_c.Scheme) = {
    proc ctxt(m : MessageSpace) : MessageSpace = {
      var k : KeySpace;
      var c : MessageSpace;
      var challenger_CTXT_c2 : MessageSpace;
      k <@ E.keygen();
      c <@ E.enc(k, m);
      challenger_CTXT_c2 <$ dMessageSpace;
      return challenger_CTXT_c2;
    }
  }.

  module Step_2L_state_1 (E : E_c.Scheme) = {
    proc ctxt(m : MessageSpace) : MessageSpace = {
      var __a0__ : KeySpace;
      var __a1__ : MessageSpace;
      var __a2__ : MessageSpace;
      __a0__ <@ E.keygen();
      __a1__ <@ E.enc(__a0__, m);
      __a2__ <$ dMessageSpace;
      return __a2__;
    }
  }.

  module Step_2L_state_2 (E : E_c.Scheme) = {
    proc ctxt(m : MessageSpace) : MessageSpace = {
      var _r0 : KeySpace;
      var __a1__ : MessageSpace;
      var __a2__ : MessageSpace;
      _r0 <@ E.keygen();
      __a1__ <@ E.enc(_r0, m);
      __a2__ <$ dMessageSpace;
      return __a2__;
    }
  }.

  module Step_2L_state_3 (E : E_c.Scheme) = {
    proc ctxt(m : MessageSpace) : MessageSpace = {
      var __a2__ : MessageSpace;
      __a2__ <$ dMessageSpace;
      return __a2__;
    }
  }.

  module Step_2L_state_4 (E : E_c.Scheme) = {
    proc ctxt(m : MessageSpace) : MessageSpace = {
      var v1 : MessageSpace;
      v1 <$ dMessageSpace;
      return v1;
    }
  }.

  module Step_2R_state_0 (E : E_c.Scheme) = {
    proc ctxt(m : MessageSpace) : MessageSpace = {
      var c : MessageSpace;
      c <$ dMessageSpace;
      return c;
    }
  }.

  module Step_2R_state_1 (E : E_c.Scheme) = {
    proc ctxt(m : MessageSpace) : MessageSpace = {
      var __a0__ : MessageSpace;
      __a0__ <$ dMessageSpace;
      return __a0__;
    }
  }.

  module Step_2R_state_2 (E : E_c.Scheme) = {
    proc ctxt(m : MessageSpace) : MessageSpace = {
      var v1 : MessageSpace;
      v1 <$ dMessageSpace;
      return v1;
    }
  }.

  (* transform: Alpha Rename (bucket=canned) *)
  lemma micro_2_left_0 :
    equiv [ Step_2L_state_0(E).ctxt ~ Step_2L_state_1(E).ctxt :
            ={m, glob E} ==> ={res, glob E} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Inline Single-Use Variables (bucket=canned) *)
  lemma micro_2_left_1 :
    equiv [ Step_2L_state_1(E).ctxt ~ Step_2L_state_2(E).ctxt :
            ={m, glob E} ==> ={res, glob E} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Topological Sorting (bucket=canned) *)
  lemma micro_2_left_2 :
    equiv [ Step_2L_state_2(E).ctxt ~ Step_2L_state_3(E).ctxt :
            ={m, glob E} ==> ={res, glob E} ].
  proof.
    (* resolution: synth-param *)
    proc.
    seq 2 0 : (={m, glob E}).
    + exists* (glob E){1}; elim* => g_E.
      call{1} (E_enc_pres g_E).
      call{1} (E_keygen_pres g_E).
      auto.
    sim.
  qed.

  (* transform: Variable Standardization (bucket=canned) *)
  lemma micro_2_left_3 :
    equiv [ Step_2L_state_3(E).ctxt ~ Step_2L_state_4(E).ctxt :
            ={m, glob E} ==> ={res, glob E} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Alpha Rename (bucket=canned) *)
  lemma micro_2_right_0_fwd :
    equiv [ Step_2R_state_0(E).ctxt ~ Step_2R_state_1(E).ctxt :
            ={m, glob E} ==> ={res, glob E} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Alpha Rename (reversed) (bucket=canned) *)
  lemma micro_2_right_0_rev :
    equiv [ Step_2R_state_1(E).ctxt ~ Step_2R_state_0(E).ctxt :
            ={m, glob E} ==> ={res, glob E} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Variable Standardization (bucket=canned) *)
  lemma micro_2_right_1_fwd :
    equiv [ Step_2R_state_1(E).ctxt ~ Step_2R_state_2(E).ctxt :
            ={m, glob E} ==> ={res, glob E} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Variable Standardization (reversed) (bucket=canned) *)
  lemma micro_2_right_1_rev :
    equiv [ Step_2R_state_2(E).ctxt ~ Step_2R_state_1(E).ctxt :
            ={m, glob E} ==> ={res, glob E} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  lemma canon_bridge_2 :
    equiv [ Step_2L_state_4(E).ctxt ~ Step_2R_state_2(E).ctxt :
            ={m, glob E} ==> ={res, glob E} ].
  proof.
    proc; sim.
  qed.

  lemma hop_2_chain :
    equiv [ Step_2L_state_0(E).ctxt ~ Step_2R_state_0(E).ctxt :
            ={m, glob E} ==> ={res, glob E} ].
  proof.
    (* Chain through per-transform micro-lemmas. *)
    transitivity Step_2L_state_1(E).ctxt (={m, glob E} ==> ={res, glob E}) (={m, glob E} ==> ={res, glob E}); [ smt() | smt() | apply micro_2_left_0 |].
    transitivity Step_2L_state_2(E).ctxt (={m, glob E} ==> ={res, glob E}) (={m, glob E} ==> ={res, glob E}); [ smt() | smt() | apply micro_2_left_1 |].
    transitivity Step_2L_state_3(E).ctxt (={m, glob E} ==> ={res, glob E}) (={m, glob E} ==> ={res, glob E}); [ smt() | smt() | apply micro_2_left_2 |].
    transitivity Step_2L_state_4(E).ctxt (={m, glob E} ==> ={res, glob E}) (={m, glob E} ==> ={res, glob E}); [ smt() | smt() | apply micro_2_left_3 |].
    transitivity Step_2R_state_2(E).ctxt (={m, glob E} ==> ={res, glob E}) (={m, glob E} ==> ={res, glob E}); [ smt() | smt() | apply canon_bridge_2 |].
    transitivity Step_2R_state_1(E).ctxt (={m, glob E} ==> ={res, glob E}) (={m, glob E} ==> ={res, glob E}); [ smt() | smt() | apply micro_2_right_1_rev |].
    apply micro_2_right_0_rev.
  qed.

  (* ===== Per-hop equivalence lemmas ===== *)

  lemma hop_0 :
    equiv [ D_c.INDOT__Real(DoubleSymEnc(E)).ctxt ~ R1(DoubleSymEnc(E), E, E_c.INDOT__Real(E)).ctxt :
            ={m, glob E} ==> ={res, glob E} ].
  proof.
    (* Per-transform: bridge wrappers to flat states, chain through. *)
    transitivity Step_0L_state_0(E).ctxt (={m, glob E} ==> ={res, glob E}) (={m, glob E} ==> ={res, glob E}); [ smt() | smt() | proc; inline *; ((sp; wp; sim) || sim) |].
    transitivity Step_0R_state_0(E).ctxt (={m, glob E} ==> ={res, glob E}) (={m, glob E} ==> ={res, glob E}); [ smt() | smt() | apply hop_0_chain | proc; inline *; ((sp; wp; sim) || sim) ].
    qed.

  lemma hop_2 :
    equiv [ R1(DoubleSymEnc(E), E, E_c.INDOT__Random(E)).ctxt ~ D_c.INDOT__Random(DoubleSymEnc(E)).ctxt :
            ={m, glob E} ==> ={res, glob E} ].
  proof.
    (* Per-transform: bridge wrappers to flat states, chain through. *)
    transitivity Step_2L_state_0(E).ctxt (={m, glob E} ==> ={res, glob E}) (={m, glob E} ==> ={res, glob E}); [ smt() | smt() | proc; inline *; ((sp; wp; sim) || sim) |].
    transitivity Step_2R_state_0(E).ctxt (={m, glob E} ==> ={res, glob E}) (={m, glob E} ==> ={res, glob E}); [ smt() | smt() | apply hop_2_chain | proc; inline *; ((sp; wp; sim) || sim) ].
    qed.

  (* ===== Per-hop probability lemmas ===== *)

  (* Hop 0: interchangeability. The two adjacent games are equivalent (no advantage). *)

  lemma hop_0_pr (A <: D_c.INDOT__Adv {-E}) &m :
    Pr[Game_step_0(E, A).main() @ &m : res] = Pr[Game_step_1(E, A).main() @ &m : res].
  proof.
    byequiv (_: ={glob A, glob E} ==> ={res}) => //; proc.
    call (_: ={glob E}); first by conseq hop_0.
    auto.
    qed.

  (* Hop 1: assumption hop. Bounded by the INDOT$_advantage axiom applied to R1_Adv. *)

  lemma hop_1_pr (A <: D_c.INDOT__Adv {-E}) &m :
    `| Pr[Game_step_1(E, A).main() @ &m : res] - Pr[Game_step_2(E, A).main() @ &m : res] | <= E_c.eps_INDOT_.
  proof.
    have hL : Pr[Game_step_1(E, A).main() @ &m : res]
            = Pr[E_c.Game_INDOT__Real(E, R1_Adv(E, A)).main() @ &m : res]
      by byequiv => //; proc; inline *; sim.
    have hR : Pr[Game_step_2(E, A).main() @ &m : res]
            = Pr[E_c.Game_INDOT__Random(E, R1_Adv(E, A)).main() @ &m : res]
      by byequiv => //; proc; inline *; sim.
    rewrite hL hR.
    apply (E_c.INDOT__advantage E (R1_Adv(E, A)) &m).
    qed.

  (* Hop 2: interchangeability. The two adjacent games are equivalent (no advantage). *)

  lemma hop_2_pr (A <: D_c.INDOT__Adv {-E}) &m :
    Pr[Game_step_2(E, A).main() @ &m : res] = Pr[Game_step_3(E, A).main() @ &m : res].
  proof.
    byequiv (_: ={glob A, glob E} ==> ={res}) => //; proc.
    call (_: ={glob E}); first by conseq hop_2.
    auto.
    qed.

  (* ===== Main theorem ===== *)

  lemma main_theorem (A <: D_c.INDOT__Adv {-E}) &m :
    `| Pr[Game_step_0(E, A).main() @ &m : res] - Pr[Game_step_3(E, A).main() @ &m : res] | <= E_c.eps_INDOT_.
  proof.
    have h0 := hop_0_pr A &m.
    have h1 := hop_1_pr A &m.
    have h2 := hop_2_pr A &m.
    smt(E_c.eps_INDOT__pos).
    qed.
end section Main.
