(* Auto-generated by ProofFrog. Do not edit. *)
require import AllCore Distr DProd DMap List.
require BitWord.

(* ===== Abstract set declarations ===== *)

op lambda : int.

op in_ : int.

op out : int.

type SharedSecretSpace.

type CiphertextSpace.

type PKeySpace.

type SKeySpace.

(* ===== Concrete primitive types ===== *)

axiom gt0_out : 0 < out.

clone BitWord as BW_bs_out with
  op n <- out
  proof gt0_n by smt(gt0_out).

type bs_out = BW_bs_out.word.

op [smt_opaque] dbs_out : bs_out distr =
  BW_bs_out.DWord.dunifin.

lemma dbs_out_ll :
  is_lossless dbs_out.
proof.
  exact BW_bs_out.DWord.dunifin_ll.
qed.

lemma dbs_out_fu :
  is_funiform dbs_out.
proof.
  exact BW_bs_out.DWord.dunifin_funi.
qed.

lemma dbs_out_full :
  is_full dbs_out.
proof.
  exact BW_bs_out.DWord.dunifin_fu.
qed.

type bs_lambda = SharedSecretSpace.

op dbs_lambda : bs_lambda distr.

axiom dbs_lambda_ll : is_lossless dbs_lambda.

axiom dbs_lambda_fu : is_funiform dbs_lambda.

axiom dbs_lambda_full : is_full dbs_lambda.

type bs_in = CiphertextSpace.

op dbs_in : bs_in distr.

axiom dbs_in_ll : is_lossless dbs_in.

axiom dbs_in_fu : is_funiform dbs_in.

axiom dbs_in_full : is_full dbs_in.

op zero_out : bs_out.

op zero_lambda : bs_lambda.

op zero_in : bs_in.

(* ===== Abstract theory: primitive + security games + assumption ===== *)

abstract theory KEM_Theory.
  type publickey.

  type secretkey.

  type sharedsecret.

  type ciphertext.

  module type Scheme = {
    proc keygen() : publickey * secretkey
    proc encaps(pk : publickey) : sharedsecret * ciphertext
    proc decaps(sk : secretkey, m : ciphertext) : sharedsecret
  }.

  op ev_decaps : secretkey -> ciphertext -> sharedsecret.

  module type KEMCorrectness_Oracle = {
    proc compute(pk : publickey, sk : secretkey) : ciphertext * sharedsecret * sharedsecret
  }.

  module KEMCorrectness_FromDecaps (K : Scheme) : KEMCorrectness_Oracle = {
    proc compute(pk : publickey, sk : secretkey) : ciphertext * sharedsecret * sharedsecret = {
      var _tup : sharedsecret * ciphertext;
      var ss_e : sharedsecret;
      var ct : ciphertext;
      var ss_d : sharedsecret;
      _tup <@ K.encaps(pk);
      ss_e <- _tup.`1;
      ct <- _tup.`2;
      ss_d <@ K.decaps(sk, ct);
      return (ct, ss_e, ss_d);
    }
  }.

  module KEMCorrectness_FromEncaps (K : Scheme) : KEMCorrectness_Oracle = {
    proc compute(pk : publickey, sk : secretkey) : ciphertext * sharedsecret * sharedsecret = {
      var _tup : sharedsecret * ciphertext;
      var ss : sharedsecret;
      var ct : ciphertext;
      _tup <@ K.encaps(pk);
      ss <- _tup.`1;
      ct <- _tup.`2;
      return (ct, ss, ss);
    }
  }.

  module type KEMCorrectness_Adv (O : KEMCorrectness_Oracle) = {
    proc distinguish() : bool
  }.

  module Game_KEMCorrectness_FromDecaps (Em : Scheme, A : KEMCorrectness_Adv) = {
    proc main() : bool = {
      var b : bool;
      b <@ A(KEMCorrectness_FromDecaps(Em)).distinguish();
      return b;
    }
  }.

  module Game_KEMCorrectness_FromEncaps (Em : Scheme, A : KEMCorrectness_Adv) = {
    proc main() : bool = {
      var b : bool;
      b <@ A(KEMCorrectness_FromEncaps(Em)).distinguish();
      return b;
    }
  }.

  op eps_KEMCorrectness : real.

  axiom eps_KEMCorrectness_pos : 0%r <= eps_KEMCorrectness.

  axiom KEMCorrectness_advantage (Em <: Scheme) (A <: KEMCorrectness_Adv) &m :
    `| Pr[Game_KEMCorrectness_FromDecaps(Em, A).main() @ &m : res] - Pr[Game_KEMCorrectness_FromEncaps(Em, A).main() @ &m : res] | <= eps_KEMCorrectness.
end KEM_Theory.

(* ===== Foreign primitive theory: PRF_Theory ===== *)

abstract theory PRF_Theory.
  type bs_lambda_t.

  op zero_lambda_t : bs_lambda_t.

  type bs_in_t.

  op zero_in_t : bs_in_t.

  type bs_out_t.

  op zero_out_t : bs_out_t.

  module type Scheme = {
    proc evaluate(seed : bs_lambda_t, input : bs_in_t) : bs_out_t
  }.

  op ev_evaluate : bs_lambda_t -> bs_in_t -> bs_out_t.
end PRF_Theory.

(* ===== Theory instantiation ===== *)

clone KEM_Theory as K_c with
  type sharedsecret <- SharedSecretSpace,
  type ciphertext <- CiphertextSpace,
  type publickey <- PKeySpace,
  type secretkey <- SKeySpace.

clone PRF_Theory as F_c with
  type bs_lambda_t <- bs_lambda,
  type bs_in_t <- bs_in,
  type bs_out_t <- bs_out.

clone KEM_Theory as KF_c with
  type sharedsecret <- bs_out,
  type ciphertext <- CiphertextSpace,
  type publickey <- PKeySpace,
  type secretkey <- SKeySpace.

(* ===== Concrete scheme implementation ===== *)

module KEMPRF (K : K_c.Scheme, F : F_c.Scheme) : KF_c.Scheme = {
  proc keygen() : PKeySpace * SKeySpace = {
    var _r0 : PKeySpace * SKeySpace;
    _r0 <@ K.keygen();
    return _r0;
  }
  proc encaps(pk : PKeySpace) : bs_out * CiphertextSpace = {
    var x : SharedSecretSpace * CiphertextSpace;
    var k : bs_lambda;
    var c : CiphertextSpace;
    var ss : bs_out;
    x <@ K.encaps(pk);
    k <- x.`1;
    c <- x.`2;
    ss <@ F.evaluate(k, c);
    return (ss, c);
  }
  proc decaps(sk : SKeySpace, c : CiphertextSpace) : bs_out = {
    var k : SharedSecretSpace;
    var ss : bs_out;
    k <@ K.decaps(sk, c);
    ss <@ F.evaluate(k, c);
    return ss;
  }
}.

section Main.
  declare module K <: K_c.Scheme.

  declare module F <: F_c.Scheme {-K}.

  (* ===== Deterministic-method specs ===== *)

  declare axiom K_decaps_det (g : (glob K)) (a0 : SKeySpace) (a1 : CiphertextSpace) : phoare[ K.decaps : (glob K) = g /\ sk = a0 /\ m = a1 ==> (glob K) = g /\ res = K_c.ev_decaps a0 a1 ] = 1%r.

  declare axiom F_evaluate_det (g : (glob F)) (a0 : bs_lambda) (a1 : bs_in) : phoare[ F.evaluate : (glob F) = g /\ seed = a0 /\ input = a1 ==> (glob F) = g /\ res = F_c.ev_evaluate a0 a1 ] = 1%r.

  (* ===== Reductions ===== *)

  module R_KEM (K : K_c.Scheme, F : F_c.Scheme, KF : KF_c.Scheme, Challenger : K_c.KEMCorrectness_Oracle) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : CiphertextSpace * bs_out * bs_out = {
      var _tup : CiphertextSpace * SharedSecretSpace * SharedSecretSpace;
      var ct : CiphertextSpace;
      var ss_e : SharedSecretSpace;
      var ss_d : SharedSecretSpace;
      var _r0 : bs_out;
      var _r1 : bs_out;
      _tup <@ Challenger.compute(pk, sk);
      ct <- _tup.`1;
      ss_e <- _tup.`2;
      ss_d <- _tup.`3;
      _r0 <@ F.evaluate(ss_e, ct);
      _r1 <@ F.evaluate(ss_d, ct);
      return (ct, _r0, _r1);
    }
  }.

  (* ===== Reductions lifted to assumption-adversaries ===== *)

  module R_KEM_Adv (K : K_c.Scheme, F : F_c.Scheme, A : KF_c.KEMCorrectness_Adv, C : K_c.KEMCorrectness_Oracle) = {
    proc distinguish() : bool = {
      var b : bool;
      b <@ A(R_KEM(K, F, KEMPRF(K, F), C)).distinguish();
      return b;
    }
  }.

  (* ===== Game-step wrappers ===== *)

  (* Game_step_0: KEMCorrectness.FromDecaps *)

  module Game_step_0 (K : K_c.Scheme, F : F_c.Scheme, A : KF_c.KEMCorrectness_Adv) = {
    proc main() : bool = {
      var b : bool;
      b <@ A(KF_c.KEMCorrectness_FromDecaps(KEMPRF(K, F))).distinguish();
      return b;
    }
  }.

  (* Game_step_1: KEMCorrectness.FromDecaps composed with reduction R_KEM *)

  module Game_step_1 (K : K_c.Scheme, F : F_c.Scheme, A : KF_c.KEMCorrectness_Adv) = {
    proc main() : bool = {
      var b : bool;
      b <@ A(R_KEM(K, F, KEMPRF(K, F), K_c.KEMCorrectness_FromDecaps(K))).distinguish();
      return b;
    }
  }.

  (* Game_step_2: KEMCorrectness.FromEncaps composed with reduction R_KEM *)

  module Game_step_2 (K : K_c.Scheme, F : F_c.Scheme, A : KF_c.KEMCorrectness_Adv) = {
    proc main() : bool = {
      var b : bool;
      b <@ A(R_KEM(K, F, KEMPRF(K, F), K_c.KEMCorrectness_FromEncaps(K))).distinguish();
      return b;
    }
  }.

  (* Game_step_3: KEMCorrectness.FromEncaps *)

  module Game_step_3 (K : K_c.Scheme, F : F_c.Scheme, A : KF_c.KEMCorrectness_Adv) = {
    proc main() : bool = {
      var b : bool;
      b <@ A(KF_c.KEMCorrectness_FromEncaps(KEMPRF(K, F))).distinguish();
      return b;
    }
  }.

  (* ===== Per-transform canonicalization chain ===== *)

  module Step_0L_state_0 (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : CiphertextSpace * bs_out * bs_out = {
      var v_KF_Encaps_x0 : SharedSecretSpace * CiphertextSpace;
      var v_KF_Encaps_k0 : bs_lambda;
      var v_KF_Encaps_c0 : CiphertextSpace;
      var v_KF_Encaps_ss0 : bs_out;
      var _tup : bs_out * CiphertextSpace;
      var ss_e : bs_out;
      var ct : CiphertextSpace;
      var v_KF_Decaps_k7 : SharedSecretSpace;
      var v_KF_Decaps_ss7 : bs_out;
      var ss_d : bs_out;
      v_KF_Encaps_x0 <@ K.encaps(pk);
      v_KF_Encaps_k0 <- v_KF_Encaps_x0.`1;
      v_KF_Encaps_c0 <- v_KF_Encaps_x0.`2;
      v_KF_Encaps_ss0 <@ F.evaluate(v_KF_Encaps_k0, v_KF_Encaps_c0);
      _tup <- (v_KF_Encaps_ss0, v_KF_Encaps_c0);
      ss_e <- _tup.`1;
      ct <- _tup.`2;
      v_KF_Decaps_k7 <@ K.decaps(sk, ct);
      v_KF_Decaps_ss7 <@ F.evaluate(v_KF_Decaps_k7, ct);
      ss_d <- v_KF_Decaps_ss7;
      return (ct, ss_e, ss_d);
    }
  }.

  module Step_0L_state_1 (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : CiphertextSpace * bs_out * bs_out = {
      var __a0__ : SharedSecretSpace * CiphertextSpace;
      var __a1__ : bs_lambda;
      var __a2__ : CiphertextSpace;
      var __a3__ : bs_out;
      var __a4__ : bs_out * CiphertextSpace;
      var __a5__ : bs_out;
      var __a6__ : CiphertextSpace;
      var __a7__ : SharedSecretSpace;
      var __a8__ : bs_out;
      var __a9__ : bs_out;
      __a0__ <@ K.encaps(pk);
      __a1__ <- __a0__.`1;
      __a2__ <- __a0__.`2;
      __a3__ <@ F.evaluate(__a1__, __a2__);
      __a4__ <- (__a3__, __a2__);
      __a5__ <- __a4__.`1;
      __a6__ <- __a4__.`2;
      __a7__ <@ K.decaps(sk, __a6__);
      __a8__ <@ F.evaluate(__a7__, __a6__);
      __a9__ <- __a8__;
      return (__a6__, __a5__, __a9__);
    }
  }.

  module Step_0L_state_2 (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : CiphertextSpace * bs_out * bs_out = {
      var __a0__ : SharedSecretSpace * CiphertextSpace;
      var __a1__ : bs_lambda;
      var __a2__ : CiphertextSpace;
      var __a3__ : bs_out;
      var __a4__ : bs_out * CiphertextSpace;
      var __a5__ : bs_out;
      var __a6__ : CiphertextSpace;
      var __a7__ : SharedSecretSpace;
      var __a8__ : bs_out;
      __a0__ <@ K.encaps(pk);
      __a1__ <- __a0__.`1;
      __a2__ <- __a0__.`2;
      __a3__ <@ F.evaluate(__a1__, __a2__);
      __a4__ <- (__a3__, __a2__);
      __a5__ <- __a4__.`1;
      __a6__ <- __a4__.`2;
      __a7__ <@ K.decaps(sk, __a6__);
      __a8__ <@ F.evaluate(__a7__, __a6__);
      return (__a6__, __a5__, __a8__);
    }
  }.

  module Step_0L_state_3 (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : CiphertextSpace * bs_out * bs_out = {
      var __a0__ : SharedSecretSpace * CiphertextSpace;
      var __a2__ : CiphertextSpace;
      var _r0 : bs_out;
      var __a4__ : bs_out * CiphertextSpace;
      var __a6__ : CiphertextSpace;
      var _r1 : SharedSecretSpace;
      var _r2 : bs_out;
      __a0__ <@ K.encaps(pk);
      __a2__ <- __a0__.`2;
      _r0 <@ F.evaluate(__a0__.`1, __a2__);
      __a4__ <- (_r0, __a2__);
      __a6__ <- __a4__.`2;
      _r1 <@ K.decaps(sk, __a6__);
      _r2 <@ F.evaluate(_r1, __a6__);
      return (__a6__, __a4__.`1, _r2);
    }
  }.

  module Step_0L_state_4 (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : CiphertextSpace * bs_out * bs_out = {
      var __a0__ : SharedSecretSpace * CiphertextSpace;
      var __a2__ : CiphertextSpace;
      var __a6__ : CiphertextSpace;
      var _r0 : bs_out;
      var _r1 : SharedSecretSpace;
      var _r2 : bs_out;
      __a0__ <@ K.encaps(pk);
      __a2__ <- __a0__.`2;
      __a6__ <- __a2__;
      _r0 <@ F.evaluate(__a0__.`1, __a2__);
      _r1 <@ K.decaps(sk, __a6__);
      _r2 <@ F.evaluate(_r1, __a6__);
      return (__a6__, _r0, _r2);
    }
  }.

  module Step_0L_state_5 (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : bs_in * bs_out * bs_out = {
      var __a0__ : bs_lambda * bs_in;
      var __a2__ : bs_in;
      var __a6__ : bs_in;
      var _r0 : bs_out;
      var _r1 : SharedSecretSpace;
      var _r2 : bs_out;
      __a0__ <@ K.encaps(pk);
      __a2__ <- __a0__.`2;
      __a6__ <- __a2__;
      _r0 <@ F.evaluate(__a0__.`1, __a2__);
      _r1 <@ K.decaps(sk, __a6__);
      _r2 <@ F.evaluate(_r1, __a6__);
      return (__a6__, _r0, _r2);
    }
  }.

  module Step_0L_state_6 (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : bs_in * bs_out * bs_out = {
      var __a0__ : bs_lambda * bs_in;
      var __a2__ : bs_in;
      var _r0 : bs_out;
      var _r1 : SharedSecretSpace;
      var _r2 : bs_out;
      __a0__ <@ K.encaps(pk);
      __a2__ <- __a0__.`2;
      _r0 <@ F.evaluate(__a0__.`1, __a2__);
      _r1 <@ K.decaps(sk, __a2__);
      _r2 <@ F.evaluate(_r1, __a2__);
      return (__a2__, _r0, _r2);
    }
  }.

  module Step_0L_state_7 (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : bs_in * bs_out * bs_out = {
      var v1 : bs_lambda * bs_in;
      var v2 : bs_in;
      var _r0 : bs_out;
      var _r1 : SharedSecretSpace;
      var _r2 : bs_out;
      v1 <@ K.encaps(pk);
      v2 <- v1.`2;
      _r0 <@ F.evaluate(v1.`1, v2);
      _r1 <@ K.decaps(sk, v2);
      _r2 <@ F.evaluate(_r1, v2);
      return (v2, _r0, _r2);
    }
  }.

  module Step_0R_state_0 (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : CiphertextSpace * bs_out * bs_out = {
      var challenger_Compute__tup0 : SharedSecretSpace * CiphertextSpace;
      var challenger_Compute_ss_e0 : SharedSecretSpace;
      var challenger_Compute_ct0 : CiphertextSpace;
      var challenger_Compute_ss_d0 : SharedSecretSpace;
      var _tup : CiphertextSpace * SharedSecretSpace * SharedSecretSpace;
      var ct : CiphertextSpace;
      var ss_e : SharedSecretSpace;
      var ss_d : SharedSecretSpace;
      var _r0 : bs_out;
      var _r1 : bs_out;
      challenger_Compute__tup0 <@ K.encaps(pk);
      challenger_Compute_ss_e0 <- challenger_Compute__tup0.`1;
      challenger_Compute_ct0 <- challenger_Compute__tup0.`2;
      challenger_Compute_ss_d0 <@ K.decaps(sk, challenger_Compute_ct0);
      _tup <- (challenger_Compute_ct0, challenger_Compute_ss_e0, challenger_Compute_ss_d0);
      ct <- _tup.`1;
      ss_e <- _tup.`2;
      ss_d <- _tup.`3;
      _r0 <@ F.evaluate(ss_e, ct);
      _r1 <@ F.evaluate(ss_d, ct);
      return (ct, _r0, _r1);
    }
  }.

  module Step_0R_state_1 (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : CiphertextSpace * bs_out * bs_out = {
      var __a0__ : SharedSecretSpace * CiphertextSpace;
      var __a1__ : SharedSecretSpace;
      var __a2__ : CiphertextSpace;
      var __a3__ : SharedSecretSpace;
      var __a4__ : CiphertextSpace * SharedSecretSpace * SharedSecretSpace;
      var __a5__ : CiphertextSpace;
      var __a6__ : SharedSecretSpace;
      var __a7__ : SharedSecretSpace;
      var _r0 : bs_out;
      var _r1 : bs_out;
      __a0__ <@ K.encaps(pk);
      __a1__ <- __a0__.`1;
      __a2__ <- __a0__.`2;
      __a3__ <@ K.decaps(sk, __a2__);
      __a4__ <- (__a2__, __a1__, __a3__);
      __a5__ <- __a4__.`1;
      __a6__ <- __a4__.`2;
      __a7__ <- __a4__.`3;
      _r0 <@ F.evaluate(__a6__, __a5__);
      _r1 <@ F.evaluate(__a7__, __a5__);
      return (__a5__, _r0, _r1);
    }
  }.

  module Step_0R_state_2 (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : CiphertextSpace * bs_out * bs_out = {
      var __a0__ : SharedSecretSpace * CiphertextSpace;
      var __a2__ : CiphertextSpace;
      var _r0 : SharedSecretSpace;
      var __a4__ : CiphertextSpace * SharedSecretSpace * SharedSecretSpace;
      var __a5__ : CiphertextSpace;
      var _r1 : bs_out;
      var _r2 : bs_out;
      __a0__ <@ K.encaps(pk);
      __a2__ <- __a0__.`2;
      _r0 <@ K.decaps(sk, __a2__);
      __a4__ <- (__a2__, __a0__.`1, _r0);
      __a5__ <- __a4__.`1;
      _r1 <@ F.evaluate(__a4__.`2, __a5__);
      _r2 <@ F.evaluate(__a4__.`3, __a5__);
      return (__a5__, _r1, _r2);
    }
  }.

  module Step_0R_state_3 (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : CiphertextSpace * bs_out * bs_out = {
      var __a0__ : SharedSecretSpace * CiphertextSpace;
      var __a2__ : CiphertextSpace;
      var __a5__ : CiphertextSpace;
      var _r0 : bs_out;
      var _r1 : SharedSecretSpace;
      var _r2 : bs_out;
      __a0__ <@ K.encaps(pk);
      __a2__ <- __a0__.`2;
      __a5__ <- __a2__;
      _r0 <@ F.evaluate(__a0__.`1, __a5__);
      _r1 <@ K.decaps(sk, __a2__);
      _r2 <@ F.evaluate(_r1, __a5__);
      return (__a5__, _r0, _r2);
    }
  }.

  module Step_0R_state_4 (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : bs_in * bs_out * bs_out = {
      var __a0__ : bs_lambda * bs_in;
      var __a2__ : bs_in;
      var __a5__ : bs_in;
      var _r0 : bs_out;
      var _r1 : SharedSecretSpace;
      var _r2 : bs_out;
      __a0__ <@ K.encaps(pk);
      __a2__ <- __a0__.`2;
      __a5__ <- __a2__;
      _r0 <@ F.evaluate(__a0__.`1, __a5__);
      _r1 <@ K.decaps(sk, __a2__);
      _r2 <@ F.evaluate(_r1, __a5__);
      return (__a5__, _r0, _r2);
    }
  }.

  module Step_0R_state_5 (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : bs_in * bs_out * bs_out = {
      var __a0__ : bs_lambda * bs_in;
      var __a2__ : bs_in;
      var _r0 : bs_out;
      var _r1 : SharedSecretSpace;
      var _r2 : bs_out;
      __a0__ <@ K.encaps(pk);
      __a2__ <- __a0__.`2;
      _r0 <@ F.evaluate(__a0__.`1, __a2__);
      _r1 <@ K.decaps(sk, __a2__);
      _r2 <@ F.evaluate(_r1, __a2__);
      return (__a2__, _r0, _r2);
    }
  }.

  module Step_0R_state_6 (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : bs_in * bs_out * bs_out = {
      var v1 : bs_lambda * bs_in;
      var v2 : bs_in;
      var _r0 : bs_out;
      var _r1 : SharedSecretSpace;
      var _r2 : bs_out;
      v1 <@ K.encaps(pk);
      v2 <- v1.`2;
      _r0 <@ F.evaluate(v1.`1, v2);
      _r1 <@ K.decaps(sk, v2);
      _r2 <@ F.evaluate(_r1, v2);
      return (v2, _r0, _r2);
    }
  }.

  (* transform: Alpha Rename (bucket=canned) *)
  lemma micro_0_left_0 :
    equiv [ Step_0L_state_0(K, F).compute ~ Step_0L_state_1(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Remove Redundant Copies (bucket=canned) *)
  lemma micro_0_left_1 :
    equiv [ Step_0L_state_1(K, F).compute ~ Step_0L_state_2(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  module Step_0L_state_2_fdet (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : CiphertextSpace * bs_out * bs_out = {
      var __a0__ : SharedSecretSpace * CiphertextSpace;
      var __a1__ : bs_lambda;
      var __a2__ : CiphertextSpace;
      var __a3__ : bs_out;
      var __a4__ : bs_out * CiphertextSpace;
      var __a5__ : bs_out;
      var __a6__ : CiphertextSpace;
      var __a7__ : SharedSecretSpace;
      var __a8__ : bs_out;
      __a0__ <@ K.encaps(pk);
      __a1__ <- __a0__.`1;
      __a2__ <- __a0__.`2;
      __a3__ <- F_c.ev_evaluate (__a1__) (__a2__);
      __a4__ <- (__a3__, __a2__);
      __a5__ <- __a4__.`1;
      __a6__ <- __a4__.`2;
      __a7__ <- K_c.ev_decaps (sk) (__a6__);
      __a8__ <- F_c.ev_evaluate (__a7__) (__a6__);
      return (__a6__, __a5__, __a8__);
    }
  }.

  module Step_0L_state_3_fdet (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : CiphertextSpace * bs_out * bs_out = {
      var __a0__ : SharedSecretSpace * CiphertextSpace;
      var __a2__ : CiphertextSpace;
      var _r0 : bs_out;
      var __a4__ : bs_out * CiphertextSpace;
      var __a6__ : CiphertextSpace;
      var _r1 : SharedSecretSpace;
      var _r2 : bs_out;
      __a0__ <@ K.encaps(pk);
      __a2__ <- __a0__.`2;
      _r0 <- F_c.ev_evaluate (__a0__.`1) (__a2__);
      __a4__ <- (_r0, __a2__);
      __a6__ <- __a4__.`2;
      _r1 <- K_c.ev_decaps (sk) (__a6__);
      _r2 <- F_c.ev_evaluate (_r1) (__a6__);
      return (__a6__, __a4__.`1, _r2);
    }
  }.

  (* transform: Inline Single-Use Variables (bucket=canned) *)
  lemma micro_0_left_2 :
    equiv [ Step_0L_state_2(K, F).compute ~ Step_0L_state_3(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-param *)
    transitivity Step_0L_state_2_fdet(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}).
    smt().
    smt().
    proc.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__}).
    call (_: true); auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__}).
    wp.
    exists* (glob F){1}, (__a1__){1}, (__a2__){1}; elim* => g0 a0_0 a0_1.
    call{1} (F_evaluate_det g0 a0_0 a0_1).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__, __a4__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__, __a4__, __a5__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__, __a4__, __a5__, __a6__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__, __a4__, __a5__, __a6__, __a7__}).
    wp.
    exists* (glob K){1}, (sk){1}, (__a6__){1}; elim* => g1 a1_0 a1_1.
    call{1} (K_decaps_det g1 a1_0 a1_1).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__, __a4__, __a5__, __a6__, __a7__, __a8__}).
    wp.
    exists* (glob F){1}, (__a7__){1}, (__a6__){1}; elim* => g2 a2_0 a2_1.
    call{1} (F_evaluate_det g2 a2_0 a2_1).
    auto.
    skip => /#.
    transitivity Step_0L_state_3_fdet(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}).
    smt().
    smt().
    proc.
    wp.
    call (_: true).
    skip => /#.
    proc.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__}).
    call (_: true); auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a2__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a2__, _r0}).
    wp.
    exists* (glob F){2}, (__a0__.`1){2}, (__a2__){2}; elim* => g3 a3_0 a3_1.
    call{2} (F_evaluate_det g3 a3_0 a3_1).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a2__, _r0, __a4__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a2__, _r0, __a4__, __a6__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a2__, _r0, __a4__, __a6__, _r1}).
    wp.
    exists* (glob K){2}, (sk){2}, (__a6__){2}; elim* => g4 a4_0 a4_1.
    call{2} (K_decaps_det g4 a4_0 a4_1).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a2__, _r0, __a4__, __a6__, _r1, _r2}).
    wp.
    exists* (glob F){2}, (_r1){2}, (__a6__){2}; elim* => g5 a5_0 a5_1.
    call{2} (F_evaluate_det g5 a5_0 a5_1).
    auto.
    skip => /#.
  qed.

  (* transform: Inline Local Tuple Literal (bucket=open) *)
  lemma micro_0_left_3 :
    equiv [ Step_0L_state_3(K, F).compute ~ Step_0L_state_4(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-param *)
    proc.
    wp.
    call (_: true).
    wp.
    call (_: true).
    wp.
    call (_: true).
    wp.
    call (_: true).
    skip => /#.
  qed.

  (* transform: Subset Type Normalization (bucket=canned) *)
  lemma micro_0_left_4 :
    equiv [ Step_0L_state_4(K, F).compute ~ Step_0L_state_5(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Remove Redundant Copies (bucket=canned) *)
  lemma micro_0_left_5 :
    equiv [ Step_0L_state_5(K, F).compute ~ Step_0L_state_6(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Variable Standardization (bucket=canned) *)
  lemma micro_0_left_6 :
    equiv [ Step_0L_state_6(K, F).compute ~ Step_0L_state_7(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Alpha Rename (bucket=canned) *)
  lemma micro_0_right_0_fwd :
    equiv [ Step_0R_state_0(K, F).compute ~ Step_0R_state_1(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Alpha Rename (reversed) (bucket=canned) *)
  lemma micro_0_right_0_rev :
    equiv [ Step_0R_state_1(K, F).compute ~ Step_0R_state_0(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  module Step_0R_state_1_fdet (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : CiphertextSpace * bs_out * bs_out = {
      var __a0__ : SharedSecretSpace * CiphertextSpace;
      var __a1__ : SharedSecretSpace;
      var __a2__ : CiphertextSpace;
      var __a3__ : SharedSecretSpace;
      var __a4__ : CiphertextSpace * SharedSecretSpace * SharedSecretSpace;
      var __a5__ : CiphertextSpace;
      var __a6__ : SharedSecretSpace;
      var __a7__ : SharedSecretSpace;
      var _r0 : bs_out;
      var _r1 : bs_out;
      __a0__ <@ K.encaps(pk);
      __a1__ <- __a0__.`1;
      __a2__ <- __a0__.`2;
      __a3__ <- K_c.ev_decaps (sk) (__a2__);
      __a4__ <- (__a2__, __a1__, __a3__);
      __a5__ <- __a4__.`1;
      __a6__ <- __a4__.`2;
      __a7__ <- __a4__.`3;
      _r0 <- F_c.ev_evaluate (__a6__) (__a5__);
      _r1 <- F_c.ev_evaluate (__a7__) (__a5__);
      return (__a5__, _r0, _r1);
    }
  }.

  module Step_0R_state_2_fdet (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : CiphertextSpace * bs_out * bs_out = {
      var __a0__ : SharedSecretSpace * CiphertextSpace;
      var __a2__ : CiphertextSpace;
      var _r0 : SharedSecretSpace;
      var __a4__ : CiphertextSpace * SharedSecretSpace * SharedSecretSpace;
      var __a5__ : CiphertextSpace;
      var _r1 : bs_out;
      var _r2 : bs_out;
      __a0__ <@ K.encaps(pk);
      __a2__ <- __a0__.`2;
      _r0 <- K_c.ev_decaps (sk) (__a2__);
      __a4__ <- (__a2__, __a0__.`1, _r0);
      __a5__ <- __a4__.`1;
      _r1 <- F_c.ev_evaluate (__a4__.`2) (__a5__);
      _r2 <- F_c.ev_evaluate (__a4__.`3) (__a5__);
      return (__a5__, _r1, _r2);
    }
  }.

  (* transform: Inline Single-Use Variables (bucket=canned) *)
  lemma micro_0_right_1_fwd :
    equiv [ Step_0R_state_1(K, F).compute ~ Step_0R_state_2(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-param *)
    transitivity Step_0R_state_1_fdet(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}).
    smt().
    smt().
    proc.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__}).
    call (_: true); auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__}).
    wp.
    exists* (glob K){1}, (sk){1}, (__a2__){1}; elim* => g0 a0_0 a0_1.
    call{1} (K_decaps_det g0 a0_0 a0_1).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__, __a4__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__, __a4__, __a5__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__, __a4__, __a5__, __a6__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__, __a4__, __a5__, __a6__, __a7__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__, __a4__, __a5__, __a6__, __a7__, _r0}).
    wp.
    exists* (glob F){1}, (__a6__){1}, (__a5__){1}; elim* => g1 a1_0 a1_1.
    call{1} (F_evaluate_det g1 a1_0 a1_1).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__, __a4__, __a5__, __a6__, __a7__, _r0, _r1}).
    wp.
    exists* (glob F){1}, (__a7__){1}, (__a5__){1}; elim* => g2 a2_0 a2_1.
    call{1} (F_evaluate_det g2 a2_0 a2_1).
    auto.
    skip => /#.
    transitivity Step_0R_state_2_fdet(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}).
    smt().
    smt().
    proc.
    wp.
    call (_: true).
    skip => /#.
    proc.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__}).
    call (_: true); auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a2__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a2__, _r0}).
    wp.
    exists* (glob K){2}, (sk){2}, (__a2__){2}; elim* => g3 a3_0 a3_1.
    call{2} (K_decaps_det g3 a3_0 a3_1).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a2__, _r0, __a4__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a2__, _r0, __a4__, __a5__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a2__, _r0, __a4__, __a5__, _r1}).
    wp.
    exists* (glob F){2}, (__a4__.`2){2}, (__a5__){2}; elim* => g4 a4_0 a4_1.
    call{2} (F_evaluate_det g4 a4_0 a4_1).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a2__, _r0, __a4__, __a5__, _r1, _r2}).
    wp.
    exists* (glob F){2}, (__a4__.`3){2}, (__a5__){2}; elim* => g5 a5_0 a5_1.
    call{2} (F_evaluate_det g5 a5_0 a5_1).
    auto.
    skip => /#.
  qed.

  (* transform: Inline Single-Use Variables (reversed) (bucket=canned) *)
  lemma micro_0_right_1_rev :
    equiv [ Step_0R_state_2(K, F).compute ~ Step_0R_state_1(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-param *)
    transitivity Step_0R_state_2_fdet(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}).
    smt().
    smt().
    proc.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__}).
    call (_: true); auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a2__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a2__, _r0}).
    wp.
    exists* (glob K){1}, (sk){1}, (__a2__){1}; elim* => g0 a0_0 a0_1.
    call{1} (K_decaps_det g0 a0_0 a0_1).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a2__, _r0, __a4__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a2__, _r0, __a4__, __a5__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a2__, _r0, __a4__, __a5__, _r1}).
    wp.
    exists* (glob F){1}, (__a4__.`2){1}, (__a5__){1}; elim* => g1 a1_0 a1_1.
    call{1} (F_evaluate_det g1 a1_0 a1_1).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a2__, _r0, __a4__, __a5__, _r1, _r2}).
    wp.
    exists* (glob F){1}, (__a4__.`3){1}, (__a5__){1}; elim* => g2 a2_0 a2_1.
    call{1} (F_evaluate_det g2 a2_0 a2_1).
    auto.
    skip => /#.
    transitivity Step_0R_state_1_fdet(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}).
    smt().
    smt().
    proc.
    wp.
    call (_: true).
    skip => /#.
    proc.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__}).
    call (_: true); auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__}).
    wp.
    exists* (glob K){2}, (sk){2}, (__a2__){2}; elim* => g3 a3_0 a3_1.
    call{2} (K_decaps_det g3 a3_0 a3_1).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__, __a4__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__, __a4__, __a5__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__, __a4__, __a5__, __a6__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__, __a4__, __a5__, __a6__, __a7__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__, __a4__, __a5__, __a6__, __a7__, _r0}).
    wp.
    exists* (glob F){2}, (__a6__){2}, (__a5__){2}; elim* => g4 a4_0 a4_1.
    call{2} (F_evaluate_det g4 a4_0 a4_1).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__, __a4__, __a5__, __a6__, __a7__, _r0, _r1}).
    wp.
    exists* (glob F){2}, (__a7__){2}, (__a5__){2}; elim* => g5 a5_0 a5_1.
    call{2} (F_evaluate_det g5 a5_0 a5_1).
    auto.
    skip => /#.
  qed.

  (* transform: Inline Local Tuple Literal (bucket=open) *)
  lemma micro_0_right_2_fwd :
    equiv [ Step_0R_state_2(K, F).compute ~ Step_0R_state_3(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-param *)
    proc.
    swap{2} 5 -1.
    wp.
    call (_: true).
    wp.
    call (_: true).
    wp.
    call (_: true).
    wp.
    call (_: true).
    skip => /#.
  qed.

  (* transform: Inline Local Tuple Literal (reversed) (bucket=open) *)
  lemma micro_0_right_2_rev :
    equiv [ Step_0R_state_3(K, F).compute ~ Step_0R_state_2(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-param *)
    proc.
    swap{1} 5 -1.
    wp.
    call (_: true).
    wp.
    call (_: true).
    wp.
    call (_: true).
    wp.
    call (_: true).
    skip => /#.
  qed.

  (* transform: Subset Type Normalization (bucket=canned) *)
  lemma micro_0_right_3_fwd :
    equiv [ Step_0R_state_3(K, F).compute ~ Step_0R_state_4(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Subset Type Normalization (reversed) (bucket=canned) *)
  lemma micro_0_right_3_rev :
    equiv [ Step_0R_state_4(K, F).compute ~ Step_0R_state_3(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Remove Redundant Copies (bucket=canned) *)
  lemma micro_0_right_4_fwd :
    equiv [ Step_0R_state_4(K, F).compute ~ Step_0R_state_5(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Remove Redundant Copies (reversed) (bucket=canned) *)
  lemma micro_0_right_4_rev :
    equiv [ Step_0R_state_5(K, F).compute ~ Step_0R_state_4(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Variable Standardization (bucket=canned) *)
  lemma micro_0_right_5_fwd :
    equiv [ Step_0R_state_5(K, F).compute ~ Step_0R_state_6(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Variable Standardization (reversed) (bucket=canned) *)
  lemma micro_0_right_5_rev :
    equiv [ Step_0R_state_6(K, F).compute ~ Step_0R_state_5(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  lemma canon_bridge_0 :
    equiv [ Step_0L_state_7(K, F).compute ~ Step_0R_state_6(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    proc; sim.
  qed.

  lemma hop_0_chain :
    equiv [ Step_0L_state_0(K, F).compute ~ Step_0R_state_0(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* Chain through per-transform micro-lemmas. *)
    transitivity Step_0L_state_1(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}); [ smt() | smt() | apply micro_0_left_0 |].
    transitivity Step_0L_state_2(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}); [ smt() | smt() | apply micro_0_left_1 |].
    transitivity Step_0L_state_3(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}); [ smt() | smt() | apply micro_0_left_2 |].
    transitivity Step_0L_state_4(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}); [ smt() | smt() | apply micro_0_left_3 |].
    transitivity Step_0L_state_5(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}); [ smt() | smt() | apply micro_0_left_4 |].
    transitivity Step_0L_state_6(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}); [ smt() | smt() | apply micro_0_left_5 |].
    transitivity Step_0L_state_7(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}); [ smt() | smt() | apply micro_0_left_6 |].
    transitivity Step_0R_state_6(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}); [ smt() | smt() | apply canon_bridge_0 |].
    transitivity Step_0R_state_5(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}); [ smt() | smt() | apply micro_0_right_5_rev |].
    transitivity Step_0R_state_4(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}); [ smt() | smt() | apply micro_0_right_4_rev |].
    transitivity Step_0R_state_3(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}); [ smt() | smt() | apply micro_0_right_3_rev |].
    transitivity Step_0R_state_2(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}); [ smt() | smt() | apply micro_0_right_2_rev |].
    transitivity Step_0R_state_1(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}); [ smt() | smt() | apply micro_0_right_1_rev |].
    apply micro_0_right_0_rev.
  qed.

  module Step_2L_state_0 (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : CiphertextSpace * bs_out * bs_out = {
      var challenger_Compute__tup0 : SharedSecretSpace * CiphertextSpace;
      var challenger_Compute_ss0 : SharedSecretSpace;
      var challenger_Compute_ct0 : CiphertextSpace;
      var _tup : CiphertextSpace * SharedSecretSpace * SharedSecretSpace;
      var ct : CiphertextSpace;
      var ss_e : SharedSecretSpace;
      var ss_d : SharedSecretSpace;
      var _r0 : bs_out;
      var _r1 : bs_out;
      challenger_Compute__tup0 <@ K.encaps(pk);
      challenger_Compute_ss0 <- challenger_Compute__tup0.`1;
      challenger_Compute_ct0 <- challenger_Compute__tup0.`2;
      _tup <- (challenger_Compute_ct0, challenger_Compute_ss0, challenger_Compute_ss0);
      ct <- _tup.`1;
      ss_e <- _tup.`2;
      ss_d <- _tup.`3;
      _r0 <@ F.evaluate(ss_e, ct);
      _r1 <@ F.evaluate(ss_d, ct);
      return (ct, _r0, _r1);
    }
  }.

  module Step_2L_state_1 (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : CiphertextSpace * bs_out * bs_out = {
      var __a0__ : SharedSecretSpace * CiphertextSpace;
      var __a1__ : SharedSecretSpace;
      var __a2__ : CiphertextSpace;
      var __a3__ : CiphertextSpace * SharedSecretSpace * SharedSecretSpace;
      var __a4__ : CiphertextSpace;
      var __a5__ : SharedSecretSpace;
      var __a6__ : SharedSecretSpace;
      var _r0 : bs_out;
      var _r1 : bs_out;
      __a0__ <@ K.encaps(pk);
      __a1__ <- __a0__.`1;
      __a2__ <- __a0__.`2;
      __a3__ <- (__a2__, __a1__, __a1__);
      __a4__ <- __a3__.`1;
      __a5__ <- __a3__.`2;
      __a6__ <- __a3__.`3;
      _r0 <@ F.evaluate(__a5__, __a4__);
      _r1 <@ F.evaluate(__a6__, __a4__);
      return (__a4__, _r0, _r1);
    }
  }.

  module Step_2L_state_2 (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : CiphertextSpace * bs_out * bs_out = {
      var __a0__ : SharedSecretSpace * CiphertextSpace;
      var __a1__ : SharedSecretSpace;
      var __a3__ : CiphertextSpace * SharedSecretSpace * SharedSecretSpace;
      var __a4__ : CiphertextSpace;
      var _r0 : bs_out;
      var _r1 : bs_out;
      __a0__ <@ K.encaps(pk);
      __a1__ <- __a0__.`1;
      __a3__ <- (__a0__.`2, __a1__, __a1__);
      __a4__ <- __a3__.`1;
      _r0 <@ F.evaluate(__a3__.`2, __a4__);
      _r1 <@ F.evaluate(__a3__.`3, __a4__);
      return (__a4__, _r0, _r1);
    }
  }.

  module Step_2L_state_3 (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : CiphertextSpace * bs_out * bs_out = {
      var __a0__ : SharedSecretSpace * CiphertextSpace;
      var __a1__ : SharedSecretSpace;
      var __a4__ : CiphertextSpace;
      var _r0 : bs_out;
      var _r1 : bs_out;
      __a0__ <@ K.encaps(pk);
      __a1__ <- __a0__.`1;
      __a4__ <- __a0__.`2;
      _r0 <@ F.evaluate(__a1__, __a4__);
      _r1 <@ F.evaluate(__a1__, __a4__);
      return (__a4__, _r0, _r1);
    }
  }.

  module Step_2L_state_4 (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : bs_in * bs_out * bs_out = {
      var __a0__ : bs_lambda * bs_in;
      var __a1__ : bs_lambda;
      var __a4__ : bs_in;
      var _r0 : bs_out;
      var _r1 : bs_out;
      __a0__ <@ K.encaps(pk);
      __a1__ <- __a0__.`1;
      __a4__ <- __a0__.`2;
      _r0 <@ F.evaluate(__a1__, __a4__);
      _r1 <@ F.evaluate(__a1__, __a4__);
      return (__a4__, _r0, _r1);
    }
  }.

  module Step_2L_state_5 (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : bs_in * bs_out * bs_out = {
      var __a0__ : bs_lambda * bs_in;
      var __a1__ : bs_lambda;
      var __a4__ : bs_in;
      var __determ_0__ : bs_out;
      __a0__ <@ K.encaps(pk);
      __a1__ <- __a0__.`1;
      __a4__ <- __a0__.`2;
      __determ_0__ <@ F.evaluate(__a1__, __a4__);
      return (__a4__, __determ_0__, __determ_0__);
    }
  }.

  module Step_2L_state_6 (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : bs_in * bs_out * bs_out = {
      var __a0__ : bs_lambda * bs_in;
      var __a1__ : bs_lambda;
      var __a4__ : bs_in;
      var __a5__ : bs_out;
      __a0__ <@ K.encaps(pk);
      __a1__ <- __a0__.`1;
      __a4__ <- __a0__.`2;
      __a5__ <@ F.evaluate(__a1__, __a4__);
      return (__a4__, __a5__, __a5__);
    }
  }.

  module Step_2L_state_7 (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : bs_in * bs_out * bs_out = {
      var __a0__ : bs_lambda * bs_in;
      var __a4__ : bs_in;
      var __a5__ : bs_out;
      __a0__ <@ K.encaps(pk);
      __a4__ <- __a0__.`2;
      __a5__ <@ F.evaluate(__a0__.`1, __a4__);
      return (__a4__, __a5__, __a5__);
    }
  }.

  module Step_2L_state_8 (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : bs_in * bs_out * bs_out = {
      var v1 : bs_lambda * bs_in;
      var v2 : bs_in;
      var v3 : bs_out;
      v1 <@ K.encaps(pk);
      v2 <- v1.`2;
      v3 <@ F.evaluate(v1.`1, v2);
      return (v2, v3, v3);
    }
  }.

  module Step_2R_state_0 (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : CiphertextSpace * bs_out * bs_out = {
      var v_KF_Encaps_x0 : SharedSecretSpace * CiphertextSpace;
      var v_KF_Encaps_k0 : bs_lambda;
      var v_KF_Encaps_c0 : CiphertextSpace;
      var v_KF_Encaps_ss0 : bs_out;
      var _tup : bs_out * CiphertextSpace;
      var ss : bs_out;
      var ct : CiphertextSpace;
      v_KF_Encaps_x0 <@ K.encaps(pk);
      v_KF_Encaps_k0 <- v_KF_Encaps_x0.`1;
      v_KF_Encaps_c0 <- v_KF_Encaps_x0.`2;
      v_KF_Encaps_ss0 <@ F.evaluate(v_KF_Encaps_k0, v_KF_Encaps_c0);
      _tup <- (v_KF_Encaps_ss0, v_KF_Encaps_c0);
      ss <- _tup.`1;
      ct <- _tup.`2;
      return (ct, ss, ss);
    }
  }.

  module Step_2R_state_1 (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : CiphertextSpace * bs_out * bs_out = {
      var __a0__ : SharedSecretSpace * CiphertextSpace;
      var __a1__ : bs_lambda;
      var __a2__ : CiphertextSpace;
      var __a3__ : bs_out;
      var __a4__ : bs_out * CiphertextSpace;
      var __a5__ : bs_out;
      var __a6__ : CiphertextSpace;
      __a0__ <@ K.encaps(pk);
      __a1__ <- __a0__.`1;
      __a2__ <- __a0__.`2;
      __a3__ <@ F.evaluate(__a1__, __a2__);
      __a4__ <- (__a3__, __a2__);
      __a5__ <- __a4__.`1;
      __a6__ <- __a4__.`2;
      return (__a6__, __a5__, __a5__);
    }
  }.

  module Step_2R_state_2 (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : CiphertextSpace * bs_out * bs_out = {
      var __a0__ : SharedSecretSpace * CiphertextSpace;
      var __a2__ : CiphertextSpace;
      var _r0 : bs_out;
      var __a4__ : bs_out * CiphertextSpace;
      var __a5__ : bs_out;
      __a0__ <@ K.encaps(pk);
      __a2__ <- __a0__.`2;
      _r0 <@ F.evaluate(__a0__.`1, __a2__);
      __a4__ <- (_r0, __a2__);
      __a5__ <- __a4__.`1;
      return (__a4__.`2, __a5__, __a5__);
    }
  }.

  module Step_2R_state_3 (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : CiphertextSpace * bs_out * bs_out = {
      var __a0__ : SharedSecretSpace * CiphertextSpace;
      var __a2__ : CiphertextSpace;
      var __a5__ : bs_out;
      __a0__ <@ K.encaps(pk);
      __a2__ <- __a0__.`2;
      __a5__ <@ F.evaluate(__a0__.`1, __a2__);
      return (__a2__, __a5__, __a5__);
    }
  }.

  module Step_2R_state_4 (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : bs_in * bs_out * bs_out = {
      var __a0__ : bs_lambda * bs_in;
      var __a2__ : bs_in;
      var __a5__ : bs_out;
      __a0__ <@ K.encaps(pk);
      __a2__ <- __a0__.`2;
      __a5__ <@ F.evaluate(__a0__.`1, __a2__);
      return (__a2__, __a5__, __a5__);
    }
  }.

  module Step_2R_state_5 (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : bs_in * bs_out * bs_out = {
      var v1 : bs_lambda * bs_in;
      var v2 : bs_in;
      var v3 : bs_out;
      v1 <@ K.encaps(pk);
      v2 <- v1.`2;
      v3 <@ F.evaluate(v1.`1, v2);
      return (v2, v3, v3);
    }
  }.

  (* transform: Alpha Rename (bucket=canned) *)
  lemma micro_2_left_0 :
    equiv [ Step_2L_state_0(K, F).compute ~ Step_2L_state_1(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  module Step_2L_state_1_fdet (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : CiphertextSpace * bs_out * bs_out = {
      var __a0__ : SharedSecretSpace * CiphertextSpace;
      var __a1__ : SharedSecretSpace;
      var __a2__ : CiphertextSpace;
      var __a3__ : CiphertextSpace * SharedSecretSpace * SharedSecretSpace;
      var __a4__ : CiphertextSpace;
      var __a5__ : SharedSecretSpace;
      var __a6__ : SharedSecretSpace;
      var _r0 : bs_out;
      var _r1 : bs_out;
      __a0__ <@ K.encaps(pk);
      __a1__ <- __a0__.`1;
      __a2__ <- __a0__.`2;
      __a3__ <- (__a2__, __a1__, __a1__);
      __a4__ <- __a3__.`1;
      __a5__ <- __a3__.`2;
      __a6__ <- __a3__.`3;
      _r0 <- F_c.ev_evaluate (__a5__) (__a4__);
      _r1 <- F_c.ev_evaluate (__a6__) (__a4__);
      return (__a4__, _r0, _r1);
    }
  }.

  module Step_2L_state_2_fdet (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : CiphertextSpace * bs_out * bs_out = {
      var __a0__ : SharedSecretSpace * CiphertextSpace;
      var __a1__ : SharedSecretSpace;
      var __a3__ : CiphertextSpace * SharedSecretSpace * SharedSecretSpace;
      var __a4__ : CiphertextSpace;
      var _r0 : bs_out;
      var _r1 : bs_out;
      __a0__ <@ K.encaps(pk);
      __a1__ <- __a0__.`1;
      __a3__ <- (__a0__.`2, __a1__, __a1__);
      __a4__ <- __a3__.`1;
      _r0 <- F_c.ev_evaluate (__a3__.`2) (__a4__);
      _r1 <- F_c.ev_evaluate (__a3__.`3) (__a4__);
      return (__a4__, _r0, _r1);
    }
  }.

  (* transform: Inline Single-Use Variables (bucket=canned) *)
  lemma micro_2_left_1 :
    equiv [ Step_2L_state_1(K, F).compute ~ Step_2L_state_2(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-param *)
    transitivity Step_2L_state_1_fdet(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}).
    smt().
    smt().
    proc.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__}).
    call (_: true); auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__, __a4__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__, __a4__, __a5__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__, __a4__, __a5__, __a6__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__, __a4__, __a5__, __a6__, _r0}).
    wp.
    exists* (glob F){1}, (__a5__){1}, (__a4__){1}; elim* => g0 a0_0 a0_1.
    call{1} (F_evaluate_det g0 a0_0 a0_1).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__, __a4__, __a5__, __a6__, _r0, _r1}).
    wp.
    exists* (glob F){1}, (__a6__){1}, (__a4__){1}; elim* => g1 a1_0 a1_1.
    call{1} (F_evaluate_det g1 a1_0 a1_1).
    auto.
    skip => /#.
    transitivity Step_2L_state_2_fdet(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}).
    smt().
    smt().
    proc.
    wp.
    call (_: true).
    skip => /#.
    proc.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__}).
    call (_: true); auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a3__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a3__, __a4__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a3__, __a4__, _r0}).
    wp.
    exists* (glob F){2}, (__a3__.`2){2}, (__a4__){2}; elim* => g2 a2_0 a2_1.
    call{2} (F_evaluate_det g2 a2_0 a2_1).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a3__, __a4__, _r0, _r1}).
    wp.
    exists* (glob F){2}, (__a3__.`3){2}, (__a4__){2}; elim* => g3 a3_0 a3_1.
    call{2} (F_evaluate_det g3 a3_0 a3_1).
    auto.
    skip => /#.
  qed.

  (* transform: Inline Local Tuple Literal (bucket=open) *)
  lemma micro_2_left_2 :
    equiv [ Step_2L_state_2(K, F).compute ~ Step_2L_state_3(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-param *)
    proc.
    wp.
    call (_: true).
    wp.
    call (_: true).
    wp.
    call (_: true).
    skip => /#.
  qed.

  (* transform: Subset Type Normalization (bucket=canned) *)
  lemma micro_2_left_3 :
    equiv [ Step_2L_state_3(K, F).compute ~ Step_2L_state_4(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Deduplicate Deterministic Calls (bucket=open) *)
  lemma micro_2_left_4 :
    equiv [ Step_2L_state_4(K, F).compute ~ Step_2L_state_5(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-param *)
    proc.
    seq 3 3 : (={glob F, glob K, __a0__, __a1__, __a4__}).
    sim.
    exists* (glob F){1}, __a1__{1}, __a4__{1}; elim* => g a0 a1.
    call{1} (F_evaluate_det g a0 a1).
    call{1} (F_evaluate_det g a0 a1).
    call{2} (F_evaluate_det g a0 a1).
    skip => /#.
  qed.

  (* transform: Alpha Rename (bucket=canned) *)
  lemma micro_2_left_5 :
    equiv [ Step_2L_state_5(K, F).compute ~ Step_2L_state_6(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  module Step_2L_state_6_fdet (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : bs_in * bs_out * bs_out = {
      var __a0__ : bs_lambda * bs_in;
      var __a1__ : bs_lambda;
      var __a4__ : bs_in;
      var __a5__ : bs_out;
      __a0__ <@ K.encaps(pk);
      __a1__ <- __a0__.`1;
      __a4__ <- __a0__.`2;
      __a5__ <- F_c.ev_evaluate (__a1__) (__a4__);
      return (__a4__, __a5__, __a5__);
    }
  }.

  module Step_2L_state_7_fdet (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : bs_in * bs_out * bs_out = {
      var __a0__ : bs_lambda * bs_in;
      var __a4__ : bs_in;
      var __a5__ : bs_out;
      __a0__ <@ K.encaps(pk);
      __a4__ <- __a0__.`2;
      __a5__ <- F_c.ev_evaluate (__a0__.`1) (__a4__);
      return (__a4__, __a5__, __a5__);
    }
  }.

  (* transform: Inline Single-Use Variables (bucket=canned) *)
  lemma micro_2_left_6 :
    equiv [ Step_2L_state_6(K, F).compute ~ Step_2L_state_7(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-param *)
    transitivity Step_2L_state_6_fdet(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}).
    smt().
    smt().
    proc.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__}).
    call (_: true); auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a4__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a4__, __a5__}).
    wp.
    exists* (glob F){1}, (__a1__){1}, (__a4__){1}; elim* => g0 a0_0 a0_1.
    call{1} (F_evaluate_det g0 a0_0 a0_1).
    auto.
    skip => /#.
    transitivity Step_2L_state_7_fdet(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}).
    smt().
    smt().
    proc.
    wp.
    call (_: true).
    skip => /#.
    proc.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__}).
    call (_: true); auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a4__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a4__, __a5__}).
    wp.
    exists* (glob F){2}, (__a0__.`1){2}, (__a4__){2}; elim* => g1 a1_0 a1_1.
    call{2} (F_evaluate_det g1 a1_0 a1_1).
    auto.
    skip => /#.
  qed.

  (* transform: Variable Standardization (bucket=canned) *)
  lemma micro_2_left_7 :
    equiv [ Step_2L_state_7(K, F).compute ~ Step_2L_state_8(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Alpha Rename (bucket=canned) *)
  lemma micro_2_right_0_fwd :
    equiv [ Step_2R_state_0(K, F).compute ~ Step_2R_state_1(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Alpha Rename (reversed) (bucket=canned) *)
  lemma micro_2_right_0_rev :
    equiv [ Step_2R_state_1(K, F).compute ~ Step_2R_state_0(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  module Step_2R_state_1_fdet (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : CiphertextSpace * bs_out * bs_out = {
      var __a0__ : SharedSecretSpace * CiphertextSpace;
      var __a1__ : bs_lambda;
      var __a2__ : CiphertextSpace;
      var __a3__ : bs_out;
      var __a4__ : bs_out * CiphertextSpace;
      var __a5__ : bs_out;
      var __a6__ : CiphertextSpace;
      __a0__ <@ K.encaps(pk);
      __a1__ <- __a0__.`1;
      __a2__ <- __a0__.`2;
      __a3__ <- F_c.ev_evaluate (__a1__) (__a2__);
      __a4__ <- (__a3__, __a2__);
      __a5__ <- __a4__.`1;
      __a6__ <- __a4__.`2;
      return (__a6__, __a5__, __a5__);
    }
  }.

  module Step_2R_state_2_fdet (K : K_c.Scheme, F : F_c.Scheme) = {
    proc compute(pk : PKeySpace, sk : SKeySpace) : CiphertextSpace * bs_out * bs_out = {
      var __a0__ : SharedSecretSpace * CiphertextSpace;
      var __a2__ : CiphertextSpace;
      var _r0 : bs_out;
      var __a4__ : bs_out * CiphertextSpace;
      var __a5__ : bs_out;
      __a0__ <@ K.encaps(pk);
      __a2__ <- __a0__.`2;
      _r0 <- F_c.ev_evaluate (__a0__.`1) (__a2__);
      __a4__ <- (_r0, __a2__);
      __a5__ <- __a4__.`1;
      return (__a4__.`2, __a5__, __a5__);
    }
  }.

  (* transform: Inline Single-Use Variables (bucket=canned) *)
  lemma micro_2_right_1_fwd :
    equiv [ Step_2R_state_1(K, F).compute ~ Step_2R_state_2(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-param *)
    transitivity Step_2R_state_1_fdet(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}).
    smt().
    smt().
    proc.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__}).
    call (_: true); auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__}).
    wp.
    exists* (glob F){1}, (__a1__){1}, (__a2__){1}; elim* => g0 a0_0 a0_1.
    call{1} (F_evaluate_det g0 a0_0 a0_1).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__, __a4__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__, __a4__, __a5__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__, __a4__, __a5__, __a6__}).
    auto.
    skip => /#.
    transitivity Step_2R_state_2_fdet(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}).
    smt().
    smt().
    proc.
    wp.
    call (_: true).
    skip => /#.
    proc.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__}).
    call (_: true); auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a2__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a2__, _r0}).
    wp.
    exists* (glob F){2}, (__a0__.`1){2}, (__a2__){2}; elim* => g1 a1_0 a1_1.
    call{2} (F_evaluate_det g1 a1_0 a1_1).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a2__, _r0, __a4__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a2__, _r0, __a4__, __a5__}).
    auto.
    skip => /#.
  qed.

  (* transform: Inline Single-Use Variables (reversed) (bucket=canned) *)
  lemma micro_2_right_1_rev :
    equiv [ Step_2R_state_2(K, F).compute ~ Step_2R_state_1(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-param *)
    transitivity Step_2R_state_2_fdet(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}).
    smt().
    smt().
    proc.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__}).
    call (_: true); auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a2__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a2__, _r0}).
    wp.
    exists* (glob F){1}, (__a0__.`1){1}, (__a2__){1}; elim* => g0 a0_0 a0_1.
    call{1} (F_evaluate_det g0 a0_0 a0_1).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a2__, _r0, __a4__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a2__, _r0, __a4__, __a5__}).
    auto.
    skip => /#.
    transitivity Step_2R_state_1_fdet(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}).
    smt().
    smt().
    proc.
    wp.
    call (_: true).
    skip => /#.
    proc.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__}).
    call (_: true); auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__}).
    wp.
    exists* (glob F){2}, (__a1__){2}, (__a2__){2}; elim* => g1 a1_0 a1_1.
    call{2} (F_evaluate_det g1 a1_0 a1_1).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__, __a4__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__, __a4__, __a5__}).
    auto.
    seq 1 1 : (={pk, sk, glob K, glob F, __a0__, __a1__, __a2__, __a3__, __a4__, __a5__, __a6__}).
    auto.
    skip => /#.
  qed.

  (* transform: Inline Local Tuple Literal (bucket=open) *)
  lemma micro_2_right_2_fwd :
    equiv [ Step_2R_state_2(K, F).compute ~ Step_2R_state_3(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-param *)
    proc.
    wp.
    call (_: true).
    wp.
    call (_: true).
    skip => /#.
  qed.

  (* transform: Inline Local Tuple Literal (reversed) (bucket=open) *)
  lemma micro_2_right_2_rev :
    equiv [ Step_2R_state_3(K, F).compute ~ Step_2R_state_2(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-param *)
    proc.
    wp.
    call (_: true).
    wp.
    call (_: true).
    skip => /#.
  qed.

  (* transform: Subset Type Normalization (bucket=canned) *)
  lemma micro_2_right_3_fwd :
    equiv [ Step_2R_state_3(K, F).compute ~ Step_2R_state_4(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Subset Type Normalization (reversed) (bucket=canned) *)
  lemma micro_2_right_3_rev :
    equiv [ Step_2R_state_4(K, F).compute ~ Step_2R_state_3(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Variable Standardization (bucket=canned) *)
  lemma micro_2_right_4_fwd :
    equiv [ Step_2R_state_4(K, F).compute ~ Step_2R_state_5(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Variable Standardization (reversed) (bucket=canned) *)
  lemma micro_2_right_4_rev :
    equiv [ Step_2R_state_5(K, F).compute ~ Step_2R_state_4(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  lemma canon_bridge_2 :
    equiv [ Step_2L_state_8(K, F).compute ~ Step_2R_state_5(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    proc; sim.
  qed.

  lemma hop_2_chain :
    equiv [ Step_2L_state_0(K, F).compute ~ Step_2R_state_0(K, F).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* Chain through per-transform micro-lemmas. *)
    transitivity Step_2L_state_1(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}); [ smt() | smt() | apply micro_2_left_0 |].
    transitivity Step_2L_state_2(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}); [ smt() | smt() | apply micro_2_left_1 |].
    transitivity Step_2L_state_3(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}); [ smt() | smt() | apply micro_2_left_2 |].
    transitivity Step_2L_state_4(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}); [ smt() | smt() | apply micro_2_left_3 |].
    transitivity Step_2L_state_5(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}); [ smt() | smt() | apply micro_2_left_4 |].
    transitivity Step_2L_state_6(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}); [ smt() | smt() | apply micro_2_left_5 |].
    transitivity Step_2L_state_7(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}); [ smt() | smt() | apply micro_2_left_6 |].
    transitivity Step_2L_state_8(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}); [ smt() | smt() | apply micro_2_left_7 |].
    transitivity Step_2R_state_5(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}); [ smt() | smt() | apply canon_bridge_2 |].
    transitivity Step_2R_state_4(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}); [ smt() | smt() | apply micro_2_right_4_rev |].
    transitivity Step_2R_state_3(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}); [ smt() | smt() | apply micro_2_right_3_rev |].
    transitivity Step_2R_state_2(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}); [ smt() | smt() | apply micro_2_right_2_rev |].
    transitivity Step_2R_state_1(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}); [ smt() | smt() | apply micro_2_right_1_rev |].
    apply micro_2_right_0_rev.
  qed.

  (* ===== Per-hop equivalence lemmas ===== *)

  lemma hop_0 :
    equiv [ KF_c.KEMCorrectness_FromDecaps(KEMPRF(K, F)).compute ~ R_KEM(K, F, KEMPRF(K, F), K_c.KEMCorrectness_FromDecaps(K)).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* Per-transform: bridge wrappers to flat states, chain through. *)
    transitivity Step_0L_state_0(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}); [ smt() | smt() | proc; inline *; ((sp; wp; sim) || sim) |].
    transitivity Step_0R_state_0(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}); [ smt() | smt() | apply hop_0_chain | proc; inline *; ((sp; wp; sim) || sim) ].
    qed.

  lemma hop_2 :
    equiv [ R_KEM(K, F, KEMPRF(K, F), K_c.KEMCorrectness_FromEncaps(K)).compute ~ KF_c.KEMCorrectness_FromEncaps(KEMPRF(K, F)).compute :
            ={pk, sk, glob K, glob F} ==> ={res, glob K, glob F} ].
  proof.
    (* Per-transform: bridge wrappers to flat states, chain through. *)
    transitivity Step_2L_state_0(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}); [ smt() | smt() | proc; inline *; ((sp; wp; sim) || sim) |].
    transitivity Step_2R_state_0(K, F).compute (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}) (={pk, sk, glob K, glob F} ==> ={res, glob K, glob F}); [ smt() | smt() | apply hop_2_chain | proc; inline *; ((sp; wp; sim) || sim) ].
    qed.

  (* ===== Per-hop probability lemmas ===== *)

  (* Hop 0: interchangeability. The two adjacent games are equivalent (no advantage). *)

  lemma hop_0_pr (A <: KF_c.KEMCorrectness_Adv {-K, -F}) &m :
    Pr[Game_step_0(K, F, A).main() @ &m : res] = Pr[Game_step_1(K, F, A).main() @ &m : res].
  proof.
    byequiv (_: ={glob A, glob K, glob F} ==> ={res}) => //; proc.
    call (_: ={glob K, glob F}); first by conseq hop_0.
    auto.
    qed.

  (* Hop 1: assumption hop. Bounded by the KEMCorrectness_advantage axiom applied to R_KEM_Adv. *)

  lemma hop_1_pr (A <: KF_c.KEMCorrectness_Adv {-K, -F}) &m :
    `| Pr[Game_step_1(K, F, A).main() @ &m : res] - Pr[Game_step_2(K, F, A).main() @ &m : res] | <= K_c.eps_KEMCorrectness.
  proof.
    have hL : Pr[Game_step_1(K, F, A).main() @ &m : res]
            = Pr[K_c.Game_KEMCorrectness_FromDecaps(K, R_KEM_Adv(K, F, A)).main() @ &m : res]
      by byequiv => //; proc; inline *; sim.
    have hR : Pr[Game_step_2(K, F, A).main() @ &m : res]
            = Pr[K_c.Game_KEMCorrectness_FromEncaps(K, R_KEM_Adv(K, F, A)).main() @ &m : res]
      by byequiv => //; proc; inline *; sim.
    rewrite hL hR.
    apply (K_c.KEMCorrectness_advantage K (R_KEM_Adv(K, F, A)) &m).
    qed.

  (* Hop 2: interchangeability. The two adjacent games are equivalent (no advantage). *)

  lemma hop_2_pr (A <: KF_c.KEMCorrectness_Adv {-K, -F}) &m :
    Pr[Game_step_2(K, F, A).main() @ &m : res] = Pr[Game_step_3(K, F, A).main() @ &m : res].
  proof.
    byequiv (_: ={glob A, glob K, glob F} ==> ={res}) => //; proc.
    call (_: ={glob K, glob F}); first by conseq hop_2.
    auto.
    qed.

  (* ===== Main theorem ===== *)

  lemma main_theorem (A <: KF_c.KEMCorrectness_Adv {-K, -F}) &m :
    `| Pr[Game_step_0(K, F, A).main() @ &m : res] - Pr[Game_step_3(K, F, A).main() @ &m : res] | <= K_c.eps_KEMCorrectness.
  proof.
    have h0 := hop_0_pr A &m.
    have h1 := hop_1_pr A &m.
    have h2 := hop_2_pr A &m.
    smt(K_c.eps_KEMCorrectness_pos).
    qed.
end section Main.
