(* Auto-generated by ProofFrog. Do not edit. *)
require import AllCore Distr DProd DMap.

(* ===== Abstract set declarations ===== *)

type MessageSpace.

type KeySpace1.

type KeySpace2.

type IntermediateSpace.

type CiphertextSpace.

(* ===== Concrete primitive types ===== *)

op dCiphertextSpace : CiphertextSpace distr.

axiom dCiphertextSpace_ll : is_lossless dCiphertextSpace.

axiom dCiphertextSpace_fu : is_funiform dCiphertextSpace.

axiom dCiphertextSpace_full : is_full dCiphertextSpace.

op dIntermediateSpace : IntermediateSpace distr.

axiom dIntermediateSpace_ll : is_lossless dIntermediateSpace.

axiom dIntermediateSpace_fu : is_funiform dIntermediateSpace.

axiom dIntermediateSpace_full : is_full dIntermediateSpace.

(* ===== Abstract theory: primitive + security games + assumption ===== *)

abstract theory SymEnc_Theory.
  type key.

  type message.

  type ciphertext.

  op dciphertext : ciphertext distr.

  axiom dciphertext_ll : is_lossless dciphertext.

  axiom dciphertext_fu : is_funiform dciphertext.

  axiom dciphertext_full : is_full dciphertext.

  module type Scheme = {
    proc keygen() : key
    proc enc(k : key, m : message) : ciphertext
    proc dec(k : key, c : ciphertext) : message
  }.

  op ev_dec : key -> ciphertext -> message.

  module type INDOT__Oracle = {
    proc ctxt(m : message) : ciphertext
  }.

  module INDOT__Real (E : Scheme) : INDOT__Oracle = {
    proc ctxt(m : message) : ciphertext = {
      var k : key;
      var c : ciphertext;
      k <@ E.keygen();
      c <@ E.enc(k, m);
      return c;
    }
  }.

  module INDOT__Random (E : Scheme) : INDOT__Oracle = {
    proc ctxt(m : message) : ciphertext = {
      var c : ciphertext;
      c <$ dciphertext;
      return c;
    }
  }.

  module type INDOT__Adv (O : INDOT__Oracle) = {
    proc distinguish() : bool
  }.

  module Game_INDOT__Real (Em : Scheme, A : INDOT__Adv) = {
    proc main() : bool = {
      var b : bool;
      b <@ A(INDOT__Real(Em)).distinguish();
      return b;
    }
  }.

  module Game_INDOT__Random (Em : Scheme, A : INDOT__Adv) = {
    proc main() : bool = {
      var b : bool;
      b <@ A(INDOT__Random(Em)).distinguish();
      return b;
    }
  }.

  op eps_INDOT_ : real.

  axiom eps_INDOT__pos : 0%r <= eps_INDOT_.

  axiom INDOT__advantage (Em <: Scheme) (A <: INDOT__Adv) &m :
    `| Pr[Game_INDOT__Real(Em, A).main() @ &m : res] - Pr[Game_INDOT__Random(Em, A).main() @ &m : res] | <= eps_INDOT_.
end SymEnc_Theory.

(* ===== Theory instantiation ===== *)

clone SymEnc_Theory as S_c with
  type message <- MessageSpace,
  type ciphertext <- IntermediateSpace,
  type key <- KeySpace1,
  op dciphertext <- dIntermediateSpace.

clone SymEnc_Theory as T_c with
  type message <- IntermediateSpace,
  type ciphertext <- CiphertextSpace,
  type key <- KeySpace2,
  op dciphertext <- dCiphertextSpace.

clone SymEnc_Theory as D_c with
  type message <- MessageSpace,
  type ciphertext <- CiphertextSpace,
  type key <- KeySpace1 * KeySpace2,
  op dciphertext <- dCiphertextSpace.

(* ===== Per-clone distribution axioms ===== *)

lemma S_dIntermediateSpace_funi :
  is_funiform dIntermediateSpace.
proof.
  exact dIntermediateSpace_fu.
qed.

lemma S_dIntermediateSpace_ll :
  is_lossless dIntermediateSpace.
proof.
  exact dIntermediateSpace_ll.
qed.

lemma T_dCiphertextSpace_funi :
  is_funiform dCiphertextSpace.
proof.
  exact dCiphertextSpace_fu.
qed.

lemma T_dCiphertextSpace_ll :
  is_lossless dCiphertextSpace.
proof.
  exact dCiphertextSpace_ll.
qed.

lemma D_dCiphertextSpace_funi :
  is_funiform dCiphertextSpace.
proof.
  exact dCiphertextSpace_fu.
qed.

lemma D_dCiphertextSpace_ll :
  is_lossless dCiphertextSpace.
proof.
  exact dCiphertextSpace_ll.
qed.

(* NOTE: the FrogLang scheme has `requires` clauses that are not enforced by the EC export. The scheme module below may fail EC type-checking because cross-clone type equalities implied by the `requires` are not expressed in the clones. Deferred to Phase 5D. *)

(* ===== Concrete scheme implementation ===== *)

module GeneralDoubleSymEnc (S : S_c.Scheme, T : T_c.Scheme) : D_c.Scheme = {
  proc keygen() : KeySpace1 * KeySpace2 = {
    var key1 : KeySpace1;
    var key2 : KeySpace2;
    key1 <@ S.keygen();
    key2 <@ T.keygen();
    return (key1, key2);
  }
  proc enc(k : KeySpace1 * KeySpace2, m : MessageSpace) : CiphertextSpace = {
    var c1 : IntermediateSpace;
    var c2 : CiphertextSpace;
    c1 <@ S.enc(k.`1, m);
    c2 <@ T.enc(k.`2, c1);
    return c2;
  }
  proc dec(k : KeySpace1 * KeySpace2, c : CiphertextSpace) : MessageSpace = {
    var c2 : IntermediateSpace;
    var m : MessageSpace;
    c2 <@ T.dec(k.`2, c);
    m <@ S.dec(k.`1, c2);
    return m;
  }
}.

section Main.
  declare module S <: S_c.Scheme.

  declare module T <: T_c.Scheme {-S}.

  (* ===== Deterministic-method specs ===== *)

  declare axiom S_dec_det (g : (glob S)) (a0 : KeySpace1) (a1 : IntermediateSpace) : phoare[ S.dec : (glob S) = g /\ k = a0 /\ c = a1 ==> (glob S) = g /\ res = S_c.ev_dec a0 a1 ] = 1%r.

  declare axiom T_dec_det (g : (glob T)) (a0 : KeySpace2) (a1 : CiphertextSpace) : phoare[ T.dec : (glob T) = g /\ k = a0 /\ c = a1 ==> (glob T) = g /\ res = T_c.ev_dec a0 a1 ] = 1%r.

  (* ===== Glob-preservation specs (dead-call drop) ===== *)

  declare axiom S_enc_pres (g : (glob S)) : phoare[ S.enc : (glob S) = g ==> (glob S) = g ] = 1%r.

  declare axiom S_keygen_pres (g : (glob S)) : phoare[ S.keygen : (glob S) = g ==> (glob S) = g ] = 1%r.

  (* ===== Reductions ===== *)

  module R1 (D : D_c.Scheme, S : S_c.Scheme, T : T_c.Scheme, Challenger : T_c.INDOT__Oracle) = {
    proc ctxt(m : MessageSpace) : CiphertextSpace = {
      var k1 : KeySpace1;
      var c1 : IntermediateSpace;
      var c2 : CiphertextSpace;
      k1 <@ S.keygen();
      c1 <@ S.enc(k1, m);
      c2 <@ Challenger.ctxt(c1);
      return c2;
    }
  }.

  (* ===== Reductions lifted to assumption-adversaries ===== *)

  module R1_Adv (S : S_c.Scheme, T : T_c.Scheme, A : D_c.INDOT__Adv, C : T_c.INDOT__Oracle) = {
    proc distinguish() : bool = {
      var b : bool;
      b <@ A(R1(GeneralDoubleSymEnc(S, T), S, T, C)).distinguish();
      return b;
    }
  }.

  (* ===== Game-step wrappers ===== *)

  (* Game_step_0: INDOT$.Real *)

  module Game_step_0 (S : S_c.Scheme, T : T_c.Scheme, A : D_c.INDOT__Adv) = {
    proc main() : bool = {
      var b : bool;
      b <@ A(D_c.INDOT__Real(GeneralDoubleSymEnc(S, T))).distinguish();
      return b;
    }
  }.

  (* Game_step_1: INDOT$.Real composed with reduction R1 *)

  module Game_step_1 (S : S_c.Scheme, T : T_c.Scheme, A : D_c.INDOT__Adv) = {
    proc main() : bool = {
      var b : bool;
      b <@ A(R1(GeneralDoubleSymEnc(S, T), S, T, T_c.INDOT__Real(T))).distinguish();
      return b;
    }
  }.

  (* Game_step_2: INDOT$.Random composed with reduction R1 *)

  module Game_step_2 (S : S_c.Scheme, T : T_c.Scheme, A : D_c.INDOT__Adv) = {
    proc main() : bool = {
      var b : bool;
      b <@ A(R1(GeneralDoubleSymEnc(S, T), S, T, T_c.INDOT__Random(T))).distinguish();
      return b;
    }
  }.

  (* Game_step_3: INDOT$.Random *)

  module Game_step_3 (S : S_c.Scheme, T : T_c.Scheme, A : D_c.INDOT__Adv) = {
    proc main() : bool = {
      var b : bool;
      b <@ A(D_c.INDOT__Random(GeneralDoubleSymEnc(S, T))).distinguish();
      return b;
    }
  }.

  (* ===== Per-transform canonicalization chain ===== *)

  (* Per-method congruence lemmas (pure-local tuple inlining) *)

  lemma S_enc_eq :
    equiv [ S.enc ~ S.enc :
            ={glob S, arg} ==> ={glob S, res} ].
  proof. proc true; auto. qed.

  lemma S_keygen_eq :
    equiv [ S.keygen ~ S.keygen :
            ={glob S, arg} ==> ={glob S, res} ].
  proof. proc true; auto. qed.

  lemma T_enc_eq :
    equiv [ T.enc ~ T.enc :
            ={glob T, arg} ==> ={glob T, res} ].
  proof. proc true; auto. qed.

  lemma T_keygen_eq :
    equiv [ T.keygen ~ T.keygen :
            ={glob T, arg} ==> ={glob T, res} ].
  proof. proc true; auto. qed.

  module Step_0L_state_0 (S : S_c.Scheme, T : T_c.Scheme) = {
    proc ctxt(m : MessageSpace) : CiphertextSpace = {
      var v_D_KeyGen_key10 : KeySpace1;
      var v_D_KeyGen_key20 : KeySpace2;
      var k : KeySpace1 * KeySpace2;
      var v_D_Enc_c13 : IntermediateSpace;
      var v_D_Enc_c23 : CiphertextSpace;
      var c : CiphertextSpace;
      v_D_KeyGen_key10 <@ S.keygen();
      v_D_KeyGen_key20 <@ T.keygen();
      k <- (v_D_KeyGen_key10, v_D_KeyGen_key20);
      v_D_Enc_c13 <@ S.enc(k.`1, m);
      v_D_Enc_c23 <@ T.enc(k.`2, v_D_Enc_c13);
      c <- v_D_Enc_c23;
      return c;
    }
  }.

  module Step_0L_state_1 (S : S_c.Scheme, T : T_c.Scheme) = {
    proc ctxt(m : MessageSpace) : CiphertextSpace = {
      var __a0__ : KeySpace1;
      var __a1__ : KeySpace2;
      var __a2__ : KeySpace1 * KeySpace2;
      var __a3__ : IntermediateSpace;
      var __a4__ : CiphertextSpace;
      var __a5__ : CiphertextSpace;
      __a0__ <@ S.keygen();
      __a1__ <@ T.keygen();
      __a2__ <- (__a0__, __a1__);
      __a3__ <@ S.enc(__a2__.`1, m);
      __a4__ <@ T.enc(__a2__.`2, __a3__);
      __a5__ <- __a4__;
      return __a5__;
    }
  }.

  module Step_0L_state_2 (S : S_c.Scheme, T : T_c.Scheme) = {
    proc ctxt(m : MessageSpace) : CiphertextSpace = {
      var __a0__ : KeySpace1;
      var __a1__ : KeySpace2;
      var __a2__ : KeySpace1 * KeySpace2;
      var __a3__ : IntermediateSpace;
      var __a4__ : CiphertextSpace;
      __a0__ <@ S.keygen();
      __a1__ <@ T.keygen();
      __a2__ <- (__a0__, __a1__);
      __a3__ <@ S.enc(__a2__.`1, m);
      __a4__ <@ T.enc(__a2__.`2, __a3__);
      return __a4__;
    }
  }.

  module Step_0L_state_3 (S : S_c.Scheme, T : T_c.Scheme) = {
    proc ctxt(m : MessageSpace) : CiphertextSpace = {
      var _r0 : KeySpace1;
      var _r1 : KeySpace2;
      var __a2__ : KeySpace1 * KeySpace2;
      var _r2 : IntermediateSpace;
      var _r3 : CiphertextSpace;
      _r0 <@ S.keygen();
      _r1 <@ T.keygen();
      __a2__ <- (_r0, _r1);
      _r2 <@ S.enc(__a2__.`1, m);
      _r3 <@ T.enc(__a2__.`2, _r2);
      return _r3;
    }
  }.

  module Step_0L_state_4 (S : S_c.Scheme, T : T_c.Scheme) = {
    proc ctxt(m : MessageSpace) : CiphertextSpace = {
      var _r0 : KeySpace2;
      var _r1 : KeySpace1;
      var _r2 : IntermediateSpace;
      var _r3 : CiphertextSpace;
      _r0 <@ T.keygen();
      _r1 <@ S.keygen();
      _r2 <@ S.enc(_r1, m);
      _r3 <@ T.enc(_r0, _r2);
      return _r3;
    }
  }.

  module Step_0R_state_0 (S : S_c.Scheme, T : T_c.Scheme) = {
    proc ctxt(m : MessageSpace) : CiphertextSpace = {
      var k1 : KeySpace1;
      var c1 : IntermediateSpace;
      var challenger_CTXT_k2 : KeySpace2;
      var challenger_CTXT_c2 : CiphertextSpace;
      var c2 : CiphertextSpace;
      k1 <@ S.keygen();
      c1 <@ S.enc(k1, m);
      challenger_CTXT_k2 <@ T.keygen();
      challenger_CTXT_c2 <@ T.enc(challenger_CTXT_k2, c1);
      c2 <- challenger_CTXT_c2;
      return c2;
    }
  }.

  module Step_0R_state_1 (S : S_c.Scheme, T : T_c.Scheme) = {
    proc ctxt(m : MessageSpace) : CiphertextSpace = {
      var __a0__ : KeySpace1;
      var __a1__ : IntermediateSpace;
      var __a2__ : KeySpace2;
      var __a3__ : CiphertextSpace;
      var __a4__ : CiphertextSpace;
      __a0__ <@ S.keygen();
      __a1__ <@ S.enc(__a0__, m);
      __a2__ <@ T.keygen();
      __a3__ <@ T.enc(__a2__, __a1__);
      __a4__ <- __a3__;
      return __a4__;
    }
  }.

  module Step_0R_state_2 (S : S_c.Scheme, T : T_c.Scheme) = {
    proc ctxt(m : MessageSpace) : CiphertextSpace = {
      var __a0__ : KeySpace1;
      var __a1__ : IntermediateSpace;
      var __a2__ : KeySpace2;
      var __a3__ : CiphertextSpace;
      __a0__ <@ S.keygen();
      __a1__ <@ S.enc(__a0__, m);
      __a2__ <@ T.keygen();
      __a3__ <@ T.enc(__a2__, __a1__);
      return __a3__;
    }
  }.

  module Step_0R_state_3 (S : S_c.Scheme, T : T_c.Scheme) = {
    proc ctxt(m : MessageSpace) : CiphertextSpace = {
      var _r0 : KeySpace2;
      var _r1 : KeySpace1;
      var _r2 : IntermediateSpace;
      var _r3 : CiphertextSpace;
      _r0 <@ T.keygen();
      _r1 <@ S.keygen();
      _r2 <@ S.enc(_r1, m);
      _r3 <@ T.enc(_r0, _r2);
      return _r3;
    }
  }.

  (* transform: Alpha Rename (bucket=canned) *)
  lemma micro_0_left_0 :
    equiv [ Step_0L_state_0(S, T).ctxt ~ Step_0L_state_1(S, T).ctxt :
            ={m, glob S, glob T} ==> ={res, glob S, glob T} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Remove Redundant Copies (bucket=canned) *)
  lemma micro_0_left_1 :
    equiv [ Step_0L_state_1(S, T).ctxt ~ Step_0L_state_2(S, T).ctxt :
            ={m, glob S, glob T} ==> ={res, glob S, glob T} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  module Step_0L_state_2_fdet (S : S_c.Scheme, T : T_c.Scheme) = {
    proc ctxt(m : MessageSpace) : CiphertextSpace = {
      var __a0__ : KeySpace1;
      var __a1__ : KeySpace2;
      var __a2__ : KeySpace1 * KeySpace2;
      var __a3__ : IntermediateSpace;
      var __a4__ : CiphertextSpace;
      __a0__ <@ S.keygen();
      __a1__ <@ T.keygen();
      __a2__ <- (__a0__, __a1__);
      __a3__ <@ S.enc(__a2__.`1, m);
      __a4__ <@ T.enc(__a2__.`2, __a3__);
      return __a4__;
    }
  }.

  module Step_0L_state_3_fdet (S : S_c.Scheme, T : T_c.Scheme) = {
    proc ctxt(m : MessageSpace) : CiphertextSpace = {
      var _r0 : KeySpace1;
      var _r1 : KeySpace2;
      var __a2__ : KeySpace1 * KeySpace2;
      var _r2 : IntermediateSpace;
      var _r3 : CiphertextSpace;
      _r0 <@ S.keygen();
      _r1 <@ T.keygen();
      __a2__ <- (_r0, _r1);
      _r2 <@ S.enc(__a2__.`1, m);
      _r3 <@ T.enc(__a2__.`2, _r2);
      return _r3;
    }
  }.

  (* transform: Inline Single-Use Variables (bucket=canned) *)
  lemma micro_0_left_2 :
    equiv [ Step_0L_state_2(S, T).ctxt ~ Step_0L_state_3(S, T).ctxt :
            ={m, glob S, glob T} ==> ={res, glob S, glob T} ].
  proof.
    (* resolution: synth-param *)
    transitivity Step_0L_state_2_fdet(S, T).ctxt (={m, glob S, glob T} ==> ={res, glob S, glob T}) (={m, glob S, glob T} ==> ={res, glob S, glob T}).
    smt().
    smt().
    proc.
    seq 1 1 : (={m, glob S, glob T, __a0__}).
    call (_: true); auto.
    seq 1 1 : (={m, glob S, glob T, __a0__, __a1__}).
    call (_: true); auto.
    seq 1 1 : (={m, glob S, glob T, __a0__, __a1__, __a2__}).
    auto.
    seq 1 1 : (={m, glob S, glob T, __a0__, __a1__, __a2__, __a3__}).
    call (_: true); auto.
    seq 1 1 : (={m, glob S, glob T, __a0__, __a1__, __a2__, __a3__, __a4__}).
    call (_: true); auto.
    skip => /#.
    transitivity Step_0L_state_3_fdet(S, T).ctxt (={m, glob S, glob T} ==> ={res, glob S, glob T}) (={m, glob S, glob T} ==> ={res, glob S, glob T}).
    smt().
    smt().
    proc.
    wp.
    call (_: true).
    wp.
    call (_: true).
    wp.
    call (_: true).
    wp.
    call (_: true).
    skip => /#.
    proc.
    seq 1 1 : (={m, glob S, glob T, _r0}).
    call (_: true); auto.
    seq 1 1 : (={m, glob S, glob T, _r0, _r1}).
    call (_: true); auto.
    seq 1 1 : (={m, glob S, glob T, _r0, _r1, __a2__}).
    auto.
    seq 1 1 : (={m, glob S, glob T, _r0, _r1, __a2__, _r2}).
    call (_: true); auto.
    seq 1 1 : (={m, glob S, glob T, _r0, _r1, __a2__, _r2, _r3}).
    call (_: true); auto.
    skip => /#.
  qed.

  (* transform: Inline Local Tuple Literal (bucket=open) *)
  lemma micro_0_left_3 :
    equiv [ Step_0L_state_3(S, T).ctxt ~ Step_0L_state_4(S, T).ctxt :
            ={m, glob S, glob T} ==> ={res, glob S, glob T} ].
  proof.
    (* resolution: synth-param *)
    proc.
    swap{2} 2 -1.
    call T_enc_eq.
    call S_enc_eq.
    wp.
    call T_keygen_eq.
    call S_keygen_eq.
    skip => /#.
  qed.

  (* transform: Alpha Rename (bucket=canned) *)
  lemma micro_0_right_0_fwd :
    equiv [ Step_0R_state_0(S, T).ctxt ~ Step_0R_state_1(S, T).ctxt :
            ={m, glob S, glob T} ==> ={res, glob S, glob T} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Alpha Rename (reversed) (bucket=canned) *)
  lemma micro_0_right_0_rev :
    equiv [ Step_0R_state_1(S, T).ctxt ~ Step_0R_state_0(S, T).ctxt :
            ={m, glob S, glob T} ==> ={res, glob S, glob T} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Remove Redundant Copies (bucket=canned) *)
  lemma micro_0_right_1_fwd :
    equiv [ Step_0R_state_1(S, T).ctxt ~ Step_0R_state_2(S, T).ctxt :
            ={m, glob S, glob T} ==> ={res, glob S, glob T} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Remove Redundant Copies (reversed) (bucket=canned) *)
  lemma micro_0_right_1_rev :
    equiv [ Step_0R_state_2(S, T).ctxt ~ Step_0R_state_1(S, T).ctxt :
            ={m, glob S, glob T} ==> ={res, glob S, glob T} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Inline Single-Use Variables (bucket=canned) *)
  lemma micro_0_right_2_fwd :
    equiv [ Step_0R_state_2(S, T).ctxt ~ Step_0R_state_3(S, T).ctxt :
            ={m, glob S, glob T} ==> ={res, glob S, glob T} ].
  proof.
    (* resolution: synth-param *)
    proc.
    swap{1} 3 -2.
    sp; wp; sim.
  qed.

  (* transform: Inline Single-Use Variables (reversed) (bucket=canned) *)
  lemma micro_0_right_2_rev :
    equiv [ Step_0R_state_3(S, T).ctxt ~ Step_0R_state_2(S, T).ctxt :
            ={m, glob S, glob T} ==> ={res, glob S, glob T} ].
  proof.
    (* resolution: synth-param *)
    proc.
    swap{1} 2 -1.
    swap{1} 3 -1.
    sp; wp; sim.
  qed.

  lemma canon_bridge_0 :
    equiv [ Step_0L_state_4(S, T).ctxt ~ Step_0R_state_3(S, T).ctxt :
            ={m, glob S, glob T} ==> ={res, glob S, glob T} ].
  proof.
    proc; sim.
  qed.

  lemma hop_0_chain :
    equiv [ Step_0L_state_0(S, T).ctxt ~ Step_0R_state_0(S, T).ctxt :
            ={m, glob S, glob T} ==> ={res, glob S, glob T} ].
  proof.
    (* Chain through per-transform micro-lemmas. *)
    transitivity Step_0L_state_1(S, T).ctxt (={m, glob S, glob T} ==> ={res, glob S, glob T}) (={m, glob S, glob T} ==> ={res, glob S, glob T}); [ smt() | smt() | apply micro_0_left_0 |].
    transitivity Step_0L_state_2(S, T).ctxt (={m, glob S, glob T} ==> ={res, glob S, glob T}) (={m, glob S, glob T} ==> ={res, glob S, glob T}); [ smt() | smt() | apply micro_0_left_1 |].
    transitivity Step_0L_state_3(S, T).ctxt (={m, glob S, glob T} ==> ={res, glob S, glob T}) (={m, glob S, glob T} ==> ={res, glob S, glob T}); [ smt() | smt() | apply micro_0_left_2 |].
    transitivity Step_0L_state_4(S, T).ctxt (={m, glob S, glob T} ==> ={res, glob S, glob T}) (={m, glob S, glob T} ==> ={res, glob S, glob T}); [ smt() | smt() | apply micro_0_left_3 |].
    transitivity Step_0R_state_3(S, T).ctxt (={m, glob S, glob T} ==> ={res, glob S, glob T}) (={m, glob S, glob T} ==> ={res, glob S, glob T}); [ smt() | smt() | apply canon_bridge_0 |].
    transitivity Step_0R_state_2(S, T).ctxt (={m, glob S, glob T} ==> ={res, glob S, glob T}) (={m, glob S, glob T} ==> ={res, glob S, glob T}); [ smt() | smt() | apply micro_0_right_2_rev |].
    transitivity Step_0R_state_1(S, T).ctxt (={m, glob S, glob T} ==> ={res, glob S, glob T}) (={m, glob S, glob T} ==> ={res, glob S, glob T}); [ smt() | smt() | apply micro_0_right_1_rev |].
    apply micro_0_right_0_rev.
  qed.

  module Step_2L_state_0 (S : S_c.Scheme, T : T_c.Scheme) = {
    proc ctxt(m : MessageSpace) : CiphertextSpace = {
      var k1 : KeySpace1;
      var c1 : IntermediateSpace;
      var challenger_CTXT_c2 : CiphertextSpace;
      var c2 : CiphertextSpace;
      k1 <@ S.keygen();
      c1 <@ S.enc(k1, m);
      challenger_CTXT_c2 <$ dCiphertextSpace;
      c2 <- challenger_CTXT_c2;
      return c2;
    }
  }.

  module Step_2L_state_1 (S : S_c.Scheme, T : T_c.Scheme) = {
    proc ctxt(m : MessageSpace) : CiphertextSpace = {
      var __a0__ : KeySpace1;
      var __a1__ : IntermediateSpace;
      var __a2__ : CiphertextSpace;
      var __a3__ : CiphertextSpace;
      __a0__ <@ S.keygen();
      __a1__ <@ S.enc(__a0__, m);
      __a2__ <$ dCiphertextSpace;
      __a3__ <- __a2__;
      return __a3__;
    }
  }.

  module Step_2L_state_2 (S : S_c.Scheme, T : T_c.Scheme) = {
    proc ctxt(m : MessageSpace) : CiphertextSpace = {
      var __a0__ : KeySpace1;
      var __a1__ : IntermediateSpace;
      var __a2__ : CiphertextSpace;
      __a0__ <@ S.keygen();
      __a1__ <@ S.enc(__a0__, m);
      __a2__ <$ dCiphertextSpace;
      return __a2__;
    }
  }.

  module Step_2L_state_3 (S : S_c.Scheme, T : T_c.Scheme) = {
    proc ctxt(m : MessageSpace) : CiphertextSpace = {
      var _r0 : KeySpace1;
      var __a1__ : IntermediateSpace;
      var __a2__ : CiphertextSpace;
      _r0 <@ S.keygen();
      __a1__ <@ S.enc(_r0, m);
      __a2__ <$ dCiphertextSpace;
      return __a2__;
    }
  }.

  module Step_2L_state_4 (S : S_c.Scheme, T : T_c.Scheme) = {
    proc ctxt(m : MessageSpace) : CiphertextSpace = {
      var __a2__ : CiphertextSpace;
      __a2__ <$ dCiphertextSpace;
      return __a2__;
    }
  }.

  module Step_2L_state_5 (S : S_c.Scheme, T : T_c.Scheme) = {
    proc ctxt(m : MessageSpace) : CiphertextSpace = {
      var v1 : CiphertextSpace;
      v1 <$ dCiphertextSpace;
      return v1;
    }
  }.

  module Step_2R_state_0 (S : S_c.Scheme, T : T_c.Scheme) = {
    proc ctxt(m : MessageSpace) : CiphertextSpace = {
      var c : CiphertextSpace;
      c <$ dCiphertextSpace;
      return c;
    }
  }.

  module Step_2R_state_1 (S : S_c.Scheme, T : T_c.Scheme) = {
    proc ctxt(m : MessageSpace) : CiphertextSpace = {
      var __a0__ : CiphertextSpace;
      __a0__ <$ dCiphertextSpace;
      return __a0__;
    }
  }.

  module Step_2R_state_2 (S : S_c.Scheme, T : T_c.Scheme) = {
    proc ctxt(m : MessageSpace) : CiphertextSpace = {
      var v1 : CiphertextSpace;
      v1 <$ dCiphertextSpace;
      return v1;
    }
  }.

  (* transform: Alpha Rename (bucket=canned) *)
  lemma micro_2_left_0 :
    equiv [ Step_2L_state_0(S, T).ctxt ~ Step_2L_state_1(S, T).ctxt :
            ={m, glob S, glob T} ==> ={res, glob S, glob T} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Remove Redundant Copies (bucket=canned) *)
  lemma micro_2_left_1 :
    equiv [ Step_2L_state_1(S, T).ctxt ~ Step_2L_state_2(S, T).ctxt :
            ={m, glob S, glob T} ==> ={res, glob S, glob T} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  module Step_2L_state_2_fdet (S : S_c.Scheme, T : T_c.Scheme) = {
    proc ctxt(m : MessageSpace) : CiphertextSpace = {
      var __a0__ : KeySpace1;
      var __a1__ : IntermediateSpace;
      var __a2__ : CiphertextSpace;
      __a0__ <@ S.keygen();
      __a1__ <@ S.enc(__a0__, m);
      __a2__ <$ dCiphertextSpace;
      return __a2__;
    }
  }.

  module Step_2L_state_3_fdet (S : S_c.Scheme, T : T_c.Scheme) = {
    proc ctxt(m : MessageSpace) : CiphertextSpace = {
      var _r0 : KeySpace1;
      var __a1__ : IntermediateSpace;
      var __a2__ : CiphertextSpace;
      _r0 <@ S.keygen();
      __a1__ <@ S.enc(_r0, m);
      __a2__ <$ dCiphertextSpace;
      return __a2__;
    }
  }.

  (* transform: Inline Single-Use Variables (bucket=canned) *)
  lemma micro_2_left_2 :
    equiv [ Step_2L_state_2(S, T).ctxt ~ Step_2L_state_3(S, T).ctxt :
            ={m, glob S, glob T} ==> ={res, glob S, glob T} ].
  proof.
    (* resolution: synth-param *)
    transitivity Step_2L_state_2_fdet(S, T).ctxt (={m, glob S, glob T} ==> ={res, glob S, glob T}) (={m, glob S, glob T} ==> ={res, glob S, glob T}).
    smt().
    smt().
    proc.
    seq 1 1 : (={m, glob S, glob T, __a0__}).
    call (_: true); auto.
    seq 1 1 : (={m, glob S, glob T, __a0__, __a1__}).
    call (_: true); auto.
    seq 1 1 : (={m, glob S, glob T, __a0__, __a1__, __a2__}).
    auto.
    skip => /#.
    transitivity Step_2L_state_3_fdet(S, T).ctxt (={m, glob S, glob T} ==> ={res, glob S, glob T}) (={m, glob S, glob T} ==> ={res, glob S, glob T}).
    smt().
    smt().
    proc.
    wp.
    rnd.
    wp.
    call (_: true).
    wp.
    call (_: true).
    skip => /#.
    proc.
    seq 1 1 : (={m, glob S, glob T, _r0}).
    call (_: true); auto.
    seq 1 1 : (={m, glob S, glob T, _r0, __a1__}).
    call (_: true); auto.
    seq 1 1 : (={m, glob S, glob T, _r0, __a1__, __a2__}).
    auto.
    skip => /#.
  qed.

  (* transform: Topological Sorting (bucket=canned) *)
  lemma micro_2_left_3 :
    equiv [ Step_2L_state_3(S, T).ctxt ~ Step_2L_state_4(S, T).ctxt :
            ={m, glob S, glob T} ==> ={res, glob S, glob T} ].
  proof.
    (* resolution: synth-param *)
    proc.
    seq 2 0 : (={m, glob S, glob T}).
    + exists* (glob S){1}; elim* => g_S.
      call{1} (S_enc_pres g_S).
      call{1} (S_keygen_pres g_S).
      auto.
    sim.
  qed.

  (* transform: Variable Standardization (bucket=canned) *)
  lemma micro_2_left_4 :
    equiv [ Step_2L_state_4(S, T).ctxt ~ Step_2L_state_5(S, T).ctxt :
            ={m, glob S, glob T} ==> ={res, glob S, glob T} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Alpha Rename (bucket=canned) *)
  lemma micro_2_right_0_fwd :
    equiv [ Step_2R_state_0(S, T).ctxt ~ Step_2R_state_1(S, T).ctxt :
            ={m, glob S, glob T} ==> ={res, glob S, glob T} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Alpha Rename (reversed) (bucket=canned) *)
  lemma micro_2_right_0_rev :
    equiv [ Step_2R_state_1(S, T).ctxt ~ Step_2R_state_0(S, T).ctxt :
            ={m, glob S, glob T} ==> ={res, glob S, glob T} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Variable Standardization (bucket=canned) *)
  lemma micro_2_right_1_fwd :
    equiv [ Step_2R_state_1(S, T).ctxt ~ Step_2R_state_2(S, T).ctxt :
            ={m, glob S, glob T} ==> ={res, glob S, glob T} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Variable Standardization (reversed) (bucket=canned) *)
  lemma micro_2_right_1_rev :
    equiv [ Step_2R_state_2(S, T).ctxt ~ Step_2R_state_1(S, T).ctxt :
            ={m, glob S, glob T} ==> ={res, glob S, glob T} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  lemma canon_bridge_2 :
    equiv [ Step_2L_state_5(S, T).ctxt ~ Step_2R_state_2(S, T).ctxt :
            ={m, glob S, glob T} ==> ={res, glob S, glob T} ].
  proof.
    proc; sim.
  qed.

  lemma hop_2_chain :
    equiv [ Step_2L_state_0(S, T).ctxt ~ Step_2R_state_0(S, T).ctxt :
            ={m, glob S, glob T} ==> ={res, glob S, glob T} ].
  proof.
    (* Chain through per-transform micro-lemmas. *)
    transitivity Step_2L_state_1(S, T).ctxt (={m, glob S, glob T} ==> ={res, glob S, glob T}) (={m, glob S, glob T} ==> ={res, glob S, glob T}); [ smt() | smt() | apply micro_2_left_0 |].
    transitivity Step_2L_state_2(S, T).ctxt (={m, glob S, glob T} ==> ={res, glob S, glob T}) (={m, glob S, glob T} ==> ={res, glob S, glob T}); [ smt() | smt() | apply micro_2_left_1 |].
    transitivity Step_2L_state_3(S, T).ctxt (={m, glob S, glob T} ==> ={res, glob S, glob T}) (={m, glob S, glob T} ==> ={res, glob S, glob T}); [ smt() | smt() | apply micro_2_left_2 |].
    transitivity Step_2L_state_4(S, T).ctxt (={m, glob S, glob T} ==> ={res, glob S, glob T}) (={m, glob S, glob T} ==> ={res, glob S, glob T}); [ smt() | smt() | apply micro_2_left_3 |].
    transitivity Step_2L_state_5(S, T).ctxt (={m, glob S, glob T} ==> ={res, glob S, glob T}) (={m, glob S, glob T} ==> ={res, glob S, glob T}); [ smt() | smt() | apply micro_2_left_4 |].
    transitivity Step_2R_state_2(S, T).ctxt (={m, glob S, glob T} ==> ={res, glob S, glob T}) (={m, glob S, glob T} ==> ={res, glob S, glob T}); [ smt() | smt() | apply canon_bridge_2 |].
    transitivity Step_2R_state_1(S, T).ctxt (={m, glob S, glob T} ==> ={res, glob S, glob T}) (={m, glob S, glob T} ==> ={res, glob S, glob T}); [ smt() | smt() | apply micro_2_right_1_rev |].
    apply micro_2_right_0_rev.
  qed.

  (* ===== Per-hop equivalence lemmas ===== *)

  lemma hop_0 :
    equiv [ D_c.INDOT__Real(GeneralDoubleSymEnc(S, T)).ctxt ~ R1(GeneralDoubleSymEnc(S, T), S, T, T_c.INDOT__Real(T)).ctxt :
            ={m, glob S, glob T} ==> ={res, glob S, glob T} ].
  proof.
    (* Per-transform: bridge wrappers to flat states, chain through. *)
    transitivity Step_0L_state_0(S, T).ctxt (={m, glob S, glob T} ==> ={res, glob S, glob T}) (={m, glob S, glob T} ==> ={res, glob S, glob T}); [ smt() | smt() | proc; inline *; ((sp; wp; sim) || sim) |].
    transitivity Step_0R_state_0(S, T).ctxt (={m, glob S, glob T} ==> ={res, glob S, glob T}) (={m, glob S, glob T} ==> ={res, glob S, glob T}); [ smt() | smt() | apply hop_0_chain | proc; inline *; ((sp; wp; sim) || sim) ].
    qed.

  lemma hop_2 :
    equiv [ R1(GeneralDoubleSymEnc(S, T), S, T, T_c.INDOT__Random(T)).ctxt ~ D_c.INDOT__Random(GeneralDoubleSymEnc(S, T)).ctxt :
            ={m, glob S, glob T} ==> ={res, glob S, glob T} ].
  proof.
    (* Per-transform: bridge wrappers to flat states, chain through. *)
    transitivity Step_2L_state_0(S, T).ctxt (={m, glob S, glob T} ==> ={res, glob S, glob T}) (={m, glob S, glob T} ==> ={res, glob S, glob T}); [ smt() | smt() | proc; inline *; ((sp; wp; sim) || sim) |].
    transitivity Step_2R_state_0(S, T).ctxt (={m, glob S, glob T} ==> ={res, glob S, glob T}) (={m, glob S, glob T} ==> ={res, glob S, glob T}); [ smt() | smt() | apply hop_2_chain | proc; inline *; ((sp; wp; sim) || sim) ].
    qed.

  (* ===== Per-hop probability lemmas ===== *)

  (* Hop 0: interchangeability. The two adjacent games are equivalent (no advantage). *)

  lemma hop_0_pr (A <: D_c.INDOT__Adv {-S, -T}) &m :
    Pr[Game_step_0(S, T, A).main() @ &m : res] = Pr[Game_step_1(S, T, A).main() @ &m : res].
  proof.
    byequiv (_: ={glob A, glob S, glob T} ==> ={res}) => //; proc.
    call (_: ={glob S, glob T}); first by conseq hop_0.
    auto.
    qed.

  (* Hop 1: assumption hop. Bounded by the INDOT$_advantage axiom applied to R1_Adv. *)

  lemma hop_1_pr (A <: D_c.INDOT__Adv {-S, -T}) &m :
    `| Pr[Game_step_1(S, T, A).main() @ &m : res] - Pr[Game_step_2(S, T, A).main() @ &m : res] | <= T_c.eps_INDOT_.
  proof.
    have hL : Pr[Game_step_1(S, T, A).main() @ &m : res]
            = Pr[T_c.Game_INDOT__Real(T, R1_Adv(S, T, A)).main() @ &m : res]
      by byequiv => //; proc; inline *; sim.
    have hR : Pr[Game_step_2(S, T, A).main() @ &m : res]
            = Pr[T_c.Game_INDOT__Random(T, R1_Adv(S, T, A)).main() @ &m : res]
      by byequiv => //; proc; inline *; sim.
    rewrite hL hR.
    apply (T_c.INDOT__advantage T (R1_Adv(S, T, A)) &m).
    qed.

  (* Hop 2: interchangeability. The two adjacent games are equivalent (no advantage). *)

  lemma hop_2_pr (A <: D_c.INDOT__Adv {-S, -T}) &m :
    Pr[Game_step_2(S, T, A).main() @ &m : res] = Pr[Game_step_3(S, T, A).main() @ &m : res].
  proof.
    byequiv (_: ={glob A, glob S, glob T} ==> ={res}) => //; proc.
    call (_: ={glob S, glob T}); first by conseq hop_2.
    auto.
    qed.

  (* ===== Main theorem ===== *)

  lemma main_theorem (A <: D_c.INDOT__Adv {-S, -T}) &m :
    `| Pr[Game_step_0(S, T, A).main() @ &m : res] - Pr[Game_step_3(S, T, A).main() @ &m : res] | <= T_c.eps_INDOT_.
  proof.
    have h0 := hop_0_pr A &m.
    have h1 := hop_1_pr A &m.
    have h2 := hop_2_pr A &m.
    smt(T_c.eps_INDOT__pos).
    qed.
end section Main.
