(* Auto-generated by ProofFrog. Do not edit. *)
require import AllCore Distr DProd DMap.

(* ===== Abstract set declarations ===== *)

type MessageSpace.

type CiphertextSpace.

type PKeySpace.

type SKeySpace.

(* ===== Concrete primitive types ===== *)

op dMessageSpace : MessageSpace distr.

axiom dMessageSpace_ll : is_lossless dMessageSpace.

axiom dMessageSpace_fu : is_funiform dMessageSpace.

axiom dMessageSpace_full : is_full dMessageSpace.

(* ===== Abstract theory: primitive + security games + assumption ===== *)

abstract theory KEM_Theory.
  type publickey.

  type secretkey.

  type sharedsecret.

  type ciphertext.

  op dsharedsecret : sharedsecret distr.

  axiom dsharedsecret_ll : is_lossless dsharedsecret.

  axiom dsharedsecret_fu : is_funiform dsharedsecret.

  axiom dsharedsecret_full : is_full dsharedsecret.

  module type Scheme = {
    proc keygen() : publickey * secretkey
    proc encaps(pk : publickey) : sharedsecret * ciphertext
    proc decaps(sk : secretkey, m : ciphertext) : sharedsecret
  }.

  op ev_decaps : secretkey -> ciphertext -> sharedsecret.

  module type KEM_INDCCA_MultiChal_Oracle = {
    proc initialize() : publickey * sharedsecret * ciphertext
    proc decaps(c : ciphertext) : sharedsecret option
  }.

  module KEM_INDCCA_MultiChal_Real (K : Scheme) : KEM_INDCCA_MultiChal_Oracle = {
    var sk : secretkey
    var ctStar : ciphertext
    proc initialize() : publickey * sharedsecret * ciphertext = {
      var _tup : publickey * secretkey;
      var pk : publickey;
      var _tup_0 : sharedsecret * ciphertext;
      var ss : sharedsecret;
      _tup <@ K.keygen();
      pk <- _tup.`1;
      sk <- _tup.`2;
      _tup_0 <@ K.encaps(pk);
      ss <- _tup_0.`1;
      ctStar <- _tup_0.`2;
      return (pk, ss, ctStar);
    }
    proc decaps(c : ciphertext) : sharedsecret option = {
      var _r0 : sharedsecret option;
      var _r1 : sharedsecret;
      if (c = ctStar) {
        _r0 <- None;
      } else {
        _r1 <@ K.decaps(sk, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module KEM_INDCCA_MultiChal_Random (K : Scheme) : KEM_INDCCA_MultiChal_Oracle = {
    var sk : secretkey
    var ctStar : ciphertext
    proc initialize() : publickey * sharedsecret * ciphertext = {
      var _tup : publickey * secretkey;
      var pk : publickey;
      var _tup_0 : sharedsecret * ciphertext;
      var ssReal : sharedsecret;
      var ss : sharedsecret;
      _tup <@ K.keygen();
      pk <- _tup.`1;
      sk <- _tup.`2;
      _tup_0 <@ K.encaps(pk);
      ssReal <- _tup_0.`1;
      ctStar <- _tup_0.`2;
      ss <$ dsharedsecret;
      return (pk, ss, ctStar);
    }
    proc decaps(c : ciphertext) : sharedsecret option = {
      var _r0 : sharedsecret option;
      var _r1 : sharedsecret;
      if (c = ctStar) {
        _r0 <- None;
      } else {
        _r1 <@ K.decaps(sk, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module type KEM_INDCCA_MultiChal_Adv (O : KEM_INDCCA_MultiChal_Oracle) = {
    proc distinguish(pk : publickey * sharedsecret * ciphertext) : bool {O.decaps}
  }.
end KEM_Theory.

(* ===== Foreign primitive theory: PKE_Theory ===== *)

abstract theory PKE_Theory.
  type publickey.

  type secretkey.

  type message.

  type ciphertext.

  module type Scheme = {
    proc keygen() : publickey * secretkey
    proc enc(pk : publickey, m : message) : ciphertext
    proc dec(sk : secretkey, ct : ciphertext) : message
  }.

  op ev_dec : secretkey -> ciphertext -> message.

  module type PKE_INDCCA_Oracle = {
    proc initialize() : publickey
    proc challenge(m0 : message, m1 : message) : ciphertext
    proc dec(ct : ciphertext) : message option
  }.

  module PKE_INDCCA_Left (E : Scheme) : PKE_INDCCA_Oracle = {
    var pk : publickey
    var sk : secretkey
    var ctStar : ciphertext
    var challenged : bool
    proc initialize() : publickey = {
      var _tup : publickey * secretkey;
      _tup <@ E.keygen();
      pk <- _tup.`1;
      sk <- _tup.`2;
      challenged <- false;
      return pk;
    }
    proc challenge(m0 : message, m1 : message) : ciphertext = {
      var ct : ciphertext;
      ct <@ E.enc(pk, m0);
      ctStar <- ct;
      challenged <- true;
      return ct;
    }
    proc dec(ct : ciphertext) : message option = {
      var _r0 : message option;
      var _r1 : bool;
      var _r2 : message;
      _r1 <- false;
      if (challenged) {
        if (ct = ctStar) {
          _r0 <- None;
          _r1 <- true;
        }
      }
      if (! _r1) {
        _r2 <@ E.dec(sk, ct);
        _r0 <- Some (_r2);
      }
      return _r0;
    }
  }.

  module PKE_INDCCA_Right (E : Scheme) : PKE_INDCCA_Oracle = {
    var pk : publickey
    var sk : secretkey
    var ctStar : ciphertext
    var challenged : bool
    proc initialize() : publickey = {
      var _tup : publickey * secretkey;
      _tup <@ E.keygen();
      pk <- _tup.`1;
      sk <- _tup.`2;
      challenged <- false;
      return pk;
    }
    proc challenge(m0 : message, m1 : message) : ciphertext = {
      var ct : ciphertext;
      ct <@ E.enc(pk, m1);
      ctStar <- ct;
      challenged <- true;
      return ct;
    }
    proc dec(ct : ciphertext) : message option = {
      var _r0 : message option;
      var _r1 : bool;
      var _r2 : message;
      _r1 <- false;
      if (challenged) {
        if (ct = ctStar) {
          _r0 <- None;
          _r1 <- true;
        }
      }
      if (! _r1) {
        _r2 <@ E.dec(sk, ct);
        _r0 <- Some (_r2);
      }
      return _r0;
    }
  }.

  module type PKE_INDCCA_Adv (O : PKE_INDCCA_Oracle) = {
    proc distinguish(pk : publickey) : bool {O.challenge, O.dec}
  }.

  module Game_PKE_INDCCA_Left (Em : Scheme, A : PKE_INDCCA_Adv) = {
    proc main() : bool = {
      var b : bool;
      var pk : publickey;
      pk <@ PKE_INDCCA_Left(Em).initialize();
      b <@ A(PKE_INDCCA_Left(Em)).distinguish(pk);
      return b;
    }
  }.

  module Game_PKE_INDCCA_Right (Em : Scheme, A : PKE_INDCCA_Adv) = {
    proc main() : bool = {
      var b : bool;
      var pk : publickey;
      pk <@ PKE_INDCCA_Right(Em).initialize();
      b <@ A(PKE_INDCCA_Right(Em)).distinguish(pk);
      return b;
    }
  }.

  op eps_PKE_INDCCA : real.

  axiom eps_PKE_INDCCA_pos : 0%r <= eps_PKE_INDCCA.

  axiom PKE_INDCCA_advantage (Em <: Scheme) (A <: PKE_INDCCA_Adv) &m :
    `| Pr[Game_PKE_INDCCA_Left(Em, A).main() @ &m : res] - Pr[Game_PKE_INDCCA_Right(Em, A).main() @ &m : res] | <= eps_PKE_INDCCA.
end PKE_Theory.

(* ===== Theory instantiation ===== *)

clone PKE_Theory as E_c with
  type message <- MessageSpace,
  type ciphertext <- CiphertextSpace,
  type publickey <- PKeySpace,
  type secretkey <- SKeySpace.

clone KEM_Theory as L_c with
  type sharedsecret <- MessageSpace,
  type ciphertext <- CiphertextSpace,
  type publickey <- PKeySpace,
  type secretkey <- SKeySpace,
  op dsharedsecret <- dMessageSpace.

(* ===== Per-clone distribution axioms ===== *)

lemma L_dMessageSpace_funi :
  is_funiform dMessageSpace.
proof.
  exact dMessageSpace_fu.
qed.

lemma L_dMessageSpace_ll :
  is_lossless dMessageSpace.
proof.
  exact dMessageSpace_ll.
qed.

(* ===== Concrete scheme implementation ===== *)

module LCK (E : E_c.Scheme) : L_c.Scheme = {
  proc keygen() : PKeySpace * SKeySpace = {
    var _r0 : PKeySpace * SKeySpace;
    _r0 <@ E.keygen();
    return _r0;
  }
  proc encaps(pk : PKeySpace) : MessageSpace * CiphertextSpace = {
    var k : MessageSpace;
    var ct : CiphertextSpace;
    k <$ dMessageSpace;
    ct <@ E.enc(pk, k);
    return (k, ct);
  }
  proc decaps(sk : SKeySpace, ct : CiphertextSpace) : MessageSpace = {
    var _r0 : MessageSpace;
    _r0 <@ E.dec(sk, ct);
    return _r0;
  }
}.

section Main.
  (* ===== Reductions ===== *)

  module B1 (E : E_c.Scheme, L : L_c.Scheme, Challenger : E_c.PKE_INDCCA_Oracle) = {
    var ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var pk : PKeySpace;
      var k0 : MessageSpace;
      var k1 : MessageSpace;
      var ct : CiphertextSpace;
      pk <@ Challenger.initialize();
      k0 <$ dMessageSpace;
      k1 <$ dMessageSpace;
      ct <@ Challenger.challenge(k0, k1);
      ctStar <- ct;
      return (pk, k0, ct);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      if (c = ctStar) {
        _r0 <- None;
      } else {
        _r0 <@ Challenger.dec(c);
      }
      return _r0;
    }
  }.

  (* ===== Reductions lifted to assumption-adversaries ===== *)

  module B1_Adv (E : E_c.Scheme, A : L_c.KEM_INDCCA_MultiChal_Adv, C : E_c.PKE_INDCCA_Oracle) = {
    proc distinguish(pk : PKeySpace) : bool = {
      var b : bool;
      var pk0 : PKeySpace * MessageSpace * CiphertextSpace;
      var pk : PKeySpace;
      var k0 : MessageSpace;
      var k1 : MessageSpace;
      var ct : CiphertextSpace;
      pk <- pk;
      k0 <$ dMessageSpace;
      k1 <$ dMessageSpace;
      ct <@ C.challenge(k0, k1);
      B1.ctStar <- ct;
      pk0 <- (pk, k0, ct);
      b <@ A(B1(E, LCK(E), C)).distinguish(pk0);
      return b;
    }
  }.

  (* ===== Game-step wrappers ===== *)

  (* Game_step_0: KEM_INDCCA_MultiChal.Real *)

  module Game_step_0 (E : E_c.Scheme, A : L_c.KEM_INDCCA_MultiChal_Adv) = {
    proc main() : bool = {
      var b : bool;
      var pk : PKeySpace * MessageSpace * CiphertextSpace;
      pk <@ L_c.KEM_INDCCA_MultiChal_Real(LCK(E)).initialize();
      b <@ A(L_c.KEM_INDCCA_MultiChal_Real(LCK(E))).distinguish(pk);
      return b;
    }
  }.

  (* Game_step_1: PKE_INDCCA.Left composed with reduction B1 *)

  module Game_step_1 (E : E_c.Scheme, A : L_c.KEM_INDCCA_MultiChal_Adv) = {
    proc main() : bool = {
      var b : bool;
      var pk : PKeySpace * MessageSpace * CiphertextSpace;
      pk <@ B1(E, LCK(E), E_c.PKE_INDCCA_Left(E)).initialize();
      b <@ A(B1(E, LCK(E), E_c.PKE_INDCCA_Left(E))).distinguish(pk);
      return b;
    }
  }.

  (* Game_step_2: PKE_INDCCA.Right composed with reduction B1 *)

  module Game_step_2 (E : E_c.Scheme, A : L_c.KEM_INDCCA_MultiChal_Adv) = {
    proc main() : bool = {
      var b : bool;
      var pk : PKeySpace * MessageSpace * CiphertextSpace;
      pk <@ B1(E, LCK(E), E_c.PKE_INDCCA_Right(E)).initialize();
      b <@ A(B1(E, LCK(E), E_c.PKE_INDCCA_Right(E))).distinguish(pk);
      return b;
    }
  }.

  (* Game_step_3: KEM_INDCCA_MultiChal.Random *)

  module Game_step_3 (E : E_c.Scheme, A : L_c.KEM_INDCCA_MultiChal_Adv) = {
    proc main() : bool = {
      var b : bool;
      var pk : PKeySpace * MessageSpace * CiphertextSpace;
      pk <@ L_c.KEM_INDCCA_MultiChal_Random(LCK(E)).initialize();
      b <@ A(L_c.KEM_INDCCA_MultiChal_Random(LCK(E))).distinguish(pk);
      return b;
    }
  }.

  (* ===== Per-transform canonicalization chain ===== *)

  module Step_0L_state_0 (E : E_c.Scheme) = {
    var sk : SKeySpace
    var ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var _tup : PKeySpace * SKeySpace;
      var pk : PKeySpace;
      var v_L_Encaps_k3 : MessageSpace;
      var v_L_Encaps_ct3 : CiphertextSpace;
      var _tup_0 : MessageSpace * CiphertextSpace;
      var ss : MessageSpace;
      _tup <@ E.keygen();
      pk <- _tup.`1;
      sk <- _tup.`2;
      v_L_Encaps_k3 <$ dMessageSpace;
      v_L_Encaps_ct3 <@ E.enc(pk, v_L_Encaps_k3);
      _tup_0 <- (v_L_Encaps_k3, v_L_Encaps_ct3);
      ss <- _tup_0.`1;
      ctStar <- _tup_0.`2;
      return (pk, ss, ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = ctStar) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(sk, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_0L_state_1 (E : E_c.Scheme) = {
    var sk : SKeySpace
    var ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a0__ : PKeySpace * SKeySpace;
      var __a1__ : PKeySpace;
      var __a2__ : MessageSpace;
      var __a3__ : CiphertextSpace;
      var __a4__ : MessageSpace * CiphertextSpace;
      var __a5__ : MessageSpace;
      __a0__ <@ E.keygen();
      __a1__ <- __a0__.`1;
      sk <- __a0__.`2;
      __a2__ <$ dMessageSpace;
      __a3__ <@ E.enc(__a1__, __a2__);
      __a4__ <- (__a2__, __a3__);
      __a5__ <- __a4__.`1;
      ctStar <- __a4__.`2;
      return (__a1__, __a5__, ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = ctStar) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(sk, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_0L_state_2 (E : E_c.Scheme) = {
    var sk : SKeySpace
    var ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a0__ : PKeySpace * SKeySpace;
      var __a1__ : PKeySpace;
      var __a2__ : MessageSpace;
      var _r0 : CiphertextSpace;
      var __a4__ : MessageSpace * CiphertextSpace;
      __a0__ <@ E.keygen();
      __a1__ <- __a0__.`1;
      sk <- __a0__.`2;
      __a2__ <$ dMessageSpace;
      _r0 <@ E.enc(__a1__, __a2__);
      __a4__ <- (__a2__, _r0);
      ctStar <- __a4__.`2;
      return (__a1__, __a4__.`1, ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = ctStar) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(sk, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_0L_state_3 (E : E_c.Scheme) = {
    var sk : SKeySpace
    var ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a2__ : MessageSpace;
      var __a0__ : PKeySpace * SKeySpace;
      var __a1__ : PKeySpace;
      var _r0 : CiphertextSpace;
      var __a4__ : MessageSpace * CiphertextSpace;
      __a2__ <$ dMessageSpace;
      __a0__ <@ E.keygen();
      __a1__ <- __a0__.`1;
      sk <- __a0__.`2;
      _r0 <@ E.enc(__a1__, __a2__);
      __a4__ <- (__a2__, _r0);
      ctStar <- __a4__.`2;
      return (__a1__, __a4__.`1, ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = ctStar) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(sk, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_0L_state_4 (E : E_c.Scheme) = {
    var sk : SKeySpace
    var ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a2__ : MessageSpace;
      var __a0__ : PKeySpace * SKeySpace;
      var __a1__ : PKeySpace;
      __a2__ <$ dMessageSpace;
      __a0__ <@ E.keygen();
      __a1__ <- __a0__.`1;
      sk <- __a0__.`2;
      ctStar <@ E.enc(__a1__, __a2__);
      return (__a1__, __a2__, ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = ctStar) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(sk, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_0L_state_5 (E : E_c.Scheme) = {
    var sk : SKeySpace
    var ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a0__ : PKeySpace * SKeySpace;
      var __a2__ : MessageSpace;
      var __a1__ : PKeySpace;
      __a0__ <@ E.keygen();
      __a2__ <$ dMessageSpace;
      __a1__ <- __a0__.`1;
      sk <- __a0__.`2;
      ctStar <@ E.enc(__a1__, __a2__);
      return (__a1__, __a2__, ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = ctStar) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(sk, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_0L_state_6 (E : E_c.Scheme) = {
    var sk : SKeySpace
    var ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var v1 : PKeySpace * SKeySpace;
      var v2 : MessageSpace;
      var v3 : PKeySpace;
      v1 <@ E.keygen();
      v2 <$ dMessageSpace;
      v3 <- v1.`1;
      sk <- v1.`2;
      ctStar <@ E.enc(v3, v2);
      return (v3, v2, ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = ctStar) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(sk, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_0L_state_7 (E : E_c.Scheme) = {
    var field1 : CiphertextSpace
    var field2 : SKeySpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var v1 : PKeySpace * SKeySpace;
      var v2 : MessageSpace;
      var v3 : PKeySpace;
      v1 <@ E.keygen();
      v2 <$ dMessageSpace;
      v3 <- v1.`1;
      field2 <- v1.`2;
      field1 <@ E.enc(v3, v2);
      return (v3, v2, field1);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = field1) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(field2, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_0L_state_8 (E : E_c.Scheme) = {
    var field1 : CiphertextSpace
    var field2 : SKeySpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var v1 : PKeySpace * SKeySpace;
      var v2 : MessageSpace;
      var v3 : PKeySpace;
      v1 <@ E.keygen();
      v2 <$ dMessageSpace;
      v3 <- v1.`1;
      field1 <@ E.enc(v3, v2);
      field2 <- v1.`2;
      return (v3, v2, field1);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = field1) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(field2, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_0L_state_9 (E : E_c.Scheme) = {
    var field1 : CiphertextSpace
    var field2 : SKeySpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var v1 : PKeySpace * SKeySpace;
      var v3 : PKeySpace;
      var v2 : MessageSpace;
      v1 <@ E.keygen();
      v3 <- v1.`1;
      v2 <$ dMessageSpace;
      field1 <@ E.enc(v3, v2);
      field2 <- v1.`2;
      return (v3, v2, field1);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = field1) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(field2, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_0L_state_10 (E : E_c.Scheme) = {
    var field1 : CiphertextSpace
    var field2 : SKeySpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var v1 : PKeySpace * SKeySpace;
      var v2 : PKeySpace;
      var v3 : MessageSpace;
      v1 <@ E.keygen();
      v2 <- v1.`1;
      v3 <$ dMessageSpace;
      field1 <@ E.enc(v2, v3);
      field2 <- v1.`2;
      return (v2, v3, field1);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = field1) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(field2, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_0R_state_0 (E : E_c.Scheme) = {
    var challenger_pk : PKeySpace
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    var challenger_challenged : bool
    var ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var challenger_Initialize__tup0 : PKeySpace * SKeySpace;
      var pk : PKeySpace;
      var k0 : MessageSpace;
      var k1 : MessageSpace;
      var challenger_Challenge_ct7 : CiphertextSpace;
      var ct : CiphertextSpace;
      challenger_Initialize__tup0 <@ E.keygen();
      challenger_pk <- challenger_Initialize__tup0.`1;
      challenger_sk <- challenger_Initialize__tup0.`2;
      challenger_challenged <- false;
      pk <- challenger_pk;
      k0 <$ dMessageSpace;
      k1 <$ dMessageSpace;
      challenger_Challenge_ct7 <@ E.enc(challenger_pk, k0);
      challenger_ctStar <- challenger_Challenge_ct7;
      challenger_challenged <- true;
      ct <- challenger_Challenge_ct7;
      ctStar <- ct;
      return (pk, k0, ct);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : bool;
      var _r2 : MessageSpace;
      if (c = ctStar) {
        _r0 <- None;
      } else {
        _r1 <- false;
        if (challenger_challenged) {
          if (c = challenger_ctStar) {
            _r0 <- None;
            _r1 <- true;
          }
        }
        if (! _r1) {
          _r2 <@ E.dec(challenger_sk, c);
          _r0 <- Some (_r2);
        }
      }
      return _r0;
    }
  }.

  module Step_0R_state_1 (E : E_c.Scheme) = {
    var challenger_pk : PKeySpace
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    var challenger_challenged : bool
    var ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a0__ : PKeySpace * SKeySpace;
      var __a1__ : PKeySpace;
      var __a2__ : MessageSpace;
      var __a3__ : MessageSpace;
      var __a4__ : CiphertextSpace;
      var __a5__ : CiphertextSpace;
      __a0__ <@ E.keygen();
      challenger_pk <- __a0__.`1;
      challenger_sk <- __a0__.`2;
      challenger_challenged <- false;
      __a1__ <- challenger_pk;
      __a2__ <$ dMessageSpace;
      __a3__ <$ dMessageSpace;
      __a4__ <@ E.enc(challenger_pk, __a2__);
      challenger_ctStar <- __a4__;
      challenger_challenged <- true;
      __a5__ <- __a4__;
      ctStar <- __a5__;
      return (__a1__, __a2__, __a5__);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : bool;
      var _r2 : MessageSpace;
      if (c = ctStar) {
        _r0 <- None;
      } else {
        _r1 <- false;
        if (challenger_challenged) {
          if (c = challenger_ctStar) {
            _r0 <- None;
            _r1 <- true;
          }
        }
        if (! _r1) {
          _r2 <@ E.dec(challenger_sk, c);
          _r0 <- Some (_r2);
        }
      }
      return _r0;
    }
  }.

  module Step_0R_state_2 (E : E_c.Scheme) = {
    var challenger_pk : PKeySpace
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    var challenger_challenged : bool
    var ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a0__ : PKeySpace * SKeySpace;
      var __a2__ : MessageSpace;
      var __a3__ : MessageSpace;
      var __a4__ : CiphertextSpace;
      __a0__ <@ E.keygen();
      challenger_pk <- __a0__.`1;
      challenger_sk <- __a0__.`2;
      challenger_challenged <- false;
      __a2__ <$ dMessageSpace;
      __a3__ <$ dMessageSpace;
      __a4__ <@ E.enc(challenger_pk, __a2__);
      challenger_ctStar <- __a4__;
      challenger_challenged <- true;
      ctStar <- __a4__;
      return (challenger_pk, __a2__, __a4__);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : bool;
      var _r2 : MessageSpace;
      if (c = ctStar) {
        _r0 <- None;
      } else {
        _r1 <- false;
        if (challenger_challenged) {
          if (c = challenger_ctStar) {
            _r0 <- None;
            _r1 <- true;
          }
        }
        if (! _r1) {
          _r2 <@ E.dec(challenger_sk, c);
          _r0 <- Some (_r2);
        }
      }
      return _r0;
    }
  }.

  module Step_0R_state_3 (E : E_c.Scheme) = {
    var challenger_pk : PKeySpace
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    var challenger_challenged : bool
    var ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a0__ : PKeySpace * SKeySpace;
      var __a2__ : MessageSpace;
      var __a3__ : MessageSpace;
      var __a4__ : CiphertextSpace;
      __a0__ <@ E.keygen();
      challenger_pk <- __a0__.`1;
      challenger_sk <- __a0__.`2;
      challenger_challenged <- false;
      __a2__ <$ dMessageSpace;
      __a3__ <$ dMessageSpace;
      __a4__ <@ E.enc(challenger_pk, __a2__);
      challenger_ctStar <- __a4__;
      challenger_challenged <- true;
      ctStar <- challenger_ctStar;
      return (challenger_pk, __a2__, ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : bool;
      var _r2 : MessageSpace;
      if (c = ctStar) {
        _r0 <- None;
      } else {
        _r1 <- false;
        if (challenger_challenged) {
          if (c = challenger_ctStar) {
            _r0 <- None;
            _r1 <- true;
          }
        }
        if (! _r1) {
          _r2 <@ E.dec(challenger_sk, c);
          _r0 <- Some (_r2);
        }
      }
      return _r0;
    }
  }.

  module Step_0R_state_4 (E : E_c.Scheme) = {
    var challenger_pk : PKeySpace
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    var challenger_challenged : bool
    var ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a0__ : PKeySpace * SKeySpace;
      var __a2__ : MessageSpace;
      var __a4__ : CiphertextSpace;
      challenger_challenged <- false;
      __a0__ <@ E.keygen();
      __a2__ <$ dMessageSpace;
      challenger_challenged <- true;
      challenger_pk <- __a0__.`1;
      challenger_sk <- __a0__.`2;
      __a4__ <@ E.enc(challenger_pk, __a2__);
      challenger_ctStar <- __a4__;
      ctStar <- challenger_ctStar;
      return (challenger_pk, __a2__, ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : bool;
      var _r2 : MessageSpace;
      if (c = ctStar) {
        _r0 <- None;
      } else {
        _r1 <- false;
        if (challenger_challenged) {
          if (c = challenger_ctStar) {
            _r0 <- None;
            _r1 <- true;
          }
        }
        if (! _r1) {
          _r2 <@ E.dec(challenger_sk, c);
          _r0 <- Some (_r2);
        }
      }
      return _r0;
    }
  }.

  module Step_0R_state_5 (E : E_c.Scheme) = {
    var challenger_pk : PKeySpace
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    var challenger_challenged : bool
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a0__ : PKeySpace * SKeySpace;
      var __a2__ : MessageSpace;
      var __a4__ : CiphertextSpace;
      challenger_challenged <- false;
      __a0__ <@ E.keygen();
      __a2__ <$ dMessageSpace;
      challenger_challenged <- true;
      challenger_pk <- __a0__.`1;
      challenger_sk <- __a0__.`2;
      __a4__ <@ E.enc(challenger_pk, __a2__);
      challenger_ctStar <- __a4__;
      return (challenger_pk, __a2__, challenger_ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : bool;
      var _r2 : MessageSpace;
      if (c = challenger_ctStar) {
        _r0 <- None;
      } else {
        _r1 <- false;
        if (challenger_challenged) {
          if (c = challenger_ctStar) {
            _r0 <- None;
            _r1 <- true;
          }
        }
        if (! _r1) {
          _r2 <@ E.dec(challenger_sk, c);
          _r0 <- Some (_r2);
        }
      }
      return _r0;
    }
  }.

  module Step_0R_state_6 (E : E_c.Scheme) = {
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    var challenger_challenged : bool
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a0__ : PKeySpace * SKeySpace;
      var __a2__ : MessageSpace;
      var __a4__ : CiphertextSpace;
      challenger_challenged <- false;
      __a0__ <@ E.keygen();
      __a2__ <$ dMessageSpace;
      challenger_challenged <- true;
      challenger_sk <- __a0__.`2;
      __a4__ <@ E.enc(__a0__.`1, __a2__);
      challenger_ctStar <- __a4__;
      return (__a0__.`1, __a2__, challenger_ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : bool;
      var _r2 : MessageSpace;
      if (c = challenger_ctStar) {
        _r0 <- None;
      } else {
        _r1 <- false;
        if (challenger_challenged) {
          if (c = challenger_ctStar) {
            _r0 <- None;
            _r1 <- true;
          }
        }
        if (! _r1) {
          _r2 <@ E.dec(challenger_sk, c);
          _r0 <- Some (_r2);
        }
      }
      return _r0;
    }
  }.

  module Step_0R_state_7 (E : E_c.Scheme) = {
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    var challenger_challenged : bool
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a0__ : PKeySpace * SKeySpace;
      var __a2__ : MessageSpace;
      var __a4__ : CiphertextSpace;
      __a0__ <@ E.keygen();
      __a2__ <$ dMessageSpace;
      challenger_challenged <- true;
      challenger_sk <- __a0__.`2;
      __a4__ <@ E.enc(__a0__.`1, __a2__);
      challenger_ctStar <- __a4__;
      return (__a0__.`1, __a2__, challenger_ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : bool;
      var _r2 : MessageSpace;
      if (c = challenger_ctStar) {
        _r0 <- None;
      } else {
        _r1 <- false;
        if (challenger_challenged) {
          if (c = challenger_ctStar) {
            _r0 <- None;
            _r1 <- true;
          }
        }
        if (! _r1) {
          _r2 <@ E.dec(challenger_sk, c);
          _r0 <- Some (_r2);
        }
      }
      return _r0;
    }
  }.

  module Step_0R_state_8 (E : E_c.Scheme) = {
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    var challenger_challenged : bool
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a0__ : PKeySpace * SKeySpace;
      var __a2__ : MessageSpace;
      __a0__ <@ E.keygen();
      __a2__ <$ dMessageSpace;
      challenger_challenged <- true;
      challenger_sk <- __a0__.`2;
      challenger_ctStar <@ E.enc(__a0__.`1, __a2__);
      return (__a0__.`1, __a2__, challenger_ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : bool;
      var _r2 : MessageSpace;
      if (c = challenger_ctStar) {
        _r0 <- None;
      } else {
        _r1 <- false;
        if (challenger_challenged) {
          if (c = challenger_ctStar) {
            _r0 <- None;
            _r1 <- true;
          }
        }
        if (! _r1) {
          _r2 <@ E.dec(challenger_sk, c);
          _r0 <- Some (_r2);
        }
      }
      return _r0;
    }
  }.

  module Step_0R_state_9 (E : E_c.Scheme) = {
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    var challenger_challenged : bool
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a0__ : PKeySpace * SKeySpace;
      var __a2__ : MessageSpace;
      __a0__ <@ E.keygen();
      __a2__ <$ dMessageSpace;
      challenger_challenged <- true;
      challenger_sk <- __a0__.`2;
      challenger_ctStar <@ E.enc(__a0__.`1, __a2__);
      return (__a0__.`1, __a2__, challenger_ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : bool;
      var _r2 : MessageSpace;
      if (c = challenger_ctStar) {
        _r0 <- None;
      } else {
        _r1 <- false;
        if (challenger_challenged) {
        }
        if (! _r1) {
          _r2 <@ E.dec(challenger_sk, c);
          _r0 <- Some (_r2);
        }
      }
      return _r0;
    }
  }.

  module Step_0R_state_10 (E : E_c.Scheme) = {
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    var challenger_challenged : bool
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a0__ : PKeySpace * SKeySpace;
      var __cse___a0___0__ : PKeySpace;
      var __a2__ : MessageSpace;
      __a0__ <@ E.keygen();
      __cse___a0___0__ <- __a0__.`1;
      __a2__ <$ dMessageSpace;
      challenger_challenged <- true;
      challenger_sk <- __a0__.`2;
      challenger_ctStar <@ E.enc(__cse___a0___0__, __a2__);
      return (__cse___a0___0__, __a2__, challenger_ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : bool;
      var _r2 : MessageSpace;
      if (c = challenger_ctStar) {
        _r0 <- None;
      } else {
        _r1 <- false;
        if (challenger_challenged) {
        }
        if (! _r1) {
          _r2 <@ E.dec(challenger_sk, c);
          _r0 <- Some (_r2);
        }
      }
      return _r0;
    }
  }.

  module Step_0R_state_11 (E : E_c.Scheme) = {
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    var challenger_challenged : bool
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a0__ : PKeySpace * SKeySpace;
      var __a2__ : MessageSpace;
      var __cse___a0___0__ : PKeySpace;
      challenger_challenged <- true;
      __a0__ <@ E.keygen();
      __a2__ <$ dMessageSpace;
      __cse___a0___0__ <- __a0__.`1;
      challenger_sk <- __a0__.`2;
      challenger_ctStar <@ E.enc(__cse___a0___0__, __a2__);
      return (__cse___a0___0__, __a2__, challenger_ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : bool;
      var _r2 : MessageSpace;
      if (c = challenger_ctStar) {
        _r0 <- None;
      } else {
        _r1 <- false;
        if (challenger_challenged) {
        }
        if (! _r1) {
          _r2 <@ E.dec(challenger_sk, c);
          _r0 <- Some (_r2);
        }
      }
      return _r0;
    }
  }.

  module Step_0R_state_12 (E : E_c.Scheme) = {
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a0__ : PKeySpace * SKeySpace;
      var __a2__ : MessageSpace;
      var __cse___a0___0__ : PKeySpace;
      __a0__ <@ E.keygen();
      __a2__ <$ dMessageSpace;
      __cse___a0___0__ <- __a0__.`1;
      challenger_sk <- __a0__.`2;
      challenger_ctStar <@ E.enc(__cse___a0___0__, __a2__);
      return (__cse___a0___0__, __a2__, challenger_ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : bool;
      var _r2 : MessageSpace;
      if (c = challenger_ctStar) {
        _r0 <- None;
      } else {
        _r1 <- false;
        if (true) {
        }
        if (! _r1) {
          _r2 <@ E.dec(challenger_sk, c);
          _r0 <- Some (_r2);
        }
      }
      return _r0;
    }
  }.

  module Step_0R_state_13 (E : E_c.Scheme) = {
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a0__ : PKeySpace * SKeySpace;
      var __a2__ : MessageSpace;
      var __a3__ : PKeySpace;
      __a0__ <@ E.keygen();
      __a2__ <$ dMessageSpace;
      __a3__ <- __a0__.`1;
      challenger_sk <- __a0__.`2;
      challenger_ctStar <@ E.enc(__a3__, __a2__);
      return (__a3__, __a2__, challenger_ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : bool;
      var _r2 : MessageSpace;
      if (c = challenger_ctStar) {
        _r0 <- None;
      } else {
        _r1 <- false;
        if (true) {
        }
        if (! _r1) {
          _r2 <@ E.dec(challenger_sk, c);
          _r0 <- Some (_r2);
        }
      }
      return _r0;
    }
  }.

  module Step_0R_state_14 (E : E_c.Scheme) = {
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a0__ : PKeySpace * SKeySpace;
      var __a2__ : MessageSpace;
      var __a3__ : PKeySpace;
      __a0__ <@ E.keygen();
      __a2__ <$ dMessageSpace;
      __a3__ <- __a0__.`1;
      challenger_sk <- __a0__.`2;
      challenger_ctStar <@ E.enc(__a3__, __a2__);
      return (__a3__, __a2__, challenger_ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = challenger_ctStar) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(challenger_sk, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_0R_state_15 (E : E_c.Scheme) = {
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var v1 : PKeySpace * SKeySpace;
      var v2 : MessageSpace;
      var v3 : PKeySpace;
      v1 <@ E.keygen();
      v2 <$ dMessageSpace;
      v3 <- v1.`1;
      challenger_sk <- v1.`2;
      challenger_ctStar <@ E.enc(v3, v2);
      return (v3, v2, challenger_ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = challenger_ctStar) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(challenger_sk, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_0R_state_16 (E : E_c.Scheme) = {
    var field1 : CiphertextSpace
    var field2 : SKeySpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var v1 : PKeySpace * SKeySpace;
      var v2 : MessageSpace;
      var v3 : PKeySpace;
      v1 <@ E.keygen();
      v2 <$ dMessageSpace;
      v3 <- v1.`1;
      field2 <- v1.`2;
      field1 <@ E.enc(v3, v2);
      return (v3, v2, field1);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = field1) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(field2, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_0R_state_17 (E : E_c.Scheme) = {
    var field1 : CiphertextSpace
    var field2 : SKeySpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var v1 : PKeySpace * SKeySpace;
      var v2 : MessageSpace;
      var v3 : PKeySpace;
      v1 <@ E.keygen();
      v2 <$ dMessageSpace;
      v3 <- v1.`1;
      field1 <@ E.enc(v3, v2);
      field2 <- v1.`2;
      return (v3, v2, field1);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = field1) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(field2, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_0R_state_18 (E : E_c.Scheme) = {
    var field1 : CiphertextSpace
    var field2 : SKeySpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var v1 : PKeySpace * SKeySpace;
      var v3 : PKeySpace;
      var v2 : MessageSpace;
      v1 <@ E.keygen();
      v3 <- v1.`1;
      v2 <$ dMessageSpace;
      field1 <@ E.enc(v3, v2);
      field2 <- v1.`2;
      return (v3, v2, field1);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = field1) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(field2, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_0R_state_19 (E : E_c.Scheme) = {
    var field1 : CiphertextSpace
    var field2 : SKeySpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var v1 : PKeySpace * SKeySpace;
      var v2 : PKeySpace;
      var v3 : MessageSpace;
      v1 <@ E.keygen();
      v2 <- v1.`1;
      v3 <$ dMessageSpace;
      field1 <@ E.enc(v2, v3);
      field2 <- v1.`2;
      return (v2, v3, field1);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = field1) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(field2, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_2L_state_0 (E : E_c.Scheme) = {
    var challenger_pk : PKeySpace
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    var challenger_challenged : bool
    var ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var challenger_Initialize__tup0 : PKeySpace * SKeySpace;
      var pk : PKeySpace;
      var k0 : MessageSpace;
      var k1 : MessageSpace;
      var challenger_Challenge_ct7 : CiphertextSpace;
      var ct : CiphertextSpace;
      challenger_Initialize__tup0 <@ E.keygen();
      challenger_pk <- challenger_Initialize__tup0.`1;
      challenger_sk <- challenger_Initialize__tup0.`2;
      challenger_challenged <- false;
      pk <- challenger_pk;
      k0 <$ dMessageSpace;
      k1 <$ dMessageSpace;
      challenger_Challenge_ct7 <@ E.enc(challenger_pk, k1);
      challenger_ctStar <- challenger_Challenge_ct7;
      challenger_challenged <- true;
      ct <- challenger_Challenge_ct7;
      ctStar <- ct;
      return (pk, k0, ct);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : bool;
      var _r2 : MessageSpace;
      if (c = ctStar) {
        _r0 <- None;
      } else {
        _r1 <- false;
        if (challenger_challenged) {
          if (c = challenger_ctStar) {
            _r0 <- None;
            _r1 <- true;
          }
        }
        if (! _r1) {
          _r2 <@ E.dec(challenger_sk, c);
          _r0 <- Some (_r2);
        }
      }
      return _r0;
    }
  }.

  module Step_2L_state_1 (E : E_c.Scheme) = {
    var challenger_pk : PKeySpace
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    var challenger_challenged : bool
    var ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a0__ : PKeySpace * SKeySpace;
      var __a1__ : PKeySpace;
      var __a2__ : MessageSpace;
      var __a3__ : MessageSpace;
      var __a4__ : CiphertextSpace;
      var __a5__ : CiphertextSpace;
      __a0__ <@ E.keygen();
      challenger_pk <- __a0__.`1;
      challenger_sk <- __a0__.`2;
      challenger_challenged <- false;
      __a1__ <- challenger_pk;
      __a2__ <$ dMessageSpace;
      __a3__ <$ dMessageSpace;
      __a4__ <@ E.enc(challenger_pk, __a3__);
      challenger_ctStar <- __a4__;
      challenger_challenged <- true;
      __a5__ <- __a4__;
      ctStar <- __a5__;
      return (__a1__, __a2__, __a5__);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : bool;
      var _r2 : MessageSpace;
      if (c = ctStar) {
        _r0 <- None;
      } else {
        _r1 <- false;
        if (challenger_challenged) {
          if (c = challenger_ctStar) {
            _r0 <- None;
            _r1 <- true;
          }
        }
        if (! _r1) {
          _r2 <@ E.dec(challenger_sk, c);
          _r0 <- Some (_r2);
        }
      }
      return _r0;
    }
  }.

  module Step_2L_state_2 (E : E_c.Scheme) = {
    var challenger_pk : PKeySpace
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    var challenger_challenged : bool
    var ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a0__ : PKeySpace * SKeySpace;
      var __a2__ : MessageSpace;
      var __a3__ : MessageSpace;
      var __a4__ : CiphertextSpace;
      __a0__ <@ E.keygen();
      challenger_pk <- __a0__.`1;
      challenger_sk <- __a0__.`2;
      challenger_challenged <- false;
      __a2__ <$ dMessageSpace;
      __a3__ <$ dMessageSpace;
      __a4__ <@ E.enc(challenger_pk, __a3__);
      challenger_ctStar <- __a4__;
      challenger_challenged <- true;
      ctStar <- __a4__;
      return (challenger_pk, __a2__, __a4__);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : bool;
      var _r2 : MessageSpace;
      if (c = ctStar) {
        _r0 <- None;
      } else {
        _r1 <- false;
        if (challenger_challenged) {
          if (c = challenger_ctStar) {
            _r0 <- None;
            _r1 <- true;
          }
        }
        if (! _r1) {
          _r2 <@ E.dec(challenger_sk, c);
          _r0 <- Some (_r2);
        }
      }
      return _r0;
    }
  }.

  module Step_2L_state_3 (E : E_c.Scheme) = {
    var challenger_pk : PKeySpace
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    var challenger_challenged : bool
    var ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a0__ : PKeySpace * SKeySpace;
      var __a2__ : MessageSpace;
      var __a3__ : MessageSpace;
      var __a4__ : CiphertextSpace;
      __a0__ <@ E.keygen();
      challenger_pk <- __a0__.`1;
      challenger_sk <- __a0__.`2;
      challenger_challenged <- false;
      __a2__ <$ dMessageSpace;
      __a3__ <$ dMessageSpace;
      __a4__ <@ E.enc(challenger_pk, __a3__);
      challenger_ctStar <- __a4__;
      challenger_challenged <- true;
      ctStar <- challenger_ctStar;
      return (challenger_pk, __a2__, ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : bool;
      var _r2 : MessageSpace;
      if (c = ctStar) {
        _r0 <- None;
      } else {
        _r1 <- false;
        if (challenger_challenged) {
          if (c = challenger_ctStar) {
            _r0 <- None;
            _r1 <- true;
          }
        }
        if (! _r1) {
          _r2 <@ E.dec(challenger_sk, c);
          _r0 <- Some (_r2);
        }
      }
      return _r0;
    }
  }.

  module Step_2L_state_4 (E : E_c.Scheme) = {
    var challenger_pk : PKeySpace
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    var challenger_challenged : bool
    var ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a0__ : PKeySpace * SKeySpace;
      var __a3__ : MessageSpace;
      var __a2__ : MessageSpace;
      var __a4__ : CiphertextSpace;
      challenger_challenged <- false;
      __a0__ <@ E.keygen();
      __a3__ <$ dMessageSpace;
      __a2__ <$ dMessageSpace;
      challenger_challenged <- true;
      challenger_pk <- __a0__.`1;
      challenger_sk <- __a0__.`2;
      __a4__ <@ E.enc(challenger_pk, __a3__);
      challenger_ctStar <- __a4__;
      ctStar <- challenger_ctStar;
      return (challenger_pk, __a2__, ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : bool;
      var _r2 : MessageSpace;
      if (c = ctStar) {
        _r0 <- None;
      } else {
        _r1 <- false;
        if (challenger_challenged) {
          if (c = challenger_ctStar) {
            _r0 <- None;
            _r1 <- true;
          }
        }
        if (! _r1) {
          _r2 <@ E.dec(challenger_sk, c);
          _r0 <- Some (_r2);
        }
      }
      return _r0;
    }
  }.

  module Step_2L_state_5 (E : E_c.Scheme) = {
    var challenger_pk : PKeySpace
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    var challenger_challenged : bool
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a0__ : PKeySpace * SKeySpace;
      var __a3__ : MessageSpace;
      var __a2__ : MessageSpace;
      var __a4__ : CiphertextSpace;
      challenger_challenged <- false;
      __a0__ <@ E.keygen();
      __a3__ <$ dMessageSpace;
      __a2__ <$ dMessageSpace;
      challenger_challenged <- true;
      challenger_pk <- __a0__.`1;
      challenger_sk <- __a0__.`2;
      __a4__ <@ E.enc(challenger_pk, __a3__);
      challenger_ctStar <- __a4__;
      return (challenger_pk, __a2__, challenger_ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : bool;
      var _r2 : MessageSpace;
      if (c = challenger_ctStar) {
        _r0 <- None;
      } else {
        _r1 <- false;
        if (challenger_challenged) {
          if (c = challenger_ctStar) {
            _r0 <- None;
            _r1 <- true;
          }
        }
        if (! _r1) {
          _r2 <@ E.dec(challenger_sk, c);
          _r0 <- Some (_r2);
        }
      }
      return _r0;
    }
  }.

  module Step_2L_state_6 (E : E_c.Scheme) = {
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    var challenger_challenged : bool
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a0__ : PKeySpace * SKeySpace;
      var __a3__ : MessageSpace;
      var __a2__ : MessageSpace;
      var __a4__ : CiphertextSpace;
      challenger_challenged <- false;
      __a0__ <@ E.keygen();
      __a3__ <$ dMessageSpace;
      __a2__ <$ dMessageSpace;
      challenger_challenged <- true;
      challenger_sk <- __a0__.`2;
      __a4__ <@ E.enc(__a0__.`1, __a3__);
      challenger_ctStar <- __a4__;
      return (__a0__.`1, __a2__, challenger_ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : bool;
      var _r2 : MessageSpace;
      if (c = challenger_ctStar) {
        _r0 <- None;
      } else {
        _r1 <- false;
        if (challenger_challenged) {
          if (c = challenger_ctStar) {
            _r0 <- None;
            _r1 <- true;
          }
        }
        if (! _r1) {
          _r2 <@ E.dec(challenger_sk, c);
          _r0 <- Some (_r2);
        }
      }
      return _r0;
    }
  }.

  module Step_2L_state_7 (E : E_c.Scheme) = {
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    var challenger_challenged : bool
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a0__ : PKeySpace * SKeySpace;
      var __a3__ : MessageSpace;
      var __a2__ : MessageSpace;
      var __a4__ : CiphertextSpace;
      __a0__ <@ E.keygen();
      __a3__ <$ dMessageSpace;
      __a2__ <$ dMessageSpace;
      challenger_challenged <- true;
      challenger_sk <- __a0__.`2;
      __a4__ <@ E.enc(__a0__.`1, __a3__);
      challenger_ctStar <- __a4__;
      return (__a0__.`1, __a2__, challenger_ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : bool;
      var _r2 : MessageSpace;
      if (c = challenger_ctStar) {
        _r0 <- None;
      } else {
        _r1 <- false;
        if (challenger_challenged) {
          if (c = challenger_ctStar) {
            _r0 <- None;
            _r1 <- true;
          }
        }
        if (! _r1) {
          _r2 <@ E.dec(challenger_sk, c);
          _r0 <- Some (_r2);
        }
      }
      return _r0;
    }
  }.

  module Step_2L_state_8 (E : E_c.Scheme) = {
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    var challenger_challenged : bool
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a0__ : PKeySpace * SKeySpace;
      var __a3__ : MessageSpace;
      var __a2__ : MessageSpace;
      __a0__ <@ E.keygen();
      __a3__ <$ dMessageSpace;
      __a2__ <$ dMessageSpace;
      challenger_challenged <- true;
      challenger_sk <- __a0__.`2;
      challenger_ctStar <@ E.enc(__a0__.`1, __a3__);
      return (__a0__.`1, __a2__, challenger_ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : bool;
      var _r2 : MessageSpace;
      if (c = challenger_ctStar) {
        _r0 <- None;
      } else {
        _r1 <- false;
        if (challenger_challenged) {
          if (c = challenger_ctStar) {
            _r0 <- None;
            _r1 <- true;
          }
        }
        if (! _r1) {
          _r2 <@ E.dec(challenger_sk, c);
          _r0 <- Some (_r2);
        }
      }
      return _r0;
    }
  }.

  module Step_2L_state_9 (E : E_c.Scheme) = {
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    var challenger_challenged : bool
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a0__ : PKeySpace * SKeySpace;
      var __a3__ : MessageSpace;
      var __a2__ : MessageSpace;
      __a0__ <@ E.keygen();
      __a3__ <$ dMessageSpace;
      __a2__ <$ dMessageSpace;
      challenger_challenged <- true;
      challenger_sk <- __a0__.`2;
      challenger_ctStar <@ E.enc(__a0__.`1, __a3__);
      return (__a0__.`1, __a2__, challenger_ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : bool;
      var _r2 : MessageSpace;
      if (c = challenger_ctStar) {
        _r0 <- None;
      } else {
        _r1 <- false;
        if (challenger_challenged) {
        }
        if (! _r1) {
          _r2 <@ E.dec(challenger_sk, c);
          _r0 <- Some (_r2);
        }
      }
      return _r0;
    }
  }.

  module Step_2L_state_10 (E : E_c.Scheme) = {
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    var challenger_challenged : bool
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a0__ : PKeySpace * SKeySpace;
      var __cse___a0___0__ : PKeySpace;
      var __a3__ : MessageSpace;
      var __a2__ : MessageSpace;
      __a0__ <@ E.keygen();
      __cse___a0___0__ <- __a0__.`1;
      __a3__ <$ dMessageSpace;
      __a2__ <$ dMessageSpace;
      challenger_challenged <- true;
      challenger_sk <- __a0__.`2;
      challenger_ctStar <@ E.enc(__cse___a0___0__, __a3__);
      return (__cse___a0___0__, __a2__, challenger_ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : bool;
      var _r2 : MessageSpace;
      if (c = challenger_ctStar) {
        _r0 <- None;
      } else {
        _r1 <- false;
        if (challenger_challenged) {
        }
        if (! _r1) {
          _r2 <@ E.dec(challenger_sk, c);
          _r0 <- Some (_r2);
        }
      }
      return _r0;
    }
  }.

  module Step_2L_state_11 (E : E_c.Scheme) = {
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    var challenger_challenged : bool
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a3__ : MessageSpace;
      var __a0__ : PKeySpace * SKeySpace;
      var __a2__ : MessageSpace;
      var __cse___a0___0__ : PKeySpace;
      challenger_challenged <- true;
      __a3__ <$ dMessageSpace;
      __a0__ <@ E.keygen();
      __a2__ <$ dMessageSpace;
      __cse___a0___0__ <- __a0__.`1;
      challenger_sk <- __a0__.`2;
      challenger_ctStar <@ E.enc(__cse___a0___0__, __a3__);
      return (__cse___a0___0__, __a2__, challenger_ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : bool;
      var _r2 : MessageSpace;
      if (c = challenger_ctStar) {
        _r0 <- None;
      } else {
        _r1 <- false;
        if (challenger_challenged) {
        }
        if (! _r1) {
          _r2 <@ E.dec(challenger_sk, c);
          _r0 <- Some (_r2);
        }
      }
      return _r0;
    }
  }.

  module Step_2L_state_12 (E : E_c.Scheme) = {
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a3__ : MessageSpace;
      var __a0__ : PKeySpace * SKeySpace;
      var __a2__ : MessageSpace;
      var __cse___a0___0__ : PKeySpace;
      __a3__ <$ dMessageSpace;
      __a0__ <@ E.keygen();
      __a2__ <$ dMessageSpace;
      __cse___a0___0__ <- __a0__.`1;
      challenger_sk <- __a0__.`2;
      challenger_ctStar <@ E.enc(__cse___a0___0__, __a3__);
      return (__cse___a0___0__, __a2__, challenger_ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : bool;
      var _r2 : MessageSpace;
      if (c = challenger_ctStar) {
        _r0 <- None;
      } else {
        _r1 <- false;
        if (true) {
        }
        if (! _r1) {
          _r2 <@ E.dec(challenger_sk, c);
          _r0 <- Some (_r2);
        }
      }
      return _r0;
    }
  }.

  module Step_2L_state_13 (E : E_c.Scheme) = {
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a3__ : MessageSpace;
      var __a0__ : PKeySpace * SKeySpace;
      var __a2__ : MessageSpace;
      var __a4__ : PKeySpace;
      __a3__ <$ dMessageSpace;
      __a0__ <@ E.keygen();
      __a2__ <$ dMessageSpace;
      __a4__ <- __a0__.`1;
      challenger_sk <- __a0__.`2;
      challenger_ctStar <@ E.enc(__a4__, __a3__);
      return (__a4__, __a2__, challenger_ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : bool;
      var _r2 : MessageSpace;
      if (c = challenger_ctStar) {
        _r0 <- None;
      } else {
        _r1 <- false;
        if (true) {
        }
        if (! _r1) {
          _r2 <@ E.dec(challenger_sk, c);
          _r0 <- Some (_r2);
        }
      }
      return _r0;
    }
  }.

  module Step_2L_state_14 (E : E_c.Scheme) = {
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a3__ : MessageSpace;
      var __a0__ : PKeySpace * SKeySpace;
      var __a2__ : MessageSpace;
      var __a4__ : PKeySpace;
      __a3__ <$ dMessageSpace;
      __a0__ <@ E.keygen();
      __a2__ <$ dMessageSpace;
      __a4__ <- __a0__.`1;
      challenger_sk <- __a0__.`2;
      challenger_ctStar <@ E.enc(__a4__, __a3__);
      return (__a4__, __a2__, challenger_ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = challenger_ctStar) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(challenger_sk, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_2L_state_15 (E : E_c.Scheme) = {
    var challenger_sk : SKeySpace
    var challenger_ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var v1 : MessageSpace;
      var v2 : PKeySpace * SKeySpace;
      var v3 : MessageSpace;
      var v4 : PKeySpace;
      v1 <$ dMessageSpace;
      v2 <@ E.keygen();
      v3 <$ dMessageSpace;
      v4 <- v2.`1;
      challenger_sk <- v2.`2;
      challenger_ctStar <@ E.enc(v4, v1);
      return (v4, v3, challenger_ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = challenger_ctStar) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(challenger_sk, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_2L_state_16 (E : E_c.Scheme) = {
    var field1 : CiphertextSpace
    var field2 : SKeySpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var v1 : MessageSpace;
      var v2 : PKeySpace * SKeySpace;
      var v3 : MessageSpace;
      var v4 : PKeySpace;
      v1 <$ dMessageSpace;
      v2 <@ E.keygen();
      v3 <$ dMessageSpace;
      v4 <- v2.`1;
      field2 <- v2.`2;
      field1 <@ E.enc(v4, v1);
      return (v4, v3, field1);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = field1) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(field2, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_2L_state_17 (E : E_c.Scheme) = {
    var field1 : CiphertextSpace
    var field2 : SKeySpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var v1 : MessageSpace;
      var v2 : PKeySpace * SKeySpace;
      var v3 : MessageSpace;
      var v4 : PKeySpace;
      v1 <$ dMessageSpace;
      v2 <@ E.keygen();
      v3 <$ dMessageSpace;
      v4 <- v2.`1;
      field1 <@ E.enc(v4, v1);
      field2 <- v2.`2;
      return (v4, v3, field1);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = field1) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(field2, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_2L_state_18 (E : E_c.Scheme) = {
    var field1 : CiphertextSpace
    var field2 : SKeySpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var v2 : PKeySpace * SKeySpace;
      var v4 : PKeySpace;
      var v3 : MessageSpace;
      var v1 : MessageSpace;
      v2 <@ E.keygen();
      v4 <- v2.`1;
      v3 <$ dMessageSpace;
      v1 <$ dMessageSpace;
      field1 <@ E.enc(v4, v1);
      field2 <- v2.`2;
      return (v4, v3, field1);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = field1) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(field2, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_2L_state_19 (E : E_c.Scheme) = {
    var field1 : CiphertextSpace
    var field2 : SKeySpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var v1 : PKeySpace * SKeySpace;
      var v2 : PKeySpace;
      var v3 : MessageSpace;
      var v4 : MessageSpace;
      v1 <@ E.keygen();
      v2 <- v1.`1;
      v3 <$ dMessageSpace;
      v4 <$ dMessageSpace;
      field1 <@ E.enc(v2, v4);
      field2 <- v1.`2;
      return (v2, v3, field1);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = field1) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(field2, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_2R_state_0 (E : E_c.Scheme) = {
    var sk : SKeySpace
    var ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var _tup : PKeySpace * SKeySpace;
      var pk : PKeySpace;
      var v_L_Encaps_k3 : MessageSpace;
      var v_L_Encaps_ct3 : CiphertextSpace;
      var _tup_0 : MessageSpace * CiphertextSpace;
      var ssReal : MessageSpace;
      var ss : MessageSpace;
      _tup <@ E.keygen();
      pk <- _tup.`1;
      sk <- _tup.`2;
      v_L_Encaps_k3 <$ dMessageSpace;
      v_L_Encaps_ct3 <@ E.enc(pk, v_L_Encaps_k3);
      _tup_0 <- (v_L_Encaps_k3, v_L_Encaps_ct3);
      ssReal <- _tup_0.`1;
      ctStar <- _tup_0.`2;
      ss <$ dMessageSpace;
      return (pk, ss, ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = ctStar) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(sk, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_2R_state_1 (E : E_c.Scheme) = {
    var sk : SKeySpace
    var ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a0__ : PKeySpace * SKeySpace;
      var __a1__ : PKeySpace;
      var __a2__ : MessageSpace;
      var __a3__ : CiphertextSpace;
      var __a4__ : MessageSpace * CiphertextSpace;
      var __a5__ : MessageSpace;
      var __a6__ : MessageSpace;
      __a0__ <@ E.keygen();
      __a1__ <- __a0__.`1;
      sk <- __a0__.`2;
      __a2__ <$ dMessageSpace;
      __a3__ <@ E.enc(__a1__, __a2__);
      __a4__ <- (__a2__, __a3__);
      __a5__ <- __a4__.`1;
      ctStar <- __a4__.`2;
      __a6__ <$ dMessageSpace;
      return (__a1__, __a6__, ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = ctStar) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(sk, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_2R_state_2 (E : E_c.Scheme) = {
    var sk : SKeySpace
    var ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a0__ : PKeySpace * SKeySpace;
      var __a1__ : PKeySpace;
      var __a2__ : MessageSpace;
      var _r0 : CiphertextSpace;
      var __a4__ : MessageSpace * CiphertextSpace;
      var __a5__ : MessageSpace;
      var __a6__ : MessageSpace;
      __a0__ <@ E.keygen();
      __a1__ <- __a0__.`1;
      sk <- __a0__.`2;
      __a2__ <$ dMessageSpace;
      _r0 <@ E.enc(__a1__, __a2__);
      __a4__ <- (__a2__, _r0);
      __a5__ <- __a4__.`1;
      ctStar <- __a4__.`2;
      __a6__ <$ dMessageSpace;
      return (__a1__, __a6__, ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = ctStar) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(sk, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_2R_state_3 (E : E_c.Scheme) = {
    var sk : SKeySpace
    var ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a2__ : MessageSpace;
      var __a0__ : PKeySpace * SKeySpace;
      var __a6__ : MessageSpace;
      var __a1__ : PKeySpace;
      var _r0 : CiphertextSpace;
      var __a4__ : MessageSpace * CiphertextSpace;
      var __a5__ : MessageSpace;
      __a2__ <$ dMessageSpace;
      __a0__ <@ E.keygen();
      __a6__ <$ dMessageSpace;
      __a1__ <- __a0__.`1;
      sk <- __a0__.`2;
      _r0 <@ E.enc(__a1__, __a2__);
      __a4__ <- (__a2__, _r0);
      __a5__ <- __a4__.`1;
      ctStar <- __a4__.`2;
      return (__a1__, __a6__, ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = ctStar) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(sk, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_2R_state_4 (E : E_c.Scheme) = {
    var sk : SKeySpace
    var ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a2__ : MessageSpace;
      var __a0__ : PKeySpace * SKeySpace;
      var __a6__ : MessageSpace;
      var __a1__ : PKeySpace;
      var __a5__ : MessageSpace;
      __a2__ <$ dMessageSpace;
      __a0__ <@ E.keygen();
      __a6__ <$ dMessageSpace;
      __a1__ <- __a0__.`1;
      sk <- __a0__.`2;
      __a5__ <- __a2__;
      ctStar <@ E.enc(__a1__, __a2__);
      return (__a1__, __a6__, ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = ctStar) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(sk, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_2R_state_5 (E : E_c.Scheme) = {
    var sk : SKeySpace
    var ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var __a2__ : MessageSpace;
      var __a0__ : PKeySpace * SKeySpace;
      var __a6__ : MessageSpace;
      var __a1__ : PKeySpace;
      __a2__ <$ dMessageSpace;
      __a0__ <@ E.keygen();
      __a6__ <$ dMessageSpace;
      __a1__ <- __a0__.`1;
      sk <- __a0__.`2;
      ctStar <@ E.enc(__a1__, __a2__);
      return (__a1__, __a6__, ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = ctStar) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(sk, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_2R_state_6 (E : E_c.Scheme) = {
    var sk : SKeySpace
    var ctStar : CiphertextSpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var v1 : MessageSpace;
      var v2 : PKeySpace * SKeySpace;
      var v3 : MessageSpace;
      var v4 : PKeySpace;
      v1 <$ dMessageSpace;
      v2 <@ E.keygen();
      v3 <$ dMessageSpace;
      v4 <- v2.`1;
      sk <- v2.`2;
      ctStar <@ E.enc(v4, v1);
      return (v4, v3, ctStar);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = ctStar) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(sk, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_2R_state_7 (E : E_c.Scheme) = {
    var field1 : CiphertextSpace
    var field2 : SKeySpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var v1 : MessageSpace;
      var v2 : PKeySpace * SKeySpace;
      var v3 : MessageSpace;
      var v4 : PKeySpace;
      v1 <$ dMessageSpace;
      v2 <@ E.keygen();
      v3 <$ dMessageSpace;
      v4 <- v2.`1;
      field2 <- v2.`2;
      field1 <@ E.enc(v4, v1);
      return (v4, v3, field1);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = field1) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(field2, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_2R_state_8 (E : E_c.Scheme) = {
    var field1 : CiphertextSpace
    var field2 : SKeySpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var v1 : MessageSpace;
      var v2 : PKeySpace * SKeySpace;
      var v3 : MessageSpace;
      var v4 : PKeySpace;
      v1 <$ dMessageSpace;
      v2 <@ E.keygen();
      v3 <$ dMessageSpace;
      v4 <- v2.`1;
      field1 <@ E.enc(v4, v1);
      field2 <- v2.`2;
      return (v4, v3, field1);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = field1) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(field2, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_2R_state_9 (E : E_c.Scheme) = {
    var field1 : CiphertextSpace
    var field2 : SKeySpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var v2 : PKeySpace * SKeySpace;
      var v4 : PKeySpace;
      var v3 : MessageSpace;
      var v1 : MessageSpace;
      v2 <@ E.keygen();
      v4 <- v2.`1;
      v3 <$ dMessageSpace;
      v1 <$ dMessageSpace;
      field1 <@ E.enc(v4, v1);
      field2 <- v2.`2;
      return (v4, v3, field1);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = field1) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(field2, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  module Step_2R_state_10 (E : E_c.Scheme) = {
    var field1 : CiphertextSpace
    var field2 : SKeySpace
    proc initialize() : PKeySpace * MessageSpace * CiphertextSpace = {
      var v1 : PKeySpace * SKeySpace;
      var v2 : PKeySpace;
      var v3 : MessageSpace;
      var v4 : MessageSpace;
      v1 <@ E.keygen();
      v2 <- v1.`1;
      v3 <$ dMessageSpace;
      v4 <$ dMessageSpace;
      field1 <@ E.enc(v2, v4);
      field2 <- v1.`2;
      return (v2, v3, field1);
    }
    proc decaps(c : CiphertextSpace) : MessageSpace option = {
      var _r0 : MessageSpace option;
      var _r1 : MessageSpace;
      if (c = field1) {
        _r0 <- None;
      } else {
        _r1 <@ E.dec(field2, c);
        _r0 <- Some (_r1);
      }
      return _r0;
    }
  }.

  declare module E <: E_c.Scheme {-B1, -E_c.PKE_INDCCA_Left, -E_c.PKE_INDCCA_Right, -L_c.KEM_INDCCA_MultiChal_Random, -L_c.KEM_INDCCA_MultiChal_Real}.

  (* ===== Deterministic-method specs ===== *)

  declare axiom E_dec_det (g : (glob E)) (a0 : SKeySpace) (a1 : CiphertextSpace) : phoare[ E.dec : (glob E) = g /\ sk = a0 /\ ct = a1 ==> (glob E) = g /\ res = E_c.ev_dec a0 a1 ] = 1%r.

  (* ===== Per-hop equivalence lemmas ===== *)

  lemma hop_0_initialize :
    equiv [ L_c.KEM_INDCCA_MultiChal_Real(LCK(E)).initialize ~ B1(E, LCK(E), E_c.PKE_INDCCA_Left(E)).initialize :
            ={glob E} ==> ={res} /\ ={glob E} /\ L_c.KEM_INDCCA_MultiChal_Real.ctStar{1} = B1.ctStar{2} /\ B1.ctStar{2} = E_c.PKE_INDCCA_Left.ctStar{2} /\ L_c.KEM_INDCCA_MultiChal_Real.sk{1} = E_c.PKE_INDCCA_Left.sk{2} ].
  proof.
    (* resolution: admit-guided *)
    (* multi-oracle hop 0, oracle 'initialize': init equiv
       with a dead F.evaluate on one side (PRF-random hop). The shared
       backbone is keygen; encaps; <fresh sample>, but one wrapper still
       runs an F.evaluate whose result the sample overwrites. Drop it with a
       one-sided phoare, then peel the common backbone:
         proc. inline *.
         (* drop the dead F.evaluate on the side that has it: *)
         seq <k> <k+1> : (={glob K, glob F} /\ <live coupling>).
         + exists* (glob F){i}, <Fseedi>, <Finputi>; elim* => gf a0 a1;
           call{i} (F_evaluate_det gf a0 a1); auto.
         wp; rnd; wp; call (_: true); wp; call (_: true); skip => /#. *)
    admit.
    qed.

  lemma hop_0_decaps :
    equiv [ L_c.KEM_INDCCA_MultiChal_Real(LCK(E)).decaps ~ B1(E, LCK(E), E_c.PKE_INDCCA_Left(E)).decaps :
            ={c} /\ ={glob E} /\ L_c.KEM_INDCCA_MultiChal_Real.ctStar{1} = B1.ctStar{2} /\ B1.ctStar{2} = E_c.PKE_INDCCA_Left.ctStar{2} /\ L_c.KEM_INDCCA_MultiChal_Real.sk{1} = E_c.PKE_INDCCA_Left.sk{2} ==> ={res} /\ ={glob E} /\ L_c.KEM_INDCCA_MultiChal_Real.ctStar{1} = B1.ctStar{2} /\ B1.ctStar{2} = E_c.PKE_INDCCA_Left.ctStar{2} /\ L_c.KEM_INDCCA_MultiChal_Real.sk{1} = E_c.PKE_INDCCA_Left.sk{2} ].
  proof.
    (* resolution: admit-guided *)
    (* multi-oracle hop 0, oracle 'decaps': post-init
       body transformed along the chain; not closed by proc; sim / reorder.
       VALIDATED fill template (det-axiom finisher; KEMPRF hop_0_challenge
       compiles EC EXIT 0). Fill <...> with this hop's EC inline names:
         proc. inline *. sp. wp.
         seq 1 1 : (={glob K, glob F} /\ <encapsResL>{1} = <encapsResR>{2}
                    /\ <live-state coupling>).
         + sim.                          (* relate the abstract encaps calls *)
         sp. wp.
         exists* (glob F){1}, <FseedL>{1}, <FinputL>{1}; elim* => gf1 a0 a1.
         call{1} (F_evaluate_det gf1 a0 a1).
         exists* (glob F){2}, <FseedR>{2}, <FinputR>{2}; elim* => gf2 b0 b1.
         call{2} (F_evaluate_det gf2 b0 b1).
         skip => /#.
       A reusable name-independent helper for the F.evaluate step (derive
       once per primitive from F_evaluate_det; lets 'wp. call F_evaluate_equiv'
       replace the two exists*/call blocks):
         lemma F_evaluate_equiv : equiv[ F.evaluate ~ F.evaluate :
           ={glob F, seed, input} ==> ={res, glob F} ].
         proof. proc*; exists* (glob F){1}, seed{1}, input{1}; elim* => g s i;
           call{1} (F_evaluate_det g s i); call{2} (F_evaluate_det g s i);
           skip => /#. qed.
       Per-shape variants (the body transform differs by hop):
       - distribution swap (e.g. dsharedsecret <-> dbs_lambda under the
         requires-equality alias): couple the two uniform samples with rnd,
         discharging the distribution equality from is_funiform + is_full;
       - sample/encaps order swap: swap{i} to align, then the det finisher;
       - dead F.evaluate: call{i} (F_evaluate_det ...) to drop it, then sim. *)
    admit.
    qed.

  lemma hop_2_initialize :
    equiv [ B1(E, LCK(E), E_c.PKE_INDCCA_Right(E)).initialize ~ L_c.KEM_INDCCA_MultiChal_Random(LCK(E)).initialize :
            ={glob E} ==> ={res} /\ ={glob E} /\ L_c.KEM_INDCCA_MultiChal_Random.ctStar{2} = B1.ctStar{1} /\ B1.ctStar{1} = E_c.PKE_INDCCA_Right.ctStar{1} /\ L_c.KEM_INDCCA_MultiChal_Random.sk{2} = E_c.PKE_INDCCA_Right.sk{1} ].
  proof.
    (* resolution: admit-guided *)
    (* multi-oracle hop 2, oracle 'initialize': init equiv
       with a dead F.evaluate on one side (PRF-random hop). The shared
       backbone is keygen; encaps; <fresh sample>, but one wrapper still
       runs an F.evaluate whose result the sample overwrites. Drop it with a
       one-sided phoare, then peel the common backbone:
         proc. inline *.
         (* drop the dead F.evaluate on the side that has it: *)
         seq <k> <k+1> : (={glob K, glob F} /\ <live coupling>).
         + exists* (glob F){i}, <Fseedi>, <Finputi>; elim* => gf a0 a1;
           call{i} (F_evaluate_det gf a0 a1); auto.
         wp; rnd; wp; call (_: true); wp; call (_: true); skip => /#. *)
    admit.
    qed.

  lemma hop_2_decaps :
    equiv [ B1(E, LCK(E), E_c.PKE_INDCCA_Right(E)).decaps ~ L_c.KEM_INDCCA_MultiChal_Random(LCK(E)).decaps :
            ={c} /\ ={glob E} /\ L_c.KEM_INDCCA_MultiChal_Random.ctStar{2} = B1.ctStar{1} /\ B1.ctStar{1} = E_c.PKE_INDCCA_Right.ctStar{1} /\ L_c.KEM_INDCCA_MultiChal_Random.sk{2} = E_c.PKE_INDCCA_Right.sk{1} ==> ={res} /\ ={glob E} /\ L_c.KEM_INDCCA_MultiChal_Random.ctStar{2} = B1.ctStar{1} /\ B1.ctStar{1} = E_c.PKE_INDCCA_Right.ctStar{1} /\ L_c.KEM_INDCCA_MultiChal_Random.sk{2} = E_c.PKE_INDCCA_Right.sk{1} ].
  proof.
    (* resolution: admit-guided *)
    (* multi-oracle hop 2, oracle 'decaps': post-init
       body transformed along the chain; not closed by proc; sim / reorder.
       VALIDATED fill template (det-axiom finisher; KEMPRF hop_0_challenge
       compiles EC EXIT 0). Fill <...> with this hop's EC inline names:
         proc. inline *. sp. wp.
         seq 1 1 : (={glob K, glob F} /\ <encapsResL>{1} = <encapsResR>{2}
                    /\ <live-state coupling>).
         + sim.                          (* relate the abstract encaps calls *)
         sp. wp.
         exists* (glob F){1}, <FseedL>{1}, <FinputL>{1}; elim* => gf1 a0 a1.
         call{1} (F_evaluate_det gf1 a0 a1).
         exists* (glob F){2}, <FseedR>{2}, <FinputR>{2}; elim* => gf2 b0 b1.
         call{2} (F_evaluate_det gf2 b0 b1).
         skip => /#.
       A reusable name-independent helper for the F.evaluate step (derive
       once per primitive from F_evaluate_det; lets 'wp. call F_evaluate_equiv'
       replace the two exists*/call blocks):
         lemma F_evaluate_equiv : equiv[ F.evaluate ~ F.evaluate :
           ={glob F, seed, input} ==> ={res, glob F} ].
         proof. proc*; exists* (glob F){1}, seed{1}, input{1}; elim* => g s i;
           call{1} (F_evaluate_det g s i); call{2} (F_evaluate_det g s i);
           skip => /#. qed.
       Per-shape variants (the body transform differs by hop):
       - distribution swap (e.g. dsharedsecret <-> dbs_lambda under the
         requires-equality alias): couple the two uniform samples with rnd,
         discharging the distribution equality from is_funiform + is_full;
       - sample/encaps order swap: swap{i} to align, then the det finisher;
       - dead F.evaluate: call{i} (F_evaluate_det ...) to drop it, then sim. *)
    admit.
    qed.

  (* ===== Per-hop probability lemmas ===== *)

  (* Hop 0: interchangeability. The two adjacent games are equivalent (no advantage). *)

  lemma hop_0_pr (A <: L_c.KEM_INDCCA_MultiChal_Adv {-E, -B1, -E_c.PKE_INDCCA_Left, -E_c.PKE_INDCCA_Right, -L_c.KEM_INDCCA_MultiChal_Random, -L_c.KEM_INDCCA_MultiChal_Real}) &m :
    Pr[Game_step_0(E, A).main() @ &m : res] = Pr[Game_step_1(E, A).main() @ &m : res].
  proof.
    byequiv (_: ={glob A, glob E} ==> ={res}) => //.
    proc.
    call (_: ={glob E} /\ L_c.KEM_INDCCA_MultiChal_Real.ctStar{1} = B1.ctStar{2} /\ B1.ctStar{2} = E_c.PKE_INDCCA_Left.ctStar{2} /\ L_c.KEM_INDCCA_MultiChal_Real.sk{1} = E_c.PKE_INDCCA_Left.sk{2}).
    + conseq hop_0_decaps.
    call hop_0_initialize.
    auto.
    qed.

  (* Hop 1: assumption hop. Bounded by the PKE_INDCCA_advantage axiom applied to B1_Adv. *)

  lemma hop_1_pr (A <: L_c.KEM_INDCCA_MultiChal_Adv {-E, -B1, -E_c.PKE_INDCCA_Left, -E_c.PKE_INDCCA_Right, -L_c.KEM_INDCCA_MultiChal_Random, -L_c.KEM_INDCCA_MultiChal_Real}) &m :
    `| Pr[Game_step_1(E, A).main() @ &m : res] - Pr[Game_step_2(E, A).main() @ &m : res] | <= E_c.eps_PKE_INDCCA.
  proof.
    have hL : Pr[Game_step_1(E, A).main() @ &m : res]
            = Pr[E_c.Game_PKE_INDCCA_Left(E, B1_Adv(E, A)).main() @ &m : res]
      by byequiv (_: ={glob A, glob E} ==> ={res}) => //; proc; inline *; wp; call (_: ={glob B1, glob E, glob E_c.PKE_INDCCA_Left}); [ proc; sim | wp; call (_: true); wp; rnd; wp; rnd; wp; call (_: true); skip => /# ].
    have hR : Pr[Game_step_2(E, A).main() @ &m : res]
            = Pr[E_c.Game_PKE_INDCCA_Right(E, B1_Adv(E, A)).main() @ &m : res]
      by byequiv (_: ={glob A, glob E} ==> ={res}) => //; proc; inline *; wp; call (_: ={glob B1, glob E, glob E_c.PKE_INDCCA_Right}); [ proc; sim | wp; call (_: true); wp; rnd; wp; rnd; wp; call (_: true); skip => /# ].
    rewrite hL hR.
    apply (E_c.PKE_INDCCA_advantage E (B1_Adv(E, A)) &m).
    qed.

  (* Hop 2: interchangeability. The two adjacent games are equivalent (no advantage). *)

  lemma hop_2_pr (A <: L_c.KEM_INDCCA_MultiChal_Adv {-E, -B1, -E_c.PKE_INDCCA_Left, -E_c.PKE_INDCCA_Right, -L_c.KEM_INDCCA_MultiChal_Random, -L_c.KEM_INDCCA_MultiChal_Real}) &m :
    Pr[Game_step_2(E, A).main() @ &m : res] = Pr[Game_step_3(E, A).main() @ &m : res].
  proof.
    byequiv (_: ={glob A, glob E} ==> ={res}) => //.
    proc.
    call (_: ={glob E} /\ L_c.KEM_INDCCA_MultiChal_Random.ctStar{2} = B1.ctStar{1} /\ B1.ctStar{1} = E_c.PKE_INDCCA_Right.ctStar{1} /\ L_c.KEM_INDCCA_MultiChal_Random.sk{2} = E_c.PKE_INDCCA_Right.sk{1}).
    + conseq hop_2_decaps.
    call hop_2_initialize.
    auto.
    qed.

  (* ===== Main theorem ===== *)

  lemma main_theorem (A <: L_c.KEM_INDCCA_MultiChal_Adv {-E, -B1, -E_c.PKE_INDCCA_Left, -E_c.PKE_INDCCA_Right, -L_c.KEM_INDCCA_MultiChal_Random, -L_c.KEM_INDCCA_MultiChal_Real}) &m :
    `| Pr[Game_step_0(E, A).main() @ &m : res] - Pr[Game_step_3(E, A).main() @ &m : res] | <= E_c.eps_PKE_INDCCA.
  proof.
    have h0 := hop_0_pr A &m.
    have h1 := hop_1_pr A &m.
    have h2 := hop_2_pr A &m.
    smt(E_c.eps_PKE_INDCCA_pos).
    qed.
end section Main.
