(* Auto-generated by ProofFrog. Do not edit. *)
require import AllCore Distr DProd DMap.

(* ===== Abstract set declarations ===== *)

type ProofMessageSpace.

type ProofCiphertextSpace.

type ProofKeySpace.

(* ===== Concrete primitive types ===== *)

op dProofCiphertextSpace : ProofCiphertextSpace distr.

axiom dProofCiphertextSpace_ll : is_lossless dProofCiphertextSpace.

axiom dProofCiphertextSpace_fu : is_funiform dProofCiphertextSpace.

axiom dProofCiphertextSpace_full : is_full dProofCiphertextSpace.

(* ===== Abstract theory: primitive + security games + assumption ===== *)

abstract theory SymEnc_Theory.
  type key.

  type message.

  type ciphertext.

  op dciphertext : ciphertext distr.

  axiom dciphertext_ll : is_lossless dciphertext.

  axiom dciphertext_fu : is_funiform dciphertext.

  axiom dciphertext_full : is_full dciphertext.

  module type Scheme = {
    proc keygen() : key
    proc enc(k : key, m : message) : ciphertext
    proc dec(k : key, c : ciphertext) : message option
  }.

  op ev_dec : key -> ciphertext -> message option.

  module type INDOT_Oracle = {
    proc eavesdrop(mL : message, mR : message) : ciphertext
  }.

  module INDOT_Left (E : Scheme) : INDOT_Oracle = {
    proc eavesdrop(mL : message, mR : message) : ciphertext = {
      var k : key;
      var c : ciphertext;
      k <@ E.keygen();
      c <@ E.enc(k, mL);
      return c;
    }
  }.

  module INDOT_Right (E : Scheme) : INDOT_Oracle = {
    proc eavesdrop(mL : message, mR : message) : ciphertext = {
      var k : key;
      var c : ciphertext;
      k <@ E.keygen();
      c <@ E.enc(k, mR);
      return c;
    }
  }.

  module type INDOT_Adv (O : INDOT_Oracle) = {
    proc distinguish() : bool
  }.

  module type INDOT__Oracle = {
    proc ctxt(m : message) : ciphertext
  }.

  module INDOT__Real (E : Scheme) : INDOT__Oracle = {
    proc ctxt(m : message) : ciphertext = {
      var k : key;
      var c : ciphertext;
      k <@ E.keygen();
      c <@ E.enc(k, m);
      return c;
    }
  }.

  module INDOT__Random (E : Scheme) : INDOT__Oracle = {
    proc ctxt(m : message) : ciphertext = {
      var c : ciphertext;
      c <$ dciphertext;
      return c;
    }
  }.

  module type INDOT__Adv (O : INDOT__Oracle) = {
    proc distinguish() : bool
  }.

  module Game_INDOT__Real (Em : Scheme, A : INDOT__Adv) = {
    proc main() : bool = {
      var b : bool;
      b <@ A(INDOT__Real(Em)).distinguish();
      return b;
    }
  }.

  module Game_INDOT__Random (Em : Scheme, A : INDOT__Adv) = {
    proc main() : bool = {
      var b : bool;
      b <@ A(INDOT__Random(Em)).distinguish();
      return b;
    }
  }.

  op eps_INDOT_ : real.

  axiom eps_INDOT__pos : 0%r <= eps_INDOT_.

  axiom INDOT__advantage (Em <: Scheme) (A <: INDOT__Adv) &m :
    `| Pr[Game_INDOT__Real(Em, A).main() @ &m : res] - Pr[Game_INDOT__Random(Em, A).main() @ &m : res] | <= eps_INDOT_.
end SymEnc_Theory.

(* ===== Theory instantiation ===== *)

clone SymEnc_Theory as ProofE_c with
  type message <- ProofMessageSpace,
  type ciphertext <- ProofCiphertextSpace,
  type key <- ProofKeySpace,
  op dciphertext <- dProofCiphertextSpace.

(* ===== Per-clone distribution axioms ===== *)

lemma ProofE_dProofCiphertextSpace_funi :
  is_funiform dProofCiphertextSpace.
proof.
  exact dProofCiphertextSpace_fu.
qed.

lemma ProofE_dProofCiphertextSpace_ll :
  is_lossless dProofCiphertextSpace.
proof.
  exact dProofCiphertextSpace_ll.
qed.

section Main.
  declare module ProofE <: ProofE_c.Scheme.

  (* ===== Deterministic-method specs ===== *)

  declare axiom ProofE_dec_det (g : (glob ProofE)) (a0 : ProofKeySpace) (a1 : ProofCiphertextSpace) : phoare[ ProofE.dec : (glob ProofE) = g /\ k = a0 /\ c = a1 ==> (glob ProofE) = g /\ res = ProofE_c.ev_dec a0 a1 ] = 1%r.

  (* ===== Reductions ===== *)

  module R1 (Se : ProofE_c.Scheme, Challenger : ProofE_c.INDOT__Oracle) = {
    proc eavesdrop(mL : ProofMessageSpace, mR : ProofMessageSpace) : ProofCiphertextSpace = {
      var _r0 : ProofCiphertextSpace;
      _r0 <@ Challenger.ctxt(mL);
      return _r0;
    }
  }.

  module R2 (Se2 : ProofE_c.Scheme, Challenger : ProofE_c.INDOT__Oracle) = {
    proc eavesdrop(mL : ProofMessageSpace, mR : ProofMessageSpace) : ProofCiphertextSpace = {
      var _r0 : ProofCiphertextSpace;
      _r0 <@ Challenger.ctxt(mR);
      return _r0;
    }
  }.

  (* ===== Reductions lifted to assumption-adversaries ===== *)

  module R1_Adv (ProofE : ProofE_c.Scheme, A : ProofE_c.INDOT_Adv, C : ProofE_c.INDOT__Oracle) = {
    proc distinguish() : bool = {
      var b : bool;
      b <@ A(R1(ProofE, C)).distinguish();
      return b;
    }
  }.

  module R2_Adv (ProofE : ProofE_c.Scheme, A : ProofE_c.INDOT_Adv, C : ProofE_c.INDOT__Oracle) = {
    proc distinguish() : bool = {
      var b : bool;
      b <@ A(R2(ProofE, C)).distinguish();
      return b;
    }
  }.

  (* ===== Game-step wrappers ===== *)

  (* Game_step_0: INDOT.Left *)

  module Game_step_0 (ProofE : ProofE_c.Scheme, A : ProofE_c.INDOT_Adv) = {
    proc main() : bool = {
      var b : bool;
      b <@ A(ProofE_c.INDOT_Left(ProofE)).distinguish();
      return b;
    }
  }.

  (* Game_step_1: INDOT$.Real composed with reduction R1 *)

  module Game_step_1 (ProofE : ProofE_c.Scheme, A : ProofE_c.INDOT_Adv) = {
    proc main() : bool = {
      var b : bool;
      b <@ A(R1(ProofE, ProofE_c.INDOT__Real(ProofE))).distinguish();
      return b;
    }
  }.

  (* Game_step_2: INDOT$.Random composed with reduction R1 *)

  module Game_step_2 (ProofE : ProofE_c.Scheme, A : ProofE_c.INDOT_Adv) = {
    proc main() : bool = {
      var b : bool;
      b <@ A(R1(ProofE, ProofE_c.INDOT__Random(ProofE))).distinguish();
      return b;
    }
  }.

  (* Game_step_3: INDOT$.Random composed with reduction R2 *)

  module Game_step_3 (ProofE : ProofE_c.Scheme, A : ProofE_c.INDOT_Adv) = {
    proc main() : bool = {
      var b : bool;
      b <@ A(R2(ProofE, ProofE_c.INDOT__Random(ProofE))).distinguish();
      return b;
    }
  }.

  (* Game_step_4: INDOT$.Real composed with reduction R2 *)

  module Game_step_4 (ProofE : ProofE_c.Scheme, A : ProofE_c.INDOT_Adv) = {
    proc main() : bool = {
      var b : bool;
      b <@ A(R2(ProofE, ProofE_c.INDOT__Real(ProofE))).distinguish();
      return b;
    }
  }.

  (* Game_step_5: INDOT.Right *)

  module Game_step_5 (ProofE : ProofE_c.Scheme, A : ProofE_c.INDOT_Adv) = {
    proc main() : bool = {
      var b : bool;
      b <@ A(ProofE_c.INDOT_Right(ProofE)).distinguish();
      return b;
    }
  }.

  (* ===== Per-transform canonicalization chain ===== *)

  module Step_0L_state_0 (ProofE : ProofE_c.Scheme) = {
    proc eavesdrop(mL : ProofMessageSpace, mR : ProofMessageSpace) : ProofCiphertextSpace = {
      var k : ProofKeySpace;
      var c : ProofCiphertextSpace;
      k <@ ProofE.keygen();
      c <@ ProofE.enc(k, mL);
      return c;
    }
  }.

  module Step_0L_state_1 (ProofE : ProofE_c.Scheme) = {
    proc eavesdrop(mL : ProofMessageSpace, mR : ProofMessageSpace) : ProofCiphertextSpace = {
      var __a0__ : ProofKeySpace;
      var __a1__ : ProofCiphertextSpace;
      __a0__ <@ ProofE.keygen();
      __a1__ <@ ProofE.enc(__a0__, mL);
      return __a1__;
    }
  }.

  module Step_0L_state_2 (ProofE : ProofE_c.Scheme) = {
    proc eavesdrop(mL : ProofMessageSpace, mR : ProofMessageSpace) : ProofCiphertextSpace = {
      var _r0 : ProofKeySpace;
      var _r1 : ProofCiphertextSpace;
      _r0 <@ ProofE.keygen();
      _r1 <@ ProofE.enc(_r0, mL);
      return _r1;
    }
  }.

  module Step_0R_state_0 (ProofE : ProofE_c.Scheme) = {
    proc eavesdrop(mL : ProofMessageSpace, mR : ProofMessageSpace) : ProofCiphertextSpace = {
      var challenger_CTXT_k0 : ProofKeySpace;
      var challenger_CTXT_c0 : ProofCiphertextSpace;
      challenger_CTXT_k0 <@ ProofE.keygen();
      challenger_CTXT_c0 <@ ProofE.enc(challenger_CTXT_k0, mL);
      return challenger_CTXT_c0;
    }
  }.

  module Step_0R_state_1 (ProofE : ProofE_c.Scheme) = {
    proc eavesdrop(mL : ProofMessageSpace, mR : ProofMessageSpace) : ProofCiphertextSpace = {
      var __a0__ : ProofKeySpace;
      var __a1__ : ProofCiphertextSpace;
      __a0__ <@ ProofE.keygen();
      __a1__ <@ ProofE.enc(__a0__, mL);
      return __a1__;
    }
  }.

  module Step_0R_state_2 (ProofE : ProofE_c.Scheme) = {
    proc eavesdrop(mL : ProofMessageSpace, mR : ProofMessageSpace) : ProofCiphertextSpace = {
      var _r0 : ProofKeySpace;
      var _r1 : ProofCiphertextSpace;
      _r0 <@ ProofE.keygen();
      _r1 <@ ProofE.enc(_r0, mL);
      return _r1;
    }
  }.

  (* transform: Alpha Rename (bucket=canned) *)
  lemma micro_0_left_0 :
    equiv [ Step_0L_state_0(ProofE).eavesdrop ~ Step_0L_state_1(ProofE).eavesdrop :
            ={mL, mR, glob ProofE} ==> ={res, glob ProofE} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Inline Single-Use Variables (bucket=canned) *)
  lemma micro_0_left_1 :
    equiv [ Step_0L_state_1(ProofE).eavesdrop ~ Step_0L_state_2(ProofE).eavesdrop :
            ={mL, mR, glob ProofE} ==> ={res, glob ProofE} ].
  proof.
    (* resolution: synth-param *)
    proc.
    wp.
    call (_: true).
    wp.
    call (_: true).
    wp.
    skip => />.
  qed.

  (* transform: Alpha Rename (bucket=canned) *)
  lemma micro_0_right_0_fwd :
    equiv [ Step_0R_state_0(ProofE).eavesdrop ~ Step_0R_state_1(ProofE).eavesdrop :
            ={mL, mR, glob ProofE} ==> ={res, glob ProofE} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Alpha Rename (reversed) (bucket=canned) *)
  lemma micro_0_right_0_rev :
    equiv [ Step_0R_state_1(ProofE).eavesdrop ~ Step_0R_state_0(ProofE).eavesdrop :
            ={mL, mR, glob ProofE} ==> ={res, glob ProofE} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Inline Single-Use Variables (bucket=canned) *)
  lemma micro_0_right_1_fwd :
    equiv [ Step_0R_state_1(ProofE).eavesdrop ~ Step_0R_state_2(ProofE).eavesdrop :
            ={mL, mR, glob ProofE} ==> ={res, glob ProofE} ].
  proof.
    (* resolution: synth-param *)
    proc.
    wp.
    call (_: true).
    wp.
    call (_: true).
    wp.
    skip => />.
  qed.

  (* transform: Inline Single-Use Variables (reversed) (bucket=canned) *)
  lemma micro_0_right_1_rev :
    equiv [ Step_0R_state_2(ProofE).eavesdrop ~ Step_0R_state_1(ProofE).eavesdrop :
            ={mL, mR, glob ProofE} ==> ={res, glob ProofE} ].
  proof.
    (* resolution: synth-param *)
    proc.
    wp.
    call (_: true).
    wp.
    call (_: true).
    wp.
    skip => />.
  qed.

  lemma canon_bridge_0 :
    equiv [ Step_0L_state_2(ProofE).eavesdrop ~ Step_0R_state_2(ProofE).eavesdrop :
            ={mL, mR, glob ProofE} ==> ={res, glob ProofE} ].
  proof.
    proc; sim.
  qed.

  lemma hop_0_chain :
    equiv [ Step_0L_state_0(ProofE).eavesdrop ~ Step_0R_state_0(ProofE).eavesdrop :
            ={mL, mR, glob ProofE} ==> ={res, glob ProofE} ].
  proof.
    (* Chain through per-transform micro-lemmas. *)
    transitivity Step_0L_state_1(ProofE).eavesdrop (={mL, mR, glob ProofE} ==> ={res, glob ProofE}) (={mL, mR, glob ProofE} ==> ={res, glob ProofE}); [ smt() | smt() | apply micro_0_left_0 |].
    transitivity Step_0L_state_2(ProofE).eavesdrop (={mL, mR, glob ProofE} ==> ={res, glob ProofE}) (={mL, mR, glob ProofE} ==> ={res, glob ProofE}); [ smt() | smt() | apply micro_0_left_1 |].
    transitivity Step_0R_state_2(ProofE).eavesdrop (={mL, mR, glob ProofE} ==> ={res, glob ProofE}) (={mL, mR, glob ProofE} ==> ={res, glob ProofE}); [ smt() | smt() | apply canon_bridge_0 |].
    transitivity Step_0R_state_1(ProofE).eavesdrop (={mL, mR, glob ProofE} ==> ={res, glob ProofE}) (={mL, mR, glob ProofE} ==> ={res, glob ProofE}); [ smt() | smt() | apply micro_0_right_1_rev |].
    apply micro_0_right_0_rev.
  qed.

  module Step_2L_state_0 (ProofE : ProofE_c.Scheme) = {
    proc eavesdrop(mL : ProofMessageSpace, mR : ProofMessageSpace) : ProofCiphertextSpace = {
      var challenger_CTXT_c0 : ProofCiphertextSpace;
      challenger_CTXT_c0 <$ dProofCiphertextSpace;
      return challenger_CTXT_c0;
    }
  }.

  module Step_2L_state_1 (ProofE : ProofE_c.Scheme) = {
    proc eavesdrop(mL : ProofMessageSpace, mR : ProofMessageSpace) : ProofCiphertextSpace = {
      var __a0__ : ProofCiphertextSpace;
      __a0__ <$ dProofCiphertextSpace;
      return __a0__;
    }
  }.

  module Step_2L_state_2 (ProofE : ProofE_c.Scheme) = {
    proc eavesdrop(mL : ProofMessageSpace, mR : ProofMessageSpace) : ProofCiphertextSpace = {
      var v1 : ProofCiphertextSpace;
      v1 <$ dProofCiphertextSpace;
      return v1;
    }
  }.

  module Step_2R_state_0 (ProofE : ProofE_c.Scheme) = {
    proc eavesdrop(mL : ProofMessageSpace, mR : ProofMessageSpace) : ProofCiphertextSpace = {
      var challenger_CTXT_c0 : ProofCiphertextSpace;
      challenger_CTXT_c0 <$ dProofCiphertextSpace;
      return challenger_CTXT_c0;
    }
  }.

  module Step_2R_state_1 (ProofE : ProofE_c.Scheme) = {
    proc eavesdrop(mL : ProofMessageSpace, mR : ProofMessageSpace) : ProofCiphertextSpace = {
      var __a0__ : ProofCiphertextSpace;
      __a0__ <$ dProofCiphertextSpace;
      return __a0__;
    }
  }.

  module Step_2R_state_2 (ProofE : ProofE_c.Scheme) = {
    proc eavesdrop(mL : ProofMessageSpace, mR : ProofMessageSpace) : ProofCiphertextSpace = {
      var v1 : ProofCiphertextSpace;
      v1 <$ dProofCiphertextSpace;
      return v1;
    }
  }.

  (* transform: Alpha Rename (bucket=canned) *)
  lemma micro_2_left_0 :
    equiv [ Step_2L_state_0(ProofE).eavesdrop ~ Step_2L_state_1(ProofE).eavesdrop :
            ={mL, mR, glob ProofE} ==> ={res, glob ProofE} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Variable Standardization (bucket=canned) *)
  lemma micro_2_left_1 :
    equiv [ Step_2L_state_1(ProofE).eavesdrop ~ Step_2L_state_2(ProofE).eavesdrop :
            ={mL, mR, glob ProofE} ==> ={res, glob ProofE} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Alpha Rename (bucket=canned) *)
  lemma micro_2_right_0_fwd :
    equiv [ Step_2R_state_0(ProofE).eavesdrop ~ Step_2R_state_1(ProofE).eavesdrop :
            ={mL, mR, glob ProofE} ==> ={res, glob ProofE} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Alpha Rename (reversed) (bucket=canned) *)
  lemma micro_2_right_0_rev :
    equiv [ Step_2R_state_1(ProofE).eavesdrop ~ Step_2R_state_0(ProofE).eavesdrop :
            ={mL, mR, glob ProofE} ==> ={res, glob ProofE} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Variable Standardization (bucket=canned) *)
  lemma micro_2_right_1_fwd :
    equiv [ Step_2R_state_1(ProofE).eavesdrop ~ Step_2R_state_2(ProofE).eavesdrop :
            ={mL, mR, glob ProofE} ==> ={res, glob ProofE} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Variable Standardization (reversed) (bucket=canned) *)
  lemma micro_2_right_1_rev :
    equiv [ Step_2R_state_2(ProofE).eavesdrop ~ Step_2R_state_1(ProofE).eavesdrop :
            ={mL, mR, glob ProofE} ==> ={res, glob ProofE} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  lemma canon_bridge_2 :
    equiv [ Step_2L_state_2(ProofE).eavesdrop ~ Step_2R_state_2(ProofE).eavesdrop :
            ={mL, mR, glob ProofE} ==> ={res, glob ProofE} ].
  proof.
    proc; sim.
  qed.

  lemma hop_2_chain :
    equiv [ Step_2L_state_0(ProofE).eavesdrop ~ Step_2R_state_0(ProofE).eavesdrop :
            ={mL, mR, glob ProofE} ==> ={res, glob ProofE} ].
  proof.
    (* Chain through per-transform micro-lemmas. *)
    transitivity Step_2L_state_1(ProofE).eavesdrop (={mL, mR, glob ProofE} ==> ={res, glob ProofE}) (={mL, mR, glob ProofE} ==> ={res, glob ProofE}); [ smt() | smt() | apply micro_2_left_0 |].
    transitivity Step_2L_state_2(ProofE).eavesdrop (={mL, mR, glob ProofE} ==> ={res, glob ProofE}) (={mL, mR, glob ProofE} ==> ={res, glob ProofE}); [ smt() | smt() | apply micro_2_left_1 |].
    transitivity Step_2R_state_2(ProofE).eavesdrop (={mL, mR, glob ProofE} ==> ={res, glob ProofE}) (={mL, mR, glob ProofE} ==> ={res, glob ProofE}); [ smt() | smt() | apply canon_bridge_2 |].
    transitivity Step_2R_state_1(ProofE).eavesdrop (={mL, mR, glob ProofE} ==> ={res, glob ProofE}) (={mL, mR, glob ProofE} ==> ={res, glob ProofE}); [ smt() | smt() | apply micro_2_right_1_rev |].
    apply micro_2_right_0_rev.
  qed.

  module Step_4L_state_0 (ProofE : ProofE_c.Scheme) = {
    proc eavesdrop(mL : ProofMessageSpace, mR : ProofMessageSpace) : ProofCiphertextSpace = {
      var challenger_CTXT_k0 : ProofKeySpace;
      var challenger_CTXT_c0 : ProofCiphertextSpace;
      challenger_CTXT_k0 <@ ProofE.keygen();
      challenger_CTXT_c0 <@ ProofE.enc(challenger_CTXT_k0, mR);
      return challenger_CTXT_c0;
    }
  }.

  module Step_4L_state_1 (ProofE : ProofE_c.Scheme) = {
    proc eavesdrop(mL : ProofMessageSpace, mR : ProofMessageSpace) : ProofCiphertextSpace = {
      var __a0__ : ProofKeySpace;
      var __a1__ : ProofCiphertextSpace;
      __a0__ <@ ProofE.keygen();
      __a1__ <@ ProofE.enc(__a0__, mR);
      return __a1__;
    }
  }.

  module Step_4L_state_2 (ProofE : ProofE_c.Scheme) = {
    proc eavesdrop(mL : ProofMessageSpace, mR : ProofMessageSpace) : ProofCiphertextSpace = {
      var _r0 : ProofKeySpace;
      var _r1 : ProofCiphertextSpace;
      _r0 <@ ProofE.keygen();
      _r1 <@ ProofE.enc(_r0, mR);
      return _r1;
    }
  }.

  module Step_4R_state_0 (ProofE : ProofE_c.Scheme) = {
    proc eavesdrop(mL : ProofMessageSpace, mR : ProofMessageSpace) : ProofCiphertextSpace = {
      var k : ProofKeySpace;
      var c : ProofCiphertextSpace;
      k <@ ProofE.keygen();
      c <@ ProofE.enc(k, mR);
      return c;
    }
  }.

  module Step_4R_state_1 (ProofE : ProofE_c.Scheme) = {
    proc eavesdrop(mL : ProofMessageSpace, mR : ProofMessageSpace) : ProofCiphertextSpace = {
      var __a0__ : ProofKeySpace;
      var __a1__ : ProofCiphertextSpace;
      __a0__ <@ ProofE.keygen();
      __a1__ <@ ProofE.enc(__a0__, mR);
      return __a1__;
    }
  }.

  module Step_4R_state_2 (ProofE : ProofE_c.Scheme) = {
    proc eavesdrop(mL : ProofMessageSpace, mR : ProofMessageSpace) : ProofCiphertextSpace = {
      var _r0 : ProofKeySpace;
      var _r1 : ProofCiphertextSpace;
      _r0 <@ ProofE.keygen();
      _r1 <@ ProofE.enc(_r0, mR);
      return _r1;
    }
  }.

  (* transform: Alpha Rename (bucket=canned) *)
  lemma micro_4_left_0 :
    equiv [ Step_4L_state_0(ProofE).eavesdrop ~ Step_4L_state_1(ProofE).eavesdrop :
            ={mL, mR, glob ProofE} ==> ={res, glob ProofE} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Inline Single-Use Variables (bucket=canned) *)
  lemma micro_4_left_1 :
    equiv [ Step_4L_state_1(ProofE).eavesdrop ~ Step_4L_state_2(ProofE).eavesdrop :
            ={mL, mR, glob ProofE} ==> ={res, glob ProofE} ].
  proof.
    (* resolution: synth-param *)
    proc.
    wp.
    call (_: true).
    wp.
    call (_: true).
    wp.
    skip => />.
  qed.

  (* transform: Alpha Rename (bucket=canned) *)
  lemma micro_4_right_0_fwd :
    equiv [ Step_4R_state_0(ProofE).eavesdrop ~ Step_4R_state_1(ProofE).eavesdrop :
            ={mL, mR, glob ProofE} ==> ={res, glob ProofE} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Alpha Rename (reversed) (bucket=canned) *)
  lemma micro_4_right_0_rev :
    equiv [ Step_4R_state_1(ProofE).eavesdrop ~ Step_4R_state_0(ProofE).eavesdrop :
            ={mL, mR, glob ProofE} ==> ={res, glob ProofE} ].
  proof.
    (* resolution: synth-static *)
    proc; ((sp; wp; sim) || sim).
  qed.

  (* transform: Inline Single-Use Variables (bucket=canned) *)
  lemma micro_4_right_1_fwd :
    equiv [ Step_4R_state_1(ProofE).eavesdrop ~ Step_4R_state_2(ProofE).eavesdrop :
            ={mL, mR, glob ProofE} ==> ={res, glob ProofE} ].
  proof.
    (* resolution: synth-param *)
    proc.
    wp.
    call (_: true).
    wp.
    call (_: true).
    wp.
    skip => />.
  qed.

  (* transform: Inline Single-Use Variables (reversed) (bucket=canned) *)
  lemma micro_4_right_1_rev :
    equiv [ Step_4R_state_2(ProofE).eavesdrop ~ Step_4R_state_1(ProofE).eavesdrop :
            ={mL, mR, glob ProofE} ==> ={res, glob ProofE} ].
  proof.
    (* resolution: synth-param *)
    proc.
    wp.
    call (_: true).
    wp.
    call (_: true).
    wp.
    skip => />.
  qed.

  lemma canon_bridge_4 :
    equiv [ Step_4L_state_2(ProofE).eavesdrop ~ Step_4R_state_2(ProofE).eavesdrop :
            ={mL, mR, glob ProofE} ==> ={res, glob ProofE} ].
  proof.
    proc; sim.
  qed.

  lemma hop_4_chain :
    equiv [ Step_4L_state_0(ProofE).eavesdrop ~ Step_4R_state_0(ProofE).eavesdrop :
            ={mL, mR, glob ProofE} ==> ={res, glob ProofE} ].
  proof.
    (* Chain through per-transform micro-lemmas. *)
    transitivity Step_4L_state_1(ProofE).eavesdrop (={mL, mR, glob ProofE} ==> ={res, glob ProofE}) (={mL, mR, glob ProofE} ==> ={res, glob ProofE}); [ smt() | smt() | apply micro_4_left_0 |].
    transitivity Step_4L_state_2(ProofE).eavesdrop (={mL, mR, glob ProofE} ==> ={res, glob ProofE}) (={mL, mR, glob ProofE} ==> ={res, glob ProofE}); [ smt() | smt() | apply micro_4_left_1 |].
    transitivity Step_4R_state_2(ProofE).eavesdrop (={mL, mR, glob ProofE} ==> ={res, glob ProofE}) (={mL, mR, glob ProofE} ==> ={res, glob ProofE}); [ smt() | smt() | apply canon_bridge_4 |].
    transitivity Step_4R_state_1(ProofE).eavesdrop (={mL, mR, glob ProofE} ==> ={res, glob ProofE}) (={mL, mR, glob ProofE} ==> ={res, glob ProofE}); [ smt() | smt() | apply micro_4_right_1_rev |].
    apply micro_4_right_0_rev.
  qed.

  (* ===== Per-hop equivalence lemmas ===== *)

  lemma hop_0 :
    equiv [ ProofE_c.INDOT_Left(ProofE).eavesdrop ~ R1(ProofE, ProofE_c.INDOT__Real(ProofE)).eavesdrop :
            ={mL, mR, glob ProofE} ==> ={res, glob ProofE} ].
  proof.
    (* Per-transform: bridge wrappers to flat states, chain through. *)
    transitivity Step_0L_state_0(ProofE).eavesdrop (={mL, mR, glob ProofE} ==> ={res, glob ProofE}) (={mL, mR, glob ProofE} ==> ={res, glob ProofE}); [ smt() | smt() | proc; inline *; ((sp; wp; sim) || sim) |].
    transitivity Step_0R_state_0(ProofE).eavesdrop (={mL, mR, glob ProofE} ==> ={res, glob ProofE}) (={mL, mR, glob ProofE} ==> ={res, glob ProofE}); [ smt() | smt() | apply hop_0_chain | proc; inline *; ((sp; wp; sim) || sim) ].
    qed.

  lemma hop_2 :
    equiv [ R1(ProofE, ProofE_c.INDOT__Random(ProofE)).eavesdrop ~ R2(ProofE, ProofE_c.INDOT__Random(ProofE)).eavesdrop :
            ={mL, mR, glob ProofE} ==> ={res, glob ProofE} ].
  proof.
    (* Per-transform: bridge wrappers to flat states, chain through. *)
    transitivity Step_2L_state_0(ProofE).eavesdrop (={mL, mR, glob ProofE} ==> ={res, glob ProofE}) (={mL, mR, glob ProofE} ==> ={res, glob ProofE}); [ smt() | smt() | proc; inline *; ((sp; wp; sim) || sim) |].
    transitivity Step_2R_state_0(ProofE).eavesdrop (={mL, mR, glob ProofE} ==> ={res, glob ProofE}) (={mL, mR, glob ProofE} ==> ={res, glob ProofE}); [ smt() | smt() | apply hop_2_chain | proc; inline *; ((sp; wp; sim) || sim) ].
    qed.

  lemma hop_4 :
    equiv [ R2(ProofE, ProofE_c.INDOT__Real(ProofE)).eavesdrop ~ ProofE_c.INDOT_Right(ProofE).eavesdrop :
            ={mL, mR, glob ProofE} ==> ={res, glob ProofE} ].
  proof.
    (* Per-transform: bridge wrappers to flat states, chain through. *)
    transitivity Step_4L_state_0(ProofE).eavesdrop (={mL, mR, glob ProofE} ==> ={res, glob ProofE}) (={mL, mR, glob ProofE} ==> ={res, glob ProofE}); [ smt() | smt() | proc; inline *; ((sp; wp; sim) || sim) |].
    transitivity Step_4R_state_0(ProofE).eavesdrop (={mL, mR, glob ProofE} ==> ={res, glob ProofE}) (={mL, mR, glob ProofE} ==> ={res, glob ProofE}); [ smt() | smt() | apply hop_4_chain | proc; inline *; ((sp; wp; sim) || sim) ].
    qed.

  (* ===== Per-hop probability lemmas ===== *)

  (* Hop 0: interchangeability. The two adjacent games are equivalent (no advantage). *)

  lemma hop_0_pr (A <: ProofE_c.INDOT_Adv {-ProofE}) &m :
    Pr[Game_step_0(ProofE, A).main() @ &m : res] = Pr[Game_step_1(ProofE, A).main() @ &m : res].
  proof.
    byequiv (_: ={glob A, glob ProofE} ==> ={res}) => //; proc.
    call (_: ={glob ProofE}); first by conseq hop_0.
    auto.
    qed.

  (* Hop 1: assumption hop. Bounded by the INDOT$_advantage axiom applied to R1_Adv. *)

  lemma hop_1_pr (A <: ProofE_c.INDOT_Adv {-ProofE}) &m :
    `| Pr[Game_step_1(ProofE, A).main() @ &m : res] - Pr[Game_step_2(ProofE, A).main() @ &m : res] | <= ProofE_c.eps_INDOT_.
  proof.
    have hL : Pr[Game_step_1(ProofE, A).main() @ &m : res]
            = Pr[ProofE_c.Game_INDOT__Real(ProofE, R1_Adv(ProofE, A)).main() @ &m : res]
      by byequiv => //; proc; inline *; sim.
    have hR : Pr[Game_step_2(ProofE, A).main() @ &m : res]
            = Pr[ProofE_c.Game_INDOT__Random(ProofE, R1_Adv(ProofE, A)).main() @ &m : res]
      by byequiv => //; proc; inline *; sim.
    rewrite hL hR.
    apply (ProofE_c.INDOT__advantage ProofE (R1_Adv(ProofE, A)) &m).
    qed.

  (* Hop 2: interchangeability. The two adjacent games are equivalent (no advantage). *)

  lemma hop_2_pr (A <: ProofE_c.INDOT_Adv {-ProofE}) &m :
    Pr[Game_step_2(ProofE, A).main() @ &m : res] = Pr[Game_step_3(ProofE, A).main() @ &m : res].
  proof.
    byequiv (_: ={glob A, glob ProofE} ==> ={res}) => //; proc.
    call (_: ={glob ProofE}); first by conseq hop_2.
    auto.
    qed.

  (* Hop 3: assumption hop. Bounded by the INDOT$_advantage axiom applied to R2_Adv. *)

  lemma hop_3_pr (A <: ProofE_c.INDOT_Adv {-ProofE}) &m :
    `| Pr[Game_step_3(ProofE, A).main() @ &m : res] - Pr[Game_step_4(ProofE, A).main() @ &m : res] | <= ProofE_c.eps_INDOT_.
  proof.
    have hL : Pr[Game_step_3(ProofE, A).main() @ &m : res]
            = Pr[ProofE_c.Game_INDOT__Random(ProofE, R2_Adv(ProofE, A)).main() @ &m : res]
      by byequiv => //; proc; inline *; sim.
    have hR : Pr[Game_step_4(ProofE, A).main() @ &m : res]
            = Pr[ProofE_c.Game_INDOT__Real(ProofE, R2_Adv(ProofE, A)).main() @ &m : res]
      by byequiv => //; proc; inline *; sim.
    rewrite hL hR.
    have H := ProofE_c.INDOT__advantage ProofE (R2_Adv(ProofE, A)) &m.
    smt().
    qed.

  (* Hop 4: interchangeability. The two adjacent games are equivalent (no advantage). *)

  lemma hop_4_pr (A <: ProofE_c.INDOT_Adv {-ProofE}) &m :
    Pr[Game_step_4(ProofE, A).main() @ &m : res] = Pr[Game_step_5(ProofE, A).main() @ &m : res].
  proof.
    byequiv (_: ={glob A, glob ProofE} ==> ={res}) => //; proc.
    call (_: ={glob ProofE}); first by conseq hop_4.
    auto.
    qed.

  (* ===== Main theorem ===== *)

  lemma main_theorem (A <: ProofE_c.INDOT_Adv {-ProofE}) &m :
    `| Pr[Game_step_0(ProofE, A).main() @ &m : res] - Pr[Game_step_5(ProofE, A).main() @ &m : res] | <= ProofE_c.eps_INDOT_ + ProofE_c.eps_INDOT_.
  proof.
    have h0 := hop_0_pr A &m.
    have h1 := hop_1_pr A &m.
    have h2 := hop_2_pr A &m.
    have h3 := hop_3_pr A &m.
    have h4 := hop_4_pr A &m.
    smt(ProofE_c.eps_INDOT__pos).
    qed.
end section Main.
