(* Auto-generated by ProofFrog. Do not edit. *)
require import AllCore Distr DProd DMap List.
require BitWord.

(* ===== Abstract set declarations ===== *)

op lambda : int.

op in_ : int.

op out : int.

type SharedSecretSpace.

type CiphertextSpace.

type PKeySpace.

type SKeySpace.

(* ===== Concrete primitive types ===== *)

op dSharedSecretSpace : SharedSecretSpace distr.

axiom dSharedSecretSpace_ll : is_lossless dSharedSecretSpace.

axiom dSharedSecretSpace_fu : is_funiform dSharedSecretSpace.

axiom dSharedSecretSpace_full : is_full dSharedSecretSpace.

axiom gt0_out : 0 < out.

clone BitWord as BW_bs_out with
  op n <- out
  proof gt0_n by smt(gt0_out).

type bs_out = BW_bs_out.word.

op [smt_opaque] dbs_out : bs_out distr =
  BW_bs_out.DWord.dunifin.

lemma dbs_out_ll :
  is_lossless dbs_out.
proof.
  exact BW_bs_out.DWord.dunifin_ll.
qed.

lemma dbs_out_fu :
  is_funiform dbs_out.
proof.
  exact BW_bs_out.DWord.dunifin_funi.
qed.

lemma dbs_out_full :
  is_full dbs_out.
proof.
  exact BW_bs_out.DWord.dunifin_fu.
qed.

type bs_lambda = SharedSecretSpace.

op dbs_lambda : bs_lambda distr.

axiom dbs_lambda_ll : is_lossless dbs_lambda.

axiom dbs_lambda_fu : is_funiform dbs_lambda.

axiom dbs_lambda_full : is_full dbs_lambda.

type bs_in = CiphertextSpace.

op dbs_in : bs_in distr.

axiom dbs_in_ll : is_lossless dbs_in.

axiom dbs_in_fu : is_funiform dbs_in.

axiom dbs_in_full : is_full dbs_in.

op zero_out : bs_out.

op zero_lambda : bs_lambda.

op zero_in : bs_in.

(* ===== Abstract theory: primitive + security games + assumption ===== *)

abstract theory KEM_Theory.
  type publickey.

  type secretkey.

  type sharedsecret.

  type ciphertext.

  op dsharedsecret : sharedsecret distr.

  axiom dsharedsecret_ll : is_lossless dsharedsecret.

  axiom dsharedsecret_fu : is_funiform dsharedsecret.

  axiom dsharedsecret_full : is_full dsharedsecret.

  module type Scheme = {
    proc keygen() : publickey * secretkey
    proc encaps(pk : publickey) : sharedsecret * ciphertext
    proc decaps(sk : secretkey, m : ciphertext) : sharedsecret
  }.

  op ev_decaps : secretkey -> ciphertext -> sharedsecret.

  module type KEM_INDCPA_MultiChal_Oracle = {
    proc initialize() : publickey
    proc challenge() : sharedsecret * ciphertext
  }.

  module KEM_INDCPA_MultiChal_Real (K : Scheme) : KEM_INDCPA_MultiChal_Oracle = {
    var pk : publickey
    var sk : secretkey
    proc initialize() : publickey = {
      var _tup : publickey * secretkey;
      _tup <@ K.keygen();
      pk <- _tup.`1;
      sk <- _tup.`2;
      return pk;
    }
    proc challenge() : sharedsecret * ciphertext = {
      var _tup : sharedsecret * ciphertext;
      var ss : sharedsecret;
      var ctxt : ciphertext;
      _tup <@ K.encaps(pk);
      ss <- _tup.`1;
      ctxt <- _tup.`2;
      return (ss, ctxt);
    }
  }.

  module KEM_INDCPA_MultiChal_Random (K : Scheme) : KEM_INDCPA_MultiChal_Oracle = {
    var pk : publickey
    var sk : secretkey
    proc initialize() : publickey = {
      var _tup : publickey * secretkey;
      _tup <@ K.keygen();
      pk <- _tup.`1;
      sk <- _tup.`2;
      return pk;
    }
    proc challenge() : sharedsecret * ciphertext = {
      var rsp : sharedsecret * ciphertext;
      var ss : sharedsecret;
      var ctxt : ciphertext;
      rsp <@ K.encaps(pk);
      ss <$ dsharedsecret;
      ctxt <- rsp.`2;
      return (ss, ctxt);
    }
  }.

  module type KEM_INDCPA_MultiChal_Adv (O : KEM_INDCPA_MultiChal_Oracle) = {
    proc distinguish(pk : publickey) : bool {O.challenge}
  }.

  module Game_KEM_INDCPA_MultiChal_Real (Em : Scheme, A : KEM_INDCPA_MultiChal_Adv) = {
    proc main() : bool = {
      var b : bool;
      var pk : publickey;
      pk <@ KEM_INDCPA_MultiChal_Real(Em).initialize();
      b <@ A(KEM_INDCPA_MultiChal_Real(Em)).distinguish(pk);
      return b;
    }
  }.

  module Game_KEM_INDCPA_MultiChal_Random (Em : Scheme, A : KEM_INDCPA_MultiChal_Adv) = {
    proc main() : bool = {
      var b : bool;
      var pk : publickey;
      pk <@ KEM_INDCPA_MultiChal_Random(Em).initialize();
      b <@ A(KEM_INDCPA_MultiChal_Random(Em)).distinguish(pk);
      return b;
    }
  }.

  op eps_KEM_INDCPA_MultiChal : real.

  axiom eps_KEM_INDCPA_MultiChal_pos : 0%r <= eps_KEM_INDCPA_MultiChal.

  axiom KEM_INDCPA_MultiChal_advantage (Em <: Scheme) (A <: KEM_INDCPA_MultiChal_Adv) &m :
    `| Pr[Game_KEM_INDCPA_MultiChal_Real(Em, A).main() @ &m : res] - Pr[Game_KEM_INDCPA_MultiChal_Random(Em, A).main() @ &m : res] | <= eps_KEM_INDCPA_MultiChal.
end KEM_Theory.

(* ===== Foreign primitive theory: PRF_Theory ===== *)

abstract theory PRF_Theory.
  type bs_lambda_t.

  op zero_lambda_t : bs_lambda_t.

  type bs_in_t.

  op zero_in_t : bs_in_t.

  type bs_out_t.

  op zero_out_t : bs_out_t.

  op dbs_lambda_t : bs_lambda_t distr.

  axiom dbs_lambda_t_ll : is_lossless dbs_lambda_t.

  axiom dbs_lambda_t_fu : is_funiform dbs_lambda_t.

  axiom dbs_lambda_t_full : is_full dbs_lambda_t.

  op dbs_out_t : bs_out_t distr.

  axiom dbs_out_t_ll : is_lossless dbs_out_t.

  axiom dbs_out_t_fu : is_funiform dbs_out_t.

  axiom dbs_out_t_full : is_full dbs_out_t.

  module type Scheme = {
    proc evaluate(seed : bs_lambda_t, input : bs_in_t) : bs_out_t
  }.

  op ev_evaluate : bs_lambda_t -> bs_in_t -> bs_out_t.

  module type PRFSecurity_MultiKey_Oracle = {
    proc lookup(x : bs_in_t) : bs_out_t
  }.

  module PRFSecurity_MultiKey_Real (F : Scheme) : PRFSecurity_MultiKey_Oracle = {
    proc lookup(x : bs_in_t) : bs_out_t = {
      var k : bs_lambda_t;
      var _r0 : bs_out_t;
      k <$ dbs_lambda_t;
      _r0 <@ F.evaluate(k, x);
      return _r0;
    }
  }.

  module PRFSecurity_MultiKey_Random (F : Scheme) : PRFSecurity_MultiKey_Oracle = {
    proc lookup(x : bs_in_t) : bs_out_t = {
      var r : bs_out_t;
      r <$ dbs_out_t;
      return r;
    }
  }.

  module type PRFSecurity_MultiKey_Adv (O : PRFSecurity_MultiKey_Oracle) = {
    proc distinguish() : bool
  }.

  module Game_PRFSecurity_MultiKey_Real (Em : Scheme, A : PRFSecurity_MultiKey_Adv) = {
    proc main() : bool = {
      var b : bool;
      b <@ A(PRFSecurity_MultiKey_Real(Em)).distinguish();
      return b;
    }
  }.

  module Game_PRFSecurity_MultiKey_Random (Em : Scheme, A : PRFSecurity_MultiKey_Adv) = {
    proc main() : bool = {
      var b : bool;
      b <@ A(PRFSecurity_MultiKey_Random(Em)).distinguish();
      return b;
    }
  }.

  op eps_PRFSecurity_MultiKey : real.

  axiom eps_PRFSecurity_MultiKey_pos : 0%r <= eps_PRFSecurity_MultiKey.

  axiom PRFSecurity_MultiKey_advantage (Em <: Scheme) (A <: PRFSecurity_MultiKey_Adv) &m :
    `| Pr[Game_PRFSecurity_MultiKey_Real(Em, A).main() @ &m : res] - Pr[Game_PRFSecurity_MultiKey_Random(Em, A).main() @ &m : res] | <= eps_PRFSecurity_MultiKey.
end PRF_Theory.

(* ===== Theory instantiation ===== *)

clone KEM_Theory as K_c with
  type sharedsecret <- SharedSecretSpace,
  type ciphertext <- CiphertextSpace,
  type publickey <- PKeySpace,
  type secretkey <- SKeySpace,
  op dsharedsecret <- dSharedSecretSpace.

clone PRF_Theory as F_c with
  type bs_lambda_t <- bs_lambda,
  type bs_in_t <- bs_in,
  type bs_out_t <- bs_out,
  op dbs_lambda_t <- dbs_lambda,
  op dbs_out_t <- dbs_out.

clone KEM_Theory as KF_c with
  type sharedsecret <- bs_out,
  type ciphertext <- CiphertextSpace,
  type publickey <- PKeySpace,
  type secretkey <- SKeySpace,
  op dsharedsecret <- dbs_out.

(* ===== Per-clone distribution axioms ===== *)

lemma K_dSharedSecretSpace_funi :
  is_funiform dSharedSecretSpace.
proof.
  exact dSharedSecretSpace_fu.
qed.

lemma K_dSharedSecretSpace_ll :
  is_lossless dSharedSecretSpace.
proof.
  exact dSharedSecretSpace_ll.
qed.

lemma F_dbs_lambda_funi :
  is_funiform dbs_lambda.
proof.
  exact dbs_lambda_fu.
qed.

lemma F_dbs_lambda_ll :
  is_lossless dbs_lambda.
proof.
  exact dbs_lambda_ll.
qed.

lemma F_dbs_out_funi :
  is_funiform dbs_out.
proof.
  exact dbs_out_fu.
qed.

lemma F_dbs_out_ll :
  is_lossless dbs_out.
proof.
  exact dbs_out_ll.
qed.

lemma KF_dbs_out_funi :
  is_funiform dbs_out.
proof.
  exact dbs_out_fu.
qed.

lemma KF_dbs_out_ll :
  is_lossless dbs_out.
proof.
  exact dbs_out_ll.
qed.

(* ===== Concrete scheme implementation ===== *)

module KEMPRF (K : K_c.Scheme, F : F_c.Scheme) : KF_c.Scheme = {
  proc keygen() : PKeySpace * SKeySpace = {
    var _r0 : PKeySpace * SKeySpace;
    _r0 <@ K.keygen();
    return _r0;
  }
  proc encaps(pk : PKeySpace) : bs_out * CiphertextSpace = {
    var x : SharedSecretSpace * CiphertextSpace;
    var k : bs_lambda;
    var c : CiphertextSpace;
    var ss : bs_out;
    x <@ K.encaps(pk);
    k <- x.`1;
    c <- x.`2;
    ss <@ F.evaluate(k, c);
    return (ss, c);
  }
  proc decaps(sk : SKeySpace, c : CiphertextSpace) : bs_out = {
    var k : SharedSecretSpace;
    var ss : bs_out;
    k <@ K.decaps(sk, c);
    ss <@ F.evaluate(k, c);
    return ss;
  }
}.

section Main.
  (* ===== Reductions ===== *)

  module R_KEM (K : K_c.Scheme, F : F_c.Scheme, KF : KF_c.Scheme, Challenger : K_c.KEM_INDCPA_MultiChal_Oracle) = {
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace;
      _r0 <@ Challenger.initialize();
      return _r0;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var _tup : SharedSecretSpace * CiphertextSpace;
      var ss : SharedSecretSpace;
      var ct : CiphertextSpace;
      var _r0 : bs_out;
      _tup <@ Challenger.challenge();
      ss <- _tup.`1;
      ct <- _tup.`2;
      _r0 <@ F.evaluate(ss, ct);
      return (_r0, ct);
    }
  }.

  module R_MultiPRF (K : K_c.Scheme, F : F_c.Scheme, KF : KF_c.Scheme, Challenger : F_c.PRFSecurity_MultiKey_Oracle) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var k : PKeySpace * SKeySpace;
      k <@ K.keygen();
      pk <- k.`1;
      return pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var rsp : SharedSecretSpace * CiphertextSpace;
      var ct : CiphertextSpace;
      var ss : bs_out;
      rsp <@ K.encaps(pk);
      ct <- rsp.`2;
      ss <@ Challenger.lookup(ct);
      return (ss, ct);
    }
  }.

  (* ===== Reductions lifted to assumption-adversaries ===== *)

  module R_KEM_Adv (K : K_c.Scheme, F : F_c.Scheme, A : KF_c.KEM_INDCPA_MultiChal_Adv, C : K_c.KEM_INDCPA_MultiChal_Oracle) = {
    proc distinguish(pk : PKeySpace) : bool = {
      var b : bool;
      b <@ A(R_KEM(K, F, KEMPRF(K, F), C)).distinguish(pk);
      return b;
    }
  }.

  module R_MultiPRF_Adv (K : K_c.Scheme, F : F_c.Scheme, A : KF_c.KEM_INDCPA_MultiChal_Adv, C : F_c.PRFSecurity_MultiKey_Oracle) = {
    proc distinguish() : bool = {
      var b : bool;
      var pk0 : PKeySpace;
      pk0 <@ R_MultiPRF(K, F, KEMPRF(K, F), C).initialize();
      b <@ A(R_MultiPRF(K, F, KEMPRF(K, F), C)).distinguish(pk0);
      return b;
    }
  }.

  (* ===== Intermediate games ===== *)

  module G_RandKey (K : K_c.Scheme, F : F_c.Scheme) : KF_c.KEM_INDCPA_MultiChal_Oracle = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var k : PKeySpace * SKeySpace;
      k <@ K.keygen();
      pk <- k.`1;
      return pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var key : bs_lambda;
      var rsp : SharedSecretSpace * CiphertextSpace;
      var ct : CiphertextSpace;
      var _r0 : bs_out;
      key <$ dbs_lambda;
      rsp <@ K.encaps(pk);
      ct <- rsp.`2;
      _r0 <@ F.evaluate(key, ct);
      return (_r0, ct);
    }
  }.

  (* ===== Game-step wrappers ===== *)

  (* Game_step_0: KEM_INDCPA_MultiChal.Real *)

  module Game_step_0 (K : K_c.Scheme, F : F_c.Scheme, A : KF_c.KEM_INDCPA_MultiChal_Adv) = {
    proc main() : bool = {
      var b : bool;
      var pk : PKeySpace;
      pk <@ KF_c.KEM_INDCPA_MultiChal_Real(KEMPRF(K, F)).initialize();
      b <@ A(KF_c.KEM_INDCPA_MultiChal_Real(KEMPRF(K, F))).distinguish(pk);
      return b;
    }
  }.

  (* Game_step_1: KEM_INDCPA_MultiChal.Real composed with reduction R_KEM *)

  module Game_step_1 (K : K_c.Scheme, F : F_c.Scheme, A : KF_c.KEM_INDCPA_MultiChal_Adv) = {
    proc main() : bool = {
      var b : bool;
      var pk : PKeySpace;
      pk <@ R_KEM(K, F, KEMPRF(K, F), K_c.KEM_INDCPA_MultiChal_Real(K)).initialize();
      b <@ A(R_KEM(K, F, KEMPRF(K, F), K_c.KEM_INDCPA_MultiChal_Real(K))).distinguish(pk);
      return b;
    }
  }.

  (* Game_step_2: KEM_INDCPA_MultiChal.Random composed with reduction R_KEM *)

  module Game_step_2 (K : K_c.Scheme, F : F_c.Scheme, A : KF_c.KEM_INDCPA_MultiChal_Adv) = {
    proc main() : bool = {
      var b : bool;
      var pk : PKeySpace;
      pk <@ R_KEM(K, F, KEMPRF(K, F), K_c.KEM_INDCPA_MultiChal_Random(K)).initialize();
      b <@ A(R_KEM(K, F, KEMPRF(K, F), K_c.KEM_INDCPA_MultiChal_Random(K))).distinguish(pk);
      return b;
    }
  }.

  (* Game_step_3 *)

  module Game_step_3 (K : K_c.Scheme, F : F_c.Scheme, A : KF_c.KEM_INDCPA_MultiChal_Adv) = {
    proc main() : bool = {
      var b : bool;
      var pk : PKeySpace;
      pk <@ G_RandKey(K, F).initialize();
      b <@ A(G_RandKey(K, F)).distinguish(pk);
      return b;
    }
  }.

  (* Game_step_4: PRFSecurity_MultiKey.Real composed with reduction R_MultiPRF *)

  module Game_step_4 (K : K_c.Scheme, F : F_c.Scheme, A : KF_c.KEM_INDCPA_MultiChal_Adv) = {
    proc main() : bool = {
      var b : bool;
      var pk : PKeySpace;
      pk <@ R_MultiPRF(K, F, KEMPRF(K, F), F_c.PRFSecurity_MultiKey_Real(F)).initialize();
      b <@ A(R_MultiPRF(K, F, KEMPRF(K, F), F_c.PRFSecurity_MultiKey_Real(F))).distinguish(pk);
      return b;
    }
  }.

  (* Game_step_5: PRFSecurity_MultiKey.Random composed with reduction R_MultiPRF *)

  module Game_step_5 (K : K_c.Scheme, F : F_c.Scheme, A : KF_c.KEM_INDCPA_MultiChal_Adv) = {
    proc main() : bool = {
      var b : bool;
      var pk : PKeySpace;
      pk <@ R_MultiPRF(K, F, KEMPRF(K, F), F_c.PRFSecurity_MultiKey_Random(F)).initialize();
      b <@ A(R_MultiPRF(K, F, KEMPRF(K, F), F_c.PRFSecurity_MultiKey_Random(F))).distinguish(pk);
      return b;
    }
  }.

  (* Game_step_6: KEM_INDCPA_MultiChal.Random *)

  module Game_step_6 (K : K_c.Scheme, F : F_c.Scheme, A : KF_c.KEM_INDCPA_MultiChal_Adv) = {
    proc main() : bool = {
      var b : bool;
      var pk : PKeySpace;
      pk <@ KF_c.KEM_INDCPA_MultiChal_Random(KEMPRF(K, F)).initialize();
      b <@ A(KF_c.KEM_INDCPA_MultiChal_Random(KEMPRF(K, F))).distinguish(pk);
      return b;
    }
  }.

  (* ===== Per-transform canonicalization chain ===== *)

  module Step_0L_state_0 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    var sk : SKeySpace
    proc initialize() : PKeySpace = {
      var _tup : PKeySpace * SKeySpace;
      _tup <@ K.keygen();
      pk <- _tup.`1;
      sk <- _tup.`2;
      return pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var v_KF_Encaps_x0 : SharedSecretSpace * CiphertextSpace;
      var v_KF_Encaps_k0 : bs_lambda;
      var v_KF_Encaps_c0 : CiphertextSpace;
      var v_KF_Encaps_ss0 : bs_out;
      var _tup : bs_out * CiphertextSpace;
      var ss : bs_out;
      var ctxt : CiphertextSpace;
      v_KF_Encaps_x0 <@ K.encaps(pk);
      v_KF_Encaps_k0 <- v_KF_Encaps_x0.`1;
      v_KF_Encaps_c0 <- v_KF_Encaps_x0.`2;
      v_KF_Encaps_ss0 <@ F.evaluate(v_KF_Encaps_k0, v_KF_Encaps_c0);
      _tup <- (v_KF_Encaps_ss0, v_KF_Encaps_c0);
      ss <- _tup.`1;
      ctxt <- _tup.`2;
      return (ss, ctxt);
    }
  }.

  module Step_0L_state_1 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    var sk : SKeySpace
    proc initialize() : PKeySpace = {
      var __a0__ : PKeySpace * SKeySpace;
      __a0__ <@ K.keygen();
      pk <- __a0__.`1;
      sk <- __a0__.`2;
      return pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var __a1__ : SharedSecretSpace * CiphertextSpace;
      var __a2__ : bs_lambda;
      var __a3__ : CiphertextSpace;
      var __a4__ : bs_out;
      var __a5__ : bs_out * CiphertextSpace;
      var __a6__ : bs_out;
      var __a7__ : CiphertextSpace;
      __a1__ <@ K.encaps(pk);
      __a2__ <- __a1__.`1;
      __a3__ <- __a1__.`2;
      __a4__ <@ F.evaluate(__a2__, __a3__);
      __a5__ <- (__a4__, __a3__);
      __a6__ <- __a5__.`1;
      __a7__ <- __a5__.`2;
      return (__a6__, __a7__);
    }
  }.

  module Step_0L_state_2 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    var sk : SKeySpace
    proc initialize() : PKeySpace = {
      var __a0__ : PKeySpace * SKeySpace;
      __a0__ <@ K.keygen();
      pk <- __a0__.`1;
      sk <- __a0__.`2;
      return pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var __a1__ : SharedSecretSpace * CiphertextSpace;
      var __a3__ : CiphertextSpace;
      var _r0 : bs_out;
      var __a5__ : bs_out * CiphertextSpace;
      __a1__ <@ K.encaps(pk);
      __a3__ <- __a1__.`2;
      _r0 <@ F.evaluate(__a1__.`1, __a3__);
      __a5__ <- (_r0, __a3__);
      return (__a5__.`1, __a5__.`2);
    }
  }.

  module Step_0L_state_3 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    var sk : SKeySpace
    proc initialize() : PKeySpace = {
      var __a0__ : PKeySpace * SKeySpace;
      __a0__ <@ K.keygen();
      pk <- __a0__.`1;
      sk <- __a0__.`2;
      return pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var __a1__ : SharedSecretSpace * CiphertextSpace;
      var __a3__ : CiphertextSpace;
      var _r0 : bs_out;
      __a1__ <@ K.encaps(pk);
      __a3__ <- __a1__.`2;
      _r0 <@ F.evaluate(__a1__.`1, __a3__);
      return (_r0, __a3__);
    }
  }.

  module Step_0L_state_4 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var __a0__ : PKeySpace * SKeySpace;
      __a0__ <@ K.keygen();
      pk <- __a0__.`1;
      return pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var __a1__ : SharedSecretSpace * CiphertextSpace;
      var __a3__ : CiphertextSpace;
      var _r0 : bs_out;
      __a1__ <@ K.encaps(pk);
      __a3__ <- __a1__.`2;
      _r0 <@ F.evaluate(__a1__.`1, __a3__);
      return (_r0, __a3__);
    }
  }.

  module Step_0L_state_5 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var __a0__ : PKeySpace * SKeySpace;
      __a0__ <@ K.keygen();
      pk <- __a0__.`1;
      return pk;
    }
    proc challenge() : bs_out * bs_in = {
      var __a1__ : bs_lambda * bs_in;
      var __a3__ : bs_in;
      var _r0 : bs_out;
      __a1__ <@ K.encaps(pk);
      __a3__ <- __a1__.`2;
      _r0 <@ F.evaluate(__a1__.`1, __a3__);
      return (_r0, __a3__);
    }
  }.

  module Step_0L_state_6 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      var __a0__ : PKeySpace;
      _r0 <@ K.keygen();
      __a0__ <- _r0.`1;
      pk <- __a0__;
      return pk;
    }
    proc challenge() : bs_out * bs_in = {
      var __a1__ : bs_lambda * bs_in;
      var __a3__ : bs_in;
      var _r0 : bs_out;
      __a1__ <@ K.encaps(pk);
      __a3__ <- __a1__.`2;
      _r0 <@ F.evaluate(__a1__.`1, __a3__);
      return (_r0, __a3__);
    }
  }.

  module Step_0L_state_7 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      pk <- _r0.`1;
      return pk;
    }
    proc challenge() : bs_out * bs_in = {
      var __a1__ : bs_lambda * bs_in;
      var __a3__ : bs_in;
      var _r0 : bs_out;
      __a1__ <@ K.encaps(pk);
      __a3__ <- __a1__.`2;
      _r0 <@ F.evaluate(__a1__.`1, __a3__);
      return (_r0, __a3__);
    }
  }.

  module Step_0L_state_8 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      pk <- _r0.`1;
      return pk;
    }
    proc challenge() : bs_out * bs_in = {
      var v1 : bs_lambda * bs_in;
      var v2 : bs_in;
      var _r0 : bs_out;
      v1 <@ K.encaps(pk);
      v2 <- v1.`2;
      _r0 <@ F.evaluate(v1.`1, v2);
      return (_r0, v2);
    }
  }.

  module Step_0L_state_9 (K : K_c.Scheme, F : F_c.Scheme) = {
    var field1 : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      field1 <- _r0.`1;
      return field1;
    }
    proc challenge() : bs_out * bs_in = {
      var v1 : bs_lambda * bs_in;
      var v2 : bs_in;
      var _r0 : bs_out;
      v1 <@ K.encaps(field1);
      v2 <- v1.`2;
      _r0 <@ F.evaluate(v1.`1, v2);
      return (_r0, v2);
    }
  }.

  module Step_0R_state_0 (K : K_c.Scheme, F : F_c.Scheme) = {
    var challenger_pk : PKeySpace
    var challenger_sk : SKeySpace
    proc initialize() : PKeySpace = {
      var challenger_Initialize__tup0 : PKeySpace * SKeySpace;
      challenger_Initialize__tup0 <@ K.keygen();
      challenger_pk <- challenger_Initialize__tup0.`1;
      challenger_sk <- challenger_Initialize__tup0.`2;
      return challenger_pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var challenger_Challenge__tup0 : SharedSecretSpace * CiphertextSpace;
      var challenger_Challenge_ss0 : SharedSecretSpace;
      var challenger_Challenge_ctxt0 : CiphertextSpace;
      var _tup : SharedSecretSpace * CiphertextSpace;
      var ss : SharedSecretSpace;
      var ct : CiphertextSpace;
      var _r0 : bs_out;
      challenger_Challenge__tup0 <@ K.encaps(challenger_pk);
      challenger_Challenge_ss0 <- challenger_Challenge__tup0.`1;
      challenger_Challenge_ctxt0 <- challenger_Challenge__tup0.`2;
      _tup <- (challenger_Challenge_ss0, challenger_Challenge_ctxt0);
      ss <- _tup.`1;
      ct <- _tup.`2;
      _r0 <@ F.evaluate(ss, ct);
      return (_r0, ct);
    }
  }.

  module Step_0R_state_1 (K : K_c.Scheme, F : F_c.Scheme) = {
    var challenger_pk : PKeySpace
    var challenger_sk : SKeySpace
    proc initialize() : PKeySpace = {
      var __a0__ : PKeySpace * SKeySpace;
      __a0__ <@ K.keygen();
      challenger_pk <- __a0__.`1;
      challenger_sk <- __a0__.`2;
      return challenger_pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var __a1__ : SharedSecretSpace * CiphertextSpace;
      var __a2__ : SharedSecretSpace;
      var __a3__ : CiphertextSpace;
      var __a4__ : SharedSecretSpace * CiphertextSpace;
      var __a5__ : SharedSecretSpace;
      var __a6__ : CiphertextSpace;
      var _r0 : bs_out;
      __a1__ <@ K.encaps(challenger_pk);
      __a2__ <- __a1__.`1;
      __a3__ <- __a1__.`2;
      __a4__ <- (__a2__, __a3__);
      __a5__ <- __a4__.`1;
      __a6__ <- __a4__.`2;
      _r0 <@ F.evaluate(__a5__, __a6__);
      return (_r0, __a6__);
    }
  }.

  module Step_0R_state_2 (K : K_c.Scheme, F : F_c.Scheme) = {
    var challenger_pk : PKeySpace
    var challenger_sk : SKeySpace
    proc initialize() : PKeySpace = {
      var __a0__ : PKeySpace * SKeySpace;
      __a0__ <@ K.keygen();
      challenger_pk <- __a0__.`1;
      challenger_sk <- __a0__.`2;
      return challenger_pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var __a1__ : SharedSecretSpace * CiphertextSpace;
      var __a4__ : SharedSecretSpace * CiphertextSpace;
      var __a6__ : CiphertextSpace;
      var _r0 : bs_out;
      __a1__ <@ K.encaps(challenger_pk);
      __a4__ <- (__a1__.`1, __a1__.`2);
      __a6__ <- __a4__.`2;
      _r0 <@ F.evaluate(__a4__.`1, __a6__);
      return (_r0, __a6__);
    }
  }.

  module Step_0R_state_3 (K : K_c.Scheme, F : F_c.Scheme) = {
    var challenger_pk : PKeySpace
    var challenger_sk : SKeySpace
    proc initialize() : PKeySpace = {
      var __a0__ : PKeySpace * SKeySpace;
      __a0__ <@ K.keygen();
      challenger_pk <- __a0__.`1;
      challenger_sk <- __a0__.`2;
      return challenger_pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var __a1__ : SharedSecretSpace * CiphertextSpace;
      var __a6__ : CiphertextSpace;
      var _r0 : bs_out;
      __a1__ <@ K.encaps(challenger_pk);
      __a6__ <- __a1__.`2;
      _r0 <@ F.evaluate(__a1__.`1, __a6__);
      return (_r0, __a6__);
    }
  }.

  module Step_0R_state_4 (K : K_c.Scheme, F : F_c.Scheme) = {
    var challenger_pk : PKeySpace
    proc initialize() : PKeySpace = {
      var __a0__ : PKeySpace * SKeySpace;
      __a0__ <@ K.keygen();
      challenger_pk <- __a0__.`1;
      return challenger_pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var __a1__ : SharedSecretSpace * CiphertextSpace;
      var __a6__ : CiphertextSpace;
      var _r0 : bs_out;
      __a1__ <@ K.encaps(challenger_pk);
      __a6__ <- __a1__.`2;
      _r0 <@ F.evaluate(__a1__.`1, __a6__);
      return (_r0, __a6__);
    }
  }.

  module Step_0R_state_5 (K : K_c.Scheme, F : F_c.Scheme) = {
    var challenger_pk : PKeySpace
    proc initialize() : PKeySpace = {
      var __a0__ : PKeySpace * SKeySpace;
      __a0__ <@ K.keygen();
      challenger_pk <- __a0__.`1;
      return challenger_pk;
    }
    proc challenge() : bs_out * bs_in = {
      var __a1__ : bs_lambda * bs_in;
      var __a6__ : bs_in;
      var _r0 : bs_out;
      __a1__ <@ K.encaps(challenger_pk);
      __a6__ <- __a1__.`2;
      _r0 <@ F.evaluate(__a1__.`1, __a6__);
      return (_r0, __a6__);
    }
  }.

  module Step_0R_state_6 (K : K_c.Scheme, F : F_c.Scheme) = {
    var challenger_pk : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      var __a0__ : PKeySpace;
      _r0 <@ K.keygen();
      __a0__ <- _r0.`1;
      challenger_pk <- __a0__;
      return challenger_pk;
    }
    proc challenge() : bs_out * bs_in = {
      var __a1__ : bs_lambda * bs_in;
      var __a6__ : bs_in;
      var _r0 : bs_out;
      __a1__ <@ K.encaps(challenger_pk);
      __a6__ <- __a1__.`2;
      _r0 <@ F.evaluate(__a1__.`1, __a6__);
      return (_r0, __a6__);
    }
  }.

  module Step_0R_state_7 (K : K_c.Scheme, F : F_c.Scheme) = {
    var challenger_pk : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      challenger_pk <- _r0.`1;
      return challenger_pk;
    }
    proc challenge() : bs_out * bs_in = {
      var __a1__ : bs_lambda * bs_in;
      var __a6__ : bs_in;
      var _r0 : bs_out;
      __a1__ <@ K.encaps(challenger_pk);
      __a6__ <- __a1__.`2;
      _r0 <@ F.evaluate(__a1__.`1, __a6__);
      return (_r0, __a6__);
    }
  }.

  module Step_0R_state_8 (K : K_c.Scheme, F : F_c.Scheme) = {
    var challenger_pk : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      challenger_pk <- _r0.`1;
      return challenger_pk;
    }
    proc challenge() : bs_out * bs_in = {
      var v1 : bs_lambda * bs_in;
      var v2 : bs_in;
      var _r0 : bs_out;
      v1 <@ K.encaps(challenger_pk);
      v2 <- v1.`2;
      _r0 <@ F.evaluate(v1.`1, v2);
      return (_r0, v2);
    }
  }.

  module Step_0R_state_9 (K : K_c.Scheme, F : F_c.Scheme) = {
    var field1 : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      field1 <- _r0.`1;
      return field1;
    }
    proc challenge() : bs_out * bs_in = {
      var v1 : bs_lambda * bs_in;
      var v2 : bs_in;
      var _r0 : bs_out;
      v1 <@ K.encaps(field1);
      v2 <- v1.`2;
      _r0 <@ F.evaluate(v1.`1, v2);
      return (_r0, v2);
    }
  }.

  module Step_2L_state_0 (K : K_c.Scheme, F : F_c.Scheme) = {
    var challenger_pk : PKeySpace
    var challenger_sk : SKeySpace
    proc initialize() : PKeySpace = {
      var challenger_Initialize__tup0 : PKeySpace * SKeySpace;
      challenger_Initialize__tup0 <@ K.keygen();
      challenger_pk <- challenger_Initialize__tup0.`1;
      challenger_sk <- challenger_Initialize__tup0.`2;
      return challenger_pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var challenger_Challenge_rsp0 : SharedSecretSpace * CiphertextSpace;
      var challenger_Challenge_ss0 : SharedSecretSpace;
      var challenger_Challenge_ctxt0 : CiphertextSpace;
      var _tup : SharedSecretSpace * CiphertextSpace;
      var ss : SharedSecretSpace;
      var ct : CiphertextSpace;
      var _r0 : bs_out;
      challenger_Challenge_rsp0 <@ K.encaps(challenger_pk);
      challenger_Challenge_ss0 <$ dSharedSecretSpace;
      challenger_Challenge_ctxt0 <- challenger_Challenge_rsp0.`2;
      _tup <- (challenger_Challenge_ss0, challenger_Challenge_ctxt0);
      ss <- _tup.`1;
      ct <- _tup.`2;
      _r0 <@ F.evaluate(ss, ct);
      return (_r0, ct);
    }
  }.

  module Step_2L_state_1 (K : K_c.Scheme, F : F_c.Scheme) = {
    var challenger_pk : PKeySpace
    var challenger_sk : SKeySpace
    proc initialize() : PKeySpace = {
      var __a0__ : PKeySpace * SKeySpace;
      __a0__ <@ K.keygen();
      challenger_pk <- __a0__.`1;
      challenger_sk <- __a0__.`2;
      return challenger_pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var __a1__ : SharedSecretSpace * CiphertextSpace;
      var __a2__ : SharedSecretSpace;
      var __a3__ : CiphertextSpace;
      var __a4__ : SharedSecretSpace * CiphertextSpace;
      var __a5__ : SharedSecretSpace;
      var __a6__ : CiphertextSpace;
      var _r0 : bs_out;
      __a1__ <@ K.encaps(challenger_pk);
      __a2__ <$ dSharedSecretSpace;
      __a3__ <- __a1__.`2;
      __a4__ <- (__a2__, __a3__);
      __a5__ <- __a4__.`1;
      __a6__ <- __a4__.`2;
      _r0 <@ F.evaluate(__a5__, __a6__);
      return (_r0, __a6__);
    }
  }.

  module Step_2L_state_2 (K : K_c.Scheme, F : F_c.Scheme) = {
    var challenger_pk : PKeySpace
    var challenger_sk : SKeySpace
    proc initialize() : PKeySpace = {
      var __a0__ : PKeySpace * SKeySpace;
      __a0__ <@ K.keygen();
      challenger_pk <- __a0__.`1;
      challenger_sk <- __a0__.`2;
      return challenger_pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var __a2__ : SharedSecretSpace;
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var __a4__ : SharedSecretSpace * CiphertextSpace;
      var __a6__ : CiphertextSpace;
      var _r1 : bs_out;
      __a2__ <$ dSharedSecretSpace;
      _r0 <@ K.encaps(challenger_pk);
      __a4__ <- (__a2__, _r0.`2);
      __a6__ <- __a4__.`2;
      _r1 <@ F.evaluate(__a4__.`1, __a6__);
      return (_r1, __a6__);
    }
  }.

  module Step_2L_state_3 (K : K_c.Scheme, F : F_c.Scheme) = {
    var challenger_pk : PKeySpace
    var challenger_sk : SKeySpace
    proc initialize() : PKeySpace = {
      var __a0__ : PKeySpace * SKeySpace;
      __a0__ <@ K.keygen();
      challenger_pk <- __a0__.`1;
      challenger_sk <- __a0__.`2;
      return challenger_pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var __a2__ : SharedSecretSpace;
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var __a6__ : CiphertextSpace;
      var _r1 : bs_out;
      __a2__ <$ dSharedSecretSpace;
      _r0 <@ K.encaps(challenger_pk);
      __a6__ <- _r0.`2;
      _r1 <@ F.evaluate(__a2__, __a6__);
      return (_r1, __a6__);
    }
  }.

  module Step_2L_state_4 (K : K_c.Scheme, F : F_c.Scheme) = {
    var challenger_pk : PKeySpace
    proc initialize() : PKeySpace = {
      var __a0__ : PKeySpace * SKeySpace;
      __a0__ <@ K.keygen();
      challenger_pk <- __a0__.`1;
      return challenger_pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var __a2__ : SharedSecretSpace;
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var __a6__ : CiphertextSpace;
      var _r1 : bs_out;
      __a2__ <$ dSharedSecretSpace;
      _r0 <@ K.encaps(challenger_pk);
      __a6__ <- _r0.`2;
      _r1 <@ F.evaluate(__a2__, __a6__);
      return (_r1, __a6__);
    }
  }.

  module Step_2L_state_5 (K : K_c.Scheme, F : F_c.Scheme) = {
    var challenger_pk : PKeySpace
    proc initialize() : PKeySpace = {
      var __a0__ : PKeySpace * SKeySpace;
      __a0__ <@ K.keygen();
      challenger_pk <- __a0__.`1;
      return challenger_pk;
    }
    proc challenge() : bs_out * bs_in = {
      var __a2__ : bs_lambda;
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var __a6__ : bs_in;
      var _r1 : bs_out;
      __a2__ <$ dbs_lambda;
      _r0 <@ K.encaps(challenger_pk);
      __a6__ <- _r0.`2;
      _r1 <@ F.evaluate(__a2__, __a6__);
      return (_r1, __a6__);
    }
  }.

  module Step_2L_state_6 (K : K_c.Scheme, F : F_c.Scheme) = {
    var challenger_pk : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      var __a0__ : PKeySpace;
      _r0 <@ K.keygen();
      __a0__ <- _r0.`1;
      challenger_pk <- __a0__;
      return challenger_pk;
    }
    proc challenge() : bs_out * bs_in = {
      var __a2__ : bs_lambda;
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var __a6__ : bs_in;
      var _r1 : bs_out;
      __a2__ <$ dbs_lambda;
      _r0 <@ K.encaps(challenger_pk);
      __a6__ <- _r0.`2;
      _r1 <@ F.evaluate(__a2__, __a6__);
      return (_r1, __a6__);
    }
  }.

  module Step_2L_state_7 (K : K_c.Scheme, F : F_c.Scheme) = {
    var challenger_pk : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      challenger_pk <- _r0.`1;
      return challenger_pk;
    }
    proc challenge() : bs_out * bs_in = {
      var __a2__ : bs_lambda;
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var __a6__ : bs_in;
      var _r1 : bs_out;
      __a2__ <$ dbs_lambda;
      _r0 <@ K.encaps(challenger_pk);
      __a6__ <- _r0.`2;
      _r1 <@ F.evaluate(__a2__, __a6__);
      return (_r1, __a6__);
    }
  }.

  module Step_2L_state_8 (K : K_c.Scheme, F : F_c.Scheme) = {
    var challenger_pk : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      challenger_pk <- _r0.`1;
      return challenger_pk;
    }
    proc challenge() : bs_out * bs_in = {
      var v1 : bs_lambda;
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var v2 : bs_in;
      var _r1 : bs_out;
      v1 <$ dbs_lambda;
      _r0 <@ K.encaps(challenger_pk);
      v2 <- _r0.`2;
      _r1 <@ F.evaluate(v1, v2);
      return (_r1, v2);
    }
  }.

  module Step_2L_state_9 (K : K_c.Scheme, F : F_c.Scheme) = {
    var field1 : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      field1 <- _r0.`1;
      return field1;
    }
    proc challenge() : bs_out * bs_in = {
      var v1 : bs_lambda;
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var v2 : bs_in;
      var _r1 : bs_out;
      v1 <$ dbs_lambda;
      _r0 <@ K.encaps(field1);
      v2 <- _r0.`2;
      _r1 <@ F.evaluate(v1, v2);
      return (_r1, v2);
    }
  }.

  module Step_2L_state_10 (K : K_c.Scheme, F : F_c.Scheme) = {
    var field1 : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      field1 <- _r0.`1;
      return field1;
    }
    proc challenge() : bs_out * bs_in = {
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var v2 : bs_in;
      var v1 : bs_lambda;
      var _r1 : bs_out;
      _r0 <@ K.encaps(field1);
      v2 <- _r0.`2;
      v1 <$ dbs_lambda;
      _r1 <@ F.evaluate(v1, v2);
      return (_r1, v2);
    }
  }.

  module Step_2L_state_11 (K : K_c.Scheme, F : F_c.Scheme) = {
    var field1 : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      field1 <- _r0.`1;
      return field1;
    }
    proc challenge() : bs_out * bs_in = {
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var v1 : bs_in;
      var v2 : bs_lambda;
      var _r1 : bs_out;
      _r0 <@ K.encaps(field1);
      v1 <- _r0.`2;
      v2 <$ dbs_lambda;
      _r1 <@ F.evaluate(v2, v1);
      return (_r1, v1);
    }
  }.

  module Step_2R_state_0 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var k : PKeySpace * SKeySpace;
      k <@ K.keygen();
      pk <- k.`1;
      return pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var key : bs_lambda;
      var rsp : SharedSecretSpace * CiphertextSpace;
      var ct : CiphertextSpace;
      var _r0 : bs_out;
      key <$ dbs_lambda;
      rsp <@ K.encaps(pk);
      ct <- rsp.`2;
      _r0 <@ F.evaluate(key, ct);
      return (_r0, ct);
    }
  }.

  module Step_2R_state_1 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var __a0__ : PKeySpace * SKeySpace;
      __a0__ <@ K.keygen();
      pk <- __a0__.`1;
      return pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var __a1__ : bs_lambda;
      var __a2__ : SharedSecretSpace * CiphertextSpace;
      var __a3__ : CiphertextSpace;
      var _r0 : bs_out;
      __a1__ <$ dbs_lambda;
      __a2__ <@ K.encaps(pk);
      __a3__ <- __a2__.`2;
      _r0 <@ F.evaluate(__a1__, __a3__);
      return (_r0, __a3__);
    }
  }.

  module Step_2R_state_2 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      pk <- _r0.`1;
      return pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var __a1__ : bs_lambda;
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var __a3__ : CiphertextSpace;
      var _r1 : bs_out;
      __a1__ <$ dbs_lambda;
      _r0 <@ K.encaps(pk);
      __a3__ <- _r0.`2;
      _r1 <@ F.evaluate(__a1__, __a3__);
      return (_r1, __a3__);
    }
  }.

  module Step_2R_state_3 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      pk <- _r0.`1;
      return pk;
    }
    proc challenge() : bs_out * bs_in = {
      var __a1__ : bs_lambda;
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var __a3__ : bs_in;
      var _r1 : bs_out;
      __a1__ <$ dbs_lambda;
      _r0 <@ K.encaps(pk);
      __a3__ <- _r0.`2;
      _r1 <@ F.evaluate(__a1__, __a3__);
      return (_r1, __a3__);
    }
  }.

  module Step_2R_state_4 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      pk <- _r0.`1;
      return pk;
    }
    proc challenge() : bs_out * bs_in = {
      var v1 : bs_lambda;
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var v2 : bs_in;
      var _r1 : bs_out;
      v1 <$ dbs_lambda;
      _r0 <@ K.encaps(pk);
      v2 <- _r0.`2;
      _r1 <@ F.evaluate(v1, v2);
      return (_r1, v2);
    }
  }.

  module Step_2R_state_5 (K : K_c.Scheme, F : F_c.Scheme) = {
    var field1 : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      field1 <- _r0.`1;
      return field1;
    }
    proc challenge() : bs_out * bs_in = {
      var v1 : bs_lambda;
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var v2 : bs_in;
      var _r1 : bs_out;
      v1 <$ dbs_lambda;
      _r0 <@ K.encaps(field1);
      v2 <- _r0.`2;
      _r1 <@ F.evaluate(v1, v2);
      return (_r1, v2);
    }
  }.

  module Step_2R_state_6 (K : K_c.Scheme, F : F_c.Scheme) = {
    var field1 : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      field1 <- _r0.`1;
      return field1;
    }
    proc challenge() : bs_out * bs_in = {
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var v2 : bs_in;
      var v1 : bs_lambda;
      var _r1 : bs_out;
      _r0 <@ K.encaps(field1);
      v2 <- _r0.`2;
      v1 <$ dbs_lambda;
      _r1 <@ F.evaluate(v1, v2);
      return (_r1, v2);
    }
  }.

  module Step_2R_state_7 (K : K_c.Scheme, F : F_c.Scheme) = {
    var field1 : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      field1 <- _r0.`1;
      return field1;
    }
    proc challenge() : bs_out * bs_in = {
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var v1 : bs_in;
      var v2 : bs_lambda;
      var _r1 : bs_out;
      _r0 <@ K.encaps(field1);
      v1 <- _r0.`2;
      v2 <$ dbs_lambda;
      _r1 <@ F.evaluate(v2, v1);
      return (_r1, v1);
    }
  }.

  module Step_3L_state_0 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var k : PKeySpace * SKeySpace;
      k <@ K.keygen();
      pk <- k.`1;
      return pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var key : bs_lambda;
      var rsp : SharedSecretSpace * CiphertextSpace;
      var ct : CiphertextSpace;
      var _r0 : bs_out;
      key <$ dbs_lambda;
      rsp <@ K.encaps(pk);
      ct <- rsp.`2;
      _r0 <@ F.evaluate(key, ct);
      return (_r0, ct);
    }
  }.

  module Step_3L_state_1 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var __a0__ : PKeySpace * SKeySpace;
      __a0__ <@ K.keygen();
      pk <- __a0__.`1;
      return pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var __a1__ : bs_lambda;
      var __a2__ : SharedSecretSpace * CiphertextSpace;
      var __a3__ : CiphertextSpace;
      var _r0 : bs_out;
      __a1__ <$ dbs_lambda;
      __a2__ <@ K.encaps(pk);
      __a3__ <- __a2__.`2;
      _r0 <@ F.evaluate(__a1__, __a3__);
      return (_r0, __a3__);
    }
  }.

  module Step_3L_state_2 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      pk <- _r0.`1;
      return pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var __a1__ : bs_lambda;
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var __a3__ : CiphertextSpace;
      var _r1 : bs_out;
      __a1__ <$ dbs_lambda;
      _r0 <@ K.encaps(pk);
      __a3__ <- _r0.`2;
      _r1 <@ F.evaluate(__a1__, __a3__);
      return (_r1, __a3__);
    }
  }.

  module Step_3L_state_3 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      pk <- _r0.`1;
      return pk;
    }
    proc challenge() : bs_out * bs_in = {
      var __a1__ : bs_lambda;
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var __a3__ : bs_in;
      var _r1 : bs_out;
      __a1__ <$ dbs_lambda;
      _r0 <@ K.encaps(pk);
      __a3__ <- _r0.`2;
      _r1 <@ F.evaluate(__a1__, __a3__);
      return (_r1, __a3__);
    }
  }.

  module Step_3L_state_4 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      pk <- _r0.`1;
      return pk;
    }
    proc challenge() : bs_out * bs_in = {
      var v1 : bs_lambda;
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var v2 : bs_in;
      var _r1 : bs_out;
      v1 <$ dbs_lambda;
      _r0 <@ K.encaps(pk);
      v2 <- _r0.`2;
      _r1 <@ F.evaluate(v1, v2);
      return (_r1, v2);
    }
  }.

  module Step_3L_state_5 (K : K_c.Scheme, F : F_c.Scheme) = {
    var field1 : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      field1 <- _r0.`1;
      return field1;
    }
    proc challenge() : bs_out * bs_in = {
      var v1 : bs_lambda;
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var v2 : bs_in;
      var _r1 : bs_out;
      v1 <$ dbs_lambda;
      _r0 <@ K.encaps(field1);
      v2 <- _r0.`2;
      _r1 <@ F.evaluate(v1, v2);
      return (_r1, v2);
    }
  }.

  module Step_3L_state_6 (K : K_c.Scheme, F : F_c.Scheme) = {
    var field1 : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      field1 <- _r0.`1;
      return field1;
    }
    proc challenge() : bs_out * bs_in = {
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var v2 : bs_in;
      var v1 : bs_lambda;
      var _r1 : bs_out;
      _r0 <@ K.encaps(field1);
      v2 <- _r0.`2;
      v1 <$ dbs_lambda;
      _r1 <@ F.evaluate(v1, v2);
      return (_r1, v2);
    }
  }.

  module Step_3L_state_7 (K : K_c.Scheme, F : F_c.Scheme) = {
    var field1 : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      field1 <- _r0.`1;
      return field1;
    }
    proc challenge() : bs_out * bs_in = {
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var v1 : bs_in;
      var v2 : bs_lambda;
      var _r1 : bs_out;
      _r0 <@ K.encaps(field1);
      v1 <- _r0.`2;
      v2 <$ dbs_lambda;
      _r1 <@ F.evaluate(v2, v1);
      return (_r1, v1);
    }
  }.

  module Step_3R_state_0 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var k : PKeySpace * SKeySpace;
      k <@ K.keygen();
      pk <- k.`1;
      return pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var rsp : SharedSecretSpace * CiphertextSpace;
      var ct : CiphertextSpace;
      var challenger_Lookup_k2 : bs_lambda;
      var ss : bs_out;
      rsp <@ K.encaps(pk);
      ct <- rsp.`2;
      challenger_Lookup_k2 <$ dbs_lambda;
      ss <@ F.evaluate(challenger_Lookup_k2, ct);
      return (ss, ct);
    }
  }.

  module Step_3R_state_1 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var __a0__ : PKeySpace * SKeySpace;
      __a0__ <@ K.keygen();
      pk <- __a0__.`1;
      return pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var __a1__ : SharedSecretSpace * CiphertextSpace;
      var __a2__ : CiphertextSpace;
      var __a3__ : bs_lambda;
      var __a4__ : bs_out;
      __a1__ <@ K.encaps(pk);
      __a2__ <- __a1__.`2;
      __a3__ <$ dbs_lambda;
      __a4__ <@ F.evaluate(__a3__, __a2__);
      return (__a4__, __a2__);
    }
  }.

  module Step_3R_state_2 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      pk <- _r0.`1;
      return pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var __a2__ : CiphertextSpace;
      var __a3__ : bs_lambda;
      var _r1 : bs_out;
      _r0 <@ K.encaps(pk);
      __a2__ <- _r0.`2;
      __a3__ <$ dbs_lambda;
      _r1 <@ F.evaluate(__a3__, __a2__);
      return (_r1, __a2__);
    }
  }.

  module Step_3R_state_3 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      pk <- _r0.`1;
      return pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var __a3__ : bs_lambda;
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var __a2__ : CiphertextSpace;
      var _r1 : bs_out;
      __a3__ <$ dbs_lambda;
      _r0 <@ K.encaps(pk);
      __a2__ <- _r0.`2;
      _r1 <@ F.evaluate(__a3__, __a2__);
      return (_r1, __a2__);
    }
  }.

  module Step_3R_state_4 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      pk <- _r0.`1;
      return pk;
    }
    proc challenge() : bs_out * bs_in = {
      var __a3__ : bs_lambda;
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var __a2__ : bs_in;
      var _r1 : bs_out;
      __a3__ <$ dbs_lambda;
      _r0 <@ K.encaps(pk);
      __a2__ <- _r0.`2;
      _r1 <@ F.evaluate(__a3__, __a2__);
      return (_r1, __a2__);
    }
  }.

  module Step_3R_state_5 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      pk <- _r0.`1;
      return pk;
    }
    proc challenge() : bs_out * bs_in = {
      var v1 : bs_lambda;
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var v2 : bs_in;
      var _r1 : bs_out;
      v1 <$ dbs_lambda;
      _r0 <@ K.encaps(pk);
      v2 <- _r0.`2;
      _r1 <@ F.evaluate(v1, v2);
      return (_r1, v2);
    }
  }.

  module Step_3R_state_6 (K : K_c.Scheme, F : F_c.Scheme) = {
    var field1 : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      field1 <- _r0.`1;
      return field1;
    }
    proc challenge() : bs_out * bs_in = {
      var v1 : bs_lambda;
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var v2 : bs_in;
      var _r1 : bs_out;
      v1 <$ dbs_lambda;
      _r0 <@ K.encaps(field1);
      v2 <- _r0.`2;
      _r1 <@ F.evaluate(v1, v2);
      return (_r1, v2);
    }
  }.

  module Step_3R_state_7 (K : K_c.Scheme, F : F_c.Scheme) = {
    var field1 : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      field1 <- _r0.`1;
      return field1;
    }
    proc challenge() : bs_out * bs_in = {
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var v2 : bs_in;
      var v1 : bs_lambda;
      var _r1 : bs_out;
      _r0 <@ K.encaps(field1);
      v2 <- _r0.`2;
      v1 <$ dbs_lambda;
      _r1 <@ F.evaluate(v1, v2);
      return (_r1, v2);
    }
  }.

  module Step_3R_state_8 (K : K_c.Scheme, F : F_c.Scheme) = {
    var field1 : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      field1 <- _r0.`1;
      return field1;
    }
    proc challenge() : bs_out * bs_in = {
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var v1 : bs_in;
      var v2 : bs_lambda;
      var _r1 : bs_out;
      _r0 <@ K.encaps(field1);
      v1 <- _r0.`2;
      v2 <$ dbs_lambda;
      _r1 <@ F.evaluate(v2, v1);
      return (_r1, v1);
    }
  }.

  module Step_5L_state_0 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var k : PKeySpace * SKeySpace;
      k <@ K.keygen();
      pk <- k.`1;
      return pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var rsp : SharedSecretSpace * CiphertextSpace;
      var ct : CiphertextSpace;
      var challenger_Lookup_r2 : bs_out;
      var ss : bs_out;
      rsp <@ K.encaps(pk);
      ct <- rsp.`2;
      challenger_Lookup_r2 <$ dbs_out;
      ss <- challenger_Lookup_r2;
      return (ss, ct);
    }
  }.

  module Step_5L_state_1 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var __a0__ : PKeySpace * SKeySpace;
      __a0__ <@ K.keygen();
      pk <- __a0__.`1;
      return pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var __a1__ : SharedSecretSpace * CiphertextSpace;
      var __a2__ : CiphertextSpace;
      var __a3__ : bs_out;
      var __a4__ : bs_out;
      __a1__ <@ K.encaps(pk);
      __a2__ <- __a1__.`2;
      __a3__ <$ dbs_out;
      __a4__ <- __a3__;
      return (__a4__, __a2__);
    }
  }.

  module Step_5L_state_2 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var __a0__ : PKeySpace * SKeySpace;
      __a0__ <@ K.keygen();
      pk <- __a0__.`1;
      return pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var __a1__ : SharedSecretSpace * CiphertextSpace;
      var __a2__ : CiphertextSpace;
      var __a3__ : bs_out;
      __a1__ <@ K.encaps(pk);
      __a2__ <- __a1__.`2;
      __a3__ <$ dbs_out;
      return (__a3__, __a2__);
    }
  }.

  module Step_5L_state_3 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      pk <- _r0.`1;
      return pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var __a3__ : bs_out;
      var _r0 : SharedSecretSpace * CiphertextSpace;
      __a3__ <$ dbs_out;
      _r0 <@ K.encaps(pk);
      return (__a3__, _r0.`2);
    }
  }.

  module Step_5L_state_4 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      pk <- _r0.`1;
      return pk;
    }
    proc challenge() : bs_out * bs_in = {
      var __a3__ : bs_out;
      var _r0 : SharedSecretSpace * CiphertextSpace;
      __a3__ <$ dbs_out;
      _r0 <@ K.encaps(pk);
      return (__a3__, _r0.`2);
    }
  }.

  module Step_5L_state_5 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      pk <- _r0.`1;
      return pk;
    }
    proc challenge() : bs_out * bs_in = {
      var v1 : bs_out;
      var _r0 : SharedSecretSpace * CiphertextSpace;
      v1 <$ dbs_out;
      _r0 <@ K.encaps(pk);
      return (v1, _r0.`2);
    }
  }.

  module Step_5L_state_6 (K : K_c.Scheme, F : F_c.Scheme) = {
    var field1 : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      field1 <- _r0.`1;
      return field1;
    }
    proc challenge() : bs_out * bs_in = {
      var v1 : bs_out;
      var _r0 : SharedSecretSpace * CiphertextSpace;
      v1 <$ dbs_out;
      _r0 <@ K.encaps(field1);
      return (v1, _r0.`2);
    }
  }.

  module Step_5R_state_0 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    var sk : SKeySpace
    proc initialize() : PKeySpace = {
      var _tup : PKeySpace * SKeySpace;
      _tup <@ K.keygen();
      pk <- _tup.`1;
      sk <- _tup.`2;
      return pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var v_KF_Encaps_x0 : SharedSecretSpace * CiphertextSpace;
      var v_KF_Encaps_k0 : bs_lambda;
      var v_KF_Encaps_c0 : CiphertextSpace;
      var v_KF_Encaps_ss0 : bs_out;
      var rsp : bs_out * CiphertextSpace;
      var ss : bs_out;
      var ctxt : CiphertextSpace;
      v_KF_Encaps_x0 <@ K.encaps(pk);
      v_KF_Encaps_k0 <- v_KF_Encaps_x0.`1;
      v_KF_Encaps_c0 <- v_KF_Encaps_x0.`2;
      v_KF_Encaps_ss0 <@ F.evaluate(v_KF_Encaps_k0, v_KF_Encaps_c0);
      rsp <- (v_KF_Encaps_ss0, v_KF_Encaps_c0);
      ss <$ dbs_out;
      ctxt <- rsp.`2;
      return (ss, ctxt);
    }
  }.

  module Step_5R_state_1 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    var sk : SKeySpace
    proc initialize() : PKeySpace = {
      var __a0__ : PKeySpace * SKeySpace;
      __a0__ <@ K.keygen();
      pk <- __a0__.`1;
      sk <- __a0__.`2;
      return pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var __a1__ : SharedSecretSpace * CiphertextSpace;
      var __a2__ : bs_lambda;
      var __a3__ : CiphertextSpace;
      var __a4__ : bs_out;
      var __a5__ : bs_out * CiphertextSpace;
      var __a6__ : bs_out;
      var __a7__ : CiphertextSpace;
      __a1__ <@ K.encaps(pk);
      __a2__ <- __a1__.`1;
      __a3__ <- __a1__.`2;
      __a4__ <@ F.evaluate(__a2__, __a3__);
      __a5__ <- (__a4__, __a3__);
      __a6__ <$ dbs_out;
      __a7__ <- __a5__.`2;
      return (__a6__, __a7__);
    }
  }.

  module Step_5R_state_2 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    var sk : SKeySpace
    proc initialize() : PKeySpace = {
      var __a0__ : PKeySpace * SKeySpace;
      __a0__ <@ K.keygen();
      pk <- __a0__.`1;
      sk <- __a0__.`2;
      return pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var __a1__ : SharedSecretSpace * CiphertextSpace;
      var __a3__ : CiphertextSpace;
      var _r0 : bs_out;
      var __a5__ : bs_out * CiphertextSpace;
      var __a6__ : bs_out;
      __a1__ <@ K.encaps(pk);
      __a3__ <- __a1__.`2;
      _r0 <@ F.evaluate(__a1__.`1, __a3__);
      __a5__ <- (_r0, __a3__);
      __a6__ <$ dbs_out;
      return (__a6__, __a5__.`2);
    }
  }.

  module Step_5R_state_3 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    var sk : SKeySpace
    proc initialize() : PKeySpace = {
      var __a0__ : PKeySpace * SKeySpace;
      __a0__ <@ K.keygen();
      pk <- __a0__.`1;
      sk <- __a0__.`2;
      return pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var __a6__ : bs_out;
      var __a1__ : SharedSecretSpace * CiphertextSpace;
      var __a3__ : CiphertextSpace;
      var _r0 : bs_out;
      var __a5__ : bs_out * CiphertextSpace;
      __a6__ <$ dbs_out;
      __a1__ <@ K.encaps(pk);
      __a3__ <- __a1__.`2;
      _r0 <@ F.evaluate(__a1__.`1, __a3__);
      __a5__ <- (_r0, __a3__);
      return (__a6__, __a5__.`2);
    }
  }.

  module Step_5R_state_4 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    var sk : SKeySpace
    proc initialize() : PKeySpace = {
      var __a0__ : PKeySpace * SKeySpace;
      __a0__ <@ K.keygen();
      pk <- __a0__.`1;
      sk <- __a0__.`2;
      return pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var __a6__ : bs_out;
      var __a1__ : SharedSecretSpace * CiphertextSpace;
      var __a3__ : CiphertextSpace;
      __a6__ <$ dbs_out;
      __a1__ <@ K.encaps(pk);
      __a3__ <- __a1__.`2;
      return (__a6__, __a3__);
    }
  }.

  module Step_5R_state_5 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var __a0__ : PKeySpace * SKeySpace;
      __a0__ <@ K.keygen();
      pk <- __a0__.`1;
      return pk;
    }
    proc challenge() : bs_out * CiphertextSpace = {
      var __a6__ : bs_out;
      var __a1__ : SharedSecretSpace * CiphertextSpace;
      var __a3__ : CiphertextSpace;
      __a6__ <$ dbs_out;
      __a1__ <@ K.encaps(pk);
      __a3__ <- __a1__.`2;
      return (__a6__, __a3__);
    }
  }.

  module Step_5R_state_6 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var __a0__ : PKeySpace * SKeySpace;
      __a0__ <@ K.keygen();
      pk <- __a0__.`1;
      return pk;
    }
    proc challenge() : bs_out * bs_in = {
      var __a6__ : bs_out;
      var __a1__ : bs_lambda * bs_in;
      var __a3__ : bs_in;
      __a6__ <$ dbs_out;
      __a1__ <@ K.encaps(pk);
      __a3__ <- __a1__.`2;
      return (__a6__, __a3__);
    }
  }.

  module Step_5R_state_7 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      var __a0__ : PKeySpace;
      _r0 <@ K.keygen();
      __a0__ <- _r0.`1;
      pk <- __a0__;
      return pk;
    }
    proc challenge() : bs_out * bs_in = {
      var __a6__ : bs_out;
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var __a1__ : bs_in;
      var __a3__ : bs_in;
      __a6__ <$ dbs_out;
      _r0 <@ K.encaps(pk);
      __a1__ <- _r0.`2;
      __a3__ <- __a1__;
      return (__a6__, __a3__);
    }
  }.

  module Step_5R_state_8 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      pk <- _r0.`1;
      return pk;
    }
    proc challenge() : bs_out * bs_in = {
      var __a6__ : bs_out;
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var __a1__ : bs_in;
      var __a3__ : bs_in;
      __a6__ <$ dbs_out;
      _r0 <@ K.encaps(pk);
      __a1__ <- _r0.`2;
      __a3__ <- __a1__;
      return (__a6__, __a3__);
    }
  }.

  module Step_5R_state_9 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      pk <- _r0.`1;
      return pk;
    }
    proc challenge() : bs_out * bs_in = {
      var __a6__ : bs_out;
      var _r0 : SharedSecretSpace * CiphertextSpace;
      var __a1__ : bs_in;
      __a6__ <$ dbs_out;
      _r0 <@ K.encaps(pk);
      __a1__ <- _r0.`2;
      return (__a6__, __a1__);
    }
  }.

  module Step_5R_state_10 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      pk <- _r0.`1;
      return pk;
    }
    proc challenge() : bs_out * bs_in = {
      var __a6__ : bs_out;
      var _r0 : SharedSecretSpace * CiphertextSpace;
      __a6__ <$ dbs_out;
      _r0 <@ K.encaps(pk);
      return (__a6__, _r0.`2);
    }
  }.

  module Step_5R_state_11 (K : K_c.Scheme, F : F_c.Scheme) = {
    var pk : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      pk <- _r0.`1;
      return pk;
    }
    proc challenge() : bs_out * bs_in = {
      var v1 : bs_out;
      var _r0 : SharedSecretSpace * CiphertextSpace;
      v1 <$ dbs_out;
      _r0 <@ K.encaps(pk);
      return (v1, _r0.`2);
    }
  }.

  module Step_5R_state_12 (K : K_c.Scheme, F : F_c.Scheme) = {
    var field1 : PKeySpace
    proc initialize() : PKeySpace = {
      var _r0 : PKeySpace * SKeySpace;
      _r0 <@ K.keygen();
      field1 <- _r0.`1;
      return field1;
    }
    proc challenge() : bs_out * bs_in = {
      var v1 : bs_out;
      var _r0 : SharedSecretSpace * CiphertextSpace;
      v1 <$ dbs_out;
      _r0 <@ K.encaps(field1);
      return (v1, _r0.`2);
    }
  }.

  declare module K <: K_c.Scheme {-G_RandKey, -KF_c.KEM_INDCPA_MultiChal_Random, -KF_c.KEM_INDCPA_MultiChal_Real, -K_c.KEM_INDCPA_MultiChal_Random, -K_c.KEM_INDCPA_MultiChal_Real, -R_MultiPRF}.

  declare module F <: F_c.Scheme {-K, -G_RandKey, -KF_c.KEM_INDCPA_MultiChal_Random, -KF_c.KEM_INDCPA_MultiChal_Real, -K_c.KEM_INDCPA_MultiChal_Random, -K_c.KEM_INDCPA_MultiChal_Real, -R_MultiPRF}.

  (* ===== Deterministic-method specs ===== *)

  declare axiom K_decaps_det (g : (glob K)) (a0 : SKeySpace) (a1 : CiphertextSpace) : phoare[ K.decaps : (glob K) = g /\ sk = a0 /\ m = a1 ==> (glob K) = g /\ res = K_c.ev_decaps a0 a1 ] = 1%r.

  declare axiom F_evaluate_det (g : (glob F)) (a0 : bs_lambda) (a1 : bs_in) : phoare[ F.evaluate : (glob F) = g /\ seed = a0 /\ input = a1 ==> (glob F) = g /\ res = F_c.ev_evaluate a0 a1 ] = 1%r.

  (* ===== Per-hop equivalence lemmas ===== *)

  lemma hop_0_initialize :
    equiv [ KF_c.KEM_INDCPA_MultiChal_Real(KEMPRF(K, F)).initialize ~ R_KEM(K, F, KEMPRF(K, F), K_c.KEM_INDCPA_MultiChal_Real(K)).initialize :
            ={glob K} /\ ={glob F} ==> ={res} /\ ={glob K} /\ ={glob F} /\ KF_c.KEM_INDCPA_MultiChal_Real.pk{1} = K_c.KEM_INDCPA_MultiChal_Real.pk{2} ].
  proof.
    (* resolution: synth-static *)
    proc; inline *; sim.
    qed.

  lemma hop_0_challenge :
    equiv [ KF_c.KEM_INDCPA_MultiChal_Real(KEMPRF(K, F)).challenge ~ R_KEM(K, F, KEMPRF(K, F), K_c.KEM_INDCPA_MultiChal_Real(K)).challenge :
            ={glob K} /\ ={glob F} /\ KF_c.KEM_INDCPA_MultiChal_Real.pk{1} = K_c.KEM_INDCPA_MultiChal_Real.pk{2} ==> ={res} /\ ={glob K} /\ ={glob F} /\ KF_c.KEM_INDCPA_MultiChal_Real.pk{1} = K_c.KEM_INDCPA_MultiChal_Real.pk{2} ].
  proof.
    (* resolution: cached-guided *)
    proc. inline *. sp. wp.
    seq 1 1 : (={glob K, glob F} /\ x{1} = _tup0{2} /\ KF_c.KEM_INDCPA_MultiChal_Real.pk{1} = K_c.KEM_INDCPA_MultiChal_Real.pk{2}).
    + sim.
    sp. wp.
    exists* (glob F){1}, k{1}, c{1}; elim* => gf1 kv cv.
    call{1} (F_evaluate_det gf1 kv cv).
    exists* (glob F){2}, ss{2}, ct{2}; elim* => gf2 ssv ctv.
    call{2} (F_evaluate_det gf2 ssv ctv).
    skip => /#.
    qed.

  lemma hop_2_initialize :
    equiv [ R_KEM(K, F, KEMPRF(K, F), K_c.KEM_INDCPA_MultiChal_Random(K)).initialize ~ G_RandKey(K, F).initialize :
            ={glob K} /\ ={glob F} ==> ={res} /\ ={glob K} /\ ={glob F} /\ K_c.KEM_INDCPA_MultiChal_Random.pk{1} = G_RandKey.pk{2} ].
  proof.
    (* resolution: synth-static *)
    proc; inline *; sim.
    qed.

  lemma hop_2_challenge :
    equiv [ R_KEM(K, F, KEMPRF(K, F), K_c.KEM_INDCPA_MultiChal_Random(K)).challenge ~ G_RandKey(K, F).challenge :
            ={glob K} /\ ={glob F} /\ K_c.KEM_INDCPA_MultiChal_Random.pk{1} = G_RandKey.pk{2} ==> ={res} /\ ={glob K} /\ ={glob F} /\ K_c.KEM_INDCPA_MultiChal_Random.pk{1} = G_RandKey.pk{2} ].
  proof.
    (* resolution: cached-guided *)
    proc. inline *.
    have eqd : dSharedSecretSpace = dbs_lambda
      by apply eq_funi_ll; [ apply dSharedSecretSpace_fu | apply dSharedSecretSpace_ll
                           | apply dbs_lambda_fu | apply dbs_lambda_ll ].
    swap{2} 1 1.
    seq 1 1 : (={glob K, glob F} /\ rsp{1} = rsp{2} /\ K_c.KEM_INDCPA_MultiChal_Random.pk{1} = G_RandKey.pk{2}).
    + sim.
    seq 1 1 : (={glob K, glob F} /\ rsp{1} = rsp{2} /\ ss0{1} = key{2} /\ K_c.KEM_INDCPA_MultiChal_Random.pk{1} = G_RandKey.pk{2}).
    + rnd (fun (x : SharedSecretSpace) => x) (fun (x : SharedSecretSpace) => x).
      skip => />. rewrite eqd. done.
    sp. wp.
    exists* (glob F){1}, ss{1}, ct{1}; elim* => gf1 a0 a1.
    call{1} (F_evaluate_det gf1 a0 a1).
    exists* (glob F){2}, key{2}, ct{2}; elim* => gf2 b0 b1.
    call{2} (F_evaluate_det gf2 b0 b1).
    skip => /#.
    qed.

  lemma hop_3_initialize :
    equiv [ G_RandKey(K, F).initialize ~ R_MultiPRF(K, F, KEMPRF(K, F), F_c.PRFSecurity_MultiKey_Real(F)).initialize :
            ={glob K} /\ ={glob F} ==> ={res} /\ ={glob K} /\ ={glob F} /\ G_RandKey.pk{1} = R_MultiPRF.pk{2} ].
  proof.
    (* resolution: synth-static *)
    proc; inline *; sim.
    qed.

  lemma hop_3_challenge :
    equiv [ G_RandKey(K, F).challenge ~ R_MultiPRF(K, F, KEMPRF(K, F), F_c.PRFSecurity_MultiKey_Real(F)).challenge :
            ={glob K} /\ ={glob F} /\ G_RandKey.pk{1} = R_MultiPRF.pk{2} ==> ={res} /\ ={glob K} /\ ={glob F} /\ G_RandKey.pk{1} = R_MultiPRF.pk{2} ].
  proof.
    (* resolution: cached-guided *)
    proc. inline *.
    swap{1} 1 2.
    seq 1 1 : (={glob K, glob F} /\ rsp{1} = rsp{2} /\ G_RandKey.pk{1} = R_MultiPRF.pk{2}).
    + sim.
    sp. wp.
    seq 1 1 : (={glob K, glob F} /\ rsp{1} = rsp{2} /\ ct{1} = ct{2} /\ x{2} = ct{2} /\ key{1} = k{2} /\ G_RandKey.pk{1} = R_MultiPRF.pk{2}).
    + rnd. skip => />.
    exists* (glob F){1}, key{1}, ct{1}; elim* => gf1 a0 a1.
    call{1} (F_evaluate_det gf1 a0 a1).
    exists* (glob F){2}, k{2}, x{2}; elim* => gf2 b0 b1.
    call{2} (F_evaluate_det gf2 b0 b1).
    skip => /#.
    qed.

  lemma hop_5_initialize :
    equiv [ R_MultiPRF(K, F, KEMPRF(K, F), F_c.PRFSecurity_MultiKey_Random(F)).initialize ~ KF_c.KEM_INDCPA_MultiChal_Random(KEMPRF(K, F)).initialize :
            ={glob K} /\ ={glob F} ==> ={res} /\ ={glob K} /\ ={glob F} /\ R_MultiPRF.pk{1} = KF_c.KEM_INDCPA_MultiChal_Random.pk{2} ].
  proof.
    (* resolution: synth-static *)
    proc; inline *; sim.
    qed.

  lemma hop_5_challenge :
    equiv [ R_MultiPRF(K, F, KEMPRF(K, F), F_c.PRFSecurity_MultiKey_Random(F)).challenge ~ KF_c.KEM_INDCPA_MultiChal_Random(KEMPRF(K, F)).challenge :
            ={glob K} /\ ={glob F} /\ R_MultiPRF.pk{1} = KF_c.KEM_INDCPA_MultiChal_Random.pk{2} ==> ={res} /\ ={glob K} /\ ={glob F} /\ R_MultiPRF.pk{1} = KF_c.KEM_INDCPA_MultiChal_Random.pk{2} ].
  proof.
    (* resolution: cached-guided *)
    proc. inline *.
    sp.
    seq 1 1 : (={glob K, glob F} /\ rsp{1} = x{2} /\ R_MultiPRF.pk{1} = KF_c.KEM_INDCPA_MultiChal_Random.pk{2}).
    + sim.
    sp.
    seq 0 1 : (={glob K, glob F} /\ rsp{1} = x{2} /\ ct{1} = x{2}.`2 /\ c{2} = x{2}.`2 /\ R_MultiPRF.pk{1} = KF_c.KEM_INDCPA_MultiChal_Random.pk{2}).
    + exists* (glob F){2}, k{2}, c{2}; elim* => gf k0 c0.
      call{2} (F_evaluate_det gf k0 c0).
      skip => /#.
    wp. rnd. wp. skip => /#.
    qed.

  (* ===== Per-hop probability lemmas ===== *)

  (* Hop 0: interchangeability. The two adjacent games are equivalent (no advantage). *)

  lemma hop_0_pr (A <: KF_c.KEM_INDCPA_MultiChal_Adv {-K, -F, -G_RandKey, -KF_c.KEM_INDCPA_MultiChal_Random, -KF_c.KEM_INDCPA_MultiChal_Real, -K_c.KEM_INDCPA_MultiChal_Random, -K_c.KEM_INDCPA_MultiChal_Real, -R_MultiPRF}) &m :
    Pr[Game_step_0(K, F, A).main() @ &m : res] = Pr[Game_step_1(K, F, A).main() @ &m : res].
  proof.
    byequiv (_: ={glob A, glob K, glob F} ==> ={res}) => //.
    proc.
    call (_: ={glob K} /\ ={glob F} /\ KF_c.KEM_INDCPA_MultiChal_Real.pk{1} = K_c.KEM_INDCPA_MultiChal_Real.pk{2}).
    + conseq hop_0_challenge.
    call hop_0_initialize.
    auto.
    qed.

  (* Hop 1: assumption hop. Bounded by the KEM_INDCPA_MultiChal_advantage axiom applied to R_KEM_Adv. *)

  lemma hop_1_pr (A <: KF_c.KEM_INDCPA_MultiChal_Adv {-K, -F, -G_RandKey, -KF_c.KEM_INDCPA_MultiChal_Random, -KF_c.KEM_INDCPA_MultiChal_Real, -K_c.KEM_INDCPA_MultiChal_Random, -K_c.KEM_INDCPA_MultiChal_Real, -R_MultiPRF}) &m :
    `| Pr[Game_step_1(K, F, A).main() @ &m : res] - Pr[Game_step_2(K, F, A).main() @ &m : res] | <= K_c.eps_KEM_INDCPA_MultiChal.
  proof.
    have hL : Pr[Game_step_1(K, F, A).main() @ &m : res]
            = Pr[K_c.Game_KEM_INDCPA_MultiChal_Real(K, R_KEM_Adv(K, F, A)).main() @ &m : res]
      by byequiv (_: ={glob A, glob K, glob F} ==> ={res}) => //; proc; inline *; sim.
    have hR : Pr[Game_step_2(K, F, A).main() @ &m : res]
            = Pr[K_c.Game_KEM_INDCPA_MultiChal_Random(K, R_KEM_Adv(K, F, A)).main() @ &m : res]
      by byequiv (_: ={glob A, glob K, glob F} ==> ={res}) => //; proc; inline *; sim.
    rewrite hL hR.
    apply (K_c.KEM_INDCPA_MultiChal_advantage K (R_KEM_Adv(K, F, A)) &m).
    qed.

  (* Hop 2: interchangeability. The two adjacent games are equivalent (no advantage). *)

  lemma hop_2_pr (A <: KF_c.KEM_INDCPA_MultiChal_Adv {-K, -F, -G_RandKey, -KF_c.KEM_INDCPA_MultiChal_Random, -KF_c.KEM_INDCPA_MultiChal_Real, -K_c.KEM_INDCPA_MultiChal_Random, -K_c.KEM_INDCPA_MultiChal_Real, -R_MultiPRF}) &m :
    Pr[Game_step_2(K, F, A).main() @ &m : res] = Pr[Game_step_3(K, F, A).main() @ &m : res].
  proof.
    byequiv (_: ={glob A, glob K, glob F} ==> ={res}) => //.
    proc.
    call (_: ={glob K} /\ ={glob F} /\ K_c.KEM_INDCPA_MultiChal_Random.pk{1} = G_RandKey.pk{2}).
    + conseq hop_2_challenge.
    call hop_2_initialize.
    auto.
    qed.

  (* Hop 3: interchangeability. The two adjacent games are equivalent (no advantage). *)

  lemma hop_3_pr (A <: KF_c.KEM_INDCPA_MultiChal_Adv {-K, -F, -G_RandKey, -KF_c.KEM_INDCPA_MultiChal_Random, -KF_c.KEM_INDCPA_MultiChal_Real, -K_c.KEM_INDCPA_MultiChal_Random, -K_c.KEM_INDCPA_MultiChal_Real, -R_MultiPRF}) &m :
    Pr[Game_step_3(K, F, A).main() @ &m : res] = Pr[Game_step_4(K, F, A).main() @ &m : res].
  proof.
    byequiv (_: ={glob A, glob K, glob F} ==> ={res}) => //.
    proc.
    call (_: ={glob K} /\ ={glob F} /\ G_RandKey.pk{1} = R_MultiPRF.pk{2}).
    + conseq hop_3_challenge.
    call hop_3_initialize.
    auto.
    qed.

  (* Hop 4: assumption hop. Bounded by the PRFSecurity_MultiKey_advantage axiom applied to R_MultiPRF_Adv. *)

  lemma hop_4_pr (A <: KF_c.KEM_INDCPA_MultiChal_Adv {-K, -F, -G_RandKey, -KF_c.KEM_INDCPA_MultiChal_Random, -KF_c.KEM_INDCPA_MultiChal_Real, -K_c.KEM_INDCPA_MultiChal_Random, -K_c.KEM_INDCPA_MultiChal_Real, -R_MultiPRF}) &m :
    `| Pr[Game_step_4(K, F, A).main() @ &m : res] - Pr[Game_step_5(K, F, A).main() @ &m : res] | <= F_c.eps_PRFSecurity_MultiKey.
  proof.
    have hL : Pr[Game_step_4(K, F, A).main() @ &m : res]
            = Pr[F_c.Game_PRFSecurity_MultiKey_Real(F, R_MultiPRF_Adv(K, F, A)).main() @ &m : res]
      by byequiv (_: ={glob A, glob K, glob F} ==> ={res}) => //; proc; inline *; sim.
    have hR : Pr[Game_step_5(K, F, A).main() @ &m : res]
            = Pr[F_c.Game_PRFSecurity_MultiKey_Random(F, R_MultiPRF_Adv(K, F, A)).main() @ &m : res]
      by byequiv (_: ={glob A, glob K, glob F} ==> ={res}) => //; proc; inline *; sim.
    rewrite hL hR.
    apply (F_c.PRFSecurity_MultiKey_advantage F (R_MultiPRF_Adv(K, F, A)) &m).
    qed.

  (* Hop 5: interchangeability. The two adjacent games are equivalent (no advantage). *)

  lemma hop_5_pr (A <: KF_c.KEM_INDCPA_MultiChal_Adv {-K, -F, -G_RandKey, -KF_c.KEM_INDCPA_MultiChal_Random, -KF_c.KEM_INDCPA_MultiChal_Real, -K_c.KEM_INDCPA_MultiChal_Random, -K_c.KEM_INDCPA_MultiChal_Real, -R_MultiPRF}) &m :
    Pr[Game_step_5(K, F, A).main() @ &m : res] = Pr[Game_step_6(K, F, A).main() @ &m : res].
  proof.
    byequiv (_: ={glob A, glob K, glob F} ==> ={res}) => //.
    proc.
    call (_: ={glob K} /\ ={glob F} /\ R_MultiPRF.pk{1} = KF_c.KEM_INDCPA_MultiChal_Random.pk{2}).
    + conseq hop_5_challenge.
    call hop_5_initialize.
    auto.
    qed.

  (* ===== Main theorem ===== *)

  lemma main_theorem (A <: KF_c.KEM_INDCPA_MultiChal_Adv {-K, -F, -G_RandKey, -KF_c.KEM_INDCPA_MultiChal_Random, -KF_c.KEM_INDCPA_MultiChal_Real, -K_c.KEM_INDCPA_MultiChal_Random, -K_c.KEM_INDCPA_MultiChal_Real, -R_MultiPRF}) &m :
    `| Pr[Game_step_0(K, F, A).main() @ &m : res] - Pr[Game_step_6(K, F, A).main() @ &m : res] | <= K_c.eps_KEM_INDCPA_MultiChal + F_c.eps_PRFSecurity_MultiKey.
  proof.
    have h0 := hop_0_pr A &m.
    have h1 := hop_1_pr A &m.
    have h2 := hop_2_pr A &m.
    have h3 := hop_3_pr A &m.
    have h4 := hop_4_pr A &m.
    have h5 := hop_5_pr A &m.
    smt(F_c.eps_PRFSecurity_MultiKey_pos K_c.eps_KEM_INDCPA_MultiChal_pos).
    qed.
end section Main.
