(* ============================================================ *)
(* Deterministic-tail row (Phase-2 Move 4): Absorb Redundant      *)
(* Early Return -- VALIDATED EC TEMPLATE (regression tripwire),   *)
(* GENERATED BY THE SYNTHESIZER ITSELF (_if_fold_step's det-tail  *)
(* row) over a mini absorb pair rendered by the real renderer.    *)
(*                                                                *)
(* Shape: after the shared prefix both tails are call/sample-free *)
(* and one side's divergence is the early-return lowering (an if  *)
(* whose then-body is a single assign); plain wp decides the      *)
(* whole lowered if-tree on both sides, so the closer is the      *)
(* ordinary prefix peel + auto => /#.                             *)
(*                                                                *)
(* Negative control (validated 2026-08-09 by mutating THIS file): *)
(* dropping the !P conjunct from AA's absorbed guard -> EC        *)
(* rejects at the closing /# (the goal's witness branch shows the *)
(* divergent write). Lockstep:                                    *)
(* tests/unit/export/test_if_fold_walk.py. Probes:                *)
(* .ec-tmp/move4/absorb_probe.ec (+ negctl_absorb.ec).            *)
(* ============================================================ *)

require import AllCore Distr.

theory K_c.
type bs_lambda.
op ev_decaps : bs_lambda -> bs_lambda -> bs_lambda.
op ev_enc : bs_lambda -> bs_lambda.
module type Scheme = {
  proc decaps(dk : bs_lambda, ct : bs_lambda) : bs_lambda
  proc enc(ss : bs_lambda) : bs_lambda
}.
end K_c.
import K_c.
type bs_lambda = K_c.bs_lambda.

section.

module AB (K : K_c.Scheme) = {
  var dk0 : bs_lambda
  proc initialize() : bs_lambda = {
    return dk0;
  }
  proc challenge(ct0 : bs_lambda, ct1 : bs_lambda) : bool = {
    var _r0 : bool;
    var d0 : bs_lambda;
    var s : bs_lambda;
    var _r1 : bool;
    _r0 <- witness;
    d0 <@ K.decaps(dk0, ct0);
    s <- ct0;
    if (d0 = ct0) {
      _r0 <- s = ct0;
    } else {
      _r1 <- false;
      if (ct0 = ct1) {
        s <- dk0;
      }
      if (! _r1) {
        _r0 <- s = ct0;
      }
    }
    return _r0;
  }
}.

module AA (K : K_c.Scheme) = {
  var dk0 : bs_lambda
  proc initialize() : bs_lambda = {
    return dk0;
  }
  proc challenge(ct0 : bs_lambda, ct1 : bs_lambda) : bool = {
    var _r0 : bool;
    var d0 : bs_lambda;
    var s : bs_lambda;
    var _r1 : bool;
    _r0 <- witness;
    d0 <@ K.decaps(dk0, ct0);
    s <- ct0;
    _r1 <- false;
    if ((d0 <> ct0) && (ct0 = ct1)) {
      s <- dk0;
    }
    if (! _r1) {
      _r0 <- s = ct0;
    }
    return _r0;
  }
}.

declare module K <: K_c.Scheme {-AB, -AA}.

declare axiom K_decaps_det (g : (glob K)) (a0 : bs_lambda) (a1 : bs_lambda) : phoare[ K.decaps : (glob K) = g /\ dk = a0 /\ ct = a1 ==> (glob K) = g /\ res = K_c.ev_decaps a0 a1 ] = 1%r.
declare axiom K_enc_det (g : (glob K)) (a0 : bs_lambda) : phoare[ K.enc : (glob K) = g /\ ss = a0 ==> (glob K) = g /\ res = K_c.ev_enc a0 ] = 1%r.

(* The early-return lowering vs the absorbed if-tree. *)
lemma micro_det_tail :
  equiv [ AB(K).challenge ~ AA(K).challenge :
          ={ct0, ct1} /\ (glob AB(K)){1} = (glob AA(K)){2} ==> ={res} /\ (glob AB(K)){1} = (glob AA(K)){2} ].
proof.
  proc.
  wp.
  call (_: true).
  auto => /#.
qed.

end section.
