(* ============================================================ *)
(* Fold Equivalent Return Branch case tree (Phase-2 Move 4) --    *)
(* the CANONICAL-FIELD-NAMING tripwire. GENERATED BY THE          *)
(* SYNTHESIZER ITSELF (_if_fold_step) over the same mini fold     *)
(* pair as fold_pair_walk.ec, but with the two flat states        *)
(* rendered under the chain-wide canonical f<NN> field naming a   *)
(* random-oracle proof uses.                                      *)
(*                                                                *)
(* Why this file exists: the route renders its OWN copy of each   *)
(* state to read the bodies its tactic names. That copy used to   *)
(* be rendered without the chain's field-naming decision, so on a *)
(* canonically-named chain every field pin named a variable the   *)
(* emitted module has not got ("unknown variable or constant:     *)
(* Step_4R_state_40._hoisted_0_1_0" on                            *)
(* CG_seedbased_LEAK_BIND_K_CT_DIFFKEY). fold_pair_walk.ec cannot *)
(* catch that: its fields are already canonical-shaped, so the    *)
(* two renderings agree by accident.                              *)
(*                                                                *)
(* Negative control (validated by mutating THIS file): replacing  *)
(* the seq invariant's d0{1} = ev_decaps (kv0) (kv1) pin argument *)
(* kv0 by kv2 -> EC rejects with "cannot prove goal (strict)".    *)
(* Lockstep: tests/unit/export/test_if_fold_walk.py.              *)
(* ============================================================ *)

require import AllCore Distr.

theory K_c.
type bs_lambda.
op ev_decaps : bs_lambda -> bs_lambda -> bs_lambda.
op ev_enc : bs_lambda -> bs_lambda.
module type Scheme = {
  proc decaps(dk : bs_lambda, ct : bs_lambda) : bs_lambda
  proc enc(ss : bs_lambda) : bs_lambda
}.
end K_c.
import K_c.
type bs_lambda = K_c.bs_lambda.

section.

module FB (K : K_c.Scheme) = {
  var f00 : bs_lambda
  var f01 : bs_lambda
  var f02 : bs_lambda
  var f03 : bs_lambda
  proc initialize() : bs_lambda = {
    return f00;
  }
  proc challenge(ct0 : bs_lambda, ct1 : bs_lambda) : bool = {
    var _r0 : bool;
    var d0 : bs_lambda;
    var d1 : bs_lambda;
    var e0 : bs_lambda;
    var e1 : bs_lambda;
    d0 <@ K.decaps(f00, ct0);
    d1 <@ K.decaps(f01, ct1);
    if ((d0 = d1) && (ct0 = ct1)) {
      _r0 <- f02 <> f03;
    } else {
      e0 <@ K.enc(d0);
      e1 <@ K.enc(d1);
      _r0 <- (e0 = e1) && (f02 <> f03);
    }
    return _r0;
  }
}.

module FA (K : K_c.Scheme) = {
  var f00 : bs_lambda
  var f01 : bs_lambda
  var f02 : bs_lambda
  var f03 : bs_lambda
  proc initialize() : bs_lambda = {
    return f00;
  }
  proc challenge(ct0 : bs_lambda, ct1 : bs_lambda) : bool = {
    var d0 : bs_lambda;
    var d1 : bs_lambda;
    var e0 : bs_lambda;
    var e1 : bs_lambda;
    d0 <@ K.decaps(f00, ct0);
    d1 <@ K.decaps(f01, ct1);
    e0 <@ K.enc(d0);
    e1 <@ K.enc(d1);
    return (e0 = e1) && (f02 <> f03);
  }
}.


declare module K <: K_c.Scheme {-FB, -FA}.

declare axiom K_decaps_det (g : (glob K)) (a0 : bs_lambda) (a1 : bs_lambda) : phoare[ K.decaps : (glob K) = g /\ dk = a0 /\ ct = a1 ==> (glob K) = g /\ res = K_c.ev_decaps a0 a1 ] = 1%r.
declare axiom K_enc_det (g : (glob K)) (a0 : bs_lambda) : phoare[ K.enc : (glob K) = g /\ ss = a0 ==> (glob K) = g /\ res = K_c.ev_enc a0 ] = 1%r.

(* Forward: the if side is side 1. *)
lemma micro_fold_canon_fwd :
  equiv [ FB(K).challenge ~ FA(K).challenge :
          ={ct0, ct1} /\ (glob FB(K)){1} = (glob FA(K)){2} ==> ={res} /\ (glob FB(K)){1} = (glob FA(K)){2} ].
proof.
  proc.
  exists* FA.f00{2}, ct0{2}, FA.f01{2}, ct1{2}, (glob K){2}; elim* => kv0 kv1 kv2 kv3 gv0.
  seq 2 2 : (={d0, d1} /\ ={ct0, ct1} /\ (glob FB(K)){1} = (glob FA(K)){2} /\ (glob K){2} = gv0 /\ d0{1} = K_c.ev_decaps (kv0) (kv1) /\ d1{1} = K_c.ev_decaps (kv2) (kv3)).
  call{1} (K_decaps_det gv0 (kv2) (kv3)).
  call{2} (K_decaps_det gv0 (kv2) (kv3)).
  call{1} (K_decaps_det gv0 (kv0) (kv1)).
  call{2} (K_decaps_det gv0 (kv0) (kv1)).
  auto => /#.
  case ((d0{1} = d1{1}) /\ (ct0{1} = ct1{1})).
  rcondt{1} 1; first by auto => /#.
  wp.
  call{2} (K_enc_det gv0 ((K_c.ev_decaps (kv2) (kv3)))).
  call{2} (K_enc_det gv0 ((K_c.ev_decaps (kv0) (kv1)))).
  skip.
  move => &1 &2 />.
  smt().
  rcondf{1} 1; first by auto => /#.
  wp.
  call (_: true).
  call (_: true).
  auto => /#.
qed.

(* Reversed: the if side is side 2. *)
lemma micro_fold_canon_rev :
  equiv [ FA(K).challenge ~ FB(K).challenge :
          ={ct0, ct1} /\ (glob FA(K)){1} = (glob FB(K)){2} ==> ={res} /\ (glob FA(K)){1} = (glob FB(K)){2} ].
proof.
  proc.
  exists* FB.f00{2}, ct0{2}, FB.f01{2}, ct1{2}, (glob K){2}; elim* => kv0 kv1 kv2 kv3 gv0.
  seq 2 2 : (={d0, d1} /\ ={ct0, ct1} /\ (glob FA(K)){1} = (glob FB(K)){2} /\ (glob K){2} = gv0 /\ d0{2} = K_c.ev_decaps (kv0) (kv1) /\ d1{2} = K_c.ev_decaps (kv2) (kv3)).
  call{2} (K_decaps_det gv0 (kv2) (kv3)).
  call{1} (K_decaps_det gv0 (kv2) (kv3)).
  call{2} (K_decaps_det gv0 (kv0) (kv1)).
  call{1} (K_decaps_det gv0 (kv0) (kv1)).
  auto => /#.
  case ((d0{2} = d1{2}) /\ (ct0{2} = ct1{2})).
  rcondt{2} 1; first by auto => /#.
  wp.
  call{1} (K_enc_det gv0 ((K_c.ev_decaps (kv2) (kv3)))).
  call{1} (K_enc_det gv0 ((K_c.ev_decaps (kv0) (kv1)))).
  skip.
  move => &1 &2 />.
  smt().
  rcondf{2} 1; first by auto => /#.
  wp.
  call (_: true).
  call (_: true).
  auto => /#.
qed.

end section.
