(* ============================================================ *)
(* Fold Equivalent Return Branch case tree (Phase-2 Move 4) --    *)
(* VALIDATED EC TEMPLATE (regression tripwire), GENERATED BY THE  *)
(* SYNTHESIZER ITSELF (_if_fold_step) over a mini fold pair       *)
(* rendered by the real renderer.                                 *)
(*                                                                *)
(* Shape: prefix; if (P) { return X; }; return Y  ->  prefix;     *)
(* return Y (the renderer's single-exit lowering turns the before *)
(* side into if (P) { _r <- X } else { <Y's calls>; _r <- Y };    *)
(* return _r). Closer: prefix ev-walk whose seq invariant ALSO    *)
(* carries the glob-pin equations (the post-seq drains' pin       *)
(* equations must ride the invariant); case (P{if-side});         *)
(* rcondt: wp + one-sided _det drains + skip; move => &1 &2 />;   *)
(* smt() (the /> crush before smt is load-bearing -- a bare       *)
(* skip => /# fails); rcondf: the paired peel.                    *)
(*                                                                *)
(* The crush and the solver are ONE tactic (`;`), not two steps.   *)
(* On an oracle whose branches both return a constant the crush    *)
(* closes the P-true goal by itself, and a following `smt().` on   *)
(* its own line would be applied to the NEXT open goal -- the      *)
(* P-false branch, whose program is not empty, giving "cannot      *)
(* prove goal (strict)" with the `if` still in place (measured on  *)
(* UG_expanded_LEAK_BIND_K_PK micro_2_challenge_left_8).           *)
(*                                                                *)
(* Negative control (validated 2026-08-09 by mutating THIS file): *)
(* falsifying FB's then-branch X to (ek0 = ek1) -> EC rejects at  *)
(* the P-true smt ("cannot prove goal", the goal showing the      *)
(* mutilated equation). Lockstep:                                 *)
(* tests/unit/export/test_if_fold_walk.py. Probes:                *)
(* .ec-tmp/move4/fold_probe.ec (+ negctl_fold.ec).                *)
(* ============================================================ *)

require import AllCore Distr.

theory K_c.
type bs_lambda.
op ev_decaps : bs_lambda -> bs_lambda -> bs_lambda.
op ev_enc : bs_lambda -> bs_lambda.
module type Scheme = {
  proc decaps(dk : bs_lambda, ct : bs_lambda) : bs_lambda
  proc enc(ss : bs_lambda) : bs_lambda
}.
end K_c.
import K_c.
type bs_lambda = K_c.bs_lambda.

section.

module FB (K : K_c.Scheme) = {
  var dk0 : bs_lambda
  var dk1 : bs_lambda
  var ek0 : bs_lambda
  var ek1 : bs_lambda
  proc initialize() : bs_lambda = {
    return dk0;
  }
  proc challenge(ct0 : bs_lambda, ct1 : bs_lambda) : bool = {
    var _r0 : bool;
    var d0 : bs_lambda;
    var d1 : bs_lambda;
    var e0 : bs_lambda;
    var e1 : bs_lambda;
    d0 <@ K.decaps(dk0, ct0);
    d1 <@ K.decaps(dk1, ct1);
    if ((d0 = d1) && (ct0 = ct1)) {
      _r0 <- ek0 <> ek1;
    } else {
      e0 <- d0;
      e1 <- d1;
      _r0 <- (e0 = e1) && (ek0 <> ek1);
    }
    return _r0;
  }
}.

module FA (K : K_c.Scheme) = {
  var dk0 : bs_lambda
  var dk1 : bs_lambda
  var ek0 : bs_lambda
  var ek1 : bs_lambda
  proc initialize() : bs_lambda = {
    return dk0;
  }
  proc challenge(ct0 : bs_lambda, ct1 : bs_lambda) : bool = {
    var d0 : bs_lambda;
    var d1 : bs_lambda;
    var e0 : bs_lambda;
    var e1 : bs_lambda;
    d0 <@ K.decaps(dk0, ct0);
    d1 <@ K.decaps(dk1, ct1);
    e0 <- d0;
    e1 <- d1;
    return (e0 = e1) && (ek0 <> ek1);
  }
}.

declare module K <: K_c.Scheme {-FB, -FA}.

declare axiom K_decaps_det (g : (glob K)) (a0 : bs_lambda) (a1 : bs_lambda) : phoare[ K.decaps : (glob K) = g /\ dk = a0 /\ ct = a1 ==> (glob K) = g /\ res = K_c.ev_decaps a0 a1 ] = 1%r.
declare axiom K_enc_det (g : (glob K)) (a0 : bs_lambda) : phoare[ K.enc : (glob K) = g /\ ss = a0 ==> (glob K) = g /\ res = K_c.ev_enc a0 ] = 1%r.

(* Forward: the if side is side 1. *)
lemma micro_fold_fwd :
  equiv [ FB(K).challenge ~ FA(K).challenge :
          ={ct0, ct1} /\ (glob FB(K)){1} = (glob FA(K)){2} ==> ={res} /\ (glob FB(K)){1} = (glob FA(K)){2} ].
proof.
  proc.
  exists* FA.dk0{2}, ct0{2}, FA.dk1{2}, ct1{2}, (glob K){2}; elim* => kv0 kv1 kv2 kv3 gv0.
  seq 2 2 : (={d0, d1} /\ ={ct0, ct1} /\ (glob FB(K)){1} = (glob FA(K)){2} /\ (glob K){2} = gv0 /\ d0{1} = K_c.ev_decaps (kv0) (kv1) /\ d1{1} = K_c.ev_decaps (kv2) (kv3)).
  call{1} (K_decaps_det gv0 (kv2) (kv3)).
  call{2} (K_decaps_det gv0 (kv2) (kv3)).
  call{1} (K_decaps_det gv0 (kv0) (kv1)).
  call{2} (K_decaps_det gv0 (kv0) (kv1)).
  auto => /#.
  case ((d0{1} = d1{1}) /\ (ct0{1} = ct1{1})).
  rcondt{1} 1; first by auto => /#.
  wp.
  wp.
  skip.
  move => &1 &2 />; smt().
  rcondf{1} 1; first by auto => /#.
  wp.
  wp.
  auto => /#.
qed.

(* Reversed (right chain): the if side is side 2. *)
lemma micro_fold_rev :
  equiv [ FA(K).challenge ~ FB(K).challenge :
          ={ct0, ct1} /\ (glob FA(K)){1} = (glob FB(K)){2} ==> ={res} /\ (glob FA(K)){1} = (glob FB(K)){2} ].
proof.
  proc.
  exists* FB.dk0{2}, ct0{2}, FB.dk1{2}, ct1{2}, (glob K){2}; elim* => kv0 kv1 kv2 kv3 gv0.
  seq 2 2 : (={d0, d1} /\ ={ct0, ct1} /\ (glob FA(K)){1} = (glob FB(K)){2} /\ (glob K){2} = gv0 /\ d0{2} = K_c.ev_decaps (kv0) (kv1) /\ d1{2} = K_c.ev_decaps (kv2) (kv3)).
  call{2} (K_decaps_det gv0 (kv2) (kv3)).
  call{1} (K_decaps_det gv0 (kv2) (kv3)).
  call{2} (K_decaps_det gv0 (kv0) (kv1)).
  call{1} (K_decaps_det gv0 (kv0) (kv1)).
  auto => /#.
  case ((d0{2} = d1{2}) /\ (ct0{2} = ct1{2})).
  rcondt{2} 1; first by auto => /#.
  wp.
  wp.
  skip.
  move => &1 &2 />; smt().
  rcondf{2} 1; first by auto => /#.
  wp.
  wp.
  auto => /#.
qed.

end section.
