(* ============================================================ *)
(* Hoist-pair micro walk (Phase-2 Move 3c) -- VALIDATED EC        *)
(* TEMPLATE (regression tripwire), GENERATED BY THE SYNTHESIZER   *)
(* ITSELF (_detect_hoist_pair / _hoist_conjunct_registry /        *)
(* _hoist_pair_step / _make_field_aware_coupling /                *)
(* _render_coupling_chain_body) over a mini Hoist pair rendered   *)
(* by the real renderer.                                          *)
(*                                                                *)
(* Shape: `Hoist Deterministic Call to Initialize` -- the after   *)
(* state caches a det call in a new field; the consumer swaps the *)
(* inline call for the field read; bystanders are untouched. The  *)
(* pair coupling carries the one-sided cache conjunct             *)
(* `<state>.h{s} = ev_f (<state>.k{s})`; consumer legs drain the  *)
(* inline call one-sided through the licensed _det axiom with     *)
(* up-front exists* pins; bystander legs take the plain peel      *)
(* (`proc; sim` fails SILENTLY under the conjunct -- the probed   *)
(* worst case). The chain lemma has NO conjunct in its own pre:   *)
(* each transitivity's first smt() witnesses the middle memory.   *)
(*                                                                *)
(* Negative control (validated 2026-08-09 by mutating THIS file): *)
(* dropping the cache statement from HZ_L1.initialize while       *)
(* keeping the conjunct is not expressible here (the conjunct is  *)
(* assumed, not derived), so the control instead falsifies the    *)
(* consumer: replacing micro_hz_L0's conjunct argument            *)
(* `HZ_L1(E, M).k{2}` with `witness` -> EC rejects at the closing *)
(* /# ("cannot prove goal"). The tactic text is asserted in       *)
(* lockstep with the synthesizer by                               *)
(* tests/unit/export/test_hoist_pair_walk.py. If this stops       *)
(* compiling, re-derive before trusting _hoist_pair_step.         *)
(* Probes: .ec-tmp/move3/hoist_probe.ec, hoist_chain_probe.ec.    *)
(* ============================================================ *)

require import AllCore Distr.

theory E_c.
type bs_lambda.
module type Scheme = {
  proc keygen() : bs_lambda
  proc enc(m : bs_lambda) : bs_lambda
  proc mix(x : bs_lambda, a : bs_lambda) : bs_lambda
}.
end E_c.
import E_c.
type bs_lambda = E_c.bs_lambda.

theory M_c.
op ev_f : bs_lambda -> bs_lambda.
module type FMod = {
  proc f(k : bs_lambda) : bs_lambda
}.
end M_c.

section.

module HZ_L0 (E : E_c.Scheme, M : M_c.FMod) = {
  var k : bs_lambda
  proc initialize() : bs_lambda = {
    k <@ E.keygen();
    return k;
  }
  proc challenge(m : bs_lambda) : bs_lambda = {
    var a : bs_lambda;
    var x : bs_lambda;
    var c : bs_lambda;
    a <@ E.enc(m);
    x <@ M.f(k);
    c <@ E.mix(x, a);
    return c;
  }
  proc guess(m : bs_lambda) : bs_lambda = {
    var d : bs_lambda;
    d <@ E.enc(m);
    return d;
  }
}.

module HZ_L1 (E : E_c.Scheme, M : M_c.FMod) = {
  var k : bs_lambda
  var h : bs_lambda
  proc initialize() : bs_lambda = {
    k <@ E.keygen();
    h <@ M.f(k);
    return k;
  }
  proc challenge(m : bs_lambda) : bs_lambda = {
    var a : bs_lambda;
    var x : bs_lambda;
    var c : bs_lambda;
    a <@ E.enc(m);
    x <- h;
    c <@ E.mix(x, a);
    return c;
  }
  proc guess(m : bs_lambda) : bs_lambda = {
    var d : bs_lambda;
    d <@ E.enc(m);
    return d;
  }
}.

module HZ_R1 (E : E_c.Scheme, M : M_c.FMod) = {
  var k : bs_lambda
  var h : bs_lambda
  proc initialize() : bs_lambda = {
    k <@ E.keygen();
    h <@ M.f(k);
    return k;
  }
  proc challenge(m : bs_lambda) : bs_lambda = {
    var a : bs_lambda;
    var x : bs_lambda;
    var c : bs_lambda;
    a <@ E.enc(m);
    x <- h;
    c <@ E.mix(x, a);
    return c;
  }
  proc guess(m : bs_lambda) : bs_lambda = {
    var d : bs_lambda;
    d <@ E.enc(m);
    return d;
  }
}.

module HZ_R0 (E : E_c.Scheme, M : M_c.FMod) = {
  var k : bs_lambda
  proc initialize() : bs_lambda = {
    k <@ E.keygen();
    return k;
  }
  proc challenge(m : bs_lambda) : bs_lambda = {
    var a : bs_lambda;
    var x : bs_lambda;
    var c : bs_lambda;
    a <@ E.enc(m);
    x <@ M.f(k);
    c <@ E.mix(x, a);
    return c;
  }
  proc guess(m : bs_lambda) : bs_lambda = {
    var d : bs_lambda;
    d <@ E.enc(m);
    return d;
  }
}.

declare module E <: E_c.Scheme {-HZ_L0, -HZ_L1, -HZ_R1, -HZ_R0}.
declare module M <: M_c.FMod {-E, -HZ_L0, -HZ_L1, -HZ_R1, -HZ_R0}.

declare axiom M_f_det (g : (glob M)) (a0 : bs_lambda) : phoare[ M.f : (glob M) = g /\ k = a0 ==> (glob M) = g /\ res = M_c.ev_f a0 ] = 1%r.

(* Consumer leg, forward: drain side 1. *)
lemma micro_hz_L0 :
  equiv [ HZ_L0(E, M).challenge ~ HZ_L1(E, M).challenge :
          ={m} /\ ={glob E} /\ ={glob M} /\ HZ_L0.k{1} = HZ_L1.k{2} /\ HZ_L1.h{2} = M_c.ev_f (HZ_L1.k{2}) ==> ={res} /\ ={glob E} /\ ={glob M} /\ HZ_L0.k{1} = HZ_L1.k{2} /\ HZ_L1.h{2} = M_c.ev_f (HZ_L1.k{2}) ].
proof.
  proc.
  exists* HZ_L0.k{1}, (glob M){1}; elim* => kv0 gv.
  wp.
  call (_: true).
  wp.
  call{1} (M_f_det gv (kv0)).
  wp.
  call (_: true).
  auto => /#.
qed.

(* Bystander leg: the plain peel -- NEVER `proc; sim`,
   which fails silently under the one-sided conjunct. *)
lemma micro_hz_by :
  equiv [ HZ_L0(E, M).guess ~ HZ_L1(E, M).guess :
          ={m} /\ ={glob E} /\ ={glob M} /\ HZ_L0.k{1} = HZ_L1.k{2} /\ HZ_L1.h{2} = M_c.ev_f (HZ_L1.k{2}) ==> ={res} /\ ={glob E} /\ ={glob M} /\ HZ_L0.k{1} = HZ_L1.k{2} /\ HZ_L1.h{2} = M_c.ev_f (HZ_L1.k{2}) ].
proof.
  proc.
  wp.
  call (_: true).
  auto => /#.
qed.

(* Consumer leg, reversed (right chain): drain side 2. *)
lemma micro_hz_R0_rev :
  equiv [ HZ_R1(E, M).challenge ~ HZ_R0(E, M).challenge :
          ={m} /\ ={glob E} /\ ={glob M} /\ HZ_R1.k{1} = HZ_R0.k{2} /\ HZ_R1.h{1} = M_c.ev_f (HZ_R1.k{1}) ==> ={res} /\ ={glob E} /\ ={glob M} /\ HZ_R1.k{1} = HZ_R0.k{2} /\ HZ_R1.h{1} = M_c.ev_f (HZ_R1.k{1}) ].
proof.
  proc.
  exists* HZ_R0.k{2}, (glob M){2}; elim* => kv0 gv.
  wp.
  call (_: true).
  wp.
  call{2} (M_f_det gv (kv0)).
  wp.
  call (_: true).
  auto => /#.
qed.

(* Canonical-end bridge (whole-glob). *)
lemma bridge_hz :
  equiv [ HZ_L1(E, M).challenge ~ HZ_R1(E, M).challenge :
          ={m} /\ (glob HZ_L1(E, M)){1} = (glob HZ_R1(E, M)){2} ==> ={res} /\ (glob HZ_L1(E, M)){1} = (glob HZ_R1(E, M)){2} ].
proof.
  proc; sim.
qed.

(* The chain: NO conjunct in its own pre/post (the anchors
   lack the cache field); every transitivity first goal
   witnesses the middle memory (h := ev_f k) by smt(). *)
lemma chain_hz :
  equiv [ HZ_L0(E, M).challenge ~ HZ_R0(E, M).challenge :
          ={m} /\ (glob HZ_L0(E, M)){1} = (glob HZ_R0(E, M)){2} ==> ={res} /\ (glob HZ_L0(E, M)){1} = (glob HZ_R0(E, M)){2} ].
proof.
  (* Chain through per-transform micro-lemmas (coupling-preserving). *)
  transitivity HZ_L1(E, M).challenge (={m} /\ ={glob E} /\ ={glob M} /\ HZ_L0.k{1} = HZ_L1.k{2} /\ HZ_L1.h{2} = M_c.ev_f (HZ_L1.k{2}) ==> ={res} /\ ={glob E} /\ ={glob M} /\ HZ_L0.k{1} = HZ_L1.k{2} /\ HZ_L1.h{2} = M_c.ev_f (HZ_L1.k{2})) (={m} /\ ={glob E} /\ ={glob M} /\ HZ_L1.k{1} = HZ_R0.k{2} /\ HZ_L1.h{1} = M_c.ev_f (HZ_L1.k{1}) ==> ={res} /\ ={glob E} /\ ={glob M} /\ HZ_L1.k{1} = HZ_R0.k{2} /\ HZ_L1.h{1} = M_c.ev_f (HZ_L1.k{1})); [ smt() | smt() | apply micro_hz_L0 |].
  transitivity HZ_R1(E, M).challenge (={m} /\ (glob HZ_L1(E, M)){1} = (glob HZ_R1(E, M)){2} ==> ={res} /\ (glob HZ_L1(E, M)){1} = (glob HZ_R1(E, M)){2}) (={m} /\ ={glob E} /\ ={glob M} /\ HZ_R1.k{1} = HZ_R0.k{2} /\ HZ_R1.h{1} = M_c.ev_f (HZ_R1.k{1}) ==> ={res} /\ ={glob E} /\ ={glob M} /\ HZ_R1.k{1} = HZ_R0.k{2} /\ HZ_R1.h{1} = M_c.ev_f (HZ_R1.k{1})); [ smt() | smt() | apply bridge_hz |].
  apply micro_hz_R0_rev.
qed.

end section.
