(* ============================================================ *)
(* IES delta-det guard-site walk (Phase-2 Move 3a) -- VALIDATED   *)
(* EC TEMPLATE (regression tripwire), GENERATED BY THE            *)
(* SYNTHESIZER ITSELF (_ies_delta_walk_step) over a mini          *)
(* state_20/21-shaped pair rendered by the real renderer.         *)
(*                                                                *)
(* Shape: shared all-det prefix; one side carries extra det calls *)
(* (the transform's Gap-D binding resolution inlined det calls    *)
(* into the rewritten guard; the renderer re-hoisted them); the   *)
(* single differing if-guard is the Injective Equality Simplify   *)
(* site. Tactic: exists* pins (UNAPPLIED module names for         *)
(* globals), seq n m with shared-local equalities + per-side      *)
(* local = ev-term conjuncts, tail-to-front det drains (delta     *)
(* one-sided, matched both sides) with wp at assign runs,         *)
(* auto => /#, then if; [smt(<inj>) | sim | sim].                 *)
(*                                                                *)
(* Negative control (validated 2026-08-09 by mutating THIS file): *)
(* falsifying State21's guard to `x0 = x0` -> EC rejects at the   *)
(* if guard-equality subgoal ("cannot prove goal (strict)").      *)
(* The tactic text below is asserted in lockstep with the         *)
(* synthesizer by tests/unit/export/test_ies_delta_walk.py.       *)
(* If this stops compiling, re-derive before trusting             *)
(* _ies_delta_walk_step.                                          *)
(* ============================================================ *)

require import AllCore Distr.

theory K_c.
type bs_lambda.
op ev_decaps : bs_lambda -> bs_lambda -> bs_lambda.
op ev_encode : bs_lambda -> bs_lambda.
module type Scheme = {
  proc decaps(dk : bs_lambda, ct : bs_lambda) : bs_lambda
  proc encode(ss : bs_lambda) : bs_lambda
}.
end K_c.
import K_c.
type bs_lambda = K_c.bs_lambda.

section.

module State20 (K : K_c.Scheme) = {
  var dk0 : bs_lambda
  var dk1 : bs_lambda
  proc initialize() : bs_lambda = {
    return dk0;
  }
  proc challenge(ct0 : bs_lambda, ct1 : bs_lambda) : bool = {
    var _r0 : bool;
    var r0 : bs_lambda;
    var e0 : bs_lambda;
    var r1 : bs_lambda;
    var e1 : bs_lambda;
    var out : bool;
    var _r1 : bool;
    _r0 <- witness;
    r0 <@ K.decaps(dk0, ct0);
    e0 <@ K.encode(r0);
    r1 <@ K.decaps(dk1, ct1);
    e1 <@ K.encode(r1);
    _r1 <- false;
    if (e0 = e1) {
      out <- true;
    } else {
      out <- false;
    }
    if (! _r1) {
      _r0 <- out;
    }
    return _r0;
  }
}.

module State21 (K : K_c.Scheme) = {
  var dk0 : bs_lambda
  var dk1 : bs_lambda
  proc initialize() : bs_lambda = {
    return dk0;
  }
  proc challenge(ct0 : bs_lambda, ct1 : bs_lambda) : bool = {
    var _r0 : bool;
    var r0 : bs_lambda;
    var e0 : bs_lambda;
    var r1 : bs_lambda;
    var e1 : bs_lambda;
    var x0 : bs_lambda;
    var x1 : bs_lambda;
    var out : bool;
    var _r1 : bool;
    _r0 <- witness;
    r0 <@ K.decaps(dk0, ct0);
    e0 <@ K.encode(r0);
    r1 <@ K.decaps(dk1, ct1);
    e1 <@ K.encode(r1);
    x0 <@ K.decaps(dk0, ct0);
    x1 <@ K.decaps(dk1, ct1);
    _r1 <- false;
    if (x0 = x1) {
      out <- true;
    } else {
      out <- false;
    }
    if (! _r1) {
      _r0 <- out;
    }
    return _r0;
  }
}.

declare module K <: K_c.Scheme {-State20, -State21}.

declare axiom K_decaps_det (g : (glob K)) (a0 : bs_lambda) (a1 : bs_lambda) : phoare[ K.decaps : (glob K) = g /\ dk = a0 /\ ct = a1 ==> (glob K) = g /\ res = K_c.ev_decaps a0 a1 ] = 1%r.
declare axiom K_encode_det (g : (glob K)) (a0 : bs_lambda) : phoare[ K.encode : (glob K) = g /\ ss = a0 ==> (glob K) = g /\ res = K_c.ev_encode a0 ] = 1%r.
declare axiom K_encode_inj (a0 : bs_lambda) (b0 : bs_lambda) : K_c.ev_encode a0 = K_c.ev_encode b0 => a0 = b0.

lemma micro_ies_walk :
  equiv [ State20(K).challenge ~ State21(K).challenge :
          ={ct0, ct1} /\ (glob State20(K)){1} = (glob State21(K)){2} ==>
          ={res} /\ (glob State20(K)){1} = (glob State21(K)){2} ].
proof.
  proc.
  exists* State21.dk0{2}, ct0{2}, State21.dk1{2}, ct1{2}, (glob K){2}; elim* => kv0 kv1 kv2 kv3 gv0.
  seq 6 8 : (={_r0, r0, e0, r1, e1, _r1} /\ ={ct0, ct1} /\ (glob State20(K)){1} = (glob State21(K)){2} /\ _r0{1} = witness /\ r0{1} = K_c.ev_decaps (kv0) (kv1) /\ e0{1} = K_c.ev_encode ((K_c.ev_decaps (kv0) (kv1))) /\ r1{1} = K_c.ev_decaps (kv2) (kv3) /\ e1{1} = K_c.ev_encode ((K_c.ev_decaps (kv2) (kv3))) /\ _r1{1} = false /\ x0{2} = K_c.ev_decaps (kv0) (kv1) /\ x1{2} = K_c.ev_decaps (kv2) (kv3)).
  wp.
  call{2} (K_decaps_det gv0 (kv2) (kv3)).
  call{2} (K_decaps_det gv0 (kv0) (kv1)).
  call{1} (K_encode_det gv0 ((K_c.ev_decaps (kv2) (kv3)))).
  call{2} (K_encode_det gv0 ((K_c.ev_decaps (kv2) (kv3)))).
  call{1} (K_decaps_det gv0 (kv2) (kv3)).
  call{2} (K_decaps_det gv0 (kv2) (kv3)).
  call{1} (K_encode_det gv0 ((K_c.ev_decaps (kv0) (kv1)))).
  call{2} (K_encode_det gv0 ((K_c.ev_decaps (kv0) (kv1)))).
  call{1} (K_decaps_det gv0 (kv0) (kv1)).
  call{2} (K_decaps_det gv0 (kv0) (kv1)).
  wp.
  auto => /#.
  if; [ smt(K_encode_inj) | sim | sim ].
qed.

end section.
