(* ============================================================ *)
(* ISUV calls-alignment walk (Phase-2 Move 6) -- VALIDATED EC     *)
(* TEMPLATE (regression tripwire), GENERATED BY THE SYNTHESIZER   *)
(* ITSELF (_isuv_align_step) over a mini inlining pair rendered   *)
(* by the real renderer.                                          *)
(*                                                                *)
(* Shape: `Inline Single-Use Variables` removed a single-use      *)
(* projection local (so the two sides differ in statement COUNT,  *)
(* defeating every permutation check) AND the inlining freed two  *)
(* independent calls of DIFFERENT declared modules to swap        *)
(* (K.ess moves up past N.exp / N.ets). `sim` cannot align calls  *)
(* at mismatched positions. Tactic: swap{2}-align side 2's calls  *)
(* to side 1's, peel the aligned backbone bottom-up, auto => /#.  *)
(*                                                                *)
(* The closer is `auto => /#`, NOT the single-oracle walker's     *)
(* `skip => /#`: _backbone_peel leaves the body's LEADING         *)
(* deterministic run to its caller, and a micro leg's body starts *)
(* with the flat state's field projections, so `skip` fails with  *)
(* "left instruction list is not empty".                          *)
(*                                                                *)
(* Measured origin: the second layer of the route-retirement      *)
(* shadow run -- once the rendered-identity row cleared the width *)
(* class, 160 of the 179 remaining chain deaths were this         *)
(* transform (plus 13 Extract Repeated Tuple Access).             *)
(*                                                                *)
(* Negative controls (validated 2026-08-10 on the probe           *)
(* .ec-tmp/move6/isuv_coupling_probe.ec, both PROOF-level):       *)
(* dropping the swap -> "K.ess and N.ets should be equal";        *)
(* falsifying an untouched-field frame conjunct by writing that   *)
(* field on the right -> "cannot prove goal (strict)".            *)
(* Lockstep: tests/unit/export/test_isuv_align.py.                *)
(* ============================================================ *)

require import AllCore Distr.

theory K_c.
type bs_lam.
module type Scheme = {
  proc decaps(dk : bs_lam, ct : bs_lam) : bs_lam
  proc ess(s : bs_lam) : bs_lam
}.
end K_c.

theory N_c.
module type Scheme = {
  proc exp(e : K_c.bs_lam, s : K_c.bs_lam) : K_c.bs_lam
  proc ets(e : K_c.bs_lam) : K_c.bs_lam
}.
end N_c.
import K_c.
type bs_lam = K_c.bs_lam.

section.

module IV_L (K : K_c.Scheme, N : N_c.Scheme) = {
  var dk0 : bs_lam
  var ek0 : bs_lam
  proc initialize() : bs_lam = {
    return dk0;
  }
  proc challenge(ct0 : bs_lam, e0 : bs_lam) : bool = {
    var d : bs_lam;
    var s : bs_lam;
    var x : bs_lam;
    var t : bs_lam;
    var u : bs_lam;
    d <- dk0;
    s <@ K.decaps(d, ct0);
    x <@ N.exp(e0, d);
    t <@ N.ets(x);
    u <@ K.ess(s);
    return u = t;
  }
}.

module IV_R (K : K_c.Scheme, N : N_c.Scheme) = {
  var dk0 : bs_lam
  var ek0 : bs_lam
  proc initialize() : bs_lam = {
    return dk0;
  }
  proc challenge(ct0 : bs_lam, e0 : bs_lam) : bool = {
    var s : bs_lam;
    var u : bs_lam;
    var x : bs_lam;
    var t : bs_lam;
    s <@ K.decaps(dk0, ct0);
    u <@ K.ess(s);
    x <@ N.exp(e0, dk0);
    t <@ N.ets(x);
    return u = t;
  }
}.

declare module K <: K_c.Scheme {-IV_L, -IV_R}.
declare module N <: N_c.Scheme {-K, -IV_L, -IV_R}.

(* Inlining + cross-module call reorder, under a field coupling. *)
lemma micro_isuv_align :
  equiv [ IV_L(K, N).challenge ~ IV_R(K, N).challenge :
          ={ct0, e0} /\ ={glob K} /\ ={glob N} /\ IV_L.dk0{1} = IV_R.dk0{2} /\ IV_L.ek0{1} = IV_R.ek0{2} ==> ={res} /\ ={glob K} /\ ={glob N} /\ IV_L.dk0{1} = IV_R.dk0{2} /\ IV_L.ek0{1} = IV_R.ek0{2} ].
proof.
  proc.
  swap{2} 3 -1.
  swap{2} 4 -1.
  wp.
  call (_: true).
  wp.
  call (_: true).
  wp.
  call (_: true).
  wp.
  call (_: true).
  auto => /#.
qed.

end section.
