(* NEGATIVE CONTROL for the plain deterministic-plumbing peel -- the last row of the
   per-leg dispatch (`_plain_plumbing_peel_step`).

   The two modules are a flat-state pair whose abstract-call BACKBONE is
   identical and whose bodies differ only in deterministic plumbing: the
   repeated use of `ct0` is extracted into a local on the right. `sim`
   cannot close it (it aligns the extra assignment against the first call);
   `wp` absorbs the deterministic runs and `/#` equates the substituted
   expressions, so the ordinary backbone peel does.

   The proof body below is GENERATED BY THE SYNTHESIZER over the matching
   mini game pair and pinned in lockstep by
   `tests/unit/export/test_plain_plumbing_peel.py`. If the two drift apart,
   the tactic this row emits is no longer the one EasyCrypt checked here.

   EasyCrypt must REFUSE this file, and that is the point. It carries the
   SAME tactic as `plain_plumbing_peel.ec` against a body whose second call
   takes the WRONG key, so the closer is handed `dk1{1} = dk0{2}` from a
   precondition that offers `dk1{1} = dk1{2}`: a false subgoal. A tactic that
   RUNS is not evidence that it did any work, and this file is what makes the
   accepting sibling mean something. If EasyCrypt ever accepts this, the peel
   is closing goals it should not. *)

require import AllCore.

type key_t.
type ct_t.
type ss_t.

module type S = {
  proc decaps(k : key_t, c : ct_t) : ss_t
  proc ess(k : key_t, c : ct_t) : ss_t
}.

module PP_L (K : S) = {
  var dk0 : key_t
  var dk1 : key_t

  proc challenge(ct0 : ct_t) : bool = {
    var s, u : ss_t;
    s <@ K.decaps(dk0, ct0);
    u <@ K.ess(dk1, ct0);
    return (u = s);
  }
}.

module PP_R (K : S) = {
  var dk0 : key_t
  var dk1 : key_t

  proc challenge(ct0 : ct_t) : bool = {
    var s, u : ss_t;
    var cse : ct_t;
    cse <- ct0;
    s <@ K.decaps(dk0, cse);
    u <@ K.ess(dk1, cse);
    return (u = s);
  }
}.

module PP_Wrong (K : S) = {
  var dk0 : key_t
  var dk1 : key_t

  proc challenge(ct0 : ct_t) : bool = {
    var s, u : ss_t;
    var cse : ct_t;
    cse <- ct0;
    s <@ K.decaps(dk0, cse);
    u <@ K.ess(dk0, cse);
    return (u = s);
  }
}.

section Tripwire.

declare module K <: S{-PP_L, -PP_R, -PP_Wrong}.

lemma plain_plumbing_peel_falsified :
  equiv [ PP_L(K).challenge ~ PP_Wrong(K).challenge :
          ={ct0} /\
          (PP_L.dk0{1}, PP_L.dk1{1}, (glob K){1}) =
          (PP_Wrong.dk0{2}, PP_Wrong.dk1{2}, (glob K){2}) ==>
          ={res} /\
          (PP_L.dk0{1}, PP_L.dk1{1}, (glob K){1}) =
          (PP_Wrong.dk0{2}, PP_Wrong.dk1{2}, (glob K){2}) ].
proof.
proc.
wp.
call (_: true).
wp.
call (_: true).
auto => /#.
qed.

end section Tripwire.
