(* ============================================================ *)
(* Rendered-identity row (Phase-2 Move 5) -- VALIDATED EC         *)
(* TEMPLATE (regression tripwire), GENERATED BY THE SYNTHESIZER   *)
(* ITSELF (_rendered_identity_step) over a mini width-annotation  *)
(* pair rendered by the real renderer.                            *)
(*                                                                *)
(* Shape: a FrogLang step whose entire effect is absorbed by the  *)
(* renderer's own normalization -- the measured class is Symbolic *)
(* Computation rewriting a bitstring WIDTH ANNOTATION             *)
(* (BitString<na + nb + nb> -> BitString<na + 2 * nb>), where the *)
(* type collector canonicalizes both to one EC type, so the two   *)
(* flat states emit the SAME module modulo its name. The row      *)
(* compares whole ec_ast.Module values (state vars + body), so a  *)
(* field rename or type change declines; equal means the lemma    *)
(* relates a module to itself and `proc; sim.` closes by          *)
(* construction.                                                  *)
(*                                                                *)
(* Measured origin: the 2026-08-09 route-retirement shadow run --  *)
(* 173 of 179 declined binding chains died on exactly this class  *)
(* at pair 1, fusing every later step of the same chain behind    *)
(* them. Verified on the real corpus: CG_expanded_LEAK_BIND_K_PK  *)
(* hop 0 challenge pair 1 renders identically and the row fires.  *)
(*                                                                *)
(* Negative control (validated 2026-08-10 by mutating THIS file): *)
(* changing ID_R's second Widen argument to dk0 makes the two     *)
(* modules genuinely differ -> `sim` cannot close and EC rejects. *)
(* Lockstep: tests/unit/export/test_rendered_identity.py.         *)
(* ============================================================ *)

require import AllCore Distr.

theory K_c.
type bs_na.
type bs_na_2_nb.
module type Scheme = {
  proc widen(x : bs_na) : bs_na_2_nb
}.
end K_c.
import K_c.
type bs_na = K_c.bs_na.
type bs_na_2_nb = K_c.bs_na_2_nb.

section.

module ID_L (K : K_c.Scheme) = {
  var dk0 : bs_na
  proc initialize() : bs_na = {
    return dk0;
  }
  proc challenge(ct0 : bs_na) : bool = {
    var w0 : bs_na_2_nb;
    var w1 : bs_na_2_nb;
    w0 <@ K.widen(dk0);
    w1 <@ K.widen(ct0);
    return w0 = w1;
  }
}.

module ID_R (K : K_c.Scheme) = {
  var dk0 : bs_na
  proc initialize() : bs_na = {
    return dk0;
  }
  proc challenge(ct0 : bs_na) : bool = {
    var w0 : bs_na_2_nb;
    var w1 : bs_na_2_nb;
    w0 <@ K.widen(dk0);
    w1 <@ K.widen(ct0);
    return w0 = w1;
  }
}.

declare module K <: K_c.Scheme {-ID_L, -ID_R}.

(* The two states render to the same module modulo its name. *)
lemma micro_rendered_identity :
  equiv [ ID_L(K).challenge ~ ID_R(K).challenge :
          ={ct0} /\ ={glob K} /\ ID_L.dk0{1} = ID_R.dk0{2} ==> ={res} /\ ={glob K} /\ ID_L.dk0{1} = ID_R.dk0{2} ].
proof.
  proc; sim.
qed.

end section.
