(* ============================================================ *)
(* Same-memory-coupling equal-body leg -- VALIDATED EC TEMPLATE   *)
(* (regression tripwire), GENERATED BY THE SYNTHESIZER ITSELF     *)
(* (_crossed_coupling_sim_step) over a mini pair rendered by the  *)
(* real renderer.                                                 *)
(*                                                                *)
(* Shape: the two states run the SAME oracle body, and the        *)
(* coupling carries (a) a same-memory conjunct SB.s0{1} =         *)
(* SB.s1{1} -- the survivor-consistency facts a broken chain      *)
(* threads -- and (b) a cross-named pair SB.pk{1} = SA.sk{2} the  *)
(* body never touches. `sim` reads a postcondition as equalities  *)
(* BETWEEN the two memories, so a one-memory conjunct makes it    *)
(* give up with "cannot infer the set of equalities" (measured on *)
(* CK_seedbased_LEAK_BIND_K_PK micro_2_hashg_left_22, a Split     *)
(* Opaque Tuple Field step). With no call and no sample in the    *)
(* body and every TOUCHED field paired under its own name, `auto` *)
(* decides both sides by wp and every other conjunct is frame.    *)
(*                                                                *)
(* Two controls, both validated by mutating THIS file:            *)
(*  * `proc; sim.` in place of the tactic -> "cannot infer the    *)
(*    set of equalities" (this is the route the gate replaces);   *)
(*  * dropping the load-bearing SB.s0{1} = SA.s0{2} conjunct from *)
(*    the precondition only -> "cannot prove goal (strict)".      *)
(* Lockstep: tests/unit/export/test_same_memory_coupling.py.      *)
(* ============================================================ *)

require import AllCore Distr.

type bs_lambda.

section.

module SB = {
  var s0 : bs_lambda
  var s1 : bs_lambda
  var pk : bs_lambda
  proc initialize() : bs_lambda = {
    return s0;
  }
  proc challenge(x : bs_lambda) : bs_lambda = {
    var _r0 : bs_lambda;
    var _r1 : bool;
    _r1 <- false;
    if (s0 = x) {
      _r0 <- s1;
      _r1 <- true;
    } else {
      _r0 <- x;
      _r1 <- true;
    }
    return _r0;
  }
}.

module SA = {
  var s0 : bs_lambda
  var s1 : bs_lambda
  var sk : bs_lambda
  proc initialize() : bs_lambda = {
    return s0;
  }
  proc challenge(x : bs_lambda) : bs_lambda = {
    var _r0 : bs_lambda;
    var _r1 : bool;
    _r1 <- false;
    if (s0 = x) {
      _r0 <- s1;
      _r1 <- true;
    } else {
      _r0 <- x;
      _r1 <- true;
    }
    return _r0;
  }
}.

lemma micro_same_memory_coupling :
  equiv [ SB.challenge ~ SA.challenge :
          ={x} /\ SB.s0{1} = SA.s0{2} /\ SB.s1{1} = SA.s1{2} /\ SB.pk{1} = SA.sk{2} /\ SB.s0{1} = SB.s1{1} ==> ={res} /\ SB.s0{1} = SA.s0{2} /\ SB.s1{1} = SA.s1{2} /\ SB.pk{1} = SA.sk{2} /\ SB.s0{1} = SB.s1{1} ].
proof.
  proc.
  auto => /#.
qed.

end section.
