name: emacs-lint

on:
  push:
    branches: [main]
    paths: ["emacs/**"]
  pull_request:
    branches: [main]
    paths: ["emacs/**"]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs-version: ["27.2", "28.2", "29.4"]
    steps:
      - uses: actions/checkout@v4

      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - name: Byte-compile
        working-directory: emacs
        run: make compile

      - name: Package-lint
        working-directory: emacs
        run: make lint

      - name: Checkdoc
        working-directory: emacs
        run: make checkdoc
